### ISSUE TITLE
Header padding in @react-navigation/native-stack

### ISSUE THREAD

**Issue by b-steel** [react-navigation/react-navigation#10058]
### Current behavior

If the default back button is hidden by passing `{headerBackVisible: false, headerLeft: () => <HeaderBackButton/>}`
where the `HeaderBackButton` component is imported from `@react-navigation/elements` there is some padding to the left of the back button that is not there when using the default back button.

This issue is not the case when using the stack navigator from `@react-navigatin/stack`
![Simulator Screen Shot - iPhone SE (1st generation) - 2021-10-15 at 15 59 33](https://user-images.githubusercontent.com/70383237/137553208-6e42ca6a-902e-427c-b8b6-af823d9a6657.png)
![Simulator Screen Shot - iPhone SE (1st generation) - 2021-10-15 at 15 59 36](https://user-images.githubusercontent.com/70383237/137553218-57212a28-c3a2-4bc0-bca4-9212bfee56a9.png)

### Expected behavior

Inserting `HeaderBackButton` for `headerLeft` should be identical to the default back button (visually) 

### Reproduction

https://github.com/b-steel/react-navigation-header-demo

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.2.4
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.2
| react-native                           | https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
| expo                                   | 42.0.1
| node                                   | 14.17.1
| npm or yarn                            | 1.22.15

**Comment by christophemenager** [comment]
I have the sale issue

**Comment by BologaMarius** [comment]
This issue should be opened for the [react-native-screens](https://github.com/software-mansion/react-native-screens) project.

This padding issue is due to the autolayout, used for [navigation](https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreenStackHeaderConfig.m#L578) bar starting with iOS 11, where the `UIBarButtonItems` with custom views have 16 pts leading constraint. More details about the native issues [here](UIBarButtonItems). Since the bar has already 16 points leading constraint and the `HeaderBackButton` icon has  already `marginLeft: 8` in [styles](https://github.com/react-navigation/react-navigation/blob/main/packages/elements/src/Header/HeaderBackButton.tsx#L202), the back button will look like having 24 pts leading margin. There might be a few workarounds for this:

1. Wrap your `headerLeft` component in a `View` and add a negative margin. Example bellow:

`  <View style={{marginLeft: -16}}>
          <HeaderBackButton
            onPress={() => navigation.goBack()}
          />
        </View>
`

2. Write a [custom header](https://reactnavigation.org/docs/native-stack-navigator#header) and use that instead of the default header. Make sure you pass the new component for the `headerLeft` prop. 

3. Changes on the native side to make sure the `leftBarButtonItem` has the proper leading margin, some solutions provided [here](https://stackoverflow.com/a/47554138)

**Comment by b-steel** [comment]
@BologaMarius 
Thanks for all the info, much appreciated. I should have thought of passing a custom header everywhere to solve the issue.
