### ISSUE TITLE
Can't navigate to a deeper stack screen before mount.

### ISSUE THREAD

**Issue by SohelIslamImran** [react-navigation/react-navigation#10212]
### Current behavior

I have navigators like this.

```
function HomeStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Home" component={Home} />
      <Stack.Screen name="Profile" component={Profile} />
    </Stack.Navigator>
  );
}

function App() {
  return (
   <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Feed" component={Feed} />
        <Tab.Screen name="HomeStack" component={HomeStack} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```
I can't navigate to "Profile" from "Feed" before going to "HomeStack" navigator. Maybe "HomeStack" do not mount at the initial load.

### Expected behavior

I want to navigate to "Profile" without going to "HomeStack" navigator first.

### Reproduction

https://snack.expo.dev/@sohelislamimran/bug

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
  "@react-navigation/bottom-tabs": | "^6.0.7"
  "@react-navigation/drawer":| "^6.1.8"
   "@react-navigation/material-top-tabs": |"^6.0.6"
    "@react-navigation/native": |"^6.0.4"
   "@react-navigation/native-stack": |"^6.2.2"
  "react-native-pager-view": |"5.0.12"
   "react-native-reanimated": |"~2.1.0"
   "react-native-safe-area-context": |"3.2.0"
   "react-native-screens": |"~3.0.0"
   "react-native-svg": |"^12.1.1"
   "react-native-tab-view": |"^3.1.1"
   "react-native-web": |"~0.13.12"

**Comment by vonovak** [comment]
hello, thanks for asking

> I want to navigate to "Profile" without going to "HomeStack" navigator first.

because Profile is inside of HomeStack, there is no way to not go to Profile without going to HomeStack first. It indeed makes sense that in order to visit Profile (which is in HomeStack) you need to go to HomeStack

the solution here is to move the Profile screen outside of HomeStack.
If you want to keep Profile in HomeStack, but want to render Profile directly, you can control that via `initialRouteName` prop that you can pass as param to HomeStack. See https://reactnavigation.org/docs/stack-navigator/#initialroutename


hope this helps :)
