### ISSUE TITLE
Unable to go back after refreshing from a Modal screen

### ISSUE THREAD

**Issue by Estevete** [react-navigation/react-navigation#10276]
### Current behavior

Let's suppose I have a TabNavigator. In a screen, I'm able to navigate to a modal screen (full screen modal => it's placed outside the TabNavigator stack) and go back but, if I refresh the browser in the modal screen (F5), I'm unable to go back. The go back button disappears.

Video describing the problem: https://recordit.co/4PULNdWRPT

### Expected behavior

We should be able to go back from the go back button.

### Reproduction

https://github.com/MADSENSE/Madsense.ReactNative.Sample

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/bottom-tabs          | 6.0.5
| @react-navigation/native-stack         | 6.1.0
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.10.1
| react-native                           | 0.64.3
| react-native-web                           | 0.17.1
| expo                                   | 44.0.0

**Comment by satya164** [comment]
It's impossible to know the browser history just from the URL, React Navigation doesn't know whether there's history to go back to be able to show the back button.

The user is still able to go back using browser's back button.

**Comment by Estevete** [comment]
> It's impossible to know the browser history just from the URL, React Navigation doesn't know whether there's history to go back to be able to show the back button.
> 
> The user is still able to go back using browser's back button.

So how could we manage this situation? Any deep link to a modal screen will be broken, because you cannot "close" the screen.

Is there any way we could provide an initialRouteName from a screen placed in a different stack?

**Comment by satya164** [comment]
> So how could we manage this situation? Any deep link to a modal screen will be broken, because you cannot "close" the screen.

https://reactnavigation.org/docs/configuring-links/#rendering-an-initial-route

**Comment by Estevete** [comment]
Well, I think I've got a workaround for those who are joining this issue...
- I check if I'm able to go back => `navigation.canGoBack()`
    - If true, `navigation.goBack()`
    - Otherwise, `navigation.navigate()` or `replace` to the nested screen https://reactnavigation.org/docs/nesting-navigators

Following this, you ensure the user will be navigating always to the same screen.

**Comment by WayneWang98** [comment]
Hi @satya164,
I am facing same issue:I hope user can go to the previous page  by using `navigation.canGoback` function although user has refreshed this page.
```typescript
export function back(): void {
  const navigator = getNavigator();
  if (navigator === null) {
    return;
  }
  if (navigator?.canGoBack()) {
    navigator.goBack();
  } else {
    reLogin(false); // reset all user config and lead user to login page
  }
}
```
However, `navigation.canGoBack()` returns `false` after user refresh.

I find 2 ways to handle this situation:
The first way is using browser history API to let user back to previous page.
```typescript
export function back(): void {
  const navigator = getNavigator();
  if (navigator === null) {
    return;
  }
  if (navigator?.canGoBack()) {
    navigator.goBack();
  } else {
    if (isWeb) { // if user can't go back and in web side, call history API to let user back
      history.go(-1);
    } else {
      reLogin(false);
    }
  }
}
```
By using this way, I've tested a lot of scenario, it seems that it can work but our team think that bypassing using react-navigation's routing state and calling the browser api directly might cause issues with browser history being out of sync with react-navigation State, but we currently have no evidence to prove this.

Due to this reason, I am using the second way to handle this scenario but also get some issues.
For the second way, I store the route state to sessionStorage and use custom callback function `getStateFromPath` and `getPathFromState` to manage our route state.  
Therefore, when web url has been change, we can recover the route state by combine the state which is from sessionStorage and another state which is from `getStateFromPath`. After we do that, the `navigator.goBack()` will return true and user can go back because we have complete routing status.
```typescript
import {
  getPathFromState as _getPathFromState,
  getStateFromPath as _getStateFromPath,
  LinkingOptions,
  NavigationState,
  ParamListBase
} from '@react-navigation/native';
import { GlobalParamList } from '../core';
import { SDK_ROUTE_PERSISTENCE_KEY } from '../utils';

let isLoaded = false; // if the page has been loaded

type CustomFields = {
  stale: true;
};

type MutableNavigationState = {
  -readonly [key in keyof NavigationState | keyof CustomFields]?: key extends keyof CustomFields
    ? CustomFields[key]
    : NavigationState[key];
};

/**
 * remove 'key' prop from navigator, because if user refreshed page, the key value would be changed so the navigate action 'RESET' with
 * payload would not be handled by any navigator.
 * therefore, we should remove 'key' so that the navigator can handle this action with a new key.
 */
function removeKeyProp(obj: MutableNavigationState) {
  if (obj) {
    delete obj['key'];
  }
  return obj;
}

const purifyState = (state: MutableNavigationState) => {
  let pureState = state;
  if (state?.routes?.[0].name === 'web-portal') {
    // we added 'web-portal' prefix for website, but we shouldn't use it in state because the web-portal is a virtual route
    pureState = state?.routes?.[0]?.state as MutableNavigationState;
  }
  return pureState as ReturnType<typeof _getStateFromPath>;
};

const combinePathAndSessionState = (sessionState: MutableNavigationState, pathState: MutableNavigationState) => {
  let mainState = sessionState,
    subRoute = pathState?.routes?.[0]?.state?.routes[0];
  // find and compare screenName from mainRoutes and subRoute recursively
  while (mainState && subRoute) {
    const mainRoutes = mainState.routes;
    const childName = subRoute.name;
    const matchedState = mainRoutes?.find((item) => item.name === childName);

    if (!subRoute.state && mainRoutes) {
      const index = mainRoutes?.findIndex((item) => item.name === childName);
      if (index !== -1) {
        // if screen name from pathState exists in session state, remove all the screen which are following
        // e.g. user clicks browser back button
        mainState.index = index;
        mainRoutes?.splice(index + 1);
      } else {
        // if screen name from pathState doesn't exist in session state, push this screen to sessionState
        // e.g. user clicks browser forward button
        mainRoutes?.push(subRoute as any);
        mainState.index = mainRoutes.length - 1;
      }
      return;
    }

    mainState = matchedState?.state as MutableNavigationState;
    subRoute = subRoute?.state?.routes[0];
  }
};

const linking: LinkingOptions<GlobalParamList> = {
  prefixes: [],
  // use getStateFromPath and getPathFromState to add prefix URL for web
  getStateFromPath(path: string, options) {
    const stateFromPath = _getStateFromPath(path, options) as MutableNavigationState;
    const stateSessionString = window?.sessionStorage?.getItem(SDK_ROUTE_PERSISTENCE_KEY);
    let stateFromSession = null;
    try {
      stateFromSession = stateSessionString ? JSON.parse(stateSessionString) : null;
      // eslint-disable-next-line no-empty
    } catch (error) {}
    const state = stateFromSession ?? stateFromPath; // state may not exist in sessionStorage
    if (!isLoaded) {
      // if user refresh page, we use state instead of combinePathAndSessionState
      isLoaded = true;
    } else {
      combinePathAndSessionState(state, stateFromPath);
    }
    const pureState = purifyState(removeKeyProp(state));
    return pureState;
  },
  getPathFromState(state, options) {
    const path = _getPathFromState(state, options);
    return '/web-portal' + path;
  }
};


```
However, we find that by using the second way, user can't go back to some screens which belong to TabNavigator. There is no way to cover all scenarios of user actions.

Hi @satya164 ,could you please have a look to the 2 ways of handling this scenario?

To conclude, I think the first way can work properly in most scenarios and we haven't find any problems with existing projects. However, this approach may result in react navigation's routing state being inconsistent with the browser's history.
By using the second approach, we were able to do our best not to call the history API directly, but that would have caused us to spend a lot of time dealing with unexpected situations.

What do you think would be a better way to deal with it, or do you have other ways to deal with it

Looking forward to your reply.
Thanks.

**Comment by WayneWang98** [comment]
can we reopen this issue now to discuss some solutions for the issue?
