### ISSUE TITLE
Tab.Navigator backBehavior "history" acts like backBehavior "firstRoute" 

### ISSUE THREAD

**Issue by patrakeevsa** [react-navigation/react-navigation#10374]
### Current behavior

After goBack command is dispatched on Tab.Navigator with backBehavior={'history'} state switches to first tab

### Expected behavior

When goBack is dispatched previous screen in history should appear  

### Reproduction

https://snack.expo.dev/lxx2hcPcX

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.8
| @react-navigation/bottom-tabs          | ^6.2.0
| @react-navigation/stack                | ^6.1.1

**Comment by AshotN** [comment]
I'm experiencing the same thing, `backBehavior` seems to change nothing

**Comment by satya164** [comment]
You have 2 screens in your repro. The first screen is the same screen that's in history. If it's a bug then you need to provide a proper repro with steps to repro.

**Comment by AshotN** [comment]
@satya164 I've created a [repro](https://snack.expo.dev/@ashotn/bottom-tabs-navigator-|-react-navigation), I am not sure if this is exactly the issue @patrakeevsa was experiencing. But I think it is

The inconsistent behavior can be triggered like this

If you first load the app and press the "Go to ScreenInDetails", the Go back button works correctly. So it takes you back to the home tab.

But if you first load the app, navigate through the tab bar to the details tab. Navigate back through the tab bar to the home tab. Then press the "Go to ScreenInDetails", the Go back button takes you to the detail tab rather than the home tab.

I hope I explained that clear enough, let me know if you need any further detail.

**Comment by satya164** [comment]
> Go back button takes you to the detail tab rather than the home tab

This is the expected behavior - the stack had the `Details` screen in history after you opened the tab and then you navigated to `ScreenInDetails` which added it to the stack's history.

As documented in the nesting docs, each navigator keeps its own history and back button will navigate inside that navigator if there is history: https://reactnavigation.org/docs/nesting-navigators/#each-navigator-keeps-its-own-navigation-history
