### ISSUE TITLE
Last character of tab label getting deleted when tab is selected

### ISSUE THREAD

**Issue by pvsmagbojos** [react-navigation/react-navigation#10467]
### Current behavior

This seems to be a problem that exists only in the Material Top Tab Navigator (tested with bottom tab navigator and it worked fine)
When a tab is focused, the last character of the tab's label is deleted

### Expected behavior

The tab's label should be displayed as-is instead of having the character at the end of the string be removed

### Reproduction

https://snack.expo.dev/@pvsmagbojos/material-top-tabs-navigator-%7C-react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/material-top-tabs    |
| react-native                           |

**Comment by pvsmagbojos** [comment]
Upon further testing, it seems that part of text seems to be clipped instead, so it has something to do with rendering the text rather than the string being the problem

**Comment by okwasniewski** [comment]
Hey @pvsmagbojos,

It looks like you are trying to make the tab bar label bolder on when it's selected: 
<img width="268" alt="CleanShot 2022-12-16 at 09 53 17@2x" src="https://user-images.githubusercontent.com/52801365/208060657-7962b0e0-bb68-4882-aa0b-9b308d066182.png">

The last character is landing on the next line and that's normal behaviour of how tabs work at the moment. We are measuring tab width during rendering and due to performance reasons we are not accounting for tab width to change. Closing this
