### ISSUE TITLE
`useLinkProps` does not use `initialRouteName` to build href

### ISSUE THREAD

**Issue by adamjseitz** [react-navigation/react-navigation#10535]
### Current behavior

If the `useLinkProps` `to` parameter is passed an object like `{screen: 'Root'}`, where `Root` is a screen that contains a nested navigation with an `initialRouteName`, e.g.:

```js
const linking = {
  config: {
    screens: {
      Root: {
        initialRouteName: 'Nested',
        screens: {
          Nested: 'nested',
        },
      },
    },
  },
};
```

then the `href` does not use the initial route (i.e., `href` is generated as `/` instead of `/nested` ). 

### Expected behavior

* The `href` should use the initial route name for the nested navigator, i.e., `/nested`.

### Reproduction

https://snack.expo.dev/@adamjseitz/react-navigation-link-props-href

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/native-stack         | 6.6.1

**Comment by satya164** [comment]
That's expected behavior. The built link will only contain the path to the screen you have specified (in this case `Root`). It's additional complexity to traverse through all child configs just in case you have a path same as initial route name. The generated link is still valid and will open that screen when visited.

If you want the link to link to a specific screen, then you should explicitly state that screen. `initialRouteName` is a hint to render the linked screen with the initial route as the first screen in the navigator. It's not used in the generated link.
