### ISSUE TITLE
[iOS] When keyboard is focused and back is pressed, previous screen moves off the screen partially

### ISSUE THREAD

**Issue by JulioRosil** [react-navigation/react-navigation#10656]
### Current behavior

https://user-images.githubusercontent.com/99291594/175606685-f68eb669-dd59-4aed-8d18-efccbecdf8bd.mp4

When I make goBack and an input is focused, the screen is moved off down.
I execute goBack() in the "Atras" button.

### Expected behavior

Make go back and the screen fits in the phone, without moving off.

### Reproduction

      <SendStack.Screen
        name="NuevoDestinatario"
        component={NewAddressee}
        options= {({ navigation, route }) => ({
          headerShown: true,
          gestureEnabled: false,
          title: '',
          headerStyle: {
            backgroundColor: '#fff',
          },
          headerLeft: (props) => (
            <TouchableOpacity
              activeOpacity={0.6}
              onPress={() => navigation.goBack()}
              style={{flexDirection: 'row', alignItems: 'center'}}
            >
              <Icon
                name='arrow-back'
                color={'#185CE5'}
                size={27}
              />
              <Text style={{fontSize: 17, color:'#185CE5'}}>
                Atrás
              </Text>
            </TouchableOpacity>
          )
        })}
      />

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.8
| @react-navigation/material-bottom-tabs | ^6.1.1
| @react-navigation/native-stack         | ^6.5.0
| react-native                           | 0.68.1

**Comment by kacperkapusciak** [comment]
Hi @JulioRosil 👋 
Could you prepare a minimal repro in a form of an Expo Snack?

Thanks!

**Comment by NazarDevsMedia** [comment]
any updates? 
facing the same issue with open keyboard when navigating between screens, ios only.

**Comment by ryan-reichenberg** [comment]
@NazarDevsMedia @JulioRosil any updates on this?

**Comment by NazarDevsMedia** [comment]
> @NazarDevsMedia @JulioRosil any updates on this?

because of iOS render bug you might notice that keyboard is shortly in _open_ state on the screen that you navigating to and there is an unreachable area in the bottom that equals yours bottom container height (in my case it is bottom nav bar). you can see it even in apple apps, kinda crazy.
there is no further github issue from me, but I can provide you a code snippet that I use to handle this Keyboard behaviour.
hope you will find it well.

at container component styling (such View etc) I pass:
`contentInset={{ bottom: Platform.OS === 'ios' && Keyboard.isVisible() ? 84 : 16 }}`
therefore you should be fine and have consistent padding across navigation screens.
