### ISSUE TITLE
useFocusEffect documentation about useCallback dependencies is unclear

### ISSUE THREAD

**Issue by shamikfresh** [react-navigation/react-navigation#10671]
### Current behavior

This is essentially a copy of:
https://github.com/react-navigation/react-navigation/issues/10230
But I'm opening this issue to track the documentation update as it caused me a lot of confusion and I think deserves a resolution.
The useFocusEffect documentation currently says:

The effect will run whenever the dependencies passed to React.useCallback change, i.e. it'll run on initial render (if the screen is focused) as well as on subsequent renders if the dependencies have changed. If you don't wrap your effect in React.useCallback, the effect will run every render if the screen is focused.

"Initial render" is ambiguous, and I and some others have assumed that it means "The first render after the first focus after mounting". In fact, it means "The first render after each focus".

### Expected behavior

I think the documentation should be updated to clarify:

The effect will run whenever the dependencies passed to React.useCallback change, i.e. it'll run on the initial render each time the screen is focused, but will only run on subsequent renders (while the screen remains focused) if the dependencies have changed. If you don't wrap your effect in React.useCallback, the effect will run every render if the screen is focused.

### Reproduction

https://snack.expo.dev/D4shrKnby

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |   6.0.10
| react-native                           |  0.64.2
| expo                                   |  44.0.1
| node                                   |  15.5.1
| yarn                            |   1.16.0

**Comment by joshuaxdmb** [comment]
I was curious so I took a look into the documentation for useCallback and useFocusEffect, as well as useEffect for reference. This is what I found in case it helps someone understand the behaviour:

### First
When a functional component re-renders, all the functions inside it are called again, and this includes any hooks and their callbacks.

### So
Without React.useCallback: Every time the component re-renders, the function you pass to useFocusEffect is a new function. Because it's new, useFocusEffect will execute it again if the component is focused.

### Thus, the behaviour is

If you use useFocusEffect without React.useCallback, it will run:

1. When the screen is brought into focus: This happens when you navigate to the screen, including the first time it's rendered and any subsequent times it becomes focused after being unfocused (e.g., when returning to the screen from another).

2. On every render while the screen remains in focus: If the screen is already focused and for any reason the component re-renders (state changes, props change, context updates, etc.), useFocusEffect will run again.

### But with useCallback()

When you wrap a function with React.useCallback, React memoizes (caches) that function and only re-creates it if one of its dependencies change. This way, even if the component re-renders, the same memoized function is provided to useFocusEffect, and it won't execute it again unless the dependencies have changed (or the screen is re-focused after being unfocused).

**Comment by satya164** [comment]
Please open documentation related issues in the documentation site or send a pull request https://github.com/react-navigation/react-navigation.github.io
