### ISSUE TITLE
Lots of updates useLinking in safari: SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds

### ISSUE THREAD

**Issue by AntonYushkevich** [react-navigation/react-navigation#11086]
### Current behavior

At every screen update history.replace is called that cause _SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds_ error in Safari. 

That peace of code trigging on each update inside components. 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/25014691/206484785-d94854d5-e71f-4ded-a95b-96f5fde24503.png">

Maybe because that useEffect is calling without dependencies
<img width="786" alt="image" src="https://user-images.githubusercontent.com/25014691/206494934-56fb60e2-a828-47f3-b607-5e9c1c4a4ca2.png">

### Expected behavior

history.replace called on screen changes

### Reproduction

http://

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/bottom-tabs          | []
| @react-navigation/drawer               | []
| @react-navigation/material-bottom-tabs | []
| @react-navigation/material-top-tabs    | []
| @react-navigation/stack                | []
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         | []
| react-native-screens                   | 3.10.0
| react-native-gesture-handler           | []
| react-native-reanimated                | []
| react-native-tab-view                  | []
| react-native-pager-view                | []
| react-native                           | 0.68.1
| expo                                   | []
| node                                   |  16.17.0
| npm or yarn                            |  1.22.18

**Comment by jparkrr** [comment]
The issue still exists.

As mentioned in previous issue https://github.com/react-navigation/react-navigation/issues/10411 (now closed for inactivity), this can be reproduced on https://react-navigation-example.netlify.app/native-stack/article/gandalf in Safari (on desktop) by vigorously resize the browser window for a few seconds, and then the page crashes.

We're also seeing this (more easily reproduced in our app) in iOS safari where the browser resizing the address bar when you scroll sends enough resize events to crash it.

https://user-images.githubusercontent.com/373062/157116779-6c54ff1e-02ec-4658-8d1d-498fea3c9896.mov

Seemingly `NavigationContainer` is calling `history.replaceState` on every render, so one workaround is to make sure you don't rerender when the window is resized, but it seems to me this could also be fixed in the library by only calling `history.replaceState` when needed, and not on every render.

**Comment by jparkrr** [comment]
Still reproducible on the latest example app as I mentioned in my comment above https://github.com/react-navigation/react-navigation/issues/11086#issuecomment-1367335042

**Comment by AntonYushkevich** [comment]
@jparkrr [https://github.com/react-navigation/react-navigation/commit/79d8dc107aaadf4923024f8b122c0b55e1079706](seems to have happened).  [https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fnative%406.1.3](v6.1.3)
