### ISSUE TITLE
transparentModal is always on the top of screen

### ISSUE THREAD

**Issue by jojohoooo** [react-navigation/react-navigation#11214]
### Current behavior

when I navigate from a transparentModal named "One" to another screen named "Second", the transparentModal named "One" is still on the top of the screen.

And if I remove transparentModal props or change native-stack to stack, it works fine, without transparent...

I guess the transparentModal is always on the top of all the screens

### Expected behavior

when I navigate from a transparentModal named "One" to another screen named "Second", the transparentModal named "One" is expected hidden and behind of the screen named "Second".

### Reproduction

""

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.0
| @react-navigation/drawer               | ^6.5.5
| @react-navigation/stack                | ^6.3.8
| @react-navigation/native-stack         | ^6.9.5
| react-native-safe-area-context         | ^4.4.1
| react-native-screens                   | ~3.18.0
| react-native-gesture-handler           | ~2.8.0
| react-native-reanimated                | ~2.12.0
| react-native                           | 0.70.5
| expo                                   | ~47.0.12
| node                                   | 16.16.0
| npm or yarn                            | yarn 1.22.19

**Comment by kacperkapusciak** [comment]
Hey @jojohoooo 👋 
Thanks for filing an issue but this is very much expected behaviour of native modals to always be on the top. Consider giving a read to [Human Design Guidelines on Modality](https://developer.apple.com/design/human-interface-guidelines/patterns/modality/) by Apple on how users expect modals to be used.

Maybe you wanted to [nest a navigator](https://reactnavigation.org/docs/nesting-navigators/) inside a modal to show a screen within the modal context?

I'm closing this issue as we don't consider it as a bug

Cheers
