### ISSUE TITLE
ScreenComponentType breaks nested navigator type

### ISSUE THREAD

**Issue by uloco** [react-navigation/react-navigation#11242]
### Current behavior

If I have a nested navigator tree (for example three nested stacks) and want to specify the exact props type of a nested navigator, typescript reports a type error at the component property of the `Stack.Screen` inside the navigator.

Sometime you have to access the nav or route prop inside the stack (not a screen) and this used to work and would be typed correctly, but now I cannot type the stack props correctly. 

See repro.

### Expected behavior

The ScreenComponentType should respect nested navigators prop type.

### Reproduction

https://www.typescriptlang.org/play?ssl=8&ssc=19&pln=8&pc=20#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoUSWOAb3LjgGFdIBnYGJAZTSKQB2ABRxg2AGgZwAcigBuwAOYoY0Xv2EooKEBPIBfONlwEAAkXQwAtAPlKVwCAID0aaEjKVw0ePUZ9ULm4YdABrWQVlVShJRmCw9SRBEQgxSUNjPHxzYmtbSIcnZzYQtFDPKh86OAA1YCQAd3E4ABUkAA94DJwsiwwbBzkPCnIYAE8wJDgAGSQhgBsAeQEkIS0daeASuABeOilZhZaGiHiygC4ZOyi1AOT13QAeQ6R544g17RBNkoA+Cn0FDcAm2Z1C0wAjLs4AEVDxSuFripoM85q9lqsHj8YL8ABQAShGwO2LyWKzB0IJu1+cFxUkeYMhADoIvZor8pIwGQjmYlBHBbCAkDt8KT3mD8DDWE5BDAdrQxScwYZnByuc5GRCWUj2eRCeRRhMpoqPlitvA9n4Zmi3gALfhgy6sm5QPmaL5sVFHe1JT4bc3-AxApygnkAJmhsKCCOdyKgXte7z93wDBKJIfgJopeypOxpdK5jLD2oKusYhfDTLdAp0wtFNpaPvhYUlbm8KwEcoVDabyrgqvpGsrsd1+sNk2t3v4yex0KtYt7dwEl1ocBAY2TlxKUGAAkUcEBQfIxPgjIAzJGLNGwiOUQvp2a-mmDR1qPBxhP70kwSkxNCWN4HBBEuv6elIYJuqBCZkpiXzYr8sTMNKQE8CBohgeWcAQWhqSeiaM4BohcQIpB6HQY2D5wQGUgcoG5DOM4cAAJICkkAAmcDoGgSBsGwcCqDWcicQIHE4AArlwcBgKIcC2kgRDNGwEBwEQIAQAoe78XJUkyWADxIFwUBwFsAoQPAKACHAqQwI4AhMseGaTomvYIpS0m4ZcX7NmUoH4tS+yMEQMBiVAlkFuW3JhNMZ4lmy0BqphcCRWU0VVkuNZCiKXluq20odl22VLiqCXquesUugl+qHuQr5VB+xo9g6JE4WIjxSC0cAdFwIl8aESBjBAmBOXalH+iU5A0nsAHsJwqEaFB4HNfNZFeQRJTNC0CEHI134IqBE0jPVcCgdC2VLUkwhkfWU7fku+B0Sew0UbdGhuehly+f5VpBSFYWckldSNCVEVtJ0vxui0-AYo8zigzi-0w4DDSVQCFBAA

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

I only needed to add `@react-navigation/stack@6.3.15` and `@react-navigation/core@6.4.7` to the ts playground to reproduce.

**Comment by satya164** [comment]
Your types are incorrect. The first generic passed to `CompositeScreenProps` needs to be the type from the navigator that contains the screen. 

In the case of `LevelThreeStack`, it should be `StackScreenProps<LevelTwoParamList>` since it's inside `LevelTwoStack`, but you have `StackScreenProps<LevelOneParamList>`. So there's a type error due to the incompatible `route` prop type.

The `StackScreenProps<LevelThreeParamList>` shouldn't be there at all since it's for a child navigator and `CompositeScreenProps` is intended to combine props from the parent. I gather you have this because you want to be able to write `navigation.navigate("LevelThreeScreen")` in the `LevelThreeStack`, but it's not recommended to do this (and will be disabled by default in next major due to its problems) - types can't guarantee that this will work. This can break especially in the case of tab and drawer navigator where the navigators need to be focused first before navigating because of lazy rendering, or if you conditionally render the nested navigator. You should use nested navigation API instead.

**Comment by uloco** [comment]
Oh I get it, thank you!! :))))

**Comment by robertocandales** [comment]
@uloco I am facing the same issue, how did you fix it?

**Comment by uloco** [comment]
I just did what satya said above. I removed the current stack from the paramlist because it should not be included.
