### ISSUE TITLE
Safe Area Context Issues

### ISSUE THREAD

**Issue by jacobp100** [react-navigation/react-navigation#11285]
### Current behavior

We get a lot of issues over on [React Native Safe Area Context](https://github.com/th3rdwave/react-native-safe-area-context) about flickering - and every single issue is always using this library

I dug into the code a little bit here - nothing too deep.

I noticed you [aren't rendering a `SafeAreaProvider` in every screen](https://github.com/react-navigation/react-navigation/blob/4163cba6b7f9a4bdff1327cde59cea37e6438a59/packages/elements/src/SafeAreaProviderCompat.tsx#L38-L40). This is incorrect - you **must** to render this at the top of every screen that's backed by a native `UIViewController` (e.g. modals, stack navigators) - and **only** those backed by a native `UIViewController`. The linked issue is talking about a drawer navigation - unless you've done some native code here, that won't be backed by a `UIViewController`, so should have never had a `SafeAreaProvider`

I also noticed you're using [the hooks in places](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/NativeStackView.native.tsx#L21-L24), which [we've documented causes flickering](https://github.com/th3rdwave/react-native-safe-area-context#usesafeareainsets)

> Note that insets are not updated synchronously so it might cause a slight delay for example when rotating the screen.

I'm happy to provide pointers and information if you want to look into fixing these issues, but won't realistically be able to provide actual code fixes for you

### Expected behavior

Not relevant

### Reproduction

Not relevant

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

Not relevant

**Comment by satya164** [comment]
Can you provide more details on why our usage will cause flickering? Or link to some issues where flickering happens when using React Navigation so I have more idea about how it's being used? The comments on the linked issue seem to talk about a layout shift that is different from flickering.

The way we use it is intended to minimize flickering. If there are `SafeAreaProvider` components inside navigators and nested navigators inside a screen of a stack navigator, the insets keep updating if the screen is animating vertically. It causes severe flickering. Have there been any changes done regarding this so that it's now safe to use on every screen?

The way we use it makes sure that the insets never change due to a screen animating vertically by rendering only one `SafeAreaProvider` at the root of the app - which minimizes rapid safe area inset changes due to a parent animating. We can add it in each screen native-stack since it renders `UIViewController`s, but that'll only be a small part. We can't render the provider inside each screen in other navigators unless it no longer causes an issue due to animation.

We use the hook internally in many places such as the header and tab bar. So far we have never received a bug report of them flickering after we changed to the current usage of `SafeAreaProvider`. The only bug report we have received is about the insets not being correct on Android on startup when not using translucent header - which seems to be related to `initialWindowMetrics`. I understand the hook can cause a delay when the safe area insets change, but why would it cause flickering?

**Comment by jacobp100** [comment]
> I'd appreciate some links to existing issues so I understand which flickering we're talking about.

E.g. https://github.com/th3rdwave/react-native-safe-area-context/issues/104

The flickering is really caused by mixing SafeAreaView with hooks. They'll update at different times and give a flicker. If you only use hooks, they are delayed, but at least everything generally moves at the same time

> Though I'm not sure it's possible to get rid of useSafeAreaInsets entirely

It does look this way currently. Stuff like `useHeaderHeight` etc. I'm not exactly sure what that's needed for - you can just use `<SafeAreaView edges={['top']} />` to avoid the header. Also I noticed `getDefaultHeaderHeight` - that's going to be wrong if the user increased their font size, no?

As you say, if you did the change, it would likely cause enough disruption to say this is a breaking change. Maybe it would be good to remove those measurement hooks since they're not particularly safe, and the values can only be retrieved asynchronously

Maybe as an intermediate, you could provide your own export of SafeAreaView that just uses the hooks and applies the padding, recommend people use that and **not** the useSafeArea hooks, then if you do switch to the native SAV internally, it'll be an easier path for the users. We can update our documentation to point them to that if you do this

> There are no view controllers in other cases

Modals use view controllers - and stuff like the sheet layout has different safe areas to the full screen. If - and only if - a screen is backed by a `UIViewController`, it needs a `SafeAreaProvider`. If it's not backed by a `UIViewController`, it's generally a bad idea to use it (but nothing will crash)

A note too when you do this - you can't use initial metrics in any of these cases. That'll mean that your measurement hooks will get delayed further

**Comment by satya164** [comment]
> E.g. https://github.com/th3rdwave/react-native-safe-area-context/issues/104

Is the comment regarding incorrect value relevant to the linked repro with JS stack (at least by default)? Tbh there are no details in the issue so it's hard to understand.

> that's going to be wrong if the user increased their font size, no?

The font size doesn't affect the header height by default. If the header height is different, then the hook will measure and report the new height - but we also respect the custom height specified in `headerStyle` and will return that when possible.

> Maybe it would be good to remove those measurement hooks since they're not particularly safe, and the values can only be retrieved asynchronously

While I'd love to have less API surface, I can't just get rid of the hooks. If you have a transparent header or bottom tab bar, it's pretty important to be able to know the correct padding to apply to your content so it doesn't end up below the header. It being async isn't ideal but the alternative is to have a hardcoded height which can be different from the actual height.

Our current approach works well for most use cases.

> Maybe as an intermediate, you could provide your own export of SafeAreaView that just uses the hooks and applies the padding, recommend people use that and not the useSafeArea hooks

I feel like it won't solve the issue. Seems people use `SafeAreaView` already even when our documentation says not to use it, so people aren't reading the docs. It'll be hard to make them use the correct `SafeAreaView` if they aren't reading our docs.

It's also not possible to use `SafeAreaView` in all circumstances - e.g. if we have a `FlatList`, we'd ideally provide top/bottom padding in `contentContainerStyle` to have good styling. It's one of the things we mention in our docs so without a replacement we'd end up with 2 different approaches and won't get rid of the hook usage entirely.

The current hooks work well in most cases. So far I haven't really noticed the hooks causing any issues due to the async nature. In most use cases the values are already available since the `SafeAreaProvider` is at the root of the app, and we're able to provide the header height synchronously.

> Modals use view controllers - and stuff like the sheet layout has different safe areas to the full screen

None of the other React Navigation's navigators use native view controllers apart from `native-stack`. The modals in JS stack are JS implementations, not native modals.

From what I understand, the main issue seems to be:

- Mixing `SafeAreaView` and `useSafeAreaContext` - I think for React Navigation users it wouldn't have been an issue if they followed React Navigation documentation where we only use `useSafeAreaContext`. Maybe `react-native-safe-area-context`'s README can link to React Navigation docs for those users.
- Due to `UIViewController` in `native-stack` - I'll need to spend some time on it to come up with a good approach. Currently, safe area context is really only needed for the Android part of native-stack, and for approx header height calculation - which should really be exposed by native stack and not calculated like this. If it did. If this was addressed, we would able to wrap each screen in `SafeAreaProvider` in native-stack.

**Comment by denissdubinin** [comment]
My summary. According to `react-navigation` [docs](https://reactnavigation.org/docs/handling-safe-area/):

> The react-native-safe-area-context library also exports a SafeAreaView component. While it works on Android, it also has the same issues related to jumpy behavior when animating. So we recommend always using the useSafeAreaInsets hook instead and avoid using the SafeAreaView component.

So the solution is to use `useSafeAreaInsets` rather than `<SafeAreaView>`. I have made a custom component you can wrap your components with:
Instead of:
`import { SafeAreaView } from 'react-native-safe-area-context';`
use
`import SafeAreaView` from `.../components/SafeAreaView';`

Custom component:
It also supports `style` prop that will calculate additional paddings.
```
import { useCallback } from 'react';
import { View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const SafeAreaView = ({
    edges = ['top', 'bottom', 'left', 'right'],
    children,
    style = {},
    ...props
}) => {
    const insets = useSafeAreaInsets();

    const generatePaddings = useCallback(() => {
        return {
            paddingTop: edges.includes('top')
                ? insets.top + (style.paddingTop || style.paddingVertical || 0)
                : 0,
            paddingBottom: edges.includes('bottom')
                ? insets.bottom + (style.paddingBottom || style.paddingVertical || 0)
                : 0,
            paddingLeft: edges.includes('left')
                ? insets.left + (style.paddingLeft || style.paddingHorizontal || 0)
                : 0,
            paddingRight: edges.includes('right')
                ? insets.right + (style.paddingRight || style.paddingHorizontal || 0)
                : 0,
        };
    }, [style, edges]);

    return (
        <View style={ [style, generatePaddings()] } { ...props }>
            { children }
        </View>
    );
}

export default SafeAreaView;
```

**Comment by uzaymacar** [comment]
Works like a charm, thanks [denissdubinin](https://github.com/denissdubinin) :)
