### ISSUE TITLE
Https deeplinks not redirecting in the app

### ISSUE THREAD

**Issue by jamzi** [react-navigation/react-navigation#11715]
### Current behavior

I've added deeplink config to the Expo managed app. I'm using the React Navigation deeplink setup with "prefixes" and "config".

When I open a http link (from an app or via the npx uri-scheme), it opens the app, but it doesn't redirect to the correct screen.

The configuration is probably correct, as the custom scheme (example://) is working normally, but the https scheme is not.

### Expected behavior

The https scheme should correctly parses the path and redirects to the screen with passed in params.

### Reproduction

https://github.com/jamzi/expo-test-universal-links

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

  "dependencies": {
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "expo": "~49.0.15",
    "expo-dev-client": "~2.4.12",
    "expo-linking": "~5.0.2",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "expo-splash-screen": "~0.20.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },

**Comment by radko93** [comment]
Is your universal links config verified to be correct?

**Comment by Zhuxf1111** [comment]
> Is your universal links config verified to be correct?

Yes, the deep link can wake up my app, but there's no response in method getStateFromPath.

`const linking = {
    prefixes: [ "https://xxxxx"],
    getStateFromPath: (path: string) => {
      console.log("getStateFromPath", "path")
      // some logic
      return undefined
    },
  }`

**Comment by angelica-snowit** [comment]
Same here.
deep link works fine in ios (both with app schema and http), works fine on android with app shema but opening an url always stuck on the first page.

**Comment by MoeKanan** [comment]
Same here! the app will open, but will doesn't navigate to the correct screen.

If we try with deeplink scheme, it works fine

**Comment by MoeKanan** [comment]
> @MoeKanan did you figure this one out?

There were a couple of issues:

- Expo EAS build was invalidating the iOS provisioning profile whenever we ran EAS build with an outdated branch that doesn't have the new "associatedDomains" in `app.config.ts (or app.json)`. There is a workaround to stop EAS from generating a new provisioning profile and invalidating the current one by adding `EXPO_NO_CAPABILITY_SYNC=1 eas build` more info can be found here https://github.com/expo/eas-cli/issues/1069#issuecomment-1264111719

- for universal links to work, you need to configure your apple-app-site-association (AASA) and deploy it to your website something like https://your-domain/.well-known/apple-app-site-association  more info can be found here https://docs.expo.dev/guides/deep-linking/#aasa-configuration
  - expo has an experimental CLI tool that can help you generate the AASA file `npx setup-safari`
  - if you're using other services such as Adjust to deeplink into your app, then you will have to configure the associated domains for these services too
  
 Example: 
```json
// in app.json or app.config.ts
{
  "expo": {
    "ios": {
      "associatedDomains": ["applinks:expo.dev", "applinks:your-domain.com"]
    }
  }
}
```

For android, you will have to do the same, but it will be under "intentFilters" instead of "associatedDomains" and the structure is slightly different. 

Hope this helps. Cheers!

**Comment by MoeKanan** [comment]
@haleyngonadi I also forgot to mention that the deep-links schema needed to be all in lowercase. We tested deep-links by typing them into the Notes app on the iPhone and clicking on the links to open the app.

We noticed that if the deep link schema is Uppercase, it will open the app, but will not redirect to the correct screen.

for example:
- yourdomain://login <-- works fine ✅
- Yourdomain://login <-- loads the app, but doesn't deep-link to the screen ❌
