### ISSUE TITLE
Screens where a presentation is set do not close after navigating to a new screen. IOS only

### ISSUE THREAD

**Issue by shahinyan11** [react-navigation/react-navigation#11725]
### Current behavior

For example there is A,B,C screens and  the B screen's presentation is set  `transparentModal` . When I navigate  from A screen to B and then try to navigate C screen from B . The B screens stays open and C screen changes to A screen in background . 

### Expected behavior

Screen B should close and Screen C should become visible. (The behavior should be the same as Web or Android)

### Reproduction

[here is code to test ](https://snack.expo.dev/ZigOSgY3M?platform=ios)

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9
| @react-navigation/bottom-tabs          | 6.5.7
| @react-navigation/stack                | 6.3.20
| @react-navigation/native-stack         | 6.9.17
| react-native-gesture-handler           | 2.13.1
| react-native-reanimated                | 2.14.4
| react-native-tab-view                  | 3.5.2
| react-native                           | 0.71.8
| node                                   | 20.9.0
| yarn                            | 1.22.19

**Comment by RhyG** [comment]
Was about to open an issue with a [repro I created](https://github.com/RhyG/modal-nav-repro) for the same thing. Recently removed a layer of navigators to help with performance in a production app, and it introduced a number of issues where modals were no longer being dismissed when navigating. Ideally we don't have to include that navigator just for modals because the performance difference is noticeable.

**Comment by satya164** [comment]
No screens close when navigating to a new screen. Previous screens always stay rendered.

In case of modals, modals are always rendered on top of all other screens due to platform native behavior on iOS. And depending on the platform and type of stack navigator, it may also have strange animation if you push regular screens on top of modal screens. So this is not supported.

If you need to navigate to a regular screen from a modal screen, try `navigation.replace` instead.

https://reactnavigation.org/docs/modal/#best-practices

**Comment by shahinyan11** [comment]
Thx everyone for answers
