### ISSUE TITLE
[RFC] API for event emitter

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#1363]
### Motivation

- There are a lot of things that can happen in a navigator which the user might want to get notified of. Right now there is no standard way of doing that.
- Many times, the user needs to call an instance method in the screen component when something happens in the tabbar/header, currently the only way is to do `setParams`, which is messy.

### Use cases
- Scroll to top on tab press (#314)
- Scroll to top on header title press
- Refresh data in screen on header button press
- Save button (#145)
- Navigation events (#51)
etc.

### Inspiration

ExNavigation has a built in event emitter https://github.com/expo/ex-navigation/blob/master/example/components/EventEmitterExample.js#L95

Disregarding the use case in the given example, which is better done with `params`, it's nice how easy it is to interact with the current screen from the tab bar/header/drawer to do one off tasks like refreshing, scrolling, saving etc. which don't actually need to change the state.

### API

The API is simple, to attach a listener:

```js
this.props.navigation.addListener('tabPress', callback)
```

To remove a listener:

```js
this.props.navigation.removeListener('tabPress', callback)
```

To emit an event:

```js
this.props.navigation.emit('tabPress', data)
```

### Technical details

The events are always scoped to the screen where they are defined. Dispatching an event in one screen will not cause another screen to receive the events.

The listeners are stored in the navigator and hence don't need to be reattached when the `navigation` prop changes, which matches how people will expect it to work.

cc @ericvicenti @skevy @grabbou @DanielMSchmidt

**Comment by DanielMSchmidt** [comment]
First of all I like this approach of RFCs and also the proposed change. It is IMHO not overengineered and provides value for a lot of use cases. I have still some maybe a bit nooby questions:

- will we ignore the return value of the callback or should there be an.option to cancel these events or something similar? 
- will we dispatch redux actions for these events as well?
- what information will we pass to the callback?
- what additional cost of maintaining this do you expect?
- where will we need to touch the docs?

Hope this feedback helps more than it is idiotic 😇

**Comment by satya164** [comment]
> will we ignore the return value of the callback or should there be an.option to cancel these events or something similar?

It won't be possible to cancel all events, so I think we should ignore the return value. However it;s still possible to pass a function in the data to cancel the event if necessary (like `e.preventDefault`) etc.

> will we dispatch redux actions for these events as well?

I'd say no. Since these are aimed at cross-communication in a single screen. People can dispatch redux actions in response to an event if the want.

> what information will we pass to the callback?

It'll depend on who is dispatching the action.

> what additional cost of maintaining this do you expect?

Event listeners are usually simple, so I think it will not be very high.

> where will we need to touch the docs?

I think we will need to document specific events like `tabPress` etc. on their respective docs. And a general documentation for the event system.

**Comment by cooperka** [comment]
I'm very much in favor of this proposal, especially as compared to component lifecycle events (as discussed in https://github.com/react-community/react-navigation/issues/51). They're not mutually exclusive though, and I'm not going to reiterate any "this vs. that" arguments because there are already enough on the earlier issue.

I like the idea of these events being one-way (a la [flux](https://github.com/facebook/flux/tree/master/examples/flux-concepts)/redux), with no way to cancel them. They're simply events to notify other components of things that have happened which they might be interested in.

However, there still needs to be a way to cancel/ignore tap events. I think defining explicit `onPress` handlers is still the way to do this. Multiple observers can subscribe to receive events, but only one `onPress` can be defined; that method should have full authority over any actions taken by the default method, including whether or not an event is dispatched.

**Comment by satya164** [comment]
There could be several approaches we could use to handle cancelling/preventing navigation
- Receive an event object with a method to cancel it as argument
- Allow a navigation option to override default `onPress` behaviour for tabs/header button
- Implement a generic way of blocking navigation from a screen, which, I believe can be more useful

I think worth opening a new issue to discuss in detail

**Comment by 0x6e6562** [comment]
I'm porting an app from ExNavigation, so I am missing the event emitter capability. What is the current idiomatic way of accessing the state of a component from with the quasi-static context of rendering buttons in headers?

**Comment by 0x6e6562** [comment]
I ended following this workaround: https://github.com/react-community/react-navigation/issues/145#issuecomment-281418095

**Comment by dantman** [comment]
I like this idea. However there is one implementation detail I'd quibble about. I'd prefer the emitter api to match the one that `react-native` uses (and hence match the same api of every event based component/api of react-native you interact with).

react-native's emitter is a little different than node's api. Instead of `addListener` returning the emitter itself for chaining in `react-native` the emitter returns the subscription itself.

This leads to the following being a common pattern in react-native:
```js
// willMount
this._subscription = emitter.addListener('event', this._handler);

// willUnmount
if ( this._subscription ) {
  this._subscription.remove();
}
```

How this should be done in the implementation is undetermined. `react-native` doesn't export its `EventEmitter` directly, only exporting `NativeEventEmitter`. I would've suggested [`fbemitter`](https://www.npmjs.com/package/fbemitter) which implements that api an appears to be internally based on the same code as `react-native`'s emitter, however `fbemitter` is missing `removeListener`.

**Comment by satya164** [comment]
> this._subscription.remove();

Yea, we need to return the subscription and also allow removing the listener with `removeListener`. Probably a custom implementation is good enough. We don't need much and it's trivial to implement it.

**Comment by dantman** [comment]
> Probably a custom implementation is good enough. We don't need much and it's trivial to implement it.

We could copy the code from react-native. That pretty much seems to be be what fbemitter is, except missing part of the code.

**Comment by 0x6e6562** [comment]
@satya164 Can https://github.com/satya164/react-navigation-addons be used to re-implement the event emitter from ExNavigation? The examples in the README refer to standard lifecycle events, so can the event emitter be accessed in the (static) navigation to fire a custom event?

**Comment by 0x6e6562** [comment]
> I ended following this workaround: https://github.com/react-community/react-navigation/issues/145#issuecomment-281418095

After some initial success with this approach, I had to give up on it because it ultimately relies on a hack that comes undone when the navigation gets reset: https://github.com/react-community/react-navigation/issues/296#issuecomment-305858800

So now I'm looking into a custom header component, which is to an extent throwaway work, but at least allows me to continue.

**Comment by melihberberolu** [comment]
Is have any solutions ? 
I have tabnavigator in stacknavigator. If i'm home tab and scroll bottom after click tab icon scrollTo top. If my home tab stack index 1 or 2 .. and click tab icon trigger back route.
I think API for event emitter solution for me.

**Comment by JulianKingman** [comment]
@satya164 out of those options, onPress is most intuitive to me, as I expect navigation-related customizations to live in the navigationOptions. I think it would also lead to more organized code, as with listeners you would be canceling navigation actions on a per-screen basis, but without it being obvious where that's happening (or when, if it's in the wrong life cycle hook). The downside is the component props and state are then no longer available, but you could still dispatch a redux action from onPress if you needed to, so my vote is for that.

You could do both, and add a `preventDefault()` method to the event "just because", but I can't think of a case where that would be needed.

I don't understand your last option, or its benefits. Why would you want to block navigation?

**Comment by satya164** [comment]
> I don't understand your last option, or its benefits. Why would you want to block navigation?

Maybe for some reason you don't want the user to navigate away without providing some info or performing a task. People have asked for this feature.

**Comment by pavm035** [comment]
@satya164 Any  updates on EventEmitter use in TabNavigator ?

**Comment by galhardi** [comment]
+1

**Comment by sospedra** [comment]
@satya164 may we shall add this one into #2585 somehow?

**Comment by wellyshen** [comment]
YEA!!! You are right. This event can help us do many things. For example press a tab twice will reset the scroll view. It's very common sense in iOS. I tried to implement this behavior and I found it's hard to be implemented by current React-Navigation library :(

**Comment by wellyshen** [comment]
@sospedra Sure, please count it into Roadmap!!

**Comment by sibelius** [comment]
can we use some package to solve this in meanwhile?

**Comment by sibelius** [comment]
easy way

```jsx
import { EventEmitter } from 'fbemitter';

const eventEmitter = new EventEmitter();

componentWillMount() {
    this._subscription = eventEmitter.addListener('onBack', this.handleBack);
  }

  componentWillUnmount() {
    this._subscription.remove();
  }

eventEmitter.emit('onBack')

```

**Comment by ericvicenti** [comment]
Ok I want to help make this happen!

For those interested in the API, can you review the RFC here? https://github.com/react-navigation/rfcs/pull/1

**Comment by gesf** [comment]
Great idea! Is this out already ?
