### ISSUE TITLE
Multiple URI Prefixes

### ISSUE THREAD

**Issue by keplersj** [react-navigation/react-navigation#1455]
### Current Behavior
Components created from Navigators currently only take one single URI prefix string.

```jsx
<App uriPrefix="https://example.com/"/>
```

### Expected Behavior
In order to work with [Apple's Universal Links](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html) and [Android's App Links](https://developer.android.com/training/app-links/index.html) which both allow for multiple http(s) URL prefixes the navigator needs to be able to handle multiple URI prefixes.

```jsx
<App uriPrefix={['https://example.com/', 'http://example.com/',' https://www.example.com/', 'http://www.example.com/', 'https://example.co/', 'http://example.co/', 'https://www.example.co/', 'http://www. example.co/']}/>
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  `git+https://github.com/react-community/react-navigation.git#ff99d6e`
| react-native     |  `0.43.3`
| node             | `v7.10.0`
| npm or yarn      | `v0.23.4`

**Comment by kevinresol** [comment]
You can use regular expressions.

For example, use this:

```js
uriPrefix={ /(?:http|https):\/\/(?:www\.)?example\.com\// }
```

to match:

- http://example.com
- https://example.com
- http://www.example.com
- https://www.example.com


Explanation: 

In the core code it uses [`string.split(uriPrefix)[1]`](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/createNavigationContainer.js#L91) to get the path part. Since `split` takes also regexp, so it will work out of the box. However, since `split` will emit captured values as well and it is hardcoded to get the value at index 1, having capturing groups in the regexp will screw things up. So be careful not to capture anything in your regex. See how I used a [non-capturing group](http://www.regular-expressions.info/brackets.html#noncap) `(?:___)` to achieve that.

**Comment by kelset** [comment]
Pinging OP @keplersj since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, the answer provided by @kevinresol is good.

**Comment by keplersj** [comment]
@kevinresol's answer has been working for us for a while now. Good to close for me

**Comment by kevinresol** [comment]
Please note that my comment includes some caveat that I think should be fixed.

**Comment by kelset** [comment]
Got it. But tbh I can't think of a situation where the incoming url can have that precise "pattern", given how they needs to be defined at iOS/Android level. Or can it happen?

**Comment by brentvatne** [comment]
good points here. moved this to a feature request: https://react-navigation.canny.io/feature-requests/p/support-multiple-uri-prefixes-via-array

**Comment by Ury18** [comment]
Hi! Correct me if I'm wrong, but this doesn't work anymore, right? I've tries it and made a build, but when opening the app it loads the splash screen and then reloads it a few times after showing a timeout error. 

I need help linking my app to https urls, could you please help me? I posted my issue here: [https://stackoverflow.com/questions/56170823/how-to-deep-link-https-urls-with-react-navigation](url)

**Comment by devtanc** [comment]
```js
const searchMatch = url.match(/^(.*)\?(.*)$/);
const params = searchMatch ? queryString.parse(searchMatch[2]) : {};
const urlWithoutSearch = searchMatch ? searchMatch[1] : url;
const delimiter = uriPrefix || '://';
let path = urlWithoutSearch.split(delimiter)[1];
```
@kevinresol Actually, since the url is split on the `?` character on that first line, the split is only run on the host and the path, without the query parameters. This makes it so that your case will still work.

I'm working on this feature right now, so I added a test with your exact case just to make sure this was a non-issue.

**Comment by halaei** [comment]
The regular expression support is still needed, because I think uriPrefix should be case-insensitive, especially in schema and domain parts. That is, if `http://example.com/foo` works, so should `Https://example.com/test` and `http://Example.com/test`.
