### ISSUE TITLE
Improve performance for React Navigation

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#1466]
I have heard several people say that the perf on low-end Android devices is bad. And it's not quite as fast as ex-navigation used to be in my mid-end Android device either.

Some easy to fix issues will be:
1. Identify unnecessary re-renders and optimize them
2. Cache stuff like navigation options

**Comment by aqnaruto** [comment]
ex-navigation is much better than this one .

**Comment by AlanFoster** [comment]
@satya164 As a new comer to react-native, how can someone contribute to this issue?

> 1. Identify unnecessary re-renders and optimize them

What would be the best approach to investigate this further? As far as I can tell for react-native the Perf tools still work, but would we need to use systrace etc for this particular issue?

Out of curiosity; Are there any tools for showing react-native redraws visually, such as Chrome's functionality or the React Developer tools?

**Comment by aqnaruto** [comment]
ok,it not not quite as fast as ex-navigation used to be, and it is still not surport goback-gesture in android

**Comment by AlanFoster** [comment]
@satya164 I've been looking into this more, viewing react native react videos etc. I'm more aware of systrace now. 

Unfortunately it's not well documented how to compile the react native ios simulator yourself to enable the Javascript flame graph profiler.  Do you have any context on this @satya164? I'd love to take a deeper look into this

**Comment by AlanFoster** [comment]
### Identify unnecessary re-renders and optimize them

react-navigation has some components that bind a new function on each render, which doesn't satisfy `PureComponent`. I have put a PR up to fix one of these issues https://github.com/react-community/react-navigation/pull/1913

The most expensive renders seem to be related to the Card/Container components, I believe this is due to the inline styles that are being used to calculate the position:

![image](https://user-images.githubusercontent.com/1271782/27265052-0d7f5460-5486-11e7-8d8a-54f4d3da3753.png)

### Cache stuff like navigation options

Caching navigation options would be good; Particularly in the redux examples which create new goBack/navigate/setParam functions on each state change. I was able to partially cheat with a small shim locally - but I'm not sure what the best library level API Is for this. Perhaps a higher order component, something similar to recompose?

For the mean-time I had just gone with a small shim based on the default redux example:

```
const navigationCacher = function () {
  let _helpers = undefined;
  const cachedFunctions = {
    goBack(...args) {
      return _helpers.goBack.apply(undefined, args);
    },

    navigate(...args) {
      return _helpers.navigate.apply(undefined, args);
    },

    setParams(...args) {
      return _helpers.setParams.apply(undefined, args);
    }
  }

  return function (navigation) {
    _helpers = addNavigationHelpers(navigation);

    return {
        ..._helpers,
        ...cachedFunctions
    };
  }
}

const addCachedNavigationHelpers = navigationCacher();
const AppWithNavigationState = ({ dispatch, nav }) => (
  <AppNavigator navigation={addCachedNavigationHelpers({ dispatch, state: nav })} />
);

const mapStateToProps = function (state) {
  return {
    nav: state.nav,
  };
}

const mapDispatchToProps = function (dispatch) {
  return {
    dispatch
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(AppWithNavigationState);
```

### Disable logging

The latest change to the logging code was https://github.com/react-community/react-navigation/commit/0f6b32868796a92a2a77a224b9140d6d5e02184e which offers a `onNavigationStateChange ` callback. I think this has been added a nice luxury for react-navigation developers, but it would be possible to change the behaviour to no longer log by default. Instead we could offer a default implementation that _could_ be used - and for developers actively working on react-navigation it wouldn't take much effort to make use of this default implementation - i.e. the current logging implementation.

Thoughts? 🤔

**Comment by satya164** [comment]
@AlanFoster thanks a lot for your help!

I prefer disabling logging by default. We should be performant by default without needing the developers to manually do it.

cc @skevy

**Comment by farwayer** [comment]
Guys I'm terrified what happened with old-fashioned NavigationExperimental when it was moved to react-navigation. I used some components from NavigationExperimental (CardStack) and now I tried to use the same parts from react-navigation. Unfortunately it works in times slower.
https://youtu.be/Q_0eqaRJiXo
https://youtu.be/DA5bnRcQ3D4

**Comment by kelset** [comment]
Closing this issue in favor of https://github.com/react-community/react-navigation/issues/739 (and also look here for [more info](https://github.com/react-community/react-navigation/issues/608#issuecomment-328635042) related to performances)
