### ISSUE TITLE
Handling back button for deep links

### ISSUE THREAD

**Issue by markdaws** [react-navigation/react-navigation#1477]
Hi - so I've been trying to add deep links to my app, it works to navigate to the desired view on load, but in the case where you have nested navigation, how do you get the back button work work correctly.  For example, lets say in my app the navigation structure looks like (using a StackNavigator):

TeamList -> Team -> Player

When you open the app, you see a list of teams, you click on one to drill down to a team, then that shows a list of players in the team, and you can click on one.  In this scenario, you can click Back to go from Player -> Team and back again to go from Team -> TeamList, however lets say I deeplink the Player screen to path: '/teams/:teamId/:playerId

When I load the app with deep linking, it loads the player screen but the back button doesn't work, I want to go back to the team screen then the teams screen.  How do I setup a navigation back history in deep linking if that makes sense.

Thanks

**Comment by JAStanton** [comment]
Any update on this? In particular I'm trying to suss out what the behavior of deep linking is.

**Comment by PatNeedham** [comment]
@markdaws I've been investigating how this library handles deep links recently and am now able to determine where the back button problem you're referring to originates from - if by saying `but the back button doesn't work` you mean after clicking it and once the back transition completes, you see the exact same screen (player screen) as before, but this time without a back button. Because that's the scenario I've run into.

@spencercarli I'm pretty sure this should get categorized as a bug and not an enhancement because (at least in my opinion) if you see a back button you'd expect to be taken back to the previous screen.

I submitted a [pull request](https://github.com/react-community/react-navigation/pull/2695) for an issue slightly related to this - in the sense that deep links aren't working properly - but what I didn't even try was clicking the back button there. To diagnose exactly how that extra duplicate screen was getting added onto the navigation stack, I printed to the console [what's getting returned](https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L397) from `StackRouter`'s `getActionForPathAndParams` function.

```
return NavigationActions.navigate({
    routeName: matchedRouteName,
    ...(params ? { params } : {}),
    ...(nestedAction ? { action: nestedAction } : {}),
  });
```

became

```
var whatToReturn = NavigationActions.navigate({
  routeName: matchedRouteName,
  ...(params ? { params } : {}),
  ...(nestedAction ? { action: nestedAction } : {}),
});
console.log("returning it here as: " + JSON.stringify(whatToReturn, null, 2))
return whatToReturn
```

The minimal demo app from my pull request linked to above has a navigation structure like this:
Top-level nav is a `StackNavigator` with two children

1. `Home` with the screen property being a React component.
2. `TheTabs` with the screen property being a `TabNavigator`.
    1. Tab 1 inside that tab bar has a screen property being a React component
    2. Tab 2 inside has screen property being a `StackNavigator`
        1. Screen 1 inside Tab 2 is a regular React component.
        2. Screen 2 inside Tab 2 is a regular React component.

After opening from launcher and manually navigating to screen 2 (inside tab 2), and using `onNavigationStateChange` as detailed within the [screen tracking guides](https://reactnavigation.org/docs/guides/screen-tracking) to log what the current state is, here is how that state looks:
```
{
  "index": 1,
  "routes": [
    {
      "routeName": "Home",
      "key": "Init-id-1507216159657-0"
    },
    {
      "routes": [
        {
          "key": "Tab1",
          "routeName": "Tab1"
        },
        {
          "index": 1,
          "routes": [
            {
              "routeName": "Nested1",
              "key": "Init-id-1507216159657-1"
            },
            {
              "key": "id-1507216159657-3",
              "routeName": "Nested2"
            }
          ],
          "key": "Tab2",
          "routeName": "Tab2"
        }
      ],
      "index": 1,
      "key": "id-1507216159657-2",
      "routeName": "TheTabs"
    }
  ]
}
```

When I open the app via deep link to access that same screen 2 inside Tab 2 (command I ran is `adb shell am start -W -a android.intent.action.VIEW -d "mychat://mychat/tabs/tab-2/foo/bar"`), the `currentState` being logged has an important difference:
```
{
  "index": 1,
  "routes": [
    {
      "routeName": "Home",
      "key": "Init-id-1507216106092-0"
    },
    {
      "routes": [
        {
          "key": "Tab1",
          "routeName": "Tab1"
        },
        {
          "index": 1,
          "routes": [
            {
              "routeName": "Nested2",
              "params": {
                "id1": "foo",
                "id2": "bar"
              },
              "key": "Init-id-1507216106092-1"
            },
            {
              "params": {
                "id1": "foo",
                "id2": "bar"
              },
              "key": "id-1507216106092-2",
              "routeName": "Nested2"
            }
          ],
          "key": "Tab2",
          "routeName": "Tab2"
        }
      ],
      "index": 1,
      "key": "id-1507216106092-3",
      "routeName": "TheTabs"
    }
  ]
}
```

The difference is that for the first (correct) navigation state created by going manually to that nested screen, it has the basic structure of: 
```
index: 1
routes: [
  { routeName: "Home" },
  {
    routes: [
      { routeName: "Tab1" },
      {
        index: 1,
        routes: [
          { routeName: "Nested1" },
          { routeName: "Nested2" }
        ]
    ]
]
```
while the (incorrect) navigation state created after opening the deep link looks like:
```
index: 1
routes: [
  { routeName: "Home" },
  {
    routes: [
      { routeName: "Tab1" },
      {
        index: 1,
        routeName "Tab2"
        routes: [
          {
            routeName: "Nested2"  // SHOULD BE Nested1
            params: { id1: "foo", id2: "bar" }
          },
          {
            routeName: "Nested2",
            params: { id1: "foo", id2: "bar" }
          }
        ],
    },
]
```

So for some reason, the screen opened from the deep link is being pushed onto the navigation state twice. Here is what the logging output I mentioned earlier (from printing the `NavigationActions.navigate({ ... })` object returned by the `getActionForPathAndParams` function) looks like for the incorrect deep link:
```
returning it here as: {
  "type": "Navigation/NAVIGATE",
  "routeName": "Nested2",
  "params": {
    "id1": "foo",
    "id2": "bar"
  }
}

returning it here as: {
  "type": "Navigation/NAVIGATE",
  "routeName": "TheTabs",
  "action": {
    "type": "Navigation/NAVIGATE",
    "routeName": "Tab2",
    "action": {
      "type": "Navigation/NAVIGATE",
      "routeName": "Nested2",
      "params": {
        "id1": "foo",
        "id2": "bar"
      }
    }
  }
}
```

I can't compare that to how it's printed while manually navigating to Screen 2 in Tab 2 from the app's Home screen (it doesn't get printed because `getActionForPathAndParams` function never runs in that scenario), but I think the key piece missing from above is that it's not specified while navigating to `TheTabs` to run a sequence of navigations - like "first navigate to the root screen in the stack, then perform the action navigating to the nested screen".

To highlight this omission, you can have a much simpler `StackNavigator` with three children:

```
const Tab2Screen = StackNavigator({
  Nested1: {screen: Tab2Screen1, path: ':id1'},
  Nested2: {screen: Tab2Screen2, path: ':id1/:id2'},
  Nested3: {screen: Tab2Screen3, path: ':id1/:id2/:id3'}
})
```

When I made that stack nav the top-level component in the app, and run the command to open the deep link `adb shell am start -W -a android.intent.action.VIEW -d "mychat://mychat/foo/bar/baz"`, it does go to screen 3 as expected, but pressing the back button returns you directly to screen 1 (not screen 2 as expected). This is due to [`getActionForPathAndParams` using `pathNameToResolve`](https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L342) to find a match, when it really should be spitting up `pathNameToResolve` into separate paths in the case (like this) where there are forward slashes (/) inside the path name. Path "foo/bar/baz" should be split by the forward slashes so that it first checks if anything matches "foo", and if it does, great, now check if anything matches "foo/bar" and if so, add that to the `action` key for whatever nested action will eventually be returned. Then finally check if anything matches "foo/bar/baz"

The current way that `action` key is specified is from [this line](https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L399) within the code:
```
return NavigationActions.navigate({
  routeName: matchedRouteName,
  ...(params ? { params } : {}),
  ...(nestedAction ? { action: nestedAction } : {}), // includes the nested action if there is one
});
```

That means the current way `nestedAction` gets created isn't working properly:
```
// Determine nested actions:
// If our matched route for this router is a child router,
// get the action for the path AFTER the matched path for this
// router
let nestedAction;
let nestedQueryString = queryString ? '?' + queryString : '';
if (childRouters[matchedRouteName]) {
  nestedAction = childRouters[matchedRouteName].getActionForPathAndParams(
    /* $FlowFixMe */
    pathMatch.slice(pathMatchKeys.length).join('/') + nestedQueryString
  );
}
```

Instead of using `pathNameToResolve` to determine `pathMatch` (`pathMatch = re.exec(pathNameToResolve);`), it should really be using a new variable such as:
```
const currentPath = pathNameToResolve.split('/').length > 0 ? pathNameToResolve.split('/')[0] : pathNameToResolve;
```

And the check that determines if a nested action is necessary (`if (childRouters[matchedRouteName])`) needs to change as well, in the case where `currentPath !== pathNameToResolve`. For that change, I think the best approach is to have a helper function that gets the next path to check. Because if the original is "foo/bar/baz" and the currentPath is "foo", we want the next path used to be "foo/bar". And for "foo/bar" we want the next (and final) to be "foo/bar/baz":
```
function getNextPath(original, current) {
   if (original === current) return undefined // there's no need for a next path because current is the final one
  var arr = original.split('/')
  for (var i = 1; i < arr.length; i++) {
    if (arr.slice(0, i).join('/') === current) {
      return arr.slice(0, i + 1).join('/')
    }
  }
  return undefined // original and current arguments were poorly formatted to begin with
}
```
`getNextPath("foo/bar/baz", "foo")` returns `"foo/bar"`, and `getNextPath("foo/bar/baz", "foo/bar")` returns `"foo/bar/baz"`.

The problem now is that we can't simply get the next path and use that to replace `pathNameToResolve`, because that next path on its own doesn't inherently know what the original path is, and therefore `getActionForPathAndParams` within `StackRouter` would only work up to two nested levels deep. One thing I'm attempting to do is change the function signature for `getActionForPathAndParams` so that it accepts an optional second parameter `originalPath`. In the case where `originalPath` is empty or missing, we'd use the value of `pathNameToResolve` as its substitute. That works fine, but since there are no child routers involved for the example of a `StackNavigator` with three regular React components as the children screens, `nestedAction` never gets assigned. @skevy @matthamil what would be the consequences of letting `NavigationActions.navigate` accept an object with key `actions`? Either using that in addition to the existing `action` or as a replacement - so that for deep linking cases like this it's possible to specify how the nav state should be formatted. What is the reasoning behind `NavigationActions.reset` accepting an 'actions` key but not `NavigationActions.navigate`?

**Comment by spencercarli** [comment]
@PatNeedham changed to bug. Honestly, you probably know more about the deep linking than I do at this point. Wish I had an answer for your questions!

**Comment by davepack** [comment]
Hey @PatNeedham, I would say the reason `navigate` does not take `actions` is precisely because `reset` does. In other words, just use `reset` in the case where you would want to apply more than one action on a single stack navigator.

**Comment by ericvicenti** [comment]
Hey folks, is there still an issue here? If so, could you file it as a new issue with a clear repro, for the current version of the library? I'm closing this one out because its hard to tell what is broken.

I will note that the deep linking behavior is slightly broken, even in current releases. I have overhauled it and added a bunch of tests in this PR here: https://github.com/react-navigation/react-navigation/pull/4671

So, if you have issues with the latest release, please try the code in the PR and see if it fixes your problem!
