### ISSUE TITLE
Redux integration docs and official example show bad practice in terms of dependencies

### ISSUE THREAD

**Issue by R1ZZU** [react-navigation/react-navigation#1809]
As per official docs and example, nav reducer depends on Navigator, which depends on components. This doesn't break anything, but `reducer` ⬅ `component` dependency seems really weird. Is there an option to break this dependency chain?

* [Reducer imports AppNavigator](https://github.com/react-community/react-navigation/blob/master/examples/ReduxExample/src/reducers/index.js#L4)
* [Navigator imports components](https://github.com/react-community/react-navigation/blob/master/examples/ReduxExample/src/navigators/AppNavigator.js#L6)

**Comment by azundo** [comment]
@R1ZZU Here's what I came up with to break the dependency on my own components by instantiating a dummy router directly:

```
import {TabRouter} from 'react-navigation';
import {View} from 'react-native';

const router = TabRouter({
  Screen1: {
    screen: View,
  },
  Screen2: {
    screen: View,
  },
  Screen3: {
    screen: View,
  },
  Screen4: {
    screen: View,
  },
});

const initialState = router.getStateForAction(
  router.getActionForPathAndParams('Screen1'));

export default function reducer(state = initialState, action) {
  const nextState = router.getStateForAction(action, state);
  return nextState || state;
}
```

Still need to DRY it up between the route configs here and the ones passed to the navigator. Did you ever come up a workaround? Would love to compare notes if so.

**Comment by xiaohanzhang** [comment]
@azundo Sorry, I don't think I understand your example. 
In my understanding, your **reducer** require **router**, **router** require **Component**. I didn't see this break any dependency.

**Comment by azundo** [comment]
@xiaohanzhang Ah, sorry, the generic naming isn't super clear. The Component here is just a generic placeholder `View` (which is only required due to react-navigation's typing). The router doesn't really care about what component is passed under the screen key (except for the nested navigators case) so now this example doesn't depend on any local component, just the globally available `View`.

**Comment by xiaohanzhang** [comment]
@azundo Thanks, I get it now. I think this solution is on the right track, but it is too hacky to me. 
I am wondering if it is possible to re-design the router, it shouldn't require screenConfig at startup time.

**Comment by azundo** [comment]
@spencercarli Does this have a resolution in an upcoming version? This issue makes react-native-navigation a poor replacement for the deprecated NavigationExperimental. I have resorted to using https://github.com/goshakkk/react-native-navigation-experimental-compat in order to keep a clean reducer/view separation.

**Comment by spencercarli** [comment]
Looks like this was incorrectly label and closed (was automated). Will re-open to investigate further

**Comment by kelset** [comment]
Pinging OP @R1ZZU since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

Moreover, a PR with clarifications / a better wording would be much appreciated. We have already added, in order to provide a "quick fix" to the docs, a new section in the README with articles, tutorials & examples to help devs understand how to use the lib.

**Comment by R1ZZU** [comment]
@kelset correct me if I'm wrong, but I believe this issue is still legit. 

from official docs:

```javascript
const navReducer = (state = initialState, action) => {
  const nextState = AppNavigator.router.getStateForAction(action, state);

  // Simply return the original `state` if `nextState` is null or undefined.
  return nextState || state;
};
```
`reducer` depends on `AppNavigator`

```javascript
const AppNavigator = StackNavigator(AppRouteConfigs);
```

`AppNavigator` depends on `AppRouteConfigs` where `AppRouteConfigs` is a mapping from route name to a route config, which should contain _component_ as value for `screen` key, so `reducer` <= `Navigator` <= `View` dependency chain is still there

**Comment by JulianKingman** [comment]
I'd love to see this change, as it is I'm getting dependency problems while setting up a new project (`undefined is not an object (evaluating AppNavigator.router)`).

**Comment by brentvatne** [comment]
a pull request to improve redux documentation (now living in https://github.com/react-navigation/react-navigation.github.io) would be welcome. sounds like a nice thing to have, please send a PR!

**Comment by R1ZZU** [comment]
@brentvatne I believe this issue is not about documentation enhancement, but architecture rethink. If this design was intended to be as it is, could you please briefly explain a motivation behind this decision, just wondering 😉

**Comment by brentvatne** [comment]
@ericvicenti could speak to that
