### ISSUE TITLE
DrawerNavigator inside TabNavigator won't open on finger swipe

### ISSUE THREAD

**Issue by divonelnc** [react-navigation/react-navigation#1849]
Hello,

When I nest a DrawerNavigator inside a TabNavigator, it becomes impossible to open the Drawer with a finger swipe. The Drawer will follow the finger up to a very small distance (about 10 pixels) and then close immediately.

Here is the minimum code required to trigger the bug (I have it when the following code describes my whole app)

```
import React, { Component } from "react";
import { View, Text } from "react-native";
import { TabNavigator, DrawerNavigator, StackNavigator } from "react-navigation";

class DrawerScreen extends Component {
  render() {
    return (
      <Text>
        Drawer Screen Content
      </Text>
    );
  }
}
class TabScreen extends Component {
  render() {
    return (
      <Text>
        Tab Screen Content
      </Text>
    );
  }
}

export default class NavSample extends Component {
  state = {};

  render() {
    const Drawer = DrawerNavigator(
      { DrawerScreen: { screen: DrawerScreen } },
      { drawerPosition: "right" }
    );

    const Tab = TabNavigator({
      TabScreen: { screen: Drawer }
    });

    return <Tab />;
  }
}
```

| software         | version
| ---------------- | -------
| react-navigation |  4.2.0
| react-native     |  0.5

Am I missing something? :(

**Comment by jcaspian** [comment]
Why not nest your navigators like this:

    StackNavigator
    - TabNavigator
    - DrawerNavigator

With `headerMode: 'none'` for the StackNavigator's config.

Android Twitter-like example:

    StackNavigator
    - Login Screen
    - Home Screen
      + TabNavigator
        - Feed
        - Search
        - Notifications
        - Messages
    - DrawerNavigator
      (custom made the content & drawer list to call navigation.navigate)
    - Profile
    - Highlights
    - Moments
    - Lists
    - Connect
    ...etc

Play around with the nesting level. Think of how you want your application to navigate between screens and nest the navigators properly.

**Comment by divonelnc** [comment]
I put the minimum code required to trigger the issue, but it's not representing what I am trying to achieve.
I want the Drawer to only exist in a specific tab. In your example, I would want the DrawerNavigator to only be available in the "Feed" tab, for example.

**Comment by divonelnc** [comment]
Also, if I modify the `DrawerScreen` code to have a button to open the drawer as such:

```
class DrawerScreen extends Component {
  render() {
    return (
      <View>
        <Text>
          Drawer Screen Content
        </Text>
        <Button
          title="open drawer"
          onPress={() => this.props.navigation.navigate("DrawerOpen")}
        />
      </View>
    );
  }
}
```

The drawer still won't open when I click the button. Only the semi-transparent black layer will appear but the drawer will sill be hidden.

**Comment by yeajig** [comment]
the same problem for me

**Comment by dk0r** [comment]
I'm seeing the same issue with the disappearing `Drawer`. However, adding a `Drawer` to a `Screen` within a `TabNavigator` should be a highly typical use case, so shouldn't there be more complaints?
  
Perhaps we are missing another way of implementing a nested `Drawer`?

**Comment by papmodern** [comment]
I have this exact problem and when I change drawerPosition to left it works perfectly!

**Edit:**
I think I figured it out why!
So it seems the problem is related to"disabled" swipe action of TabNavigator. 
drawerPosition to right with the latest tab in left selected, It works normally. 
drawerPosition to left with the latest tab in right selected, It works normally.
It's because when the latest tab in right is selected, there is no swipe action to left so maybe the TabNavigator disabled that and prevent to send the event to DrawerNavigator! and vice versa.

**Comment by soundstage** [comment]
Having this same issue.

Regardless of left or right, DrawerLayoutAndroid does not seem to want to open up as tab navigator's swipe triggers are given higher priority. So it has now become impossible to open up DrawerLayoutAndroid with a single swipe. I am forced to retry many times before it opens up.

**Comment by donni106** [comment]
Wow! Accidentally I have a fix! 💥 

With enabling the scroll for tabs per TabNavigatorConfig, the Drawer works!

```
tabBarOptions: {
    scrollEnabled: true
  }
```

**Comment by trsh** [comment]
Same problem here. scrollEnabled: true doesn't help

**Comment by stevenpal** [comment]
I'm experiencing the same issue.  Works on iOS but not Android.  Just to add some additional observations:

1) You can get the drawer to open and appear on the screen if you swipe using a gesture.  When the drawer opens, there's a semi-translucent background that appears (as expected).  However, the only way to close the drawer is via a swipe.  Having a button that calls DrawerClose just removes the semi-translucent background, but the drawer remains open on the screen.  In addition, having a button on screen that calls DrawerOpen only toggles the semi-translucent background.  So generally speaking, DrawerOpen, DrawerClose, and DrawerToggle just influence the semi-translucent background -- not the drawer.  Given this is inside a tab navigator, it's easier to observe this behavior if you set `swipeEnabled` to false in the enclosing TabNavigator (otherwise your swipe might be handled by the TabNavigator).

2) Nesting a DrawerNavigator inside a StackNavigator (instead of a TabNavigator) seems to work fine on Android.  I may pursue this as an alternative solution until the issue is resolved.  Has anyone else tried this?

**Comment by Loliner** [comment]
`tabBarOptions: {
  scrollEnabled: true
}`
is work, but the style of tab should be change by ourself.

**Comment by getgetxx** [comment]
Hello, 
Same issue for me...
My workaround with no width problem is :  
```
tabBarOptions: {
    scrollEnabled: false,            
},
animationEnabled:false,
```

**Comment by brentvatne** [comment]
general advice is don't make drawer children of tabs right now

**Comment by brentvatne** [comment]
https://snack.expo.io/S1YmEvR6M

works as expected on bottom tabs. don't do this with top tab navigator though :P

moving into umbrella issue
