### ISSUE TITLE
[Feature] Show error when user tries to navigate to unknown screen

### ISSUE THREAD

**Issue by iRoachie** [react-navigation/react-navigation#1890]
### Current Behavior

Navigating to a screen that doesn't exist doesn't show any errors or anything.

### Expected Behavior

Navigating to a new screen with `this.props.navigation.navigate('screen')` should show an error or warning if the screen isn't registered in the navigator. Currently no feedback is provided to the developer.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45
| node             | 8.0
| npm or yarn      | 5.0, 0.24.6

**Comment by matthamil** [comment]
You can override your router's `getActionForPathAndParams` to achieve this. Look at [this](https://github.com/react-community/react-navigation/blob/673b9d2877d7e84fbfbe2928305ead7e51b04835/docs/api/routers/Routers.md#handling-custom-uris) to see an example of overriding `getActionForPathAndParams`. This method takes a string path and returns a `NavigationAction` if it finds a valid screen path. You can override this method to throw an error instead of returning `null` [like it currently does](https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L347-L350). If you think this should be a part of the library (i.e. a feature request), I encourage you to open a new issue or comment again, otherwise I will close this one for now.

**Comment by iRoachie** [comment]
@matthamil Sorry my bad, I was a suggesting a feature

**Comment by vonovak** [comment]
@iRoachie would you be willing to submit a PR for this?

**Comment by iRoachie** [comment]
Sure! I don’t mind. Any tips you can give me?

**Comment by kelset** [comment]
@iRoachie I think you can start by reading https://github.com/react-community/react-navigation/blob/master/docs/CONTRIBUTING.md

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
