### ISSUE TITLE
onNavigationStateChange is incompatible with Redux integration

### ISSUE THREAD

**Issue by jordanmkoncz** [react-navigation/react-navigation#2074]
### Current Behavior
If you've integrated react-navigation with Redux, you will have an AppNavigator like the following:

```
<AppNavigator
  navigation={addNavigationHelpers({ dispatch, state: navState })}
/>
```

If you then try to update your AppNavigator to the following:

```
<AppNavigator
  navigation={addNavigationHelpers({ dispatch, state: navState })}
  onNavigationStateChange={null}
/>
```

The app will fail to run due to an error: "This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "onNavigationStateChange" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop."

But adding `onNavigationStateChange` like this is the recommended solution for disabling react-navigation's default logging, as shown at https://github.com/react-community/react-navigation/issues/360#issuecomment-296690849 and https://reactnavigation.org/docs/navigators/#onNavigationStateChange-prevState-newState-action.

The error is coming from `NavigationContainer._validateProps` in `react-navigation/src/createNavigationContainer.js`, which is preventing the app from running when you've passed a navigation prop to the navigator (meaning the navigator is not "stateful") and then you also try to pass `onNavigationStateChange`.

### Expected Behavior
Allow `onNavigationStateChange` to be used alongside Redux integration so that the solution of passing `onNavigationStateChange={null}` to the navigator will work for people using Redux with react-navigation.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1

**Comment by punksta** [comment]
have this issue too.

**Comment by goleador0322** [comment]
me too......... <img src="http://cultofthepartyparrot.com/parrots/parrotdad.gif" height="23" />

**Comment by tom-p-uk** [comment]
+1

**Comment by DiogoAbu** [comment]
Maybe this can help: https://github.com/react-community/react-navigation/blob/master/docs/guides/Screen-Tracking.md
Source: https://www.reddit.com/r/reactnative/comments/69xm4p/react_navigation_tab_change_event/

**Comment by jordanmkoncz** [comment]
@DiogoAbu could you clarify how that applies here? This issue is specifically relating to adding the `onNavigationStateChange` prop to your root AppNavigator, and the error that results from this if you're using the Redux integration approach.

**Comment by jose920405** [comment]
+1

**Comment by JingLiangWen** [comment]
+1

**Comment by kelset** [comment]
@JingLiangWen @jose920405 @tom-p-uk @goleador0322 @punksta please don't pollute issues with useless comments. There's the 👍 emoji for that.

**Comment by ShMcK** [comment]
I found a workaround, which doesn't involve fixing the underlying incompatibility issue.

Add redux middleware which can listen to dispatched navigation route changes.

```js
const reactNavigationMiddleware = store => dispatch => action => {
  switch (action.type) {

      case 'Navigation/NAVIGATE':
        const { routeName } = action.routeName
        // do something

      case 'Navigation/RESET':
        const { routeName } = action.actions[action.index]
        // do something

      default:
       // do nothing
       dispatch(action)
  }
}
```

**Comment by brentvatne** [comment]
so the original issue here is about using this to disable logging, which isn't really needed because it's now off by default and you can use `process.env.REACT_NAV_LOGGING` to enable it.

it's not clear to me why you would want to put your state in redux and then use this prop to monitor state changes. you could have a redux afterware that compares navstate (prevState !== state) and does something if so, or a middleware like @ShMcK mentioned above. additionally, even if you were to pass in `onNavigationStateChange` and not get a warning it would do nothing because this behavior is implemented on a navigation container, and there is no navigation container in the context of redux because you have to provide that. see: https://github.com/react-navigation/react-navigation/blob/4b39e2db3cf20b44bed0a7dc9f5986175f568d0c/src/createNavigationContainer.js#L157-L184

i think the confusion here arises from the implicit navigation container that we add with react-navigation on a top level navigator. we should move away from this at some point :O

**Comment by jordanmkoncz** [comment]
@brentvatne that sounds fine to me. I only opened this issue because at the time, adding onNavigationStateChange like this was the recommended solution for disabling react-navigation's default logging. I was not interested in using `onNavigationStateChange` to monitor state changes, I actually did have this requirement but I implemented it with middleware (similar to what @ShMcK posted). So if react-navigation has logging disabled by default now, then I guess this is no longer an issue. :)
