### ISSUE TITLE
Compatibility with libraries like redux-actions (Flux Standard Actions)

### ISSUE THREAD

**Issue by RobIsHere** [react-navigation/react-navigation#2158]
### Current Behavior
The action payload is like this:
{ type: 'Navigation/NAVIGATE', routeName: 'DrawerOpen' }

### Expected Behavior
There is a standard for the payload, many people already use.
{ type: 'Navigation/NAVIGATE', payload: { routeName: 'DrawerOpen' } }
See https://github.com/acdlite/flux-standard-action

Would be great if this lib could become compatible! Because with this change existing redux support libs would work!

Things like createAction https://redux-actions.js.org/docs/api/createAction.html#createactiontype-payloadcreator
```
// actions.js

import { createAction } from "redux-actions";
import { NavigationActions } from "react-navigation";

export const openMenu = createAction(NavigationActions.NAVIGATE, () => { return { routeName: "DrawerOpen" } });
```

**Comment by kelset** [comment]
Pinging OP @RobIsHere since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

---

Moreover I don't think we should add this support because if would mean that you would have two different ways to do the navigation action, which could lead people to confusion.

@vonovak @Ashoat what do you think? 🤔

---

That said, there was a PR open for this #2223 which is currently not possible to merge ( @mindmelting ).

**Comment by RobIsHere** [comment]
I think proper redux integration is important. Following conventions make the library easier to learn. It integrates better with foreign components, redux dev tools etc...

RN has the NIH version and should be fixed IMHO... https://en.wikipedia.org/wiki/Not_invented_here#In_computing ;)

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
