### ISSUE TITLE
Stack navigator disable gestures globally

### ISSUE THREAD

**Issue by pensierinmusica** [react-navigation/react-navigation#2463]
Hi,

in Stack Navigator is there a way to disable gestures globally instead of being a per-card setting?

https://reactnavigation.org/docs/navigators/stack#gesturesEnabled

Thanks!

**Comment by spencercarli** [comment]
Not currently - but I imagine it would be useful to people!

**Comment by pensierinmusica** [comment]
That's actually also what the docs suggest, although it doesn't work: https://reactnavigation.org/docs/navigators/navigation-options#Default-Navigation-Options

**Comment by kelset** [comment]
Pinging OP @pensierinmusica since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover, it looks this is more of a bug (your second part). I use the default nav options without any issue, can you please provide a snack that reproduces your issue of those options not working?

**Comment by kelset** [comment]
Hi there @pensierinmusica ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by pensierinmusica** [comment]
@kelset this issue should stay open until it's fixed. Just removing issues instead of fixing them does not help. Thanks!

**Comment by kelset** [comment]
> this issue should stay open until it's fixed. Just removing issues instead of fixing them does not help. Thanks!

You could have simply commented this issue during those 7 days.

**Comment by xyzzyxyzzy0077** [comment]
const RootStackNavigator = StackNavigator(
  {
    Login: {
      screen: LoginScreen
    },
    Main: {
      screen: MainDrawerNavigator
    }
  },
  {
    index: 0,
    initialRouteName: 'Login',
    headerMode: 'none',
    navigationOptions: {
      gesturesEnabled: false
    }
  }
);

From #1063

**Comment by pensierinmusica** [comment]
@xyzzyxyzzy0077 have you tried it and tested that it actually works?

**Comment by xyzzyxyzzy0077** [comment]
@pensierinmusica Yep, am using it right in my configuration.

**Comment by pensierinmusica** [comment]
Awesome, then this can be closed I guess  :)

**Comment by oseifrimpong** [comment]
@xyzzyxyzzy0077 That code works perfectly. Thanks.

**Comment by xyzzyxyzzy0077** [comment]
@oseifrimpong with pleasure
