### ISSUE TITLE
Web integration: URL Redirects

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#2500]
It's necessary to have support for redirecting to other screens in the web browser when auth fails. I.e. if the user clicks on a link that goes to

`/some/secret/stuff`

but they are not logged in / authenticated, they should be redirected in the browser to

`/login`
 
which is a separate screen that implements a login form.

**Comment by spencercarli** [comment]
I've never used this package on the web but I wonder if you could use the [linking](https://reactnavigation.org/docs/guides/linking) to accomplish that?

**Comment by rmevans9** [comment]
The first issue here is `react-navigation` actually does absolutely nothing to the URL out of the box. It doesn't read it, write to it or anything. Thats because it keeps all its state in a components state or whatever state you provide (eg redux). So the first issue you have to overcome is getting it to use the URL. The docs site is actually built using `react-navigation` but it handled the logic for using the URL in code specific for the website itself leaving everyone else that is using `react-navigation` on web out to fend for themselves to handle it... which I guess could be seen as a good or a bad thing depending on your stance.

Some relevant bits of code from the website:

This code handles the user hitting the back button.
https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js#L37

This code handles updating the URL as the user navigates the app.
https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js#L47

This code makes it so the URL the user actually enters is what is shown.
https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js#L22

I am sure there are other parts but that is how they manage the URL but this gives you a head start.

**Comment by matthamil** [comment]
The web support for react-navigation out-of-the-box is subpar. I'm not sure if it will be included in our new roadmap to 1.0 (see discussion here https://github.com/react-community/react-navigation/issues/2476, and the original roadmap here: https://github.com/react-community/react-navigation/issues/723). You'll most likely have to take heavy inspiration from the source code that @rmevans9 pointed out for now.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by geminiyellow** [comment]
working?
