### ISSUE TITLE
Only Material Design for DrawerNavigator?

### ISSUE THREAD

**Issue by heliojuniorkroger** [react-navigation/react-navigation#2555]
Hi Guys. I'm really enjoying this library, it helps me a lot.
When I run the DrawerNavigator in a iOS simulator, it keeps the Material Design for the Drawer (overlaying the content). I want something like this:
![68747470733a2f2f7261772e6769746875622e636f6d2f6172796178742f694f532d536c6964652d4d656e752f6d61737465722f736c6964654d656e75416e696d6174696f6e2e676966](https://user-images.githubusercontent.com/22944925/30176828-1cf1c728-93da-11e7-9218-62904fd1ab7e.gif)

Thanks!

**Comment by kelset** [comment]
Pinging OP @heliojuniorkroger since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

Moreover I think this is not doable, because of the way we implement the Drawer in the first place, which is [react-native-drawer-layout-polyfill ](https://github.com/react-native-community/react-native-drawer-layout-polyfill), a polyfill for DrawerLayoutAndroid.

**Comment by iRoachie** [comment]
Only lib I've seen doing it is [react-native-drawer](https://github.com/root-two/react-native-drawer) with their `type` prop set to `displace`. Actually apps I've seen doing it is the twitter mobile app on ios. I think it would great to have

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
