### ISSUE TITLE
Regarding routes design decision

### ISSUE THREAD

**Issue by sospedra** [react-navigation/react-navigation#2594]
**I'm not reporting a bug but a question**

Open question here. Why navigators are objects and not arrays? The code transforms the object routes into an array later anyway.

Also, and very related. Why - while using these objects - the *de facto* is navigate to a `routeName` instead of using the universally accepted paths?

Won't be much more easy to understand and integrate (web, deeplinks, etc) the use of paths as the "route identifiers"?

Explaining with code.

I don't understand why this one...

```js
StackNavigator({
  MyRoute: { ... }
})
```

...is better than this other

```js
StackNavigator([
  { path: '/my-route', ... }
])
```

:)

**Comment by kelset** [comment]
cc @ericvicenti @grabbou @skevy ?

**Comment by sospedra** [comment]
I just wanted to bump up this thread since now we're moving into a more stable stage and I think this debate is tightly coupled to the core of the library. Honestly, from my exp and those who I asked this is one of the more confusing design decisions about react-navigation.

**Comment by satya164** [comment]
> Why navigators are objects and not arrays

An object is a better data structure here because it can be used hashmap, i.e. it prevents you from having routes with duplicate names. The fact that it's later converted to an array is an implementation detail.

I'm closing this since the issue tracker is reserved only for bug reports. If you have suggestions for improvements or want to discuss, post it on https://github.com/react-navigation/rfcs for discussion
