### ISSUE TITLE
specify initialRouteName when navigating into a nested StackNavigator

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#2621]
Let's say I have a root Stack Navigator and nested within, another Stack navigator. I want to transition from a root screen to a screen within the nested navigator.

I would expect that, on click, my screen would just push one new screen onto the stack. And if I press "Back", I'll go back to where I just was - on the root screen.

But what actually happens is that `react-navigation` pushes two screens: the initial route for the new stack (if it's different from the screen specified, which it almost always is), and then the new screen that you actually wanted.

So when the user presses the "Back" button, there's this screen sandwiched in the middle that they navigate back to. Which is really confusing!

**Comment by joncursi** [comment]
In other words, I want the initial route to be the one I'm defining at runtime in my call to `.navigate(...)` rather than having to define a static value.

**Comment by joncursi** [comment]
Related issue: https://github.com/react-community/react-navigation/issues/2289

**Comment by vonovak** [comment]
why do you nest one stackNavigator into another one? Why not just have one?

**Comment by joncursi** [comment]
I would love to be able to do that. But I need some screens to animate in differently and unfortunately this library requires you to define that at the stack level rather than at the screen level

**Comment by vonovak** [comment]
you should be able to construct the stack at runtime and change the initial screen so that it is the one you need, and only the initial one will be pushed.

**Comment by vonovak** [comment]
@spencercarli I think issue can be closed because 
1 . the stack can be generated at runtime along with the correct initialRoute
2 . a feature that would "Omit / ignore initialRouteName" doesn't make much sense so I don't think it will ever be included

**Comment by IgorVanian** [comment]
How exactly can we set the initial route while navigating? :/

**Comment by vonovak** [comment]
@IgorVanian first, create a function that accepts the initial `routeName`. That function returns a new `StackNavigator` eg:

```js
const createMainStack = initialRouteName =>
  StackNavigator(
    {
      LoginScreen: { screen: ... },
      SomeOtherScreen: { screen: ... },
    },
    {
      initialRouteName,
    }
  );
```

second, render that navigator in a component (you can navigate to this component and pass the initalScreenString as a navigation param):

```js
render() {
    let initialScreenString = 'LoginScreen';

      const Root = createMainStack(initialScreenString);

      return (
            <Root />
      );
    }
```

**Comment by IgorVanian** [comment]
This is really weird, especially if your initialRoot has important `componentWillMount` logic :(

**Comment by kelset** [comment]
Pinging OP @joncursi since this issue has not been active for a while, and it's related to an old version of the lib.

Moreover @vonovak proposed solution is actually quite good.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @joncursi,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by douglasjunior** [comment]
Sorry for revive this thread, but we have any update?

I have a situation where I need to navigate to specific routes inside a nested Stack, but the initial route is aways rendered first.

I have this scenario:

- MainStackNavigator
   - RouteMainA
   - RouteMainB
   - OneStackNavigator
         - RouteOneA
         - RouteOneB
   - OtherStackNavigator
         - RouteOtherA
         - RouteOtherB

When I navigate from `RouteMainB` to `RouteOtherB` the `RouteOtherA` is rendered too, and my stack looks like this:

1. RouteMainB (MainStackNavigator)
2. RouteOtherA (OtherStackNavigator)
3. RouteOtherB (OtherStackNavigator)

I chose to work with nested stacks because I have situations where I need to do a `popToTop` and close all routes in a nested stack.

Any suggestions?

**Comment by douglasjunior** [comment]
I got it, solved with a custom `push` action.

```js
        const pushAction = StackActions.push({
            routeName: 'OtherStackNavigator',
            action: StackActions.push({
                routeName: 'RouteOtherB',
                params: {
                    ...
                },
            }),
        });

        navigation.dispatch(pushAction);
```
