### ISSUE TITLE
Tab Navigator with transparent background

### ISSUE THREAD

**Issue by eemebarbe** [react-navigation/react-navigation#2637]
I'd a single background to show through for every tab scene, but this doesn't appear to be possible. Is there a tab navigator container view that can be targeted?

**Comment by linkinmedo** [comment]
you might find what you want here:
https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarBottom-default-tab-bar-on-iOS

**Comment by kelset** [comment]
Pinging OP @eemebarbe since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @eemebarbe,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
