### ISSUE TITLE
Animate headerTintColor

### ISSUE THREAD

**Issue by romaluca** [react-navigation/react-navigation#2653]
Hi, i'm following this tutorial: 
[https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e](https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e)

For animate the react-navigation header background color on scroll.
It works.

I want also animate  the headerTintcolor, it must be white for the firsts 200px and gray for the others.
But i can't because if i try to use:

```
static navigationOptions = ({ navigation, screenProps }) =>  { 
....
headerTintColor: (navigation.state.params.animatedColorValue  ? navigation.state.params.animatedColorValue : '#fff')
...

```
i receive an error.

how can i change it after 200px of  scroll? 
thanks!

**Comment by PatNeedham** [comment]
@romaluca what is the error you receive when attempting that?

**Comment by harumanu** [comment]
I just ran into this problem as well, the error I'm getting is "Cannot add property _animatedView, object is not extensible"

I'm trying to do the same thing as @romaluca romaluca, hooking up headerTintColor with an animated value

react-native version 0.48.4
react-navigation version 1.0.0-beta.13

![image](https://user-images.githubusercontent.com/3128083/31361393-73c0596a-ad53-11e7-9e41-f293e304c28a.png)

**Comment by vonovak** [comment]
At the moment, you'll need to implement your own custom header to support this.

**Comment by kelset** [comment]
Pinging OP @romaluca since this issue has not been active for a while, and it's related to an old version of the lib.

Moreover, as pointed out by Vonovak, you need to rely on a custom header to get this behaviour.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @romaluca,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
