### ISSUE TITLE
reset action not working with StackNavigator nested in TabNavigator

### ISSUE THREAD

**Issue by rickardinho** [react-navigation/react-navigation#2670]
Hi,

I have the following routes:

Stack Navigator "Root"
--Tab Navigator
    --- Stack Navigator A
           ----Screen "Feed"
    --- Stack Navigator B
           ----Screen "1"
           ----Screen "2"

I have navigated through to "Feed", then to "Screen1" and then to "Screen 2".

I now wish to go to screen "Feed", popping off all the other screens in one go.  I assume this is what the reset action is for, so I've put the code as per the docs, here is my code:

```
import { NavigationActions } from 'react-navigation';

export default function discardEvent (navigation) {

  const resetAction = NavigationActions.reset({
    index: 1,
    actions: [
      NavigationActions.navigate({
        routeName: '1'
      }),
      NavigationActions.navigate({
        routeName: 'Feed'
      })
    ]
  });

  navigation.dispatch(resetAction);

}

```

However, this doesn't work, I get the error "There is no route defined for screen "Feed", must be one of "1" or "2".

The only way I can get back to Feed is by doing navigation.navigate("Feed"), which works, but it doesn't pop the other screens.

**Comment by Krizzu** [comment]
Just landed with the same issue today.

**Comment by musicode** [comment]
+1

**Comment by rmilesson** [comment]
+1

**Comment by chuece** [comment]
I believe you can use `key` parameter to reset root navigator state:
```
const resetAction = NavigationActions.reset({
    index: 1,
    actions: [
      NavigationActions.navigate({
        routeName: '1'
      }),
      NavigationActions.navigate({
        routeName: 'Feed'
      })
    ],
    key: null
});
```

**Comment by linhanyang** [comment]
+1

**Comment by kelset** [comment]
Hi - reset is currently a method that has some issues, we are looking to better control the behaviour of it in future releases.

In the meantime, I suggest you take a look at issue #1127 (in particular from [this comment](https://github.com/react-community/react-navigation/issues/1127#issuecomment-319727619) on) to better understand how it works / how you may have to fix your method call.

I'd like to close this issue since it's mostly a duplicate, but I'd prefer to wait to hear back from you before that.

**Comment by ZKeLin** [comment]
@chuece that's cool!!! this question,i have already been troubled for 3 hours , but i don't know ,why add 'key:null' will be work?

**Comment by chuece** [comment]
@ZKeLin as far as I know this `key` feature is working in a strange way right now. `key: null` makes navigation reset on root router. And as for me this is most predictable way to manage navigation right now.
[https://reactnavigation.org/docs/navigators/navigation-actions#Reset](url)

**Comment by ZKeLin** [comment]
@chuece Ok, I probably got it, this way is suitable for me, thanks.

**Comment by mindwards** [comment]
IMO for the time being, in order to avoid many issues a sensible workaround is to **ALWAYS** use the `key` parameter when dispatching the `reset` action. Either specifying `key: null` and **always the full tree of nested navigators** or using the `key` of the right navigator (I still don't know how to do that as `key` seems to be some kind of hash.

**Comment by kelset** [comment]
Pinging OP @rickardinho since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @rickardinho,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
