### ISSUE TITLE
goBack(key) does nothing

### ISSUE THREAD

**Issue by sean-macfarlane** [react-navigation/react-navigation#2708]
### Current Behavior
I've followed the docs and other issues in implementing goBack() with a key as the param, but it does nothing with no error. 

The correct key is being passed as I use console.log to verify.
```
// IN LOGIN
     this.props.navigation.navigate('Signup', {loginKey: this.props.navigation.state.key });

// IN SIGNUP
 closeModal = () => {
        console.log(this.props.navigation.state.params.loginKey)
        this.props.navigation.goBack(this.props.navigation.state.params.loginKey);
    }
```
My Navigation: 
```
const AuthStackNavigator = StackNavigator({
    Login: { screen: LoginModal },
    Signup: { screen: Signup }
}, {
        headerMode: 'none'
    });

const RootStackNavigator = StackNavigator({
    MainTabNavigator: { screen: NavTabBar },
    AuthStackNavigator : { screen: AuthStackNavigator }
}, {
        headerMode: 'none',
        mode: 'modal'
    });
```

### Expected Behavior
How I am trying to navigate is:
MainTabNavigator --> AuthStackNavigator : Login --> AuthStackNavigator : Signup --> goBack: Login (MainTabNavigator)

I am passing the key of my Login Screen and I am expecting it to go back to the TabNavigator as if I did goBack() on the Login Screen, but nothing happens.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.48.0

**Comment by kelset** [comment]
Hey, I'm kinda confused by the overall structure; in your code there is no TabNavigator.

What I understand of the structure from your code is

```
   Stack:
      (1st card) -> (tab navigator)
                                |-> ???
      (2nd card) -> (another stack)
                                |-> Login |-> Signup
```

And the back that doesn't seem to work is the one in the signup to go back to login right?

**Comment by sean-macfarlane** [comment]
@kelset sorry I didnt include the code for the TabNavigator, because I didnt deem it necessary to my issue. 
But yes the structure you have is correct.

The back that isnt working is in Signup using the state key of Login so I can go back to the Tab Navigator.
`A screen in MainTabNavigator -> Login -> Signup -> back to a screen in MainTabNavigator`

**Comment by kelset** [comment]
I don't think that `goBack` would/should work in the way you want it to.
I'm surprised that it "does nothing", since from my understanding (which is quite limited since you haven't really shown much code) the `goBack` in the screen `Signup` should get you back to `Login`.

Can you provide a screencast or something like that?

**Comment by chrusart** [comment]
Maybe navigation.navigate u should do on RootStackNavigator, not on AuthStackNavigator cause Login is the first screen in this stack and nowhere to go back, Root.. have two screens Tab.. and Auth.. so navigation.goBack(AuthStackNavgator.key) should work, but not 100% sure the key for AuthStackNavigator thou.

**Comment by sean-macfarlane** [comment]
@kelset `goBack()` with no params or param `null` works and in Signup goes back to Login that is not my issue. I'm trying to pass the Login state key as a param to `goBack` like in the code I included above, so in Signup I can go back to MainTabNavigator. 

@chrusart thanks I will try and find the key for `AuthStackNavigator` and see if that works. I was using the Login key because if I do `goBack(null)` in Login it does go back to MainTabNavigator, so I thought that would work.

**Comment by justinobney** [comment]
@sean-macfarlane 

So.. this is a little misleading due to the docs. The docs make it appear that the `key` is the "Route Name" (Ex: Dashboard). However, to get this working, I had to keep track of the key (`navigation.state.key`) property and use this key in `goBack(key)`.

Example:

```
[Screen A (reference only)]

---

[Screen B]
const {navigation: {navigate, state: {key}}} = this.props;
...
onPress={() => navigate('ScreenC', {from: key})}

---

[ScreenC] (Equivalent to going "back" from ScreenB => ScreenA)
const {navigation: {goBack, state}} = this.props;
onPress={() => goBack(state.params.from)}
```

**Comment by mauron85** [comment]
@justinobney I had exactly same feeling about *key* being route name after reading [docs](https://reactnavigation.org/docs/navigators/navigation-prop#goBack-Close-the-active-screen-and-move-back).

Qoute from https://reactnavigation.org/docs/navigators/navigation-prop#goBack-Close-the-active-screen-and-move-back
> Going back from a specific screen
Consider the following navigation stack history:
navigation.navigate(SCREEN_KEY_A);
...
navigation.navigate(SCREEN_KEY_B);
...
navigation.navigate(SCREEN_KEY_C);
...
navigation.navigate(SCREEN_KEY_D);
Now you are on screen D and want to go back to screen A (popping D, C, and B). Then you need to supply a key to goBack FROM:
navigation.goBack(SCREEN_KEY_B) // will go to screen A FROM screen B

I suggest adding following line:

> Screen keys (SCREEN_KEY_A, SCREEN_KEY_B, ...) are not arbitrary keys (or route names), but value of `navigation.state.key` prop.

**Comment by sean-macfarlane** [comment]
@justinobney I am do exactly that as shown in my code in my original post, my issue is that's not working

**Comment by levsero** [comment]
I believe in earlier versions of react-navigation you could set the key, which would have allowed for easy reference of it in a later call. But now that the keys are randomly generated having to use the key as the prop seems highly impractical, would be great if there was another way of specifying which screen to go back to 🤔

**Comment by lucianomlima** [comment]
Maybe, Router can have a method to retrieve the key.
Can be like getActionForPathAndParams but for key, ex: getKeyForRouteName.

**Comment by kelset** [comment]
I think there's currently an open PR for it: https://github.com/react-community/react-navigation/pull/3085

You can test it / review it if you want, it would surely help speeding up the process of adding it as a feature.

**Comment by AlexMouton** [comment]
@mauron85 Hi Marian
Would love to see those docs updated too but I want to challenge your suggestion before they are.
The parameter to navigate is still 'route' screen keys, correct? You seem to be flipping all 'keys' to the generated value, but only goBack uses it here.

Thanks
Alex

**Comment by brentvatne** [comment]
@ericvicenti - this is out of date I believe. not sure how to act on the issue

**Comment by pcasa** [comment]
I do not think this is working as it should.

Have Tabs with nested StackNavigators.  ie. One of the Tab View's has a stack navigator with "List", "Create_step_1", "Create_step_2".

On the "List" view, have a headerRight button in the navigationOptions section.  Button links to "Create_step_1".  I assign `onPress={() => navigation.navigate('Create_step_1', {goBackKey: navigation.state.key})}`

goBackKey is passed from "Create_step_1" to "Create_step_2".  Then on the "Create_step_2" view have a "Cancel" button also on the headerRight and `onPress={() => navigation.goBack(navigation.state.params.goBackKey)}`.

Expect, when "Cancel" button is pressed on "Create_step_2" that it goes back to "List".
But nothing happens when key is passed in to the button.  Logger says Action `{type: 
"Navigation/BACK", key: "id-1518968308255-5" }` but no Back and no error.  

Using 
React 16.2
React-native 0.52.0
React-navigation 1.0.0-beta.30
Redux 3.7.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Qiu800820** [comment]
Example:
[Screen A]
console.log(this.props.navigation.state)  //{routeName: "A", key: "Init-id-1523178678978-0"}

[Screen B]
console.log(this.props.navigation.state)  //{routeName: "B", key: "id-1523178678978-2"}

[Screen C]
console.log(this.props.navigation.state)  //{routeName: "C", key: "id-1523178678978-5"}
// goBack A
this.props.navigation.goBack('Init-id-1523178678978-0'); // not work
this.props.navigation.goBack('id-1523178678978-2'); // bingo :trollface:

At the beginning, I think A => Init-id-1523178678978-0,  but A => id-1523178678978-2

**Comment by thangkho** [comment]
@Qiu800820 I try it but it not working.
When console.log it show: state {routeName: "HomeTab", key: "id-1531208528805-1"}.
In other component I call this.props.navigation.goBack('id-1531208528805-1')) an nothing happen

**Comment by Qiu800820** [comment]
@thangkho You may have nested routes, and there is no id-1531208528805-1 in your Tab Router.
