### ISSUE TITLE
Blocks updates due to context changes?

### ISSUE THREAD

**Issue by Ephys** [react-navigation/react-navigation#2770]
If I use this library, updates due to changes in the context of `react-intl` are not propagated past the Navigator component. Meaning the text in my app does not get translated until the view is forced to update.

Poking around, I noticed that changing [this class](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/views/SceneView.js) from a `PureComponent` to a `Component` resolved the problem. Although it's probably not the best way to solve the issue.

---

### Minimum viable working example

This gist contains an example that uses React-Navigation's `StackNavigator` and one that renders a view directly: https://gist.github.com/Ephys/270e55a2a5dc1a432f522dbf2e470a91

### Current Behavior
- In the example with `StackNavigator`, the displayed text does not update when I change react-intl's locale.
- In the example without `StackNavigator`, the displayed text gets translated correctly.

### Expected Behavior
- The `FormattedMessage` component updates and displays the translated text.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.13
| react-native     | 0.48.4
| node             | 8.7.0
| npm or yarn      | yarn 1.1.0

**Comment by kelset** [comment]
Hi @Ephys thanks for reporting using the template.

One easy way to "force the update" could be to simply pass the navigator props to the underlying component. I suppose your case for "dynamically" changing the language is related to a user modifying the language in the settings; are you using redux?

I don't think changing the SceneView to a Component is a viable solution because the number of re-renders caused by that modification would affect overall performances. That said, it's a small modification so on the other hand, a fork+PR would be an easy way to test it out and get a second opinion from other maintainers.

**Comment by serhiipalash** [comment]
Hi @Ephys !
I am working on this issue last two days and I can't find any good solution. Please help.

> Poking around, I noticed that changing this class from a PureComponent to a Component resolved the problem. 

Doesn't work for me. I don't know why.

> pass the navigator props to the underlying component.

Also doesn't work.

Only thing that work is to pass `key={locale` into `<IntlProvider>`, but this rerenders the whole dom-tree on locale change.

If anyone has ideas how to fix broken React context please help.

**Comment by satya164** [comment]
Libraries using context to pass data to children need to use a subscription system to broadcast updates. Due to the way context works in React, any `shouldComponentUpdate` can short-circuit context updates if a broadcasting system is not used. Libraries such as React Router do a similar thing and use the https://github.com/ReactTraining/react-broadcast package. The context API will change in future so that it's not necessary anymore, but it's really a bug in `react-intl` if it's not using such a system. Even common HOCs such as Redux's `connect` implements a `shouldComponentUpdate`, so changing `react-navigation` doesn't really address the bug in `react-intl`'s context usage.

**Comment by brentvatne** [comment]
great points @satya164, we should add docs around this, moving issue to https://github.com/react-navigation/react-navigation.github.io/issues/44
