### ISSUE TITLE
Navigation Events hitting every reducer, triggering navigate actions in other stacks

### ISSUE THREAD

**Issue by mujavidb** [react-navigation/react-navigation#2962]
This will be based on the architecture below, using redux: https://reactnavigation.org/docs/guides/redux

```
/TabNavigator
    /StackNavigator - List
        /UserList - initial
        /UserProfile
    /StackNavigator - Search
        /UserSearch - initial
        /UserProfile
```

### Current Behavior

Currently, if I am in the Search tab, i.e. using the Search StackNavigator, and am on the UserSearch Screen, if I dispatch a `Navigate` action, to go to the `UserProfile`, the reducer for each stack will respond to the action and trigger a new state. Thus both stacks will transition to the `UserProfile`.

However, I only wanted my current stack (the Search stack) to navigate to the `UserProfile`.

### Expected Behavior

I would want to have a concept of current/active stack, so at the very least the state clearly shows which screen is the current, and based on that only dispatches actions to the one reducer, or something along these lines.

If not, how would I work around this problem?

**Comment by kelset** [comment]
Thanks for reporting.
I was quite sure there was another issue about this precisely, but couldn't find so I'll keep this open.

Somewhat related it https://github.com/react-community/react-navigation/issues/2270 - but anyway yes, at the moment something like what you are describing may happen if you have two routes defined with the same name, as far as I can tell. I actually think this is also the main cause of many `reset` issues (basically, it gets called on all navs and kaboom - yeah I know it's kinda simplified).

Anyway, the base workaround is to simply have a different name for each route. A more subtle one would be to, since you are in control of the actions/reducers, to hijack the behaviour, ex:

```
export const bottomTabBarReducer = (state, action) => {
  switch (action.type) {
    case 'JUMP_TO_TAB':
      return { ...state, index: 0 };
    case 'Navigation/BACK':
      return state;
    case 'Navigation/RESET':
      return BottomTabBar.router.getStateForAction(
        NavigationActions.reset({
          index: 0,
          key: 'BottomTabBar',
          actions: [NavigationActions.navigate({ routeName: 'EventsStackNavigation' })],
        }),
        state,
      );
    default:
      return BottomTabBar.router.getStateForAction(action, state) || state;
  }
};
```

I'll tag this as bug but tbh I'm not sure, it's more related to some feature requests already out there of having the navigators integrate https://github.com/react-community/react-navigation/issues/88

**Comment by mujavidb** [comment]
I was also considering creating separate `NavigationActions` for each stack, to better target a specific stack, but this felt like a more hacky workaround.

**Comment by brentvatne** [comment]
hi there! we changed the requirements for issues so we need to have an example that reproduces the problem. if you can provide that i will happily reopen. thanks!
