### ISSUE TITLE
Native module cannot be null in hybrid IOS App

### ISSUE THREAD

**Issue by tonychan818** [react-navigation/react-navigation#2977]
Trying to use React Native with StackNavigator in my existing IOS native App.
when I comment the StackNavigator part in my js file, it works without error.
So I am pretty sure StackNavigator leads to this error.

![screen shot 2017-11-15 at 3 03 47 pm](https://user-images.githubusercontent.com/5890291/32823043-6d39ba66-ca16-11e7-8230-aaa4f2a4d7b0.png)

and I found out that this is due to missing pod linkage in cocoapod.

here is my Podfile.

pod 'RNI18n', :path => '../js/node_modules/react-native-i18n'
pod 'yoga', :path => '../js/node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
    'BatchedBridge',
    'RCTLinkingIOS'
]

which subspecs is missing? and how can I find out which subspecs I am missing when I added a new react native module?

**Comment by kelset** [comment]
1. next time **please** follow the issue template.
1. It looks like you are missing the Linking (RCTLinking) lib - according to the [react-native documentation](https://facebook.github.io/react-native/docs/linking.html)

**Comment by sunnylqm** [comment]
RCTLinking is required

**Comment by allison7** [comment]
I'm also encountering this, and with both Xcode and RN slightly changing how things work the docs have become extremely difficult to follow. Advice?

**Comment by kelset** [comment]
Hi there @tonychan818,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

---

@allison7 just follow the [react-native documentation](https://facebook.github.io/react-native/docs/linking.html)

**Comment by bithavoc** [comment]
the subspec is called `RCTLinkingIOS`;

```
 pod 'React', :path => '../node_modules/react-native', :subspecs => [
    . . . 
    'RCTLinkingIOS',
    . . .
  ]
```
