### ISSUE TITLE
Tabbar navigator shows grey screen briefly

### ISSUE THREAD

**Issue by RasmusFredensborg** [react-navigation/react-navigation#3035]
Hi :-)

Firstly, thank you for an amazing navigation framework. I've been using the 1.0.0-beta.15 release for quite a while now, and finally decided to upgrade to 1.0.0-beta.16. This introduced an unexpected behaviour in my TabNavigator.

Some context:
- I have a TabNavigator with five tabs
- After logging in, the user is presented with the TabNavigator, which shows the first tab while data is fetched
- I'm using react-redux for application state 

### Current Behavior - version 1.0.0-beta.16
When logging in, the TabNavigator briefly shows a grey screen with all five tabs pushed together to the left side of the screen, with about 4 pixels each, as shown on the screen shot, until data is fetched, and the app state is updated via redux.
![screenshot_1511358647](https://user-images.githubusercontent.com/8933720/33161663-3d0617b2-d025-11e7-8ac7-5c8ce388b3e4.png)

### Expected Behavior - version 1.0.0-beta.15
The TabNavigator shows the first tab out of the five tabs, while data is fetched and the app state is updated via redux.
  
As I said, this issue was introduced with the upgrade from 1.0.0-beta.15 to 1.0.0-beta.16. I tried to update to beta.17, beta.19 and even beta.21, but the issue still persists. I would love to provide some code, but honestly, I have no idea where to start. The TabNavigator I've been using from releases 1.0.0-beta.11 through 1.0.0-beta.15 has worked as expected.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.50.3
| node             |6.9.5
| npm or yarn      |yarn: 1.0.1

**Comment by kelset** [comment]
Hi @RasmusFredensborg thanks for reporting.

I think this issue has been reported a couple times already but since you are the one providing the most information I'll close those in favour of this ( https://github.com/react-community/react-navigation/issues/2914,  https://github.com/react-community/react-navigation/issues/2930 ).

That said, I actually started seeing this behaviour in my app too when I tried to upgrade to `react-native` 0.50.3, does it happen to you on rn 49?
Moreover, I haven't investigated properly back then when I tried upgrading 'cause I had to roll back for other issues, but can you try answering this questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. it looks like you are using an old version of Node & yarn, probably it's not related to that but can you also try updating those tools?

([`beta.16`](https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.16) was a huge release, in the "Bugfixes & Improvements" there are many PRs related to tabs, maybe it was introduced by one of those? )

**Comment by yateeshr12** [comment]
Hi @kelset 
I'm facing the same issue on Android. I've tried versions 1.0.0-beta.15/16/17/21. The bug is from version 1.0.0-beta.16  onwards. Tested on RN v0.49.5 and v0.50.3. I think it might be from one of the PRs related to tabs in 1.0.0-beta.16 as you've mentioned.

**Comment by yiky84119** [comment]
Set TabNavigator option { animationEnabled: false }, i'll work fine.

**Comment by yateeshr** [comment]
animationEnabled: true/false didn't help.

**Comment by RasmusFredensborg** [comment]
Hi @kelset,
I'll answer your questions the best I can:
1. Does it happen only on Android/iOS?
    * I'm only developing for Android using lots of native code, so unfortunately I cannot easily verify that it also happens on iOS
2. Does it happen on both Debug and Release modes?
    * Both
3. Does it happen with Debugger On or Off? Both?
    * Both
4. It looks like you are using an old version of Node & yarn, probably it's not related to that but can you also try updating those tools?
    * I tried updating yarn to 1.3.2 and node v. 6.12.0 and the problem still persists

I would gladly help out isolating the problem, so let me know of other configuration changes you want me to try out, @kelset :-)

@yiky84119, I'll try out the ```animationEnabled``` option later today.

**Comment by RasmusFredensborg** [comment]
Setting ```{ animationEnabled: true }``` in the TabNavigator options actually works for me, @yateeshr and @kelset. Although I'm not interested in the tab bar animating when changing tabs, it might help out in finding the bug introduced in version 1.0.0-beta.16.

**Comment by kelset** [comment]
Uhm gotcha. Thanks for reporting back.

**Comment by yateeshr** [comment]
Hi @kelset 
Any workaround for this bug so that I can manually fix until there's a fix in upcoming releases?

**Comment by bharadwajsampath** [comment]
this issue happens with ver 1.1.1 as well.
adding the `animationEnabled: True` to the `TabNavigator` options did not help.

Saw this happening when there are multiple transitions happening.
First I send the user to the dashboard (Root of the TabNav) and then to the specific page based on some logic.
![image](https://user-images.githubusercontent.com/13538284/36409118-b244f484-165d-11e8-951b-ed99e945f077.png)

Quick fix was to add some `delay(redux-saga)` , you could also try adding `timeout`

**Comment by brentvatne** [comment]
hey folks, can you add please post an example on snack.expo.io to reproduce this? thanks you!

**Comment by kocyigityunus** [comment]
ResourceSavingSceneView looking for 'Navigation/COMPLETE_TRANSITION' action to render another tab.

i think you're using tab navigator as a nested navigator with redux. in this case _onAction method on ResourceSavingSceneView not called. because you cant pass true addListener method to nested navigators.

i don't think this is a bug. this is a architecture design error, this library is not the best for nested or multiple navigators. we need names for every navigator, and every action has to have navigationName property which they are targeting.

**Comment by kocyigityunus** [comment]
i think i may find a solution for this. if this works i will share tomorrow.

**Comment by hovoodd** [comment]
Hi @kocyigityunus 
Did you find any solution?

**Comment by brentvatne** [comment]
this seems stale. if the problem persists, please post an issue to https://github.com/react-navigation/react-navigation-tabs
