### ISSUE TITLE
Unexpected token < in JSON at position 143711 after npm install 

### ISSUE THREAD

**Issue by devSeb** [react-navigation/react-navigation#3103]
Hello,

I would like to install react-navigation but I have an error after a npm install.

I try : 
npm install --save react-navigation  
npm install --save react-navigation@1.0.0-beta.21

My error : 
npm ERR! Unexpected token < in JSON at position 143711

My env:
node : 6.11.4
npm:  5.0.3

I must install an other package on react-navigation ?

**Comment by kelset** [comment]
It really looks like it's an npm related error. Try:
1. upgrading to latest npm
1. updating node
1. using yarn

And make sure to remove the node_modules after each test installation.

> I must install an other package on react-navigation ?

No.

**Comment by jeyakumarsbe** [comment]
rm package-lock.json worked for me.

**Comment by kelset** [comment]
Hi there @devSeb,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by AnilBhandare09** [comment]
Delete package-lock.json file,and run command of npm install then its work fine.
