### ISSUE TITLE
Reset to Home without mounting a new Home screen

### ISSUE THREAD

**Issue by carsonwah** [react-navigation/react-navigation#3121]
### Current Behavior

Dispatching a reset navigation action to return to Home screen will mount a new Home screen, also without unmounting any other screen.

```javascript
const resetToHome = NavigationActions.reset({
    index: 0,
    key: null, // no matter have this or not
    actions: [
      NavigationActions.navigate({routeName: 'Home'}),
    ],
  });
```

a snack demo: https://snack.expo.io/HJ72TdAWG

### Expected Behavior

Have a way to return to Home without remounting it once.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50 with expo 23.0.0
| node             | v6.11.0
| yarn      | 1.3.2

-------  
This is useful or rather important if the Home screen needs to do some data fetching when mounting. If it's not the purpose of `reset`, then it's about having the `goBack(n)` or `goBack to xxx` feature instead of using "reset".

**Comment by kelset** [comment]
Random question related to this: have you tried using `NavigationActions.init() ` instead of `.navigate`? I know it's not well documented, but I seem to recall @spencercarli knew something more about its behaviour.

**Comment by carsonwah** [comment]
@kelset It gives me the following error. I cannot make it work.

```javascript
const resetToHome = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.init(), // or NavigationActions.init({routeName: 'Home'})
  ],
});
```

```
Invariant Violation: Cannot get config because the route does not have a routeName.

This error is located at:
    in TabView (at withCachedChildNavigation.js:66)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:65)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:216)
    in NavigationContainer (at Router.js:8)
    in Router (at AppStartUpWrapper.js:17)
    in AppStartUpWrapper (created by Connect(AppStartUpWrapper))
    in Connect(AppStartUpWrapper) (at ReduxWrapper.js:71)
    in Provider (at ReduxWrapper.js:70)
    in ReduxWrapper (at App.js:105)
    in App (at registerRootComponent.js:34)
    in RootErrorBoundary (at registerRootComponent.js:33)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
```

**Comment by kelset** [comment]
Uhm, gotcha.
Hopefully there's something we can do about it quickly.

**Comment by sOm2y** [comment]
any updates on that?

**Comment by flynnch** [comment]
try version v1.0.0-beta.15

**Comment by j-wang** [comment]
Agree with @flynnch.

In the meantime, this approach works for me on @carsonwah's code:

```

**Comment by carsonwah** [comment]
@j-wang Thanks for the workaround. Now init() can be used. However, it still does not produce the desired result. It still mount the Home screen again.

https://snack.expo.io/ByAqaReXf

I am suspecting if init() is the right action to achieve this, as it means initializing the whole stack from scratch.

**Comment by revh** [comment]
I use this pieace of code (instead of the reset method) for going back without re-mounting the first screen, and seems it is working:

in a tab navigator screen i provide a custom function for tabBarOnPress

```
static navigationOptions = ({ navigation }) => ({
    tabBarOnPress: tabBarOnPress(navigation)
})
```


```
const tabBarOnPress = navigation => config => {
    if (!config.scene.focused) {
        config.jumpToIndex(config.scene.index)
    } else {

        if (config.scene.route.routes.length > 1) {
            for (let i = 0; i < config.scene.route.routes.length - 1; i += 1) {
                const backAction = NavigationActions.back()
                navigation.dispatch(backAction)
            }
        }
    }
}
```

btw I hope to find a better solution

**Comment by zeflash** [comment]
Hey, so I've been getting this issue for a while, and I managed to fix it properly - in my case :)!
Context: I wasn't using redux before, no I do. I ended up having the same kind of un mounting issue, just because Navigation.reset does remount all screens instead of just going back.

My nav layout is a stack navigator at the root, with a tab navigator in it (MainTabNavigator), along with a sign in (SignIn) that's usually "below" the tab, and multiple other screens that can end up above the tab navigator.

Given I'm now using redux, I'm not entirely sure how this would fit in an app without redux. In my case what I gathered is that I replace the existing routes with something else in the router. I would assume you could achieve the same thing by calling the Navigation.router directly? 

So, my initial Reset state:
```
      let resetState = RootStackNavigator.router.getStateForAction(
        NavigationActions.reset({
          index: 1,
          actions: [
            NavigationActions.navigate({ routeName: "SignIn" }),
            NavigationActions.navigate({ routeName: "MainTabNavigator" })
          ]
        })
      );

      return {
          ...resetState,
          routes: resetState.routes.map(route => {
            return route.routeName === "MainTabNavigator"
              ? { ...route, index: 1 }
              : { ...route };
          })
      };
```

As you can see, the goal here is to return to the tab navigator & to select the second tab in it.
All tabs in the tab navigator were being reset doing so, and I could see the "key" change for both SignIn & the TabNavigator. 

I turned it into the following (state being the existing state of the router): 
```
      return {
        ...state,
          index: 1,
          routes: state.routes
            .filter((_, i) => i <= 1)
            .map(route => {
              return route.routeName === "MainTabNavigator"
                ? { ...route, index: 1 }
                : { ...route };
            })
        }
      };
```

As you can see, in that case I'm just filtering the existing routes (and then changing the index on the tab navigator to switch tabs)

And voilà! it's not blinking/reloading all my tab screens, which is pretty important in my case given I'm retrieving stuff off the net on every init. Now it's much faster & prettier.

I hope it helps someone. I know I've struggled for days to try to figure out how everything worked.

**Comment by Masoodt** [comment]
this is my working solution for reset back to home (root) without creating new route

```
let k = this.categoriesNav.state.nav.routes[1].key;
this.categoriesNav.dispatch(NavigationActions.back({key: k}));

```
categoriesNav is refrenced to my stack navigator

**Comment by brentvatne** [comment]
you can use `popToTop()` for this or specify the key like @Masoodt mentioned

additionally, you may want to see if `SwitchNavigator` is a good fit for your usecase
