### ISSUE TITLE
Community should find better solution for navigation

### ISSUE THREAD

**Issue by shukerullah** [react-navigation/react-navigation#3205]
It really is painful that the such basic feature in mobile development like navigation is not really solved yet in react native.

I personally believe we should focus more on native navigation so we can have a native side that would do navigation (iOS 11,  Android shared element transition and other iPhone X features) job automatically instead of having to make all these workarounds. Otherwise, we will be left behind than the native developers.

**Comment by satya164** [comment]
"Finding better solution for navigation" is not an easy task. If it was, lots of people would have done already. Unless you have a bunch of talented devs having free time to build another navigation solution, it's not very productive approach as well. A better approach would be to discuss the pain points you have with this library, and how we can solve them. I already attempted https://github.com/react-navigation/react-navigation/issues/3195, comments are welcome.

> I personally believe we should focus more on native navigation so we can have a native side that would do navigation

This is debatable. Building it in native doesn't essentially make it better. I'm not against building solutions in native, and I had written my thoughts about it https://blog.callstack.io/why-you-should-not-re-implement-native-features-in-react-native-c699a70be76c

> iOS 11, Android shared element transition and other iPhone X features

Which iOS 11 and iPhone X features are you referring to? The notch, space for home button etc. are already handled.

Regarding shared transitions. It's not very difficult to build in React Native, and I don't believe that the feature has to be built into a navigation library. It's totally possible to build a custom navigator for React Navigation which handles shared transitions instead of building it into StackNavigator, which is overcomplicating things IMO.

Building a navigation library in native isn't an easy task. And even when you build it, there are several things involved to actually make it a good solution. If you are looking for a native navigation library, you already have https://github.com/wix/react-native-navigation. But they have been rewriting it for v2 for quite a long time. There is also https://github.com/airbnb/native-navigation, which seems to be abandoned.

**Comment by shukerullah** [comment]
I know its not easy to build/update navigation, what I am saying is why to spent time on those features which native navigation is already providing instead we focus on performance, features and other RN bugs & issues.

**Comment by kelset** [comment]
I find it funny that to open this kind of issue is someone who never opened a PR to this library (nor any other nav lib as far as I can tell).

I could spend words, as @satya164 did, replying you properly. But I won't.

Because not only you are opening it without any good reason aside from just throwing random flames - for which moreover we already allow an open issue https://github.com/react-navigation/react-navigation/issues/2031 - but also, you should have been opening this kind of issue on the main react native library in the first place.
