### ISSUE TITLE
clear history from routes stack for better performance/best practice?

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#3235]
I am using react-navigation 1.0.0-beta.21 and RN 0.48.4.

I have a stack navigation that is build from 3 stacks - 2 stack navigators and one Tab Navigator.

My question is:
Once I reach my tab navigator I will never return to the stack navigators.
Is clearing the history of my navigation routes stack is the best practice? will it make my navigation faster or it won't matter?

Thanks

**Comment by kelset** [comment]
Hi @assafb81! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you, in particular, the FAQ about performances.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Comment by otoinsa** [comment]
Hi!

I would like this to be reopened. Here's the reason why:
react-navigation and it's StackNavigator has a lot of performance issues - I'm using mobx for my state managment and as the history stack piles up, I've noticed really bad performance issues.

This might be caused by the fact, that all the views are observables and some of them share some observable data. That would probably cause rerenders in the views below the stack, since they are kept drawn.



As you navigate further trough the app, each navigation push takes longer and longer and eventually it's unusable. Waiting half a minute for a view to appear is not OK, that kind of UX will not make to production ever. Imagine using the app for prolonged periods; at some point you achieve extreme frustration.

Since I use react-navigation only on Android side, I do not want to implement unecessary shouldComponentUpdate methods for each of the views, since on iOS NavigatoriOS performs well.



Until these issues are fixed, I would like to limit the size of the history stack;
And any way I don't want the user to be able to navigate in some abiss of history, usually 10 back steps are enough, since in most cases users will actually user navigation drawer to get somewhere in the app; detail views usually don't get deeper than 3 or 4 levels...

P.s. need some decent way to disable scene transitions, as they perform poorly as well; regardless of history stack size.

**Comment by kelset** [comment]
There's a [FAQ related](https://github.com/react-navigation/react-navigation#my-app-is-really-slow) to performances and a couple of issues already opened on those subjects, so I won't reopen this issue.
