### ISSUE TITLE
react-navigation": "1.0.0-beta.23" has some problem

### ISSUE THREAD

**Issue by dcwang316** [react-navigation/react-navigation#3248]
const MyApp = DrawerNavigator({
	Home: {
		screen: MyHomeScreen,
	},
	Notifications: {
		screen: MyNotificationsScreen,
	}
},{
	drawerWidth:200
});
when add drawerWidth ，it's go wrong，why？how to use it?

**Comment by Ajith-Pandian** [comment]
@dcwang316  Need more information. What do you mean by `it's go wrong`? Describe more.

You should follow **issue template**. It will help to understand your problem exactly. If you are not following issue template, this issue will be closed. For more information - [ISSUE TEMPLATE](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by kelset** [comment]
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

(thanks @Ajith-Pandian for your comment)
