### ISSUE TITLE
Stacks in tabs

### ISSUE THREAD

**Issue by robertmylne** [react-navigation/react-navigation#3256]
I can't seem to find an example for "Stacks in tabs" only for "Stacks over tabs". 

Can someone point me in the right direction please.

My stacks over tabs code:
```
export default Routes = StackNavigator({
    Tabs: {
        screen: TabRoutes // TabNavigator
    },
    Profile: {
        screen: ProfileView,
        path: 'profile/:id',
        navigationOptions: ({navigation}) => ({
            title: `${navigation.state.params.user.name}`
        })
    }
})
```

Profile screen in the stack that is meant to be inside the tab, but it sits over the tabs.

**Comment by kelset** [comment]
Hi @robertmylne! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Comment by Ajith-Pandian** [comment]
@robertmylne 
I think this is not an issue about **react-navigation**. Please create **issues** if you find any bug/issue in the repo. Questions like this should be posted on [StackOverflow](https://stackoverflow.com/) with tag `react-navigation`.

Though you are creating an issue, [ISSUE_TEMPLATE](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) should be should be followed.
This issue will be closed because you are not following ISSUE_TEMPLATE.

**StackNavigator** is used to stack multiple screens. 
```js
const App = StackNavigator({
  First: { screen: FirstScreen },   /* seperate screen */
  Second: { screen: SecondScreen }  /* seperate screen */
});
```

**TabNavigator** is used to show multiple views on the same screen. 
```js
const App = TabNavigator({
  First: { screen: FirstTab },   /* same shared screen */
  Second: { screen: SecondTab }  /* same shared screen */
});
```

If you want to show ProfileScreen inside tabs, then you should put ProfileScreen inside TabNavigator, not on StackNavigator.
```js
const TabRoutes = TabNavigator({
  First: { screen: YourFirstTab } /* some screen */,
  Second: { screen: YourSecondTab } /* some screen */,
  Profile: {
    screen: ProfileView,
    path: "profile/:id",
    navigationOptions: ({ navigation }) => ({
      title: `${navigation.state.params.user.name}`
    })
  }
});

export default Routes = StackNavigator({
   /* other screens */
    Tabs: {
        screen: TabRoutes // TabNavigator
    },
   /* other screens */
 })
````
