### ISSUE TITLE
Lazy Load Select Tabs, or stagger loading

### ISSUE THREAD

**Issue by joecaraccio** [react-navigation/react-navigation#3292]
Hi Everyone,

Has anyone ever looked into lazy loading only select tabs in the tab bar, but not alll tabs?

For example, I have 3 tabs I want to load like normal, but 2 tabs that aren't needed immediately and would work with a lazy load.. is this possible?
I guess if I just wanted to stagger loading I could use a timer in the componentDidMount or something

Any ideas?

**Comment by kelset** [comment]
Hi @joecaraccio ! It looks like this is not a bug of the library nor a feature request, so I'll close it: I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of questions. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord. There are React Native and React Navigation channels with helpful people who might be able to answer your question. I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

That said, since `beta.23` `lazy` has been dropped and soon-ish a new feature will be in place to make you able to detect which screen is focused, so the whole logic will change towards that.

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Comment by joecaraccio** [comment]
well it kinda is a feature request :( , but I wanted to see if it existed to begin with

**Comment by joncursi** [comment]
@joecaraccio this used to be a feature, but it was removed after beta 22. You might want to downgrade. I did.

https://github.com/react-navigation/react-navigation/pull/3064

**Comment by MaxInMoon** [comment]
@joecaraccio  so if I understand well, `lazy` can only be apply for all or none tabs from a TabNavigator? (not just one tab?)

**Comment by brentvatne** [comment]
@MaxInMoon - correct. but you can build this by yourself by turning lazy to false and using `withNavigationFocus` on your tabs
