### ISSUE TITLE
react navigation transitionConfig use custom for Android and default only for iOS

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#3343]
I want to implement horizontal animation when performing navigation between screens and stacks.
I used the very helpful reply in #1759 by @kumarpatel.

in the last part of code I wrote:
```
const HORIZONTAL_SLIDE_TRANSITION_OVERRIDE = () => ({
  transitionSpec: {
    duration: 250,                                     // These are optional, so feel free to modify them as you see fit.
    easing: Easing.inOut(Easing.ease),
    timing: Animated.timing
  },
  screenInterpolator: (Platform.OS === 'android')
      ? forHorizontalSlideInFromLeft
      : NavigationSceneRendererProps.defaultTransitionConfig,
});
```

I know this is not the right way, since I am getting `can't find variable: NavigationSceneRendererProps`

**Comment by kelset** [comment]
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Comment by assafb81** [comment]
Hi @kelset,
All that data is in issue #1759.
its not a bug, but a question on how to use?

**Comment by satya164** [comment]
@assafb81 the issue tracker is only reserved for bugs. please post questions on stack overflow.
