### ISSUE TITLE
How I get routes length ?

### ISSUE THREAD

**Issue by stevelyc** [react-navigation/react-navigation#3349]
In my project, I want to get the length of StackNavigator`s routes. To my disappointed, I can`t find method to get it.What should i do

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta
| react-native     | 2.0.1
| node             | 9.3.0
| npm or yarn      |  1.3.2

**Comment by brentvatne** [comment]
hi there! as the issue template suggests, this is for bugs. for your reference, the issue template again:

## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

**Comment by joshuapinter** [comment]
@stevelyc Did you ever come up with a solution for this? We need to handle when we're at the root of the StackNavigation so that we can trigger a `BackHandler.exitApp()` instead of `navigation.goBack()`, which does nothing. 

In v1 we could just check the return value of `navigation.goBack()` because it was `undefined` _only_ when at the root of the StackNavigation. In v2, this is no longer the case, it returns `undefined` always.

Thanks!

**Comment by brentvatne** [comment]
@joshuapinter - that sounds like an unintentional breaking change
