### ISSUE TITLE
Solutions to Delay?

### ISSUE THREAD

**Issue by joecaraccio** [react-navigation/react-navigation#3351]
Hi Everyone,

this is a more general question but I think there is a feature not working correctly.

I compiled a release build of my React Native app, and noticed any sort of navigating with React Navigation.. like tab bars or using 'this.props.navigate' that there seems to be a uniform delay, where upon button press there is a slight delay that feels just slightly too long.

I did some research, and this is where I could be wrong that found that there is a transition delay by default defined in the Transitioner.js file in the source of React Navigation.
(https://github.com/react-navigation/react-navigation/blob/master/src/views/Transitioner.js)

On line 8, I tried changing duration from 250 to 0. I guess that is supposed to be 250ms, so I tried to change it to 0 to create as minimal a delay as possible. Is this the wrong thinking? I am guessing there is a way to pass it inline to each navigator.. but couldn't really understand how to do so.

The issue is this didn't seem to make a difference transition wise.. still had that slight delay on each press, that just feels a smidge too long

**Comment by kelset** [comment]
Hi @joecaraccio - as far as delay/performances I recommend you read the linked issues in this [section of the README](https://github.com/react-navigation/react-navigation#my-app-is-really-slow).

For what you are saying about the 250ms delay, as you point out that's the default behaviour (which may be related to multiple reasons, like UX patterns or avoiding to overload the JScore during the transition - maybe @ericvicenti has some more insight).

You can also override it via [this property](https://reactnavigation.org/docs/views/transitioner#configureTransition-function) if you feel the necessity; but tbh most likely the 'slowness' you perceive is caused by 'too much going on' when you navigate/load a new screen.

(yeah I had an hard time choosing the tags, sry about that)

**Comment by iamsoorena** [comment]
@joecaraccio I have the same exact problem, did you find a solution?
the only thing that I found out useful was to revert back `1.5` version

**Comment by iamsoorena** [comment]
@kelset I assure you that there is something absolutely wring about version 2.
my app has two identical branches, the only differences are about upgrading from 1.5 version to 2.
version 1.5 works right!
but every StackNavigator transition in version at least takes 250ms.
If you look through issues that people face. this is one of the most frequent ones.

**Comment by danilo525** [comment]
I had the same problem, I was using SwitchNavigator, then I changed to createSwitchNavigator. Now it's working well.

**Comment by kerwin1** [comment]
same

**Comment by gabrielhpugliese** [comment]
Something is really broken within createStackNavigator. I can also confirm that going back to v1 makes it with no lag at all. Also using createSwitchNavigator makes it to work but sometimes you don't want to use it.

**Comment by ventr1x** [comment]
Why is this closed without any comment and an unrelated reference (which again is closed with another unrelated reference)?
I have the same issue right now with an app with empty screens.
The delay is always the same (about 250ms), seemingly only on Android.
It is stupid to force such a delay upon people without documentation or reasoning behind it. It makes the entire app slower than every webapp.

And please stop referencing docs without writing the actual solution. As this lib has clearly no competent planning, every single link is broken (that is a problem on 95% of all links in all issues and search results, good work devs!).

**Comment by fawaz-ahmed** [comment]
I did this workaround for smooth transitions, maybe this can help. You can wrap your screen container in this HOC and transitions will go smooth again. The trick is to render after `interactions`:

```import React, { PureComponent } from 'react';
import { InteractionManager } from 'react-native';

export default class LazyHOC extends PureComponent {

  state = {
    hidden: true,
  };

  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      this.setState({ hidden: false });
    });    
  }

  render() {
    if(this.state.hidden) {
      return null;
    }

    return this.props.children;
  }
}
```
and then in your screen container:
```
<LazyHOC>
  {/* Your container */}
</LazyHOC>
```

**Comment by Deprofets** [comment]
I noticed animation performance is heavily influenced by the components being used in the screen, so in order to get it smoother you have to make use of InteractionManager in the componentDidMount lifecycle. 

A workaround is to mount as little as you can and force a rerender with runAfterInteractions afterwards.

**Comment by club9822** [comment]
> I had the same problem, I was using SwitchNavigator, then I changed to createSwitchNavigator. Now it's working well.

why you should replace switch navigator if i wanna unmount Auth screens ?  have a auth workflow ?  how you implemented the `https://reactnavigation.org/docs/en/3.x/auth-flow.html` ?

**Comment by syedsaadqamar** [comment]
I was facing the slow tab navigate issue, The slow issues occur when having nesting things like in my case

I have Drawer from react-navigation/drawer FIRST LEVEL
Second I have Tabs from '@react-navigation/bottom-tabs' under the drawer SECOND LEVEL
The third thing I have a stack (it has multiple screens) from @react-navigation/stack under the Tabs THIRD LEVEL
<Drawer.Navigator>
   <Tab.Navigator>
       <Stack.Navigator>
           <Stack.Screen name="Home"></Stack.Screen>
           <Stack.Screen name="Details"></Stack.Screen>
       </Stack.Navigator>
      <Stack.Navigator>
           <Stack.Screen name="Task"></Stack.Screen>
           <Stack.Screen name="Details"></Stack.Screen>
       </Stack.Navigator>
       .....
   </Tab.Navigator>
</Drawer.Navigator>
So if I remove any one thing from above the slow issue was gone for example if I remove Drawer.Navigator so I have only two nested things Tab.Navigator and Stack.Navigator so issue was gone.

So what I did I remove Drawer and use a drawer from native base(you can use another drawer package).

   <Tab.Navigator>
       <Stack.Navigator>
           <Stack.Screen name="Home"></Stack.Screen>
           <Stack.Screen name="Details"></Stack.Screen>
       </Stack.Navigator>
      <Stack.Navigator>
           <Stack.Screen name="Task"></Stack.Screen>
           <Stack.Screen name="Details"></Stack.Screen>
       </Stack.Navigator>
       .....
   </Tab.Navigator>
I know how pain is that I suffering it for a long time and didn't find any solution from the official team, Hope Team will fix nesting issue soon, for now, you can use that solution.

**Comment by spencer741** [comment]
For those experiencing rendering delay and are using a custom header with React Native Paper, I recommend reading [this comment](https://github.com/callstack/react-native-paper/issues/975#issuecomment-653647600). Whether you're using a custom header you built or loading a ton of data (i.e., where you might be using react-native ScrollView instead of FlatList and/or impacting app performance with synchronous data fetching), the problem is likely not with React Navigation.

That being said, I can't attribute to the reasoning behind @kelset 's answer ... I will re-tag @ericvicenti in asking about the reasoning for the built -in delay.
