### ISSUE TITLE
Dynamically enable / disable swipe for StackNavigator nested in TabNavigator

### ISSUE THREAD

**Issue by seeksort** [react-navigation/react-navigation#3379]
### Current Behavior

We currently have a TabNavigator with nested StackNavigators. `swipeEnabled` is set to `true` for the TabNavigator, however for our use case we would like to dynamically disable the swiping when a different screen is popped onto the stack.

We reviewed a related issue and fix, [#1760](https://github.com/react-navigation/react-navigation/issues/1760) and [#2906](https://github.com/react-navigation/react-navigation/pull/2906), in which the `swipeEnabled` boolean was added to resolve the initial problem in 1760. However `swipeEnabled` only turns the swiping between tabs on and off, not the swiping in individual screens stacked on top of the base TabNav. 

### Expected Behavior

For our use case, we need to be able to swipe between tabs at their default screens, but then turn off the swiping when we reach additional pages in our stack navigator. So, `swipeEnabled: true` for navigating b/w the Home and Notifications tabs (see [this Expo Snack](https://gist.github.com/seeksort/6ac8d7a88d714425bb7296dd5947b3c6)) and `swipeEnabled: false` when NewMessageScreen or SubsequentMessageScreen is on top of the stack.

We messed around in the `TabView.js` and were successful in getting `swipeEnabled` to dynamically change by subscribing it to props for child components, per [this comment](https://github.com/react-navigation/react-navigation/issues/1760#issuecomment-306153641) in 1760, however we wondered if others had the same use case as us.

### How to reproduce

- Run `react-native init PROJECT_NAME` from command line
- cd into the directory
- `npm i react-navigation`
- Overwrite App.js with the code from [this Gist](https://gist.github.com/seeksort/6ac8d7a88d714425bb7296dd5947b3c6)

If you go to the Notifications tab, then go to other screens in the stack (MessageScreen or SubsequentScreen), you're still able to swipe back over to the Home Tab. We would like to prevent this from happening on the MessageScreen and SubsequentScreens.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.27
| react-native     | ^0.52.0
| node             | 8.9.3
| npm or yarn  | 5.6.0

**Comment by kelset** [comment]
Hi @seeksort! It looks like this is not a bug in the library, so I'll close it.

For questions, I suggest next time you should use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of issues. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord: there are React Native and React Navigation channels with helpful people who might be able to answer your question.

I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

For feature requests, you need to use [Canny](https://react-navigation.canny.io/feature-requests) instead. Or you can write an RFC if you have ideas for how to implement a feature request [on the dedicated repo](https://github.com/react-navigation/rfcs).

That said, this issue lays in a sort of a grey area tbh - I'm not sure if this may be caused by a bug in props not being passed properly. Maybe @satya164 knows.

If you believe that you are experiencing a bug, please open a new Issue following the dedicated template or submit a PR.

**Comment by hoodsy** [comment]
@seeksort did you have any luck getting this to work for you?
