### ISSUE TITLE
Dynamically disabling swipeEnabled on tab navigator

### ISSUE THREAD

**Issue by joecaraccio** [react-navigation/react-navigation#3380]
When I try to dynamically enable and disable swiping in a TabNavigator using the setParams option, that works.

However it triggered a Rerender of the TabNavigator, and looks poor when I do that. Is there a way to dynamically do this without causing a Rerender on the tabnavigator?

**Comment by kelset** [comment]
Hi @joecaraccio! It looks like this is not a bug in the library, so I'll close it.

For questions, I suggest next time you use [Stack Overflow](https://stackoverflow.com/search?q=react-navigation) which is better suited for answering these types of issues. I also encourage you to join the [Reactiflux](https://www.reactiflux.com/) community on Discord: there are React Native and React Navigation channels with helpful people who might be able to answer your question.

I would also like to mention that there is a collection of helpful links and tutorials for React Navigation in the [README](https://github.com/react-community/react-navigation#community-contributions) which might be helpful for you.

For feature requests, you need to use [Canny](https://react-navigation.canny.io/feature-requests) instead. Or you can write an RFC if you have ideas for how to implement a feature request [on the dedicated repo](https://github.com/react-navigation/rfcs).

That said, you should also keep an eye on this https://github.com/react-navigation/react-navigation/issues/3379 because it's around the same subject.

If you believe that you are experiencing a bug, please open a new Issue following the dedicated template or submit a PR.

**Comment by joecaraccio** [comment]
it might as well be a bug..

**Comment by brentvatne** [comment]
@joecaraccio - not sure what you mean by that. it's currently configured statically when the navigator is initialized, so not being able to change that is expected behavior. a missing feature that you think should exist is not a bug :) making it dynamic would be adding a feature to the library. I agree we should probably make it dynamic though, and if you'd like to submit a pull request for this then I will look at it.
