### ISSUE TITLE
TabNavigator Custom Transition (Doc + Expo)

### ISSUE THREAD

**Issue by LouisJS** [react-navigation/react-navigation#3464]
### Current Behavior

We should be able to create custom animation by switching from a tab to another thanks to [#2222](https://github.com/react-navigation/react-navigation/pull/2222) 
But even on the Expo project, in the section 'Animated Tabs Example', it doesn't change anything.

### Expected Behavior

Be Able to implement custom transition between tabs such as fade-in animation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.53
| node             |   9.5
| npm or yarn      |  4.6

**Comment by brentvatne** [comment]
hi there, you might want to create something on the website repo to ask for clarification in the docs: http://github.com/react-navigation/website

the animated tabs only slide from one tab to the other, they don't do fade. you can do this using `addListener` on the tabs

**Comment by brentvatne** [comment]
@LouisJS - this is a place for bugs, not feature suggestions or requests. please read the issue template:

<hr />

## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repoistory as that is outside of the scope of Rect Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |
