### ISSUE TITLE
Typescript definitions out-of-date

### ISSUE THREAD

**Issue by jbrodriguez** [react-navigation/react-navigation#3491]
### Current Behavior

There's an issue with typescript definitions

```js
Argument of type '{ dispatch: NavigationDispatch<any>; state: NavigationState; addListener: any; }' is not assignable to parameter of type 'NavigationProp<NavigationState, NavigationStackAction>'.
  Object literal may only specify known properties, and 'addListener' does not exist in type 'NavigationProp<NavigationState, NavigationStackAction>'.
```

comes from 

```js
<Navigator
  navigation={addNavigationHelpers({
	dispatch: this.props.dispatch as NavigationDispatch<any>,
	state: this.props.nav,
	addListener,
  })}
/>
```

### Expected Behavior

It shouldn't flag addlistener as an error

### How to reproduce
By following the steps mentioned in redux-integration, and using typescript for type definitions

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.52.2
| node             | 8.4.0
| npm or yarn      | npm 5.6.0

initial issue: https://github.com/react-navigation/react-navigation-redux-helpers/issues/3

**Comment by brentvatne** [comment]
nobody working on react-navigation maintains the typescript definitions. if you would like to take charge of that it would be great! until they're part of this repo (like the [flow interface](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js)) I won't consider this to be a bug. we are very open to this: https://github.com/react-navigation/react-navigation/pull/1972#issuecomment-364497553 

if you're interested please submit a pull request. until then the appropriate place for this issue is on definitelytyped

**Comment by brentvatne** [comment]
sorry I noticed that @Ashoat pointed you here after reading the initial issue you linked to.

> More generally, this question is about figuring out a way to maintain a TypeScript libdef as we iterate on the library. (We have a pipeline in place for this for Flow, but not for TypeScript right now.)

:+1: I agree with this but I don't think that putting it in an issue here is the right place, because issues on this repo are exclusively for bugs. so a PR or a [RFC](https://github.com/react-navigation/rfcs) or a [feature request](http://react-navigation.canny.io/) would be more appropriate. sorry for the run around!

**Comment by Ashoat** [comment]
I think the main thing we’d need is a way to flag CI whenever types break. The approach we use for Flow is an in-repo libdef that is consumed within a in-repo typed example project. The downside is that it relies on the coverage of that example project. I’m not familiar with TypeScript best practices.
