### ISSUE TITLE
Error: There is no route defined for key DrawerClose.

### ISSUE THREAD

**Issue by rupy** [react-navigation/react-navigation#3506]
Hi,
To create two side drawer,
I set drawer route config according to #1803 .

```
    drawerOpenRoute: 'RightDrawerOpen',
    drawerCloseRoute: 'RightDrawerClose',
    drawerToggleRoute: 'RightDrawerToggle',
```

but I got this error:

```
Error: There is no route defined for key DrawerClose. Must be one of: 'RightDrawerClose', 'RightDrawerOpen', 'RightDrawerToggle'
```
react-navigation version is 1.0.3.
Please tell me if there are any good ways.

Thanks.

**Comment by matthamil** [comment]
Hey @rupy , can you create a reproducible [Snack](https://snack.expo.io/) of this problem?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
@Louxis 

please create a new issue and follow the template
