### ISSUE TITLE
Header Back Button doesn't working (redux integration)

### ISSUE THREAD

**Issue by felipemendesbraga** [react-navigation/react-navigation#3547]
Guys, recently I updated the react-navigation from version v1.0.0-beta.24 to 1.0.3. Because of this process, the header back button has stopped working on my StackNavigator, I press it and no action occurs, (including redux dispatch). 

my code:

```
// reducer function
const initialState = MyNavigator.router.getStateForAction(
  MyNavigator.router.getActionForPathAndParams('Intro')
);

export default function navReducer (state = initialState, action) {
  const nextState = MyNavigator.router.getStateForAction(action, state);

  // Simply return the original `state` if `nextState` is null or undefined.
  return nextState || state;
};


// reducer
const reducers = combineReducers({
  navigation: navReducer,
// ...
});

// Store
const navMiddleware = createReactNavigationReduxMiddleware(
  "root",
  state => state.navigation,
);

const createMyStore = compose(
    applyMiddleware(
      thunkMiddleware,
      ReduxPromise,
      logger,
      navMiddleware
    )

)(createStore)

const store = createMyStore(reducers)

// App

Component App extends Component {
  constructor(props) {
    super(props)
    this.addListener = createReduxBoundAddListener("root");
  }

  render() {
    return (
        <MyNavigator
          ref="navigator"
          navigation={addNavigationHelpers({addListener: this.addListener, dispatch: this.props.dispatch, state: this.props.navigation})}
        />
    );
  }
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
