### ISSUE TITLE
FEATURE REQUEST: fallback route and onError callback for root navigator

### ISSUE THREAD

**Issue by serhiipalash** [react-navigation/react-navigation#3566]
I have complex nav reducer with complex logic. It is possible that next nav state redirects on non-existing routeName in some cases.

Can you add api to set "fallback route"? Like on websites there is "fallback on home page".

```
Error: There is no route defined for key ...
```

Assume this error has code 404, then

```
<AppNavigator
  navigation={addNavigationHelpers({
    dispatch: this.props.dispatch,
    state: this.props.nav,
    addListener: this.addListener,
  })}
  onError={error => {
    if (error.code === 404) {
       return "HomeScreen"
    }
  }}
/>
```

**Comment by brentvatne** [comment]
hi there!

the correct place for feature requests is https://react-navigation.canny.io/feature-requests as per the issue template :) the issues here are only for bugs

**Comment by brentvatne** [comment]
the issue template, for your reference:

<hr />

## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repoistory as that is outside of the scope of Rect Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by serhiipalash** [comment]
I solved it with [`ErrorBoundary` wrapper](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html) that was added in lates React
```
<ErrorBoundary auth={this.props.auth} dispatch={this.props.dispatch}>
  <AppNavigator
    navigation={addNavigationHelpers({
      dispatch: this.props.dispatch,
      state: this.props.nav,
      addListener: this.addListener,
    })}
  />
</ErrorBoundary>
```

`ErrorBoundary.js`
```
export default class ErrorBoundary extends React.Component {
  render() {
    return this.props.children
  }

  componentDidCatch(error, info) {
    if (
      error &&
      error.message &&
      /Error: There is no route defined for key/g.test(error.message)
    ) {
      console.log('[ERROR BOUNDARY] missing route error!')

      if (this.props.auth.isEmpty) {
        this.props.dispatch({
          type: NAV__SET_AUTHENTICATED_USER_INITIAL_STATE,
        })
      } else {
        this.props.dispatch({
          type: NAVIGATION__SET_ANONYMOUS_USER_INITIAL_STATE,
        })
      }
    }
  }
}
```

**Comment by serhiipalash** [comment]
> hi there!
> 
> the correct place for feature requests is https://react-navigation.canny.io/feature-requests as per the issue template :) the issues here are only for bugs

Ok, sorry.

**Comment by brentvatne** [comment]
nice solution :)

**Comment by serhiipalash** [comment]
> nice solution :)

Maybe as temporary fix )
But I still see Red Error screen in production. User have to press "dismiss" to continue with app. 

@brentvatne is there anything to make Navigator's errors silent?

Sorry, if I am asking it in wrong place.

**Comment by brentvatne** [comment]
not that i'm aware of
