### ISSUE TITLE
Swiping backwards are not triggering redux subscribers

### ISSUE THREAD

**Issue by hampustagerud** [react-navigation/react-navigation#3575]
I'm using react-navigation with redux and it works fine most of the time except when I swipe backwards, then the subscribers to the store is no longer notified. The action is printed in the log and I can catch it in my reducer but it is not passed on to my subscribers. This is the only event and the only way I have found that it is not passed, it works when pressing a back button or manually triggering goBack().

### How to reproduce

- Implement react-navigation with redux and try to subscribe to events in an object.
- Navigation/BACK events are not passed to redux subscribers when swiping backwards (even though it passes through the reducer).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.2
| react-native     | 0.53.0
| node             | 9.4.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
