### ISSUE TITLE
Header and view zIndex

### ISSUE THREAD

**Issue by guizmo** [react-navigation/react-navigation#3576]
I would like to know if it is possible for a view to overlap the header (using the StackNavigator) ...

![screen shot 2018-02-23 at 15 46 28](https://user-images.githubusercontent.com/699063/36578359-c0d61082-18b0-11e8-957b-82f8dd823fa7.png)

**Comment by brentvatne** [comment]
zIndex in react-native is the source of a lot of pains for developers because it doesn't quite work the same as on the web. you can use something like a portal or 'root-modal' to render over top of the content, or render your own header on the screen (set header: null in navigation options and render it as another component).
