### ISSUE TITLE
Breaking change in minor revision

### ISSUE THREAD

**Issue by ScreamZ** [react-navigation/react-navigation#3582]
Hello,

I'll stay calm but I'm really getting sad after what I'm seeing.... React navigation is supposed to be the "most" official way to deal with navigation in react native.

We are supposed to be (now) **on V1 stable** and we still get breaking changes in minor revisions ? Why not in beta, but we are no longer in beta.

I've passed 3 days refactoring my app according to the new version and now that I try to patch to 1.1.X to fix issues, my app broke for a simple...

```js
this.props.navigation.dispatch(
      NavigationActions.reset({
        index: 0,
        actions: [NavigationActions.navigate({ routeName })]
      })
    )
```

After some times, i've seen that lazy loading has been activated. And this force me to use addListener everywhere instead of componentDidMount. This is not a bad thing in fact, but please stop change the behavior everyday...

Can we please consider adopting a stable, production ready workflow and avoid those kind of "random breaking" changes ? The library is already hard to take in hand and if you keep break changing this is really hard to make it work and elaborate functional patterns.

As said in semantic versioning: 

```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner
```

Without animosity,
Best regards

**Comment by bryaneaton13** [comment]
I ran into this same issue. It seems to be using the `initialRouteName` (or first route) that's set in your StackNavigator instead of using the value that gets passed in.

**Comment by ScreamZ** [comment]
I also check deeply the behavior, reset is doing its reset on the current route, which means that if you don't use lazyload all your components are mounted at the same time and if you use `componentDidMount` on any of tab 2 or 3 this, this will trigger the reset as if you were on the first route and fail.

The lazy load API is critical, this completely break the behavior of an application. I agreed with the principale that lazyload should be disabled and you have to rely on your own with loading state while you're not on the select tab.

So please, **take a decision on that assertion and keep it along the current MAJOR VERSION**. 
And do not change it…

regards

**Comment by brentvatne** [comment]
hi there,

first of all, sorry for the hassle, i really do not want to inconvenience people and i'm trying to make people's lives easier with work on this project.

going forward i'll try to follow semantic versioning more faithfully. that said, you should always read release notes (https://github.com/react-navigation/react-navigation/releases). the changes that impacted your app fix broken behavior (slow loading because of rendering all tabs up front) but break in some edge cases (like yours). in hindsight this should have been a major release, and i'll be more cautious about this going forward, but please look at release notes.
