### ISSUE TITLE
Backbutton default behavior buggy ?

### ISSUE THREAD

**Issue by ScreamZ** [react-navigation/react-navigation#3584]
Hi,

it seems that the condition is inverted... This make the backbutton exit the app instead of going back in the stack.

https://github.com/react-navigation/react-navigation/blob/b3bf80634d20238130c700964a01c92b9c47cacb/src/createNavigationContainer.js#L51

It look like we are achieving the right behavior (meaning goback) by replacing by 

```js
_isStateful() {
      return !!this.props.navigation
}
```

What do you think ? Semantically speaking, having navigation mean being stateful isn't ? Not the opposite

Should I make a PR if you confirm ?

Regards

**Comment by markgoodyear** [comment]
I'm seeing the same issue @ScreamZ.

However, if I change the source to:

```
_isStateful() {
      return !!this.props.navigation
}
```

My app no longer navigates, the back button works again though from what I can tell, as tab navigation still works, and can go back to the previous tab with the back button.

**Comment by ScreamZ** [comment]
I'm also using redux, and I implement my own behavior in the RootNavigator that is using redux.

The thing is that if you don't do that, due to the issue I shown above your app is exiting.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
