### ISSUE TITLE
Blank screen with TabBar

### ISSUE THREAD

**Issue by alizahid** [react-navigation/react-navigation#3585]
These are my navigators

```
const AppNavigator = TabNavigator({
  One,
  Two,
  Three
})

export const Navigator = StackNavigator({
  login: Login,
  app: AppNavigator
})
```

### Current Behavior

Starts with `login`, and then navigates to `app`.

But once there, other than the initial tab `One`, the rest are all blank if I navigate using the `TabBar`. If I navigate with a custom `navigate('Two')`, it works fine.

At first, I thought maybe it was my views. So I replaced all three with the first one, which renders properly. But that didn't work.

This leads me to believe that `TabBar` isn't invoking the proper methods for navigation, or some such issue.

### Expected Behavior

`TabBar` should render the other screens. I've even tried setting `lazy` to `false`, but that didn't help.

### How to reproduce

Code included above. Has `redux` integration.

### Your Environment

| software  | version
| ----- | -----
| react-navigation | 1.1.2
| react-native | 0.53.3
| node | 9.5.0
| yarn | 1.3.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
