### ISSUE TITLE
DrawerNavigator dynamic routes not working.

### ISSUE THREAD

**Issue by alex-gunning** [react-navigation/react-navigation#3587]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior

I'm trying to implement a DrawerNavigator with a list of dynamic routes from Redux state. The DrawerNavigator is a child of a TabNavigator. The TabNavigator is setup so there is a **menu** button which toggles the drawer open and closed

**in TabNavigation.js**
```
Food: {
    screen: FoodDrawerHOC,
    navigationOptions: ({ navigation }) => ({
      title: 'Menu',
      headerLeft: <MenuIcon onPress={() => navigation.navigate('DrawerToggle')} />,
      tabBarLabel: <HamburgerTabIcon />,
    })
  },
```

**in DrawerNavigation.js**
```
const FoodDrawer = dynamicRoutes => DrawerNavigator(
  dynamicRoutes,
  {
    initialRouteName: 'All',
    drawerWidth: 250,
  }
);

class FoodDrawerHOC extends React.Component {
  // static router = ???
  componentWillMount(props) {
    const routes = composeRoutes(this.props.categories);
    this.FoodDraw = FoodDrawer(routes);
  }
  render() {
    return React.createElement(this.FoodDraw, omit(this.props, 'categories'));
  }
}

// FoodDrawerHOC.router = ???

const mapStateToProps = ({ menu }) => ({
  categories: menu.categories,
});

export default connect(mapStateToProps, () => ({}))(FoodDrawerHOC)
```

Now I understand that React-navigation needs the static `router` property on the HOC but how would I copy that from the instance component `this.FoodDraw`?

This thread has helped me the most so far. 
https://github.com/react-navigation/react-navigation/issues/3076

This works fine (as expected) when I hardcode the routes in and set 
```FoodDrawerHOC.router = FoodDrawer.router```

### Expected Behavior

I should be able to copy the `router` property from the child instance onto the parent HOC and thereby create dynamic routes based on state.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation  | 1.1.1
| react-native     | 0.52
| node             | 9.4.0
| npm or yarn      | 4.6.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by alex-gunning** [comment]
Okay. I will make one tomorrow :)
