### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by dsrini94** [react-navigation/react-navigation#3605]
I am Getting this error "undefined is not an object(evaluating '_this4.props.navigation.navigate')"    when I try to navigate using react-navigation 

MY Code 

import SortableListView from 'react-native-sortable-listview'

let data = {
  hello: { text: 'To Calculate nearest Sotes in the customer location',color:'#c42d17',status:'To Do',assignedTo:'Robert',completed:'0%' },
  how: { text: 'Storing the cart information in the database',color:'#e0953a',status:'Doing',assignedTo:'James',completed:'60%'  },
  test: { text: 'Calculate the delivery cost based on the weight of the product',color:'#22912c',status:'Done',assignedTo:'Robert',completed:'100%'  },
  this: { text: 'Tracking the orders',color:'#e0953a',status:'Doing',assignedTo:'Robert',completed:'50%'  },
  a: { text: 'To find the delivery cost based on the weather and trafic',color:'#c42d17',status:'To Do',assignedTo:'James',completed:'0%'  },

}

let order = Object.keys(data)

export default class UserStoryInfo extends React.Component {

  static navigationOptions = ({ navigation }) => ({
    title: `${navigation.state.params.oppTitle}`,
    });

    constructor(props){
      super(props);
    }

  render() {
    return (
      <SortableListView
       style={{ flex: 1 }}
       data={data}
       order={order}
       onRowMoved={e => {
         order.splice(e.to, 0, order.splice(e.from, 1)[0])
         this.forceUpdate()
       }}
       renderRow={row => <RowComponent data={row} />}
     />
      );
  }

renderRow({data, active,navigation}) {
      return <Row data={data} active={active} navigation={navigation}/>
    }
}

class RowComponent extends React.Component {

  constructor(props){
    super(props);
  }

  render() {
    return (
      <TouchableHighlight underlayColor={'#eee'} onPress={()=>this.props.navigation.navigate('activityInfo')}
        style={{
          flex:1,
          margin:10,
          backgroundColor: '#F8F8F8',
          borderColor: '#eee',
          elevation:5,
        }}
        {...this.props.sortHandlers} >
        <View style={{flex:1,flexDirection:'row',justifyContent:'space-between'}} >
          <View style={{flex:2}}>
            <Text style={{color:'black',fontSize:15,paddingBottom:5,paddingTop:5,paddingLeft:10,paddingRight:10,fontWeight:'bold'}}>{this.props.data.text}</Text>
            <Text style={{color:'black',fontSize:15,paddingBottom:5,paddingTop:5,paddingLeft:10,paddingRight:10}}>Assigned To {this.props.data.assignedTo}</Text>
            <Text style={{fontSize:15,paddingBottom:5,paddingTop:5,paddingLeft:10,paddingRight:10}}>Completed {this.props.data.completed}</Text>
          </View>
          <View style={{flex:1,backgroundColor:this.props.data.color,justifyContent:'center',alignItems:'center'}}>
            <Text style={{color:'white',fontSize:25}}>{this.props.data.status}</Text>
          </View>
        </View>
      </TouchableHighlight>
    )
  }
}

**Comment by satya164** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
