### ISSUE TITLE
`withNavigation` doesn't work with `SwitchNavigator`

### ISSUE THREAD

**Issue by migueloller** [react-navigation/react-navigation#3642]
### Current Behavior

- What code are you running and what is happening? Using `SwitchNavigator`

![image](https://user-images.githubusercontent.com/5677929/36918827-25413e52-1e29-11e8-9eaa-4fa2da058743.png)

### Expected Behavior

- What do you expect should be happening? `withNavigation` should work with `SwitchNavigator`.

### How to reproduce

- Wrap a component within one of the `SwitchNavigator` screens with `withNavigation`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |v1.3.0
| react-native     |https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz
| node             |v9.5.0
| npm or yarn      |v1.3.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by migueloller** [comment]
@brentvatne,

I apologize for no posting the repro. I don't think it's necessary to open a new issue, yeah?

https://snack.expo.io/S1HHbNwuG

Thanks for looking into this!
