### ISSUE TITLE
moving between modal and card

### ISSUE THREAD

**Issue by Tomatoo** [react-navigation/react-navigation#3671]
### Current Behavior

when I from ReportList to InfoModal, it is from bottom to top, that is right.
but when I from InfoModal to ReportDetail, it is also from bottom to too, I expect it is from right to left, how can I do? 

code:

```
const MainStack = StackNavigator(
    {
        ReportList: { screen: ReportList },
        ReportDetail: { screen: ReportDetail, navigationOptions: ({ navigation }) => ({ gesturesEnabled: false }) }
    },
    {
        mode: 'card'
    }
);

const RootStack = StackNavigator(
    {
        Main: {
            screen: MainStack,
        },
        InfoModal: {
            screen: InfoModal,
        }
    },
    {
        mode: 'modal',
        headerMode: 'none'
    }
)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.44.0
| node             | 6.12.3
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Tomatoo** [comment]
really thanks for your replay. this is my [demo](https://snack.expo.io/SJyvNfpOz)

**Comment by brentvatne** [comment]
if you don't set the `mode` to `modal` and instead just leave it as-is this will get you the behavior that you want.  see: https://snack.expo.io/BJWcpXkFz.

`modal` is a very bad name for this, it basically just changes the transition style to bottom-to-top rather than right-to-left and `headerMode` to screen (unless you override to set it to none, as you did).

we are going to rework modals soon, more discussion at https://github.com/react-navigation/rfcs/issues/15

**Comment by Tomatoo** [comment]
sorry if i do this, i cannot navigate modal from bottom to top.you can see [https://snack.expo.io/BJWcpXkFz](https://snack.expo.io/BJWcpXkFz), i want navigator to InfoModal(it is a modal) from bottom to top like a modal, but it from right to left like a card mode.

thanks.
