### ISSUE TITLE
Cannot use marginHorizontal within tabBarOptions > style

### ISSUE THREAD

**Issue by julesmoretti** [react-navigation/react-navigation#3675]
### Current Behavior

- When trying to add margins to just the TabBar.js section, the Indicator does not take the margin into consideration.

### Expected Behavior

- When assigning a margin Horizontal for the indicator to reduce size further.

### How to reproduce

- Create a TabNavigator as such:
```
const Tab = TabNavigator(
  {
    First: {
      screen: FirstScreen,
    },
    Second: {
      screen: SecondScreen,
    },
    Third: {
      screen: ThirdScreen,
    },
  },
  {
    tabBarOptions: {
      style: {
        marginHorizontal: 50,
      },
...
```
- you should see that the indicator is larger than 1 cell of the tab.

Snack: https://snack.expo.io/Sylo40adM

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.1.1
| react-native     | 0.52.0
| node             | v9.4.0
| npm or yarn      | 4.6.1

**Comment by matthamil** [comment]
:wave: Hi! Thanks for the issue. As stated in the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md), all bugs require a reproducible example, preferably made with [Snack](https://snack.expo.io/). Since this is missing a required part of the issue template, I'm going to mark this issue as closed. I'll gladly reopen it once it is reproducible. Thanks!

**Comment by julesmoretti** [comment]
@matthamil - I had not played with Snack before, its really cool!

Here you go: https://snack.expo.io/Sylo40adM

**Comment by brentvatne** [comment]
@satya164 - is this supposed to be supported? if not we should maybe warn if people pass these styles in

**Comment by julesmoretti** [comment]
Would love for those to be supported :)

**Comment by brentvatne** [comment]
moved to https://github.com/react-navigation/react-navigation-tabs/issues/17
