### ISSUE TITLE
TypeError : undefined is not an object (evaluating 'this.props.navigation.navigate')

### ISSUE THREAD

**Issue by Krishna812** [react-navigation/react-navigation#3679]
TypeError : undefined is not an object (evaluating 'this.props.navigation.navigate')

Here is my code 
/* @flow */

import React, { Component } from 'react';
import {
  View,
  Text,
  StyleSheet,
} from 'react-native';
import { Container, Header, Content, Button} from 'native-base';
import Loginuser from './Loginuser';
import {
  StackNavigator,
} from 'react-navigation';

const AppNavigator = StackNavigator(
    {
        Loginuser: {screen: Loginuser},
    })

export default class Login extends Component {
  render() {
     const { navigate } = this.props.navigation;
   return (
     <Container>
       <Content>
         <Button block
            onPress={()=> navigation.navigate("Loginuser")
            }
         >
           <Text> Click here for Login/Registers</Text>
          </Button>
       </Content>
     </Container>
   );
 }
}

Kindly help me to resolve this issue

**Comment by matthamil** [comment]
It looks like you may be rendering the screen component rather than the navigator itself. Try exporting the `AppNavigator` instead. I can't really see what is happening in your abbreviated code snippet.

I'm going to close this issue. Issues are reserved for bug reports, and this looks like a usage question. I recommend posting to Stack Overflow or joining the [Reactiflux](http://reactiflux.com) community and asking in the #need-help channel.
