### ISSUE TITLE
Change header title in presentational component

### ISSUE THREAD

**Issue by giacomocerquone** [react-navigation/react-navigation#3687]
### Current Behavior

Hi guys, I was looking at this post: https://github.com/react-navigation/react-navigation/issues/1675
Actually I've always asked myself that exact same question, more important is: what do I do if I have to change the title of the header?

### Expected Behavior

For example, I can change title using something like:

  static navigationOptions = ({ navigation }) => ({
    title: 'my new title',
    headerTitleStyle: {fontSize:13}
  });

But I need to do this in the container component despite it is a presentational matter... is there a way to pass down something to the presentational component in order to call there this static method? I already pass down the prop navigation in order to navigate toward other components

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.53.0
| node             | 9.2.0
| npm or yarn      | npm 5.7.1

Ps. this may sound a question instead of a bug, but actually I believe it could be considered as a bug since I think there is no way to call the static navigationoptions method inside the presentational component

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
