### ISSUE TITLE
Cannot perform reset StackNavigator to Index

### ISSUE THREAD

**Issue by huynhtansi** [react-navigation/react-navigation#3697]
### Current Behavior

This is my login navigator

const LoginNavigator = StackNavigator({
		Welcome: { screen: WelcomeView },
		SignUp: { screen: SignUpView },
		SignIn: { screen: SignInView },
		Confirm: { screen: ConfirmView },
                Verify: { screen: VerifyView },
	});

Steps: Welcome -> SignUp -> SignIn -> Confirm -> Verify

At 'VerifyView' I perform action reset like this:

NavigationActions.reset({
				index: 2,
				actions: [
					NavigationActions.navigate({ routeName: 'Welcome' }),
					NavigationActions.navigate({ routeName: 'SignUp' }),
					NavigationActions.navigate({ routeName: 'SignIn', params: {email} }),
				]})

Instead of SignIn, it resets to root (Welcome).

### Expected Behavior

On v1.0.0.beta11 it works fine, I had just updated repo currently.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.0
| react-native     |0.53.0
| node             |8.9.1
| npm or yarn      |5.5.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
