### ISSUE TITLE
When using Tab navigator with Stack navigator it shows 2 strange errors 

### ISSUE THREAD

**Issue by ArtyomBaykov** [react-navigation/react-navigation#3715]
![29026121_1805530686148614_5213406963752239104_o](https://user-images.githubusercontent.com/33861066/37251937-805cec5e-2532-11e8-9ecf-acdfff4b8ba1.png)

![29063440_1805530846148598_6242474745552437248_o](https://user-images.githubusercontent.com/33861066/37251893-abc492e4-2531-11e8-9d8c-067dcfc1da84.jpg)

We are getting these 2 errors when clicking on the login button. Here is the code:

```
 const MainTabBar = TabNavigator(
  {

   Home: {screen: HomeScreen},
   Profile: {screen: ProfileScreen},

  },

    {
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        let iconName;
        if (routeName === 'Home') {
          iconName = 'search';
        } 
         else if (routeName === 'Profile') {
          iconName = 'contact';
        }

        return <Ionicons name={iconName} size={25} color={tintColor} />;
      },
    }),
    tabBarOptions: {
      activeTintColor: '#222222',
      inactiveTintColor: '#222222',
    },
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    animationEnabled: false,
    swipeEnabled: false,
    initialRouteName: 'Saved'

  }
);

const Main = StackNavigator(
  {
   Signin: {screen: SigninScreen},
    Signup: {screen: SignupScreen},
    Welcome: {screen: WelcomeScreen},
   Settings: {screen: SettingsScreen},
   Post: {screen: PostScreen},
   MainTab: {screen: MainTabBar}
  },
  {
    initialRouteName: "Signin",
    headerMode: "none",
  },
);
```

For login button we tried 2 things:

this.props.navigation.navigate('Home')
this.props.navigation.navigate('MainTab')

Both ways show the same issues.

Hope this time I can get help from you instead of just closing issue :)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
> Hope this time I can get help from you instead of just closing issue :)

if you follow the template next time and provide an example we can run on snack.expo.io or clone a repo then you will get help! otherwise you will not. sorry!

**Comment by ArtyomBaykov** [comment]
@brentvatne  just one question. Can you just look at this code which was written above can you just check combination part of stack navigator and tab navigator. I think as the one of creators of this library you may not need to run the code to see the mistake or the line that causes it.  There should be noticeable  thing. It's not a huge bug for which I must upload all project for running and finding where is the issue. I am sure that issue is inside the navigator part which was written above.

**Comment by brentvatne** [comment]
no, sorry i cannot. i don't have time to look at incomplete code examples :( if you provide a runnable example and create a new issue with it then i am happy to look
