### ISSUE TITLE
Android crash on navigate()

### ISSUE THREAD

**Issue by tommynordli** [react-navigation/react-navigation#3733]
### Current Behavior

I'm experiencing crashes on android sometimes when navigating to a view. I'm navigating to this view from four different places, and it only crashes from two of them. I'm not doing anything special on navigation when it crashes. Anyone else experienced this?
```
IllegalViewOperationException: Trying to add unknown view tag: 848
 detail: View tag:850
  children(1): [
847,
 ],
  viewsToAdd(1): [
[1,848],
 ],

    at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:394)
    at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:819)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
...
(15 additional frame(s) were not displayed)

Trying to add unknown view tag: 848
 detail: View tag:850
  children(1): [
847,
 ],
  viewsToAdd(1): [
[1,848],
 ],
```

### How to reproduce

I don't know why it happens, so I don't have any steps to reproduce. 

### Your Environment

| react-navigation | 1.2.1
| react-native        | 0.53.3
| node                    | 8.9.4
| npm                     | 5.6.0

**Comment by tommynordli** [comment]
Looks like it's only happening in debug

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
