### ISSUE TITLE
react native navigate

### ISSUE THREAD

**Issue by bawhari** [react-navigation/react-navigation#3735]
hi
what is the problem? help me plz
I want to go to the new page by pressing the button

export default class App extends Component<Props> {
    render() {
        return (
            <View style={styles.container}>

                <View style={{alignSelf: 'stretch', height: 80, opacity: .7, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'
                }}>
                    <TouchableOpacity onPress={() =>
                        navigate('iot')}
                        <Image source={require('./assets/image/ic_menu.png')}
                               style={{width: 50, height: 50, marginLeft: 60}}/>
                    </TouchableOpacity>
                    <TouchableOpacity>
                        <Image source={require('./assets/image/ic_menu.png')}
                               style={{width: 50, height: 50}}/>
                    </TouchableOpacity>
                    <TouchableOpacity>
                        <Image source={require('./assets/image/ic_menu.png')}
                               style={{width: 50, height: 50, marginRight: 60}}/>
                    </TouchableOpacity>

                </View>
            </View>
        );
    }
}

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
