### ISSUE TITLE
Navigation not working on RTL screen at v1.5.2

### ISSUE THREAD

**Issue by AlirezaAkbarix** [react-navigation/react-navigation#3747]
I've updated package version (from `1.0.0-beta2x` to **`1.5.1`**) and use [THIS link](https://reactnavigation.org/docs/redux-integration.html) to fix issues with redux, after updating I face with a bigger problem, in LTR devices it works fine but when I change locale to an RTL locale, only first page render and others are blank (**`TabNavigator`**)

**Comment by mojtabaatt** [comment]
Thank you mr. akbari. i also have this problem. god bless you. God Power you...

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by AlirezaAkbarix** [comment]
@brentvatne It's very easy to reproduce the issue! It's just a `I18nManager.forceRTL(true);` snippet that forces app load rtl.
If you think it's necessary to share a code feel free and just say it :)

**Comment by AlirezaAkbarix** [comment]
@brentvatne, I've found the problem!!
**`animationEnabled: false`** this line made this error when the app is RTL.
