### ISSUE TITLE
StatusBar backgroundColor is not working for views under TabNavigator in Android

### ISSUE THREAD

**Issue by harikrishnanp** [react-navigation/react-navigation#3756]
### Current Behavior

**App.js**

```
render() {
 const MainTabNavigator = TabNavigator({
      Tab1: {
        screen: TabView1,
      },
      Tab2: {
        screen: TabView2,
      },
   },
 tabBarPosition: 'bottom',
      animationEnabled: true,
      swipeEnabled: false,
      tabBarOptions: {
        activeTintColor: '#e91e63',
        showIcon: true,
        showLabel: false,
        style: {
          backgroundColor: '#000000',
        },
        indicatorStyle: {
          opacity: 0,
        },
      },
   });
return (<MainTabNavigator />);
}
```
**TabView1**

 ```
render(){
  return(
    <View style={styles.safeArea}>
     <StatusBar
       backgroundColor="green"
       barStyle="light-content"
     />
    />
  );
}
```

But in TabView1 the status bar colour is blue instead of green.

### Expected Behavior

In TabView1 the status bar colour should be green.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.52.0
| node             | v9.3.0
| npm or yarn      | 1.3.2

### Note

It works perfectly for `StackNavigator`

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by harikrishnanp** [comment]
No problem. I shall add it in snack.expo when I get time.
