### ISSUE TITLE
React navigation tries to render the previous screen when rendering another screen

### ISSUE THREAD

**Issue by christiansaiki** [react-navigation/react-navigation#3770]
The issue that I am facing is when I navigate from the Home screen to the Live Stream screen, I present an alert to the user if there is no live stream at the moment. If I go back and click immediately to another screen (Programas e Retrospectos), the alert pops up to me.
If I do the same procedure, but wait a few seconds before clicking in the Programs and Retrospects screen the alert does not pop up.

I know, it is a bit confusing, therefore I am leaving a link to a [video of this issue](https://drive.google.com/file/d/1wZE4wkM7fkriQ7oW_PPgKycEm5WnPSEG/view?usp=sharing)

The issue occurs in iOS on both device and simulator.

The issue does not occur in android.

Thank you so much.

**Comment by dverma4u** [comment]
i am also facing same issue

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

**Comment by rbadr** [comment]
Might be related to #3592

**Comment by ujjwalagrawal17** [comment]
@christiansaiki   Did you got any solution ??

**Comment by christiansaiki** [comment]
@ujjwalagrawal17, unfortunately this project I was working on was cancelled, therefore I didn't fix this issue.
