### ISSUE TITLE
state.params not working

### ISSUE THREAD

**Issue by montao** [react-navigation/react-navigation#3782]
I set an `id` parameter like this in screen 1 when I link to screen 2:

```
 <TouchableWithoutFeedback onPress={ ()=> this.props.navigation.navigate('FontsTab', { id: item.id }) } style={styles.listHeader} >
                <View  style={styles.listRowContainer}>
                    <View  style={styles.listinside1Container}>
                        <Image  style={styles.listImage} source={item.icon} />
                        <View  style={styles.listContainer} onPress={(event) => this._selectedItem(item.text)}  >
                            <Text style={styles.listHeader} >
                              {item.title}
                            </Text>
                            <Text  style={styles.listValue} >{item.value}</Text>
                            <Image 
                                style={{width: 50, height: 50}}
                                source={{uri: item.img}}
                            />

                        </View>
                    </View>

                                </View>
            </TouchableWithoutFeedback>
```

But it's not working. In screen 2 I can't use the `state.params` :

```
     <ScrollView style={styles.container}>
          <Text>{ JSON.stringify(this.props.navigation)}</Text>
          <Text>TEST{ state.params }</Text>
          <Image
              style={{width: 150, height: 150}}
              source={{uri: this.state.dataSource.img}}
          />
          <Text  style={styles.textStyle} >{this.state.dataSource.text}</Text>
      </ScrollView>
```

When I debug the `state` object there are no `params`. 

<img src="https://i.stack.imgur.com/8230B.png">

**Comment by lichenglu** [comment]
It might be you were confused about how to access the navigation params. It should be `this.props.navigation.state.params`, but it seems you tried to access the params with your component state. My preferred way is to use react navigation's helper `this.navigation.getParam('youParamKey', defaultValueIfParamNull)`

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
