### ISSUE TITLE
Nested StackNavigator renders twice within a SwitchNavigator

### ISSUE THREAD

**Issue by LiHsuanChen** [react-navigation/react-navigation#3786]
I am trying to navigate from Home to StackOne, it renders the StackOne screen twice (constructor called two times). Also, at first rendering, params aren't received at StackOne, but it does at the second time. So blocking the second rendering (suggested in #2599) doesn't solve the issue. Also since it renders twice, clicking on the back button at the second rendering goes back to the first rendering, which is the same screen.
```
export default SwitchNavigator({
    Home : Home,
    MyStack : StackNavigator({
      StackOne : { screen : StackOne },
      StackTwo : { screen : StackTwo }
    }, { initialRouteName : 'StackOne' })
  },
  { initialRouteName: 'Home' }
);
```
Here's the code used at Home to navigate to StackOne:
```
this.props.navigation.navigate({
      routeName: 'MyStack', 
      params: { user : userObj }
});
````
I've also tried, no luck.
```
this.props.navigation.navigate({
      routeName: 'MyStack', 
      params: {},
      action: NavigationActions.navigate({ routeName: 'StackOne', params: { user : userObj } })
});
```

| software         | version
| ---------------- | -------
| react-navigation | 1.5.7
| react-native     | 0.52.0
| node             | 6.10.1
| npm      | 4.6.1

**Comment by papayuca** [comment]
+1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
