### ISSUE TITLE
In first route page using navigation.goBack() in hardwareBackPress callback cause  callback fire infinitely.

### ISSUE THREAD

**Issue by yqz0203** [react-navigation/react-navigation#3799]
### Current Behavior

I custom a `Header` component and add a callback to listen `hardwareBackPress` event.

In first route page if I click the  back button, the callback will fire infinitely, I can see many `Navigation/BACK` actions dispatched.

If I don't use `hardwareBackPress` event , and just add a click event on a element, everything goes fine.

I can't find the reason, please help.

my code：
```
componentWillMount() {
    BackHandler.addEventListener('hardwareBackPress', this.handleBack);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.handleBack);
  }

  handleBack = () => {
    Keyboard.dismiss();
    if (this.props.onBack) {
      this.props.onBack();
      return true;
    }else{
      this.props.navigation.goBack();
    }
    return true;
  }
```

![image](https://user-images.githubusercontent.com/8850879/37644349-7d1339e4-2c5e-11e8-813e-eff869898471.png)

### Expected Behavior

- the callback only fire once.

### How to reproduce

- bind `hardwareBackPress` event in first route page, in the callback call ` this.props.navigation.goBack` function.

- click the android hardware back button.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     |0.51.0
| node             | 7.7.1
| npm or yarn      |5.4.2

**Comment by vonovak** [comment]
please include a runnable reproduction

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
