### ISSUE TITLE
LayoutAnimation on CustomTabBarBottom TabNavigator

### ISSUE THREAD

**Issue by syanbo** [react-navigation/react-navigation#3800]
![CustomTabBarBottom](http://oy5rz3rfs.bkt.clouddn.com/github/TabBar.gif)
```
<TabView
              key={index}
              tabStyle={tabStyle}
              labelStyle={labelStyle}
              curIndex={stateIndex}
              focused={focused}
              onPress={() => {
                if (onPress) {
                  onPress({
                    previousScene,
                    scene,
                    jumpToIndex,
                    defaultHandler: this._handleTabPress
                  });
                } else {
                  this._handleTabPress(index);
                }
                LayoutAnimation.configureNext(
                  LayoutAnimation.Presets.easeInEaseOut
                );
              }}
              icon={icon}
              labelText={label}
            />
```
if I delete LayoutAnimation code, it become correct, but I need LayoutAnimation

software | version
------------ | -------------
react-navigation |  1.5.2
react-native | 0.52.0

**Comment by vonovak** [comment]
From the description, it is not clear what your expected behavior is. LayoutAnimation *will* animate all of your layout, not only the component where you configured it. This is simply how it works, and is not an issue with react-navigation.

If you really think there is an issue with LayoutAnimation and react-navigation, please file an issue with a proper description.
