### ISSUE TITLE
Does not show any components in the output after giving prop event to the button

### ISSUE THREAD

**Issue by Krishna812** [react-navigation/react-navigation#3801]
Here is my code:

import React, { Component } from 'react';
import {
  View,
  Text,
  StyleSheet,
  AppRegistry,
} from 'react-native';
import { StackNavigator } from 'react-navigation';
import { Container, Header, Content, Form, Item, Input, Label,  Button , Left,Right,} from 'native-base';
 class Login extends React.Component {
  render() {
    return (
         <View style ={{flex:1,}}>
         <Form>
             <Item stackedLabel
            style={{justifyContent:'center' }}
             >
               <Label>Username</Label>
               <Input />
             </Item>
             <Item stackedLabel last>
               <Label>Password</Label>
               <Input />
             </Item>
                <Button
                 style={{
                   height: 50, width: 150,marginLeft: 110,justifyContent: 'center',
                   alignItems: 'center',marginTop: 20,
                 }}>
                  <Text style={{  color: '#fff',
                    fontSize:25,
                    fontWeight: 'bold',}}> Sign In </Text>
                </Button>
                <Left>
                  <Button transparent style={{marginLeft: -170,marginTop: 20,}}>
                  <Text>Forgot Password</Text>
                  </Button>
                </Left>
                <Right>
                  <Button transparent
                  style={{marginLeft: 250,marginTop: 20,}}
                  onPress={() => this.props.navigation.navigate('Register')}>
                  <Text>Create Account</Text>
                  </Button>
                </Right>
            </Form>
          </View>
    )
  }
}
 class Register extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Writehere</Text>
      </View>
    );
  }
}
const MainStack = StackNavigator(
  {
    Login: {
      screen: Login,
    },
    Register: {
      screen: Register,
    },
  },
    {
      initialRouteName: 'Login',
    }

);
  export default class Loginu extends React.Component {
    render() {
      return <MainStack />;
    }
  }

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
