### ISSUE TITLE
Top TabBar on iPhone X shadow?

### ISSUE THREAD

**Issue by DLevai94** [react-navigation/react-navigation#3811]
Hey! 

I am using SafeAreaView from React Native, and I've created a top positioned TabBar in a TabNavigator nested inside a StackNavigator but it has a shadow. I think by default it doesn't need it. I've attached screenshot and code.

![simulator screen shot - iphone x - 2018-03-22 at 01 53 21](https://user-images.githubusercontent.com/15244882/37745199-d67dee6e-2d73-11e8-8658-e33d3f7ae58c.png)

Code:

StackNav:
```
{
    Main: { screen: TabNavigator },
  },
  {
    navigationOptions: {
      header: null,
      cardStyle: {
        elevation: 0,
        shadowOpacity: 0,
      },
    },
  }
```

TabNav:
```
{
    navigationOptions: {
      header: null,
    },
    tabBarPosition: 'top',
    initialRouteName: 'Home',
    animationEnabled: true,
    swipeEnabled: true,
    tabBarOptions: {
      style: {
        height: 40,
        backgroundColor: '#fff',
      },
    },
  }
```

| software         | version
| ---------------- | -------
| react-navigation | 1.5.6
| react-native     | 0.52.0

**Comment by brentvatne** [comment]
hi there. you need to provide a full runnable example, the code you provided would still require us to create a project and attempt to repro it. my usual thing below:

<hr />

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by SeongmanMannKim** [comment]
Hey, I had same issue with you on my iphone X.
I wasn't able to resolve this without changing the original source.

Since you do not have header (header:null), the shadow is on the card.
What I did was,
first expore to 

(your project root)/node_modules/react-navigation/src/views/StackView/StackViewCard.js
And search for 'shadow', and comment out all of shadow component.

this helped me on my project.

const styles = StyleSheet.create({
  main: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#E9E9EF',
    // shadowColor: 'black',
    // shadowOffset: { width: 0, height: 0 },
    // shadowOpacity: 0.2,
    // shadowRadius: 5,
  },
});

The code above is the solution.

Hope this helps you and others who have same issue.

(Well,  I know this would be a hassle if you do 'npm install'.

**Comment by ali-sao** [comment]
@SeongmanMannKim I agree , is there any other way to disable this styling ? since it is receiving styles via props  : const { children, pointerEvents, style } = this.props;

**Comment by ali-sao** [comment]
Use the `cardStyle` visual option , this code will solve your problem :

```
createStackNavigator(
  {
    Landing: { screen: Landing },
    SignIn: { screen: SignIn },
    }
  },
  {
    cardStyle: { shadowColor: 'transparent' }
  },
)
```
