### ISSUE TITLE
cannot go back in the header by default 

### ISSUE THREAD

**Issue by jadelmir** [react-navigation/react-navigation#3815]
## The issue tracker is reserved for bug reports only.

I cannot go back in stack navigation while I press the default back button I am using stack navigator 
wi   "react-navigation": "^1.5.7", 

the button doesn't do anything 

I am using redux too 

this is my navigation 

export const Auth = StackNavigator(
	{
		Login: { screen: Login },
		SignUpScene: { screen: SignUp }
	},
	{
		headerMode: 'none',
		initialRouteName: 'Login'
	}
);

export const MainStack = StackNavigator({
	Home: {
		screen: MainScreen,
		navigationOptions: { header: null }
	},
	CalendarScreen: { screen: Calendar, navigationOptions }
});
export const mainNavigator = StackNavigator(
	{
		MainTab: { screen: MainStack }
	},
	{
		headerMode: 'none'
	}
);
export const AppNavigator = StackNavigator(
	{
		Auth: { screen: Auth },
		Main: { screen: mainNavigator }
	},
	{
		headerMode: 'none'
	}
);

I am using the header on the calendar screen 
and need to move back to the main page 
it is in the same stack 

| software         | version
| ---------------- | -------
| react-navigation | 1.5.7
| react-native     | 0 .54.2
| node             | 8.9.3
| npm or yarn      |5.5.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
