### ISSUE TITLE
StatusBar not showing on android

### ISSUE THREAD

**Issue by huiming1313** [react-navigation/react-navigation#3816]
Anyone else experiencing this ? I can't see android StatusBar and if i set marginTop: Expo.Constants.statusBarHeight, i can see the header but the color is a bit weird.

This is the result
![screenshot_2018-03-23-01-35-31-108_host exp exponent](https://user-images.githubusercontent.com/15344977/37788816-66518298-2e3d-11e8-8019-e62741110d59.png)

This is the result with marginTop: Expo.Constants.statusBarHeight in navigationOptions
![screenshot_2018-03-23-01-38-01-245_host exp exponent](https://user-images.githubusercontent.com/15344977/37788833-6f27078a-2e3d-11e8-8087-d8e9147a1a8b.png)

This is the result in IOS
![img_7852](https://user-images.githubusercontent.com/15344977/37788838-72901b96-2e3d-11e8-8e8f-21365d8f724e.PNG)

The status bar should be like this
![screenshot_2018-03-23-01-38-24-129_com ddctimes](https://user-images.githubusercontent.com/15344977/37788843-750b06e2-2e3d-11e8-861a-3ccd23241e3b.png)

software | version
-- | --
react-navigation | ^1.5.1
react-native | 0 .52
expo | ^25.0.0

**Comment by brentvatne** [comment]
hi -- you didn't post any code or a link to an example project, but i do appreciate the effort with screenshots!

as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
