### ISSUE TITLE
navigationOption not working as expected.

### ISSUE THREAD

**Issue by Yria** [react-navigation/react-navigation#3838]
I would like to change the navigation option in the router. 

I’ve tried changing the statis navigationOptions, but it did not work. 

How can I change the navigation option in the router?

| software         | version
| ---------------- | -------
| react-navigation | v1.5.8
| react-native     | v0.54.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
