### ISSUE TITLE
Solution prevent duplicate 'navigate' calls by pressing button too quickly

### ISSUE THREAD

**Issue by navata** [react-navigation/react-navigation#3839]
Hi all,

I have issue about navigate, which open multi screens when user press quickly. I find solution for this issue but not question better.

Beside, I try to set key in function navigate:
`this.props.navigation.navigate({routeName, params, action, key}) `
But it not working.
Note: My version react-navigation: 1.0.0-beta.22

Thanks for your support!

**Comment by aknad** [comment]
key was added in 1.0.0-beta.28 so I think you should update to use it
https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.28

**Comment by gre** [comment]
I'm facing the same problem, what would be neat to me is if `navigate()` could return a Promise. this is how I solve this in all my button: button hangs (render a pending state) & prevent touchability until the promise in done.

this way, you can just connect it like this `<Touchable onPress={()=>navigation.navigate("foo")}>..` , (Touchable is my custom component, it understand onPress that returns promises)

**Comment by rbadr** [comment]
This is a really a big issue for a lot of users, however no proper solution have been decided or implemented in the core. There is an open rfc [here ](https://github.com/react-navigation/rfcs/issues/16).

There are a few workarounds I have found : 

- Idempotent pushes by using a unique key when navigating : 
`this.props.navigation.navigate({routeName: 'myRouteName', key: 'myUniqueKey'})`
However this doesn't solve the issue when using NavigationActions.NAVIGATE.

- Overriding the navigator's router, by checking the route name and params before pushing a new route : 

```
const defaultGetStateForAction = MainNavigator.router.getStateForAction;
MainNavigator.router.getStateForAction = (action, state) => {
  if (action.type === NavigationActions.NAVIGATE) {
    const { routeName, params } = action;
    const lastRoute = state.routes[state.routes.length - 1];

    if (routeName === lastRoute.routeName && params === lastRoute.params) {
      return { ...state };
    }
  }
  return defaultGetStateForAction(action, state);
};
```

- Using debouncing in your touchable onPress handler to avoid pushing the route quickly.


It would be great if a proper solution is implemented in react-navigation, because for me there is no use case where you want to push the same route twice and with the same params.

**Note:** Native navigation (android and ios) handles it for the user.

**Comment by brentvatne** [comment]
closing this issue because it's well known and we can discuss further in RFCs
