### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Component.router.getStateForAction') when trying to run the CustomTabs example

### ISSUE THREAD

**Issue by dylancompanjen** [react-navigation/react-navigation#3844]
I am getting the error: TypeError: undefined is not an object (evaluating 'Component.router.getStateForAction'), when I try to replicate the 'Custom Tabs' example.
Is it still up-to-date?

https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by idgafl7** [comment]
still an issue..

**Comment by SurpassRabbit** [comment]
me too

```
[error][tid:com.facebook.react.JavaScript] TypeError: undefined is not an object (evaluating 'Component.router.getStateForAction')
```

**Comment by Manoj002** [comment]
im having same issue seems like the issue is with createAppContainer...

**Comment by halfbeep** [comment]
Getting exactly the same error. Is it not possible to address this purely in RN?  I am seeing the error on iOS too. Many thanks

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
