### ISSUE TITLE
Force React Navigation go back without re-rendering

### ISSUE THREAD

**Issue by pexea12** [react-navigation/react-navigation#3847]
I am using `DrawerNavigator` from [react-navigation](https://github.com/react-navigation/react-navigation) with Redux for my React Native app (using [Expo](https://expo.io)). My Home screen contains a map (using [react-native-maps](https://github.com/react-community/react-native-maps)). From Home screen, I navigate to a new screen. 

Whenever I click the Back button in this new screen to go back to Home screen: `dispatch(NavigationActions.back()`, the Home screen always re-render. Is there any way to go back without re-rendering my Home screen and keep all the states and props unchanged?

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
