### ISSUE TITLE
Navigate from StackNavigator to DrawerNavigator

### ISSUE THREAD

**Issue by danieloprado** [react-navigation/react-navigation#3866]
### Current Behavior
When navigate to a specific screen inside a DrawerNavigator from a StackNavigator open the initialRoute of Drawer instead of the specific screen.

### Expected Behavior
Open the specific screen when navigate to DrawerNavigator from a StackNavigator

#### Current Behavior
https://github.com/danieloprado/react-navigation-error-sample/tree/current-behaviour

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8 (since 1.3)
| react-native     | 0.54.3
| node             | 8
| npm or yarn      | yarn

**Comment by jsouza181** [comment]
I may be misunderstanding your issue, but I believe that your problem is that you have multiple routes defined as 'Drawer1' and 'Drawer2'. So when you navigate to the 'Drawer2' route from the Home screen, you are taken to the Drawer2 defined in the stack navigator instead of the one defined in the drawer navigator. You can fix this by removing the naming conflict and simplify it further by defining just two routes in the stack navigator - Home and Drawer. 

```
const Navigator = StackNavigator({
  Home: { screen: Home },
  Drawer: { screen: appDrawer },
}, { initialRouteName: 'Home' });
```
