### ISSUE TITLE
Not release the view immediately when Back action

### ISSUE THREAD

**Issue by leogeng** [react-navigation/react-navigation#3872]
I implement a list view using FlatView and go to play an audio when tapping an item.

1. Play an audio in the list. 

2. Quit the playing within 3 seconds at the beginning of the playing.

3. Quickly open another audio to play.

The previous audio is still playing at the same time with the second audio playing.

I find the audio player view is constructed twice when opening another audio to play **quickly**(**step 3**),
and the first construction is same as in **step 1**, but the navigation is only one time in **step 3**

I do not know why construct the audio player view twice in step3.
Everything is ok when quit the first playing and wait for several seconds then play the second audio.
I guess something wrong when executing back action with react-navigation.

### Your Environment

| software         | version
| ---------------- | -------
    "react-navigation": "^1.5.4",
  "react": "^16.3.0-alpha.1",
    "react-native": "0.53.0",
| node             |
| npm or yarn      |

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
