### ISSUE TITLE
Issue with Android hardware back button in Nested navigators (with screenProps) 

### ISSUE THREAD

**Issue by mc-lean** [react-navigation/react-navigation#3905]
### Current Behavior

If you launch a Modal from any tab that isn't the first tab of a Tab Navigator and press the Hardware Back button the Tab Navigator goes back and the Modal is not dismissed.

Note: _This behavior only happens if you are using `screenProps` to pass navigators around_ 

### Expected Behavior

The Hardware back button should dismiss the Modal on the first press

### How to reproduce

[Snack Reproduction](https://snack.expo.io/@mcl3an/nested-navigator-bug)

Path to reproduce:
1. Select _Tab Two_
2. Select _Go To Modal_
3. Press _Android Hardware Back_
4. Press _Android Hardware Back Again_

Note: _Tab One is now focused_

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.9
| react-native     | Expos current version

**Comment by ericvicenti** [comment]
> Note: This behavior only happens if you are using screenProps to pass navigators around

Please do not pass references to navigators in through screenProps. This is not a recommended or documented practice. In most applications, screenProps should be avoided entirely, because each change to a screenProp will result in each screen being re-rendered

This is not a good approach to nest navigators. Instead, please use the technique documented here:

https://next.reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator

https://next.reactnavigation.org/docs/en/custom-navigators.html#extending-navigators

**Comment by mc-lean** [comment]
Gahhh,

I must have missed that in the updated docs.  Thank you for the quick reply!
