### ISSUE TITLE
iOS StatusBar abnormal when tab switched

### ISSUE THREAD

**Issue by FaiChou** [react-navigation/react-navigation#3928]
It is normal when first time I switched to the last tab with StatusBar `dark-content`.

![normal situation](https://user-images.githubusercontent.com/18500846/38453070-4198d36a-3a82-11e8-8551-9e53f680b3f2.jpeg)

But when I switched to another tab then switched back, The StatusBar is abnormal `light-content`.

![abnormal](https://user-images.githubusercontent.com/18500846/38453074-53c68316-3a82-11e8-96c5-e738a2dee0ec.jpeg)

Another four tabs are all `light-content`, and only the last tab `dark-content`.

last tab:

```
<View>
  <StatusBar barStyle="dark-content" />
</View>
```

I am not sure it is react-navigation or react-native's bug or feature or something I do it wrong.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.5.0
  Yarn: 1.5.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1
  react-navigation:  "^1.0.0-beta.21"

**Comment by FaiChou** [comment]
In Xcode debug mode

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by peteychuk** [comment]
@FaiChou here is the doc:
https://reactnavigation.org/docs/en/status-bar.html
I believe that it explains your case.
