### ISSUE TITLE
app crashed when switch screen in release.apk,everything is ok in debug mode

### ISSUE THREAD

**Issue by jinxin479** [react-navigation/react-navigation#3942]
I used SwitchNavigator to control auth flow.
```
export const RootNavigator = SwitchNavigator({
    Main: {
        screen: HomeStack,
    },
    Login: {
        screen: LoginStack,
    },
    Loading:{
        screen:LoadingScreen
    }
},{
    initialRouteName: 'Loading',
  });
```
now ,when app launched ,can not switch to "Main" after I logined, and sometimes the app can route to "Main",however,when I click the Button to route to another Screen,the app stop running. 
I don not know why

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
