### ISSUE TITLE
Issue when trying to override headerStyle inside TabNavigator Screen

### ISSUE THREAD

**Issue by Rzygan** [react-navigation/react-navigation#3947]
Hello everyone,

I'm trying to override a StackNavigator header style.
My structure is:  a root StackNavigator with a TabNavigator (with some screens inside), and another screen, here i define the global navigationOption like this: 

```
const AppStack = StackNavigator(
  {
    Tabs: AppTabNavigator, 
    Messages: MessagesScreen 
  },
  {
    navigationOptions: ({ navigation }) =>({
      headerStyle: {
        backgroundColor: PRIMARY_COLOR
      },
      headerRight: (
        <TouchableOpacity onPress={() => navigation.navigate('Messages')}>
          <Image source={require('./assets/icons/message.png')} style={{width: 40, height: 40, margin: 10}} />
        </TouchableOpacity>
      ),
      
    })
  }
);
```

In one of the Tab screen's, the ProfileScreen i need to override some headerStyle properties like height and color, so i do this:

```
export default class MyProfileScreen extends React.Component {
    static navigationOptions = () => {
      return {
        headerStyle: {
          backgroundColor: 'blue',
          height: 100
        }
      };
    };
  
    render() {
      return (
        <View style={styles.container}>
          <Text>Profile</Text>
        </View>
      );
    }
  } 
```

but the header dont change... but if i add to my headerStyle something like title, it changes.

Using the snack by expo.io i'm able to override this when playing with 2 simple screen within a Stacknavigator. How can i implement the override? It's a TabNavigator Problem??

Best Regards

UPDATE: i confirm that it's caused by having a TabNavigator, because i can override the messagesScreen

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by giacomocerquone** [comment]
@brentvatne sorry but I believe this is not a bug and so no snack should be required.
In fact it is exactly the way you structured the new navigationoptions override. You have this rule printed in your doc:

`You can only modify navigation options for a navigator from one of its screen components. This applies equally to navigators that are nested as screens`

But since tab hasn't a header, the only way to let it have a header is to wrap the tab navigator in a stack navigator.
Then what do you do to try to override the header? You put a navigationoptions inside one screen of a tab but this doesn't work for the previous rule... kaboom.


I'm about to put up an example anyway... 3 thumbs up and the guy that wrote the issues couldn't do it... life is funny sometimes 😄 

I'll recreate a new issue obv.
