### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by tonyhb** [react-navigation/react-navigation#3948]
Can we https://keepachangelog.com/en/1.0.0/?  It's hard to see what's coming in each release.

I get that we can do a compare and look at the commits.  That doesn't really help explain a prioritized list of new features, fixes, and changes - especially with the upcoming 2.

Hopefully if we did this it'd be much easier to keep up to date with all of the hard work here :)

**Comment by brentvatne** [comment]
any significant release includes release notes: https://github.com/react-navigation/react-navigation/releases

we haven't written those yet for 2.0 because it's still in progress. the high level release notes are here https://reactnavigation.org/blog/2018/04/06/react-navigation-2.0-rc.html

we should probably follow a changelog in this format. can you champion this and get it started?

**Comment by brentvatne** [comment]
no response for 2 weeks, closing
