### ISSUE TITLE
when i killed app and open in IOS "previousScreen rendering everytime rather than splashScreen"

### ISSUE THREAD

**Issue by MaheshNandam** [react-navigation/react-navigation#3965]
react - 16.0.0
react-native - 0.50.4
react-navigation - 1.5.11

This is happening on every screen, 
Screen flow:
- I have opened the app 
- I have closed the app
- When I'm opening the app again then the last screen is rendering rather than the splash screen,

@brentvatne @skevy @ericvicenti Can anyone help me to solve this issue?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by MaheshNandam** [comment]
Hey @brentvatne,

Okay, nonetheless
I have implemented the 'react-native-ux-cam', which causes this problem.

**Comment by brentvatne** [comment]
hi @MaheshNandam. sorry we don't have bandwidth to help without a reproducible example. please create a new issue with it
