### ISSUE TITLE
There is no route defined for key "Component Name or Screen Name"

### ISSUE THREAD

**Issue by Aashir1** [react-navigation/react-navigation#3976]
There are two nested routes one is Auth and another one is Tabes. Maybe code make better sense.
Code
`
const AuthStack = StackNavigator(
{
SignUp: {
screen: SignupDemo,
},
LogIn: {
screen: LoginDemo,
},
},
{
initialRouteName: 'LogIn',
}
);

const Routes = StackNavigator({
Auth: {
screen: AuthStack
},
Tabes: {
screen: TabNavigator({
Camera: {
screen: Camera
},
Home: {
screen: Home
},
})
},
})

**Error Image**

![screenshot_2018-04-13-18-46-44-93](https://user-images.githubusercontent.com/25276195/38739644-ee1b0934-3f4e-11e8-82fe-eaf607d891c8.png)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
