### ISSUE TITLE
Screen's navigationOptions in StackNavigator in DrawerNavigator cannot be updated by this.props.navigation.setParams

### ISSUE THREAD

**Issue by mannok** [react-navigation/react-navigation#3982]
### Current Behavior

[DrawerNav](https://imgur.com/3kaRztv)
[StackNav](https://imgur.com/6a2iMVr)
[Screen](https://imgur.com/uwFowaN)

### Expected Behavior

When I click on the icon, the screen title should be change from "Volunteer Schedule" to "aaa"

### How to reproduce

Just replace the codes then you can reproduce.

### Your Environment

| software         | version
| ---------------- | -------
react-native-cli: 2.0.1
react-native: 0.54.2
node: v9.11.1
npm: 5.6.0

**Comment by puneet94** [comment]
Can you provide expo snack?

**Comment by Ashwin-Mothilal** [comment]
I think so, you have to set the params title to the title object to use it - navigation.state.params.title

`title:navigation.state.params ? navigation.state.params.title:Volunteer Schedule`
 
I haven't used your way yet.

**Comment by cyphire** [comment]
Isn't this the issue that a lot of people are having?  Lots of comments on setParams not working with Redux and in drawerNavigation... I'm having the same problem right now and looking for the answer.  By the way upgrading to 55.3 does not solve anything...

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
