### ISSUE TITLE
Warning: Can't call setState (or forceUpdate) on an unmounted component..

### ISSUE THREAD

**Issue by Ananlabs** [react-navigation/react-navigation#3992]
Environment:
OS: Windows 10
Node: 8.9.4
Yarn: 1.3.2
npm: 5.6.0
Watchman: Not Found
Xcode: N/A
Android Studio: Version 3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.2 => 0.55.2

"dependencies": {
"axios": "^0.18.0",
"native-base": "^2.4.2",
"react": "16.3.1",
"react-native": "0.55.2",
"react-navigation": "^1.5.11",
"react-redux": "^5.0.7",
"redux": "^3.7.2",
"redux-thunk": "^2.2.0"
}
![untitl445ed](https://user-images.githubusercontent.com/497913/38785127-31c32602-411c-11e8-83fa-57d77f54d55d.jpg)

**Comment by jkoskela** [comment]
I am encountering this too. What tool do you use to print your environment?

**Comment by bang88** [comment]
Same here 😢

**Comment by ericvicenti** [comment]
Can somebody post an example code snippet that causes this warning?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by LeviWilliams** [comment]
I'm getting this error as well even though I am using react-native-router-flux (because it is now based on react-navigation). Not quite sure what this means but its screwing up my navigation flows

**Comment by brentvatne** [comment]
@LeviWilliams - if you can reproduce it in a new issue that would be great. otherwise we can't do much with this issue so i am going to lock it

**Comment by Ashoat** [comment]
This is an issue with `react-native-safe-area-view`. [This PR](https://github.com/react-community/react-native-safe-area-view/pull/32) should fix it.
