### ISSUE TITLE
StackNavigator over MapView

### ISSUE THREAD

**Issue by KchTT** [react-navigation/react-navigation#4010]
Hi, im trying to add a stacknavigator into a component over a MapView. When a do that i cant drag the map....can anybody help me?

`<View>
  <MapView 
  provider={PROVIDER_GOOGLE}
  style={styles.map}
    initialRegion={{ latitude: 37.78825,  longitude: -122.4324, latitudeDelta: 0.0922, longitudeDelta: 0.0421,  }} /> 
  <View style={styles.container} pointerEvents="box-none" >
    <DrawerNavigation style={styles.busquedaStackContainer}  pointerEvents="none" />
  </View>
</View>`

**Comment by ericvicenti** [comment]
It looks like your drawer navigator is not rendered correctly as a sub-navigator:

https://v2.reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator

But I'm not sure that has to do with your map-in-stack issue. Can you possibly post an example of this issue on expo snack? That will help us verify the problem.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Victorien-Tardif** [comment]
Hi @KchTT , I'm having the same problem, If you managed to handle it I'd like to know how!
Thanks
