### ISSUE TITLE
Card is cut off on iPhone X (v2)

### ISSUE THREAD

**Issue by franckmaurin** [react-navigation/react-navigation#4012]
Hello here,

I've updated react-navigation from 1.0 to 2.0. Thanks for your great work, I can see a lot of optims and improvements. I've just a last bug on Iphone X. The card mode screens are cut to the top. As you can see, it's 24px. I don't use SafeAreaView component in my code (because I use custom headers).

![Image](https://i.imgur.com/X6LktQz.png)

But If I set mode: "modal", the screen of the StackNagivator will not cut.

My configs
"react": "16.3.1"
"react-native": "0.55.2"
"react-navigation": "2.0.0-rc.2"

Thanks

**Comment by franckmaurin** [comment]
I fixed it by

```
import ReactNavigation from 'react-navigation'
ReactNavigation.SafeAreaView.setStatusBarHeight(20)
```

But I have no idea what I am doing... 😂

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
