### ISSUE TITLE
navigation.setParams doesn't work property when navigate.navigate('DrawOpen') at the same time

### ISSUE THREAD

**Issue by DrakeXiang** [react-navigation/react-navigation#4025]
I tried to simulate a side menu using DrawerNavigator in a TabNavigator screen, I managed to show/hide the tab bar using `navigation.setParams` and `tabBarVisible`. I'd like to open the drawer menu, and hide the tab bar at the same time, but got stuck with code below:

```typescript
    // GrowthHomeScreen.ts
    this.props.navigation.setParams({ showTabBar: !wasShow });
    this.props.navigation.navigate('DrawerOpen');
```

```typescript
   // router.ts
const GrowthHomeStack = DrawerNavigator({
    Home: {
        screen: GrowthHomeScreen
    }
});

// app
const AppStack = TabNavigator(
  {
    Growth: {
      screen: GrowthHomeStack,
      navigationOptions: {
        tabBarLabel: 'Growth',
        tabBarIcon: function(status: { focused: boolean; tintColor: string }) {
          const imgURL = iconSrc[0][status.focused ? 'active' : 'inactive'];
          return <Image style={{ width: 24, height: 24 }} source={imgURL} />;
        },
      },
    },
    ...
}
```

The drawer open/close without problem, but the tab bar can't hide/show properly, is it a bug? Or I shouldn't do it at the first..

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
