### ISSUE TITLE
StackNavigator with transparent header - first FlatList item not clickable

### ISSUE THREAD

**Issue by kosmicbird** [react-navigation/react-navigation#4027]
This seems like a noob question but I couldn't find any documentation on this and setting zIndex doesn't seem to help. 

My FlatList is working fine except the very first item is not clickable since it is being "covered" by the StackNavigator header. Covered is actually not a good word to use here since the list item is actually visible (headerTransparent: true) but the FlatList is not "on top" of the StackNavigator so the transparent header interferes with touch. If I set marginTop to bring the FlatList down the screen I'm able to tap the item. I changed zIndexes on headerStyle, cardStyle, and my FlatList component with no success. 

How do I make the transparent StackNavigator render underneath my screen elements so it doesn't interfere with the first FlatList item at the top of the screen?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by kosmicbird** [comment]
-___- lol I didn't think this issue was deep enough to require a snack, but ok. I will do that. Thanks and looking forward to the help.

**Comment by brentvatne** [comment]
honestly I just close any issue that doesn't follow the template because it's an easy heuristic to ensure quality of issues. sorry if that's annoying, it's the only way we can handle issues with the quantity that we receive and the number of people who work on this project!

**Comment by kosmicbird** [comment]
I understand :) More than happy to follow the rules to make your life easier, so that someone can hopefully make mine easier in return haha. Will be reposting momentarily.
