### ISSUE TITLE
Orientation.lockToPortrait does not work with 'did/willBlur' event of react-navigation

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#4042]
I am trying to lock orientation in portrait when switching tabs when using react-navigation while listening to didBlur / willBlur events.

my code is as follows:

    componentDidMount() {
        Orientation.addOrientationListener(this.onRotated);
        BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
        if (this.props.navigation) {
            this.blurEvent = this.props.navigation.addListener('didBlur', this.handleVideoBlur);
        }
    }

    componentWillUnmount() {
        Orientation.removeOrientationListener(this.onRotated);
        BackHandler.removeEventListener('hardwareBackPress');
        if (this.blurEvent) {
            this.blurEvent.remove();
        }
        Orientation.lockToPortrait();
    }
    ... [other component methods]...
    handleVideoBlur = () => {
        Orientation.lockToPortrait();        
    }

    render() {...}

| software         | version
| ---------------- | -------
| react-navigation |1.5.11
| react-native-orientation|3.1.0
| react-native     |0.52
| node             |8.9.3
| yarn      |1.3.2

**Comment by vonovak** [comment]
hi there! This does not seem to be an issue with react-navigation but with `Orientation.lockToPortrait`. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
