### ISSUE TITLE
TabNavigator scrollEnabled is not working in iOS

### ISSUE THREAD

**Issue by MrPeproni** [react-navigation/react-navigation#4043]
![screen shot 2018-04-23 at 1 41 34 pm](https://user-images.githubusercontent.com/25629063/39115250-cae24614-46fe-11e8-9d02-1efeea368ae5.png)
These tabs are not scrollable and getting this extra space in green also...
I want to make these tabs scrollable

```
{
    tabBarPosition: 'top',
    swipeEnabled: false,
    tabBarOptions: {
      scrollEnabled: true,
      showIcon: false,
      upperCaseLabel: false,
      activeTintColor: '#fff',
      inactiveTintColor: '#fff',
      tabStyle: {
        backgroundColor: '#3e4f6e',
        paddingBottom: 0,
        paddingTop: 0,
        height: 50,
        justifyContent: 'center',
        width: '100%'
      },
      labelStyle: {
        fontSize: 16,
      },
      indicatorStyle: {
        height: 0
      },
      style: {
        backgroundColor: 'green'
      }
    }
  }
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by MSSPL-PiyaleeMaiti** [comment]
@brentvatne The property `scrollEnabled: true,` is not working for ios its working fine in android. 
Can you suggest any solution so that I can use scrollable tab in ios also? I need that functionality in my project urgently.

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
