### ISSUE TITLE
In v2.0.0-rc.x, drawerNavigator error occured.

### ISSUE THREAD

**Issue by SehyukNoh** [react-navigation/react-navigation#4046]
### Current Behavior

In react-navigation v1.5.x, it is not problem.
it only occurs in v2.0.0-rc.x.

I made DrawerNavigator using the 'createDrawerNavigator'.
please refer to below code.

```javascript

const WelcomeScreen = ({ navigation }) => (
    <Welcome navigation={navigation} />
)

WelcomeScreen.navigationOptions = {
    drawerLabel: 'Welcome',
    drawerIcon: ({ tintColor }) => (
        <Image
            source={require('./asset/settings.png')}
            style={[naviStyles.icon, { tintColor: tintColor }]}
        />
    ),
}

const WelcomeStack = createStackNavigator({
    Welcome: { screen: WelcomeScreen },
});

const BlankScreen = ({ navigation }) => (
    <BlankScreen navigation={navigation} />
)

BlankScreen.navigationOptions = {
    drawerLabel: 'BlankScreen',
    drawerIcon: ({ tintColor }) => (
        <Image
            source={require('./asset/settings.png')}
            style={[naviStyles.icon, { tintColor: tintColor }]}
        />
    ),
}

const BlankStack = createStackNavigator({
    Blank: { screen: BlankScreen },
});



const DrawerNavi = createDrawerNavigator({


    Welcome: {
        screen: WelcomeStack,

        path: 'drawer/:welcome',
    },

    Settings: {
        screen: BlankStack,

        navigationOptions: {
            drawerLabel: 'Settings',
            drawerIcon: ({ tintColor }) => (
                <Image
                    source={require('./asset/settings.png')}
                    style={[naviStyles.icon, { tintColor: tintColor }]}
                />
            ),
        },
    }
})
```
### Expected Behavior

If i touch 'Settings' on drawer menu, i can navigate 'BlankStack'.
But, the error occured.

The error is as follows.

![screenshot_2018-04-24-15-18-52](https://user-images.githubusercontent.com/38681804/39169496-fe239ecc-47d2-11e8-9770-49512e698c05.png)

### How to reproduce

Please refer to my code.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.0-rc.3
| react-native     | 0.55.3
| node             | 9.8.0
| npm or yarn      | 4.6.1

**Comment by brentvatne** [comment]
please post your example to snack so we can run it

**Comment by brentvatne** [comment]
posting my usual reply to similarly formulated issues for convenience:

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
