### ISSUE TITLE
TabNavigator reset bug.

### ISSUE THREAD

**Issue by wuyunqiang** [react-navigation/react-navigation#4060]
### Current Behavior
I use reset and show me.
no route defined for key.
if I navigate and will be ok.

<img width="294" alt="1bf6d663-e830-465f-ab41-0707146c5133" src="https://user-images.githubusercontent.com/13480948/39236628-d989439e-48ab-11e8-8f6b-e232e9c48da9.png">

### Expected Behavior
I hope I use reset and to MinePage

### How to reproduce
```
const TabContainer = TabNavigator(
    {
        Home: {
            screen: HomePage
        },
        BidPage: {screen: BidPage,},
        MinePage: {screen: MinePage,},
    },
    {
        lazy: true,
        swipeEnabled: false,
        tabBarPosition: 'bottom',
        animationEnabled: false,
        backBehavior: 'none', // 按 back 键是否跳转到第一个Tab(首页)， none 为不跳转
        // tabBarOptions: tabbaroption,
        configureTransition:()=>_configureTransition(),
        tabBarComponent:props => <Tab {...props}/>,
    });
const Routes = {
    TabContainer:{screen: TabContainer,},
    Login:{screen:Login},
    SomePage:{screen: SomePage},
};
const AppNavigator = StackNavigator(
    {
        ...Routes,
        Index: {
            screen: TabContainer,
        },
    },
    {
        initialRouteName: 'Index',
        headerMode: 'screen',
        gesturesEnabled: false,
        mode: 'card',
        transitionConfig: TransitionConfiguration,
       // navigationOptions: ({navigation}) => StackOptions({navigation}),
    }
);
```

MinePage->Login->SomePage 
and in SomePage reset to MinePage
```
  let resetAction = NavigationActions.reset({
            index: 0,
            actions: [
                NavigationActions.navigate({routeName: MinePage})
            ]
        });
        this.props.navigation.dispatch(resetAction)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.5.11
| react-native     | 0.54.2
| node             | v9.11.1
|  yarn      | 1.5.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
