### ISSUE TITLE
Using TabBarTop as a tabBarComponent crashes the application

### ISSUE THREAD

**Issue by ozercevikaslan** [react-navigation/react-navigation#4088]
### Current Behavior

TabNavigator configured with the property tabBarComponent as a TabBarTop used to working like a month ago but recently, I figured it out that it culminates with crashing of the application. The error :

![simulator screen shot - iphone 7 - 2018-04-28 at 16 46 51](https://user-images.githubusercontent.com/19668362/39397245-bba84234-4b04-11e8-93bf-e46decf49c69.png)

If I use my own custom tab menu component as a tab bar component it runs perfectly but then, I had some design issues which will cost me a lot of time.

```
const ShopCatTabNav = TabNavigator(routes, {
    tabBarPosition: 'top',
    swipeEnabled: true,
    lazy: true,
    tabBarOptions: {
      scrollEnabled: true,
      showLabel: true,
      showIcon: true,
      activeTintColor: 'yellow',
      inactiveTintColor: 'purple',
      style: {
        backgroundColor: 'white',
      },
      tabStyle: {
        backgroundColor: 'gray',
        width: Object.keys(routes).length > 4 ? width / 4 : width / Object.keys(routes).length,
        height: height / 12,
        alignContent: 'center',
        justifyContent: 'center',
        alignItems: 'center',
      },
      labelStyle: {
        textAlign: 'center',
        fontSize: 12,
        fontWeight: 'bold',
      },
      indicatorStyle: {
        backgroundColor: 'teal',
      },
      allowFontScaling: true,
      upperCaseLabel: true,
    },
    tabBarComponent: TabBarTop,
  });
```

### Expected Behavior

-The expected behavior is a fully working tab navigator which has several stack navigators inside of it as described in the docs.

### How to reproduce

-Using TabBarTop or TopBarBottom as a tabBarComponent property inside of your configuration code in TabNavigator. You can use the above code for reproduction the bug.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^ 1.5.11
| react-native     | 0.55.3
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
