### ISSUE TITLE
Open two tabs after double click

### ISSUE THREAD

**Issue by marquinmpfs** [react-navigation/react-navigation#4107]
I have a problem, when I click twice times or more in button, open several tabs in my app.
Why resolved this problem?

My routes:

`import { createTabNavigator } from 'gam-components';

import Routes from './Routes';

const routeMaps = [
  {
    id: 'aba_1',
    routes: Routes,
    config: {
      initialRouteName: 'Consulta',
    },
  }
];

const fullscreenMap = {
  routes: Routes
};

export default createTabNavigator({ routeMaps, fullscreenMap });`

`import Consulta from '../pages/Consulta.page';
import Objetos from '../pages/Objetos.page';

export default Routes = { 
  Consulta: {
    id: 'consulta',
    name: 'Consulta',
    description: 'Consulta de Dossie',
    screen: Consulta
  },
  Objetos: {
    id: 'objetos',
    name: 'Objetos',
    description: 'Objeto de Negócio',
    screen: Objetos
  },`

My component:

`<TouchableOpacity
               onPress={() => {
              const params = {
                codigo: xxxx,
                item: xxxx,
                grupo: xxxxx
              };           
              this.props.navigation.navigate('Objetos', params);
            }}`

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
