### ISSUE TITLE
Using navigation outside the Sidebar

### ISSUE THREAD

**Issue by Gshock1** [react-navigation/react-navigation#4113]
Hi all,

I would like to resolve the following issue:

I have a DrawerNavigator that contains custom Drawer content component.
The last is containing all the screens and also another component which doesn't have any screen reference [UserInfo].

What I'm trying to do is to connect the other component to the navigation competent and to use its functions.

Here is my Code:

```
 var CustomDrawerContentComponent = props => (
    <View style={{ flex: 4, backgroundColor: 'white' }}>
      <View style={{ marginTop: 20, justifyContent: 'center', alignItems: 'center' }}>
        <UserInfo/>
      </View>
      <DrawerItems {...props} />
        <View style = {styles.container}>
            <Text> Version 1.3 </Text>
        </View>
    </View>
  ); 
```

```
var DrawerExample = DrawerNavigator(
            {
                Home: {
                    path: '/',
                    screen: HomeScreen,
                    navigationOptions: {
                        drawerLabel: Strings.SideBarHomeScreenLable
                      }

             ...

            {
                initialRouteName :   this.state.isLoggedIn? 'Home': 'IntroScreen' ,
                drawerPosition: 'left',
                drawerWidth: SCREEN_WIDTH * 0.7,
                backBehavior: 'none',
                //contentComponent: SideMenu,
                contentComponent: CustomDrawerContentComponent,
                contentOptions: {
                    activeTintColor: '#00a8ff',
                    activeBackgroundColor: 'transparent',
                    //inactiveTintColor: '#ffffff',
                    inactiveBackgroundColor: 'transparent',
                    labelStyle: {
                      fontSize: 18,
                      marginLeft: 0,
                    },
                }
        
            }    
        );
        return <DrawerExample ref = {"navigation"}/>;
```

Thank you all.

React native 0.49
Android
Windows 10

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
