### ISSUE TITLE
iphoneX SafeAreaView not working in custom header when tabNavigator lazy set to false

### ISSUE THREAD

**Issue by M1chaelChen** [react-navigation/react-navigation#4142]
### Current Behavior
I have a tabNavigator with five tabs, and the lazy option is set to false since I need a screen from the second tab to render immediately. The second tab has a custom header with a searchbar and an icon. I have to wrap them in a `SafeAreaView` from `react-navigation` to avoid them overlap on the status bar. But the `SafeAreaView` does not have any effects when the lazy option is false. It works fine when lazy render is enabled.
![image](https://user-images.githubusercontent.com/19735641/39685772-a64d1a9c-5179-11e8-906d-db7d54a41d41.png)

### Expected Behavior
`SafeAreaView` will prevent header overlap the status bar.
![image](https://user-images.githubusercontent.com/19735641/39685782-b2a530f4-5179-11e8-9acb-b910ee2f04e0.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.1
| react-native     | 0.55.3
| node             | 8.10.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by M1chaelChen** [comment]
I got a demo code in [here](https://github.com/M1chaelChen/react-navigation-4142).

**Comment by brentvatne** [comment]
thanks!

**Comment by brentvatne** [comment]
I copied this example over to Snack and updated to the latest version of react-navigation, it works as expected: https://snack.expo.io/Hk4nrsZfm

**Comment by nathsimpson** [comment]
Having the same issue too, however I am on 3.11 (latest version before 4.0).
