### ISSUE TITLE
Cannot access props.navigation.navigate() in custom tabBarComponent

### ISSUE THREAD

**Issue by tobby1177** [react-navigation/react-navigation#4149]
### Current Behavior

I have a `tabNavigator` created with `createBottomTabNavigator`, and want to create a custom `tabBarComponent` which I easily passed and used `withNavigation()` on my custom `tabBarComponent` to pass the `navigation` object to my props. On my custom `tabBarComponent`, I of course have button so I could use for navigation between the tabs, but I just can access `navigation.navigate()` as it keeps returning `undefined`. Other properties are being passed but not `.navigate()`.

### Expected Behavior

I should be able to use `navigation.navigate()`.

### How to reproduce

You could reproduce it by creating by creating your navigator with `createBottomTabNavigator()` with one of the tabs nested.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.9
| react-native     | 0.55.2
| node             | 9.9.0
| npm or yarn      | yarn 1.5.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
