### ISSUE TITLE
Regression: SafeAreaView: Broken in react-navigation v2.0.0

### ISSUE THREAD

**Issue by fbartho** [react-navigation/react-navigation#4156]
### Current Behavior

Neither `react-navigation:SafeAreaView` nor `react-native:SafeAreaView` appear to be working correctly / consistently when used with `react-navigation@2.0.0` on an iPhone X device.

### Expected Behavior

Using `react-navigation@1.5.12` both above-referenced SafeAreaView implementations function as expected on an iPhone X device, presenting your content correctly inset when necessary.

### How to reproduce

Simple Example:

1. Create a hierarchy of Navigators containing a Screen (in my case StackNavigator(configured for Modals)<-TabNavigator<-StackNavigator<-ScreenA )
2. Make sure none of your StackNavigators have a visible header. `header: null`
3. Wrap the content of your ScreenA in a SafeAreaView
4. Load this app structure on an iPhone X device.
5.a Notice how the top content of your screen slides behind your device cutout.
5.b Notice how the top content is inset below the device cutout when using `react-navigation@1.5.12`

Example B.

1. Create the above hierarchy
2. Present a screen modally as a peer of the TabNavigator, but present it quickly on launch. -- Notice how it lays out as expected.
3. Present a different screen modally (ModalB) as a peer of TabNavigator, but present it after dismissing the first modal, and then tapping on content inside ScreenA.
4. Notice how the SafeAreaView protecting ModalB fails to inset ModalB's top content.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0
| react-native     | 0.55.3
| node             | 9.11.1
| npm or yarn      | 1.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
