### ISSUE TITLE
Unable to set CustomTabBarComponent Parent View Background Color styling

### ISSUE THREAD

**Issue by export-mike** [react-navigation/react-navigation#4167]
I'm using react-navigation 2.0 I'm currently configuring a tabBarComponent it appears to be inside of a view with a backgroundColor of white. I've tried changing the colors from what I think is the correct config. Please help.
```js
export default createBottomTabNavigator({
  Home: {
    screen: HomeScreen,
  },
}, {
    tabBarOptions: {
        style: {
            backgroundColor: 'red',
        },
    },
  initialRouteName: 'Home',
    tabBarComponent: () => <NavBar />
});
```
![unknown](https://user-images.githubusercontent.com/2983327/39786062-dc295752-5372-11e8-9787-3df8927e6f8d.png)
As my custom tabBarComponent uses rounded corners it reveals the parent view which has a white bg.

the style prop on tabBarOptions works as expected when I'm not rendering a custom component.

I have replicated the issue here https://snack.expo.io/ByJ7Io1Cz

**Comment by brentvatne** [comment]
hi @export-mike! the problem here is that the background behind the tab bar is actually white! and we don't currently support a translucent tab bar, so the only workaround here is to make sure that the view that is rendered behind the tab bar is the color that you want it to be. see: https://snack.expo.io/r1XdDTkAz

if you have the tab bar inside of a stack, you'll need to set the cardStyle for it in that case. I'm hoping to get to implementing translucent tab bar in the coming months but a PR would be welcome for it too

**Comment by export-mike** [comment]
@brentvatne hi just wondering if there's been any updates to how I can have a translucent tab bar?

**Comment by brentvatne** [comment]
no updates, not working on it right now but won't get around to it for a bit. if you want to give it a go you could jump over to http://github.com/react-navigation/react-navigation-tabs and open a pr!

**Comment by export-mike** [comment]
ok cool will take a look so functionality has been extracted and now an independant package?
