### ISSUE TITLE
Params not passed immediatly from view A to B

### ISSUE THREAD

**Issue by Alex94800** [react-navigation/react-navigation#4181]
## The issue tracker is reserved for bug reports only.

Hello everyone,

I'm facing the current issue. 

I want to pass an id from view A to view B. From view A, I'm calling this method : 
`onPress: () => this.props.navigation.navigate('About', {id: item.id})`

When I'm in View B, I wrote this in the hook componentDidMount : 
`this._focusListener = this.props.navigation.addListener('didFocus', this._setTodo)`

Basically, the _setTodo method is going to do `setState({id: this.props.navigation.getParam('id', null)})`

And here comes the issue I'm facing. I'm expecting to receive the item.id as this.props.navigation.getParam('id', null), but If I try to get the value, I'm getting null. I have to set a timeout of 1ms to have the id value. This is a hacky solution, but the id displayed on the view B is not displayed straight after the view is visible.

If I'm not clear enough, I'll try to explain more in detail, and have some screenshots. Thanks in advance
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.12
| react-native     | 0.55.2
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
