### ISSUE TITLE
DrawerLockMode on drawerScreen is ignored

### ISSUE THREAD

**Issue by sebastienbarbier** [react-navigation/react-navigation#4201]
### Current Behavior

Specifying `drawerLockMode` option on drawerScreen does not apply on `DrawerLayout` component.

### Expected Behavior

Should be apply.

### How to reproduce

```
const App = createDrawerNavigator(
  { Home: {
      screen: AppNavigator,
      navigationOptions: { drawerLockMode: 'locked-closed' }
    }
  }
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0
| react-native     | 0.54.2
| node             | latest
| npm or yarn      | latest

**Comment by jamsch** [comment]
Confirmed. Drawer Lock Mode doesn't work on nested StackNavigators either.

```javascript
const DashboardNavigator = createStackNavigator({
  ProfileScreen: { screen: ProfileScreen },
});

const DrawerNavigator = createDrawerNavigator({
  DashboardNavigator: { screen: DashboardNavigator },
});

class ProfileScreen extends React.PureComponent {
  static navigationOptions = {
     drawerLockMode: 'locked-closed',
  }
}
```

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-tabs/issues/20

**Comment by jamsch** [comment]
Hey @brentvatne, I went through your Expo example and the only way I could apply "drawerLockMode" was on the second parameter of createDrawerNavigator (DrawerNavigatorConfig). 

The [docs](https://reactnavigation.org/docs/en/drawer-navigator.html) imply that "drawerLockMode" is a screen navigation option and not under DrawerNavigatorConfig however placing this inside the DrawerNavigatorConfig seems to work. 

This isn't intended for me because what I'm looking for is a way disable the drawer for a specific screen in a StackNavigator and can't find a viable solution. Resorting to using another StackNavigator in the drawer will be treated like a Switch with no back button.

Here's the Expo:
https://snack.expo.io/S1iXwyY0f

Are you sure that this is the intended effect and there's no way to set screen options for a nested route?

**Comment by silenjs** [comment]
> Confirmed. Drawer Lock Mode doesn't work on nested StackNavigators either.
> 
> software	version
> react-navigation	2.0.1
> react-native	0.55.4
> node	8.5.0
> npm	5.8.0
> ```js
> const DashboardNavigator = createStackNavigator({
>   ProfileScreen: { screen: ProfileScreen },
> });
> 
> const DrawerNavigator = createDrawerNavigator({
>   DashboardNavigator: { screen: DashboardNavigator },
> });
> 
> class ProfileScreen extends React.PureComponent {
>   static navigationOptions = {
>      drawerLockMode: 'locked-closed',
>   }
> }
> ```

https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens

we need to set navigationOptions on the FeedStack

**Comment by jamonholmgren** [comment]
Just in case someone is looking to figure out why their `drawerLockMode` is being ignored and Google leads them here, this issue helped me fix the problem.

https://github.com/react-navigation/react-navigation/issues/1082#issuecomment-411080810

```js
const Drawer = createDrawerNavigator({
    Drawer: SomeScreen,
},
    {
        drawerLockMode: 'locked-closed'
    }
);
```
