### ISSUE TITLE
createBottomTabNavigator doesn't show tab icon in v2.0.1

### ISSUE THREAD

**Issue by wellyshen** [react-navigation/react-navigation#4210]
### Current Behavior

I wrap 3 routes with `createStackNavigator` inside a `createBottomTabNavigator`, the tab icons won't show in v2.0.1. If I don't wrap the routes with `createStackNavigator`, the tab icons will show.

BTW, the tab icons will show in v1.5.11.

### Expected Behavior

Tab icon will show.

### How to reproduce

Try the following structure to reproduce:

----- createBottomTabNavigator
    |--- createStackNavigator
    |--- createStackNavigator
    |--- createStackNavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v2.0.1
| react-native     | v0.55.4
| node             | v9.11.1
| yarn      | v1.3.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
