### ISSUE TITLE
Opened drawer behaves different when 'BACK' button is pressed

### ISSUE THREAD

**Issue by adyanced** [react-navigation/react-navigation#4216]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| Android      |7.0

My app has such structure:
 NavDrawer { 
---------------NavStack {
--------------------------- HomeScreen
--------------------------- DevScreen
--------------------------}
--------------- SettingScreen
--------------- AboutScreen
--------------}
If 'BACK' button is pressed while drawer is open, app will exit. Buf if I minimize app then restore it, open drawer and press 'BACK', the drawer will be closed but not exit app. I think it is what we want.

**Comment by adyanced** [comment]
@mc-lean Thank u for ur comment.
I ever tried such code as below, but there's an issue "undefined is not an objece(evaluating 'NavDrawer.router')".  
` export const NavDrawer = createDrawerNavigator(...} 
const defaultDrawerGetStateForAction = NavDrawer.router.getStateForAction;
NavDrawer.router.getStateForAction = (action, state) => {
  if (state && (action.type === NavigationActions.BACK) &&
     (state.routes[state.index].routeName === 'HomeRoute')) {...}
}`

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
