### ISSUE TITLE
NavigationContainer opens URLs even without a uriPrefix defined

### ISSUE THREAD

**Issue by jeffreyffs** [react-navigation/react-navigation#4225]
---

### Current Behavior

I have an authentication flow that needs to happen when the app starts up and I want to support deep linking in my app. I need to wait until my auto login has finished before attempting to do the deep link. I'm queuing up the link the app was opened with and generating the appropriate action using 'getActionForPathAndParams'... but my root navigator is handling the deep link even though I didn't specify a 'uriPrefix'. https://github.com/react-navigation/react-navigation/blob/08e1b53f2e144a5354a485a327ba9dc6e89acd96/src/createNavigationContainer.js#L210
This makes it impossible to work around without forking the repo.

### Expected Behavior

I do not expect my navigators to be handling URLs unless I specify them to do so. A simple check for a uriPrefix or a boolean to disable deep link handling would be sufficient.

### How to reproduce

- Use the sample app, but remove the uriPrefix. The app will still handle the deep link.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.53
| node             | 8.3.0
| npm or yarn      | 1.1.0

**Comment by brentvatne** [comment]
cc @ericvicenti

**Comment by ericvicenti** [comment]
So the current behavior is to handle all URLs, and to handle all paths that are `appname://path`. (Of course, this behavior only works on iOS because android requires the domain).

Unforunately that means we cannot use the `pathPrefix` as the flag for handling URLs, because some people may depend on the current behavior.

@jeffreyffs, we should add a new prop for you that allows you to disable the built-in URL handling

**Comment by jeffreyffs** [comment]
👍 That would work for me. Thanks!

**Comment by satya164** [comment]
Closing since there's a prop to disable deep link handling https://reactnavigation.org/docs/4.x/deep-linking#disable-deep-linking
