### ISSUE TITLE
When a child route calls parent Route with different Param = No Reload/Rerender?

### ISSUE THREAD

**Issue by bonbonio** [react-navigation/react-navigation#4231]
Hello,

I have a Profile screen, and the parameter passed is the ID to be reloaded, but when I call `this.props.navigation.navigate('Profile', { userId : userId }); ` with different userId's it does not start the render function on the Profile page. Even the animation looks like a back animation.

The parameter does get changed, but the render isnt called, so I have to do a pullToRefresh to see the new profile, which then cascades as not all my child components seem to redraw; so the issue above is the flaw.

I think I might need to pass a random key value or something? But this doesnt seem to do the trick either;

`this.props.navigation.navigate('Profile', { userId : userId }, null, null);`

I have so many crazy bugs in React-Navigation! I would say its a bug that the same route with a different parameter doesnt trigger a full re-render?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
