### ISSUE TITLE
Drawer not working after loggin back in the app

### ISSUE THREAD

**Issue by ezekel** [react-navigation/react-navigation#4293]
I am using redux in my react-native app with stack,tabs and drawer navigator.
my problem is that when I am going to logout in my and then I will login again.when I am going to click my humberger menu to open the drawer it will not open. I will drag first the drawer in order to function it back. 

**Here is my routes.js**
```
const Credit = StackNavigator({
    Credit: {
      screen: Screen1,
      navigationOptions: ({ navigation }) => ({
        title: 'Credit',
        headerLeft: <Icon name="menu" size={30} color="white" onPress={ () => navigation.navigate('DrawerOpen') } />,
        headerTintColor: 'white',
        headerStyle:{
          backgroundColor: '#6200EE',
          elevation: 0,
         // showdowOpacity: 0
        },
        tabBarIcon: ({ tintColor }) => {
          return (
            <Icon
            name='ios-cash'
            type='ionicon'
            color={tintColor}
            size={26}
        
        
            />
          );
        }
      })
    }
  },{
    headerMode: 'none'
  });


//here is the drawer
export const RootNavigator = DrawerNavigator({
  Tabsroot: MainStacktab
}, {
  contentComponent:({props})  => <DrawerScreen {...props} />,
});

```

## Environment

```
Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
```

Here is my package.json maybe this will help add more info.

```
 "dependencies": {
    "axios": "^0.18.0",
    "install": "^0.11.0",
    "moment": "^2.22.0",
    "moment-timezone": "^0.5.14",
    "numeral": "^2.0.6",
    "react": "16.3.1",
    "react-moment": "^0.7.0",
    "react-native": "0.55.4",
    "react-native-action-button": "^2.8.4",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.8",
    "react-navigation-redux-helpers": "^1.0.3",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "tcomb-form-native": "^0.6.12"
  },
```

Thank you in advance.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
