### ISSUE TITLE
How can i pass param to another screen??

### ISSUE THREAD

**Issue by ycman0307** [react-navigation/react-navigation#4356]
I want to pass another params to another screen. The followings code works but fail in V2.

this.props.navigation.navigate('screen2', {
                title: 'screen2',
                datail: 'Hello!!'
            });  

Screen2.js
componentDidMount() {
  this.props.navigation.getParam('title');
}

it will show undefined.

Anyone can suggest how to fix it?

**Comment by hodgef** [comment]
Try accessing the property directly from params.
`navigation.state.params.title`

**Comment by ycman0307** [comment]
Also fail. it shows "TypeError: Cannot read property 'title' of undefined"

I found that there is no "params" in state of navigation. It also has routeName and Key. I think there is a big change in V2.

Can you suggest another method for me??

**Comment by vikrantnegi** [comment]
Hi ycman0307,

Can you create a [snack](https://snack.expo.io/) of the code? It will help us to investigate more on the issue.
Thanks.

**Comment by cwhenderson20** [comment]
I am encountering the same issue in v2.0.4, though I believe it is a bit more nuanced. Specifically, I have a setup where I navigate from a screen in one stack to a screen from another stack. With v1, the following worked:

```js
this.props.navigation.navigate("OtherStack", {
  onPress: (value) => console.log(value),
});
```

where `OtherStack` is a stack navigator with a default screen set. 

However, with v2, the navigation still happens, but the params are `undefined`. I noticed that a workaround is to navigate to the name of the default screen within that stack rather than to the stack itself. For example:

**Route definition:**
```js
const OtherStack = createStackNavigator(
  {
    FirstScreen: {
      screen: FirstScreen
  },
  {
    initialRouteName: "FirstScreen"
  }
});
```
**Navigation in component:**
```js
this.props.navigation.navigate("FirstScreen", {
  onPress: (value) => console.log(value),
});
```
The reason I was navigating to the name of the stack rather than the screen within the stack is that the route name appears in other stacks as well, and React Navigation chooses the wrong one by default

I'll try to put together a snack for a minimal reproduction.

**Comment by hodgef** [comment]
I am able to access params from the `navigation.state.params` object just fine. I can also navigate from a page in one stack to another page in another stack (without it being the default) properly.

It's maybe a freshly broken feature. @ycman0307 , could you confirm your version? I have exactly:
"react-navigation": "^2.0.0"

You can also see if everything works once you roll back:
`npm install react-navigation@2.0.0 --save`
