### ISSUE TITLE
The gesturesEnabled don't working

### ISSUE THREAD

**Issue by scriptgb** [react-navigation/react-navigation#4363]
I'm actually working in a project that contains a Drawer with Login screen on it. I know that is not the best way, but I was facing some stranger behavior when the drawer wasn't the initialRoute. The problem is that the user can access the sideMenu with the swap on the left, so I want to remove that possibility, once I have a top button to call the side menu on the Main screen, so I don't need the gesture to open it.

I seen some examples, to use gesturesEnabled: false, but it didn't work. I  tried both examples, but the sideMenu still enable.

```
Login: {
	screen: Login ,
	navigationOptions: () => ({
	      gesturesEnabled: false
	}),
},
```

and

```
const AppNavigator = StackNavigator(
	{
		Drawer: { screen: Drawer },
                Login: { screen: Login },
                ......//some others screens
	},
	{
		initialRouteName: "Drawer",
		gesturesEnabled: false,
		headerMode: "none",
	}
);

```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
