### ISSUE TITLE
When use static navigationOptions in <Consumer> component, it dosn't work

### ISSUE THREAD

**Issue by kirning** [react-navigation/react-navigation#4399]
I use React Context in my project. 
![image](https://user-images.githubusercontent.com/7327933/40831300-3707a534-65bb-11e8-9e2f-644aad836462.png)

The static navigationOptions can't override 
![image](https://user-images.githubusercontent.com/7327933/40831354-5a93f62e-65bb-11e8-8d46-a00ab62dec4c.png)

default value.

react 16.3.1
react-native:0.55.4
react-navigation:2.0.0
Ide: vs code v1.23.1
how can i do?

**Comment by bitting304** [comment]
because of version. Go back to 1.5.11, and you will find everything is ok. just :npm install react-navigation@1.5.11 --save

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
