### ISSUE TITLE
back button not showing

### ISSUE THREAD

**Issue by jsina** [react-navigation/react-navigation#4410]
when I try to run the app on IOS devices, as you could see on picture the back navigation button not appear, although when I click on right position it works but the icon not showed there.

![x](https://user-images.githubusercontent.com/2977960/40885993-81454c1a-6745-11e8-942c-3d3a1bb502eb.jpg)

| software         | version
| ---------------- | -------
| react-navigation | "^1.5.11"
| react-native     | "0.55.2"

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by ChathuraPrabhash** [comment]
###Solved
use headerLeft props for override back Button 
`static navigationOptions = ({ navigation }) => ({
    headerLeft: <Icon
        name={'chevron-circle-left'}
        size={30}
        color='#ffffff'
        style={{paddingLeft: 20}}
        onPress={ () => { navigation.goBack() }} />,
    title: 'My Title',
  });`
