### ISSUE TITLE
Replace  current route page

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [react-navigation/react-navigation#4419]
### Current Behavior

- Can't replace current route page with next route page.
- Can't restructure route stack history, can't remove from current route page from the stack

### Expected Behavior

- I want to remove current route page from the navigation stack
- I only want that for the login page. After login in APP, I want to remove that page from route stack.

### How to reproduce

- I am trying to use **NavigationActions**  but there is two problem : 
     1. I can't reset all route stack, I have set minimul few route manually.
     2. Navigation can't reset if I want to route to tab navigator which is exist in between main stack navigator. Also can't get params in that tab navigation. 

- I just want to remove login page route from route stack so that when I want to back after login then all others pages are coming except login page. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.5.10
| react-native     | 0.54.4
| node             | v6.14.1
| npm     |  3.10.10

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
