### ISSUE TITLE
TabBar Icon not visible

### ISSUE THREAD

**Issue by shahen94** [react-navigation/react-navigation#4420]
### Current Behavior

TabBar icon is not visible when Tab's Root is a Stack navigator

<img width="428" alt="screen shot 2018-06-04 at 3 56 52 pm" src="https://user-images.githubusercontent.com/13334788/40916236-137322c2-6810-11e8-8ea3-73ebe2dffce6.png">

<img width="253" alt="screen shot 2018-06-04 at 3 57 01 pm" src="https://user-images.githubusercontent.com/13334788/40916240-1674456e-6810-11e8-9f50-5fba818acc3f.png">

### Expected Behavior

Icon should be visible as it was in 1.* version. I just updated React-navigation from 1.5 to latest version and got this issue.

### How to reproduce

Just pass StackNavigator to your tabBar screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4 (current)
| react-native     | (0.55)
| node             | (9.6.0)
| npm or yarn      | (npm: 6.1.0)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by vtechguys** [comment]
Hi I have a similar issue and here is github repo. [AppGitHub](https://github.com/vtechguys/app-rn).
