### ISSUE TITLE
Error: There is no route defined... after switching tabs inside drawer scenes

### ISSUE THREAD

**Issue by Mtnt** [react-navigation/react-navigation#4421]
### Current Behavior

`Error: There is no route defined for key 'Stack0'. Must be one of: 'scene2','scene3'`

### Expected Behavior

The `Tab0.Stack0.scene0` is opened.

### How to reproduce

Navigation stack (default is made by `initialRouteName` config property):
```
Drawer
  Tab0,
    Stack0(default)
      scene0(default)
      scene1
    Stack1
      scene2(default)
      scene3
  Tab1(default)
    Stack2(default)
      scene4
    Stack3
      scene4
```
Test path (made by pressing drawer menu and tabs):
```
Tab1.Stack2.scene4 ->
Tab0.Stack0.scene0 ->
Tab0.Stack1.scene2 ->
Tab1.Stack2.scene4 ->
Tab0(.Stack0.scene0) - in parentheses because the error is happened here
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.55.4
| node             | 10.0.0
| npm           | 6.1.0

# ALSO

### Current Behavior

`Tab0.Stack1.scene2` is opened

### Expected Behavior

The `Tab0.Stack0.scene0` is opened (cos it is a default tab).

### How to reproduce

Navigation stack is the same.
Test path: 
```
Tab1.Stack2.scene4 ->
Tab0.Stack0.scene0 ->
Tab0.Stack1.scene2 ->
Tab1.Stack2.scene4 ->
navigation.navigate("Tab0")
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
