### ISSUE TITLE
setParams not idiomatic react

### ISSUE THREAD

**Issue by Rojuinex** [react-navigation/react-navigation#4426]
Isn't suggesting to only render react-navigation once and use setParams a react anti-pattern?  setState seems to be the defacto way to update props on a component.  I believe react-router for web used to also have this same limitation but they updated their code to be idiomatic a few years ago I think.  It would be great if we weren't forced into use redux and could just use react as it was designed to be used.

**Comment by brentvatne** [comment]
hi! react-router on the web solves a similar problem (and they do a very good job of it!) but react-navigation has a broader scope so it can't be compared apples to apples.

if you have some concrete proposals you are welcome to open a rfc on https://github.com/react-navigation/rfcs

otherwise please in the future keep in mind that the issues here are only for bug reports
