### ISSUE TITLE
createMaterialTopTabNavigator with FlatList bug on iphonex

### ISSUE THREAD

**Issue by cbjs** [react-navigation/react-navigation#4446]
this bug only exist on iphoneX, when swipeEnabled is set to true, the "Pull to Refrsh" of FlatList(in MessageDetail) is not working.

for now, I have to hack for iphonex. disable swiping while checking current device is iphonex.
```js
const Message = createMaterialTopTabNavigator({
  reply: {
    screen: (props) => <MessageDetail {...props} label="reply"/>,
    navigationOptions: {
      tabBarLabel: `Reply`,
    }
  },
  at: {
    screen: (props) => <MessageDetail {...props} label="at"/>,
    navigationOptions: {
      tabBarLabel: `@You`,
    }
  },
  like: {
    screen: (props) => <MessageDetail {...props} label="like"/>,
    navigationOptions: {
      tabBarLabel: `Likes`,
    }
  },
  inbox: {
    screen: (props) => <MessageDetail {...props} label="inbox"/>,
    navigationOptions: {
      tabBarLabel: `Inbox`,
    }
  }
}, {
  initialRouteName: 'reply',
  tabBarPosition: 'top',
  swipeEnabled: !isIphoneX(),
});
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
