### ISSUE TITLE
DrawerOpen

### ISSUE THREAD

**Issue by SumitThakr** [react-navigation/react-navigation#4450]
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import {Icon,Button,Container,Header,Content,Left, Tab} from 'native-base';
export default class CustomHeader extends Component {
//   static navigationOptions={
//     title:'देश',
//  };
  render() {
    const {navigate}=this.props.navigation;
     return (
         <View style={styles.container}>
         {/* <Text onPress={() =>this.props.navigation.navigate('DrawerOpen')}>Menu</Text>         */}
         <Left>
            <Button  transparent
              **onPress={() =>navigate('DrawerOpen')}**
                // {
                // const {navigate}=this.props.navigation;
                // navigate("DrawerOpen")}}
             >
                  <Icon name="menu" />
                </Button >
            </Left>
         </View>
     );
  
  }
}

const styles = StyleSheet.create({
    container: {
      //flex: 1,
      height:'10%',
     width:'100%',
     backgroundColor:'red'
      // justifyContent: 'center',
      // alignItems: 'center',
     
    },

    headerStyle:{
     width:'100%',
     height:'20%',
      backgroundColor:'#e30514'
    }
  
  });
problem is DrawerOpen not working

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by igor90007** [comment]
i have the same problem.
