### ISSUE TITLE
Custom header background image

### ISSUE THREAD

**Issue by jskidd3** [react-navigation/react-navigation#4466]
### Current Behavior

Image is expanding to fill whole screen, not just container.

![Current behaviour](https://i.imgur.com/CgAR5mQ.png)

### Expected Behavior

It should fill the header not the whole screen like this:

![Expected behaviour](https://i.imgur.com/haUGJmk.png)

### How to reproduce

```
const ImageHeader = props => (
  <View style={{ backgroundColor: '#eee' }}>
    <Image
      style={StyleSheet.absoluteFill}
      source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg' }}
    />
    <Header {...props} style={{ backgroundColor: 'transparent' }}/>
  </View>
);

const MapStack = StackNavigator(
  {
    Map: {
      screen: MapScreen
    }
  },
  {
    navigationOptions: {
      headerTitleStyle: { color: '#fff' },
      header: (props) => <ImageHeader {...props} />,
      headerStyle: {
        backgroundColor: 'transparent'
      }
    }
  }
);
```

Any ideas how I can fix this?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
