### ISSUE TITLE
navigationOptions dos not work with react-native meteor

### ISSUE THREAD

**Issue by imspikey** [react-navigation/react-navigation#4471]
### Expected Behavior
navigationOptions should (did before) work when using react native meteor

### Current Behavior
It dos not work as there is no effect even when adding navigationOptions to the component itself

### How to reproduce

const MainDrawer = DrawerNavigator({
    Home: {
        screen:()=> <MainScreen/>,
        navigationOptions : {
            header:(navigation)=><View style={{
                height: 60,
                backgroundColor: '#3498db',
                justifyContent: 'center',
                alignItems: 'center',
            }} >
                <View style={{height:20,width,backgroundColor:'#006aa9'}}/>
                <View style={{
                    backgroundColor:"orange",
                    flexGrow:1,
                }} >
                    <Text style={{color:'black',weight:'900',fontSize:25}}>المبادرات</Text></View>

                <Icon
                    onPress={()=>{
                        console.log( navigation)
                        navigation.navigation.navigate('DrawerToggle')
                    }}
                    containerStyle={{ width:50,height:50, position:'absolute',bottom:-10,right:0}}
                    name={'navicon'}
                    size={30}
                    color='black'
                    type={'evilicon'}
                />
                {/*<Text style={{color:'yellow'}} >Olla</Text>*/}
            </View>

        }
    },
    AboutUs:{screen: AboutUs}
}, {
    contentComponent:navigation => <MainDrawerComponent navigation={navigation}/>,
    drawerPosition: 'right',
    drawerWidth: 200,
    contentOptions: {
    activeTintColor: '#000'
    }

});

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.5
| react-native     |   0.54.0
| node             | v9.7.1
| npm or yarn      |  npm

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
also, i would like to point out that we will not help with any bug that you are unable to reproduce without using a third party library. if you cannot reproduce it with just react-navigation then it's a bug in the other library or your code.
