### ISSUE TITLE
How to reset the screen state while it pushing?

### ISSUE THREAD

**Issue by PMExtra** [react-navigation/react-navigation#4472]
I found that the state would kept when I go back and re-push to a screen in StackNavigator.
It's confusing to me, I remember in iOS native, the controller will be destroy immediately when I go back from the view. And it will be a new one when push it again.
So I want to find an awesome way to reset the state to the `INITIALSTATE`, I thought it's an "ugly" way that add `Reset` action to every redux and dispatch it in every screen.
(The project using react-redux)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
