### ISSUE TITLE
_navigator.dispatch is not a function

### ISSUE THREAD

**Issue by Tokyohots** [react-navigation/react-navigation#4483]
function setTopLevelNavigator(navigatorRef) {
  _navigator = navigatorRef;
}

function getTopLevelNavigator() {
  return _navigator;
}

function navigate(routeName, params) {
  _navigator.dispatch(
    NavigationActions.navigate({
      type: NavigationActions.NAVIGATE,
      routeName,
      params
    })
  );
}

// add other navigation functions that you need and export them

export default {
  navigate,
  setTopLevelNavigator,
  getTopLevelNavigator
};

err:
pushRouter error: TypeError: _navigator.dispatch is not a function
    at Object.navigate (D:\RNDev\young\src\navigator\NavigationService.js:14)
    at pushRouter (D:\RNDev\young\src\utils\pushRouter.js:100)
    at D:\RNDev\young\index.js:150
    at D:\RNDev\young\node_modules\jpush-react-native\index.js:422
    at RCTDeviceEventEmitter.emit (D:\RNDev\young\node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:181)
    at MessageQueue.__callFunction (D:\RNDev\young\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:302)
    at D:\RNDev\young\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:116
    at MessageQueue.__guard (D:\RNDev\young\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:265)
    at MessageQueue.callFunctionReturnFlushedQueue (D:\RNDev\young\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:115)
    at debuggerWorker.js:72

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by graig12** [comment]
Was this issue resolved ? i am facing the same issue "_navigator.dispatch is not a function"
when ever i tried to navigate from any module in my app

**Comment by brentvatne** [comment]
i believe you are looking for `props.navigation`. please read docs at https://reactnavigation.org/ to learn how to use the library and if you run into anything you think is a bug then open an issue and fill out the issue template!

**Comment by EphraimMwanda** [comment]
how do you solve the problem mentioned above?
i followed the steps mentioned in the docs(https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html) of react-navigation completely but when i run the code on my console log, it says "_navigator.dispatch is not a function"

**Comment by EphraimMwanda** [comment]
ok, sorry but i dont really understand what you mean by that?

**Comment by EphraimMwanda** [comment]
how do i make sure the ref is set before calling something on it?

**Comment by EphraimMwanda** [comment]
how do i make sure the ref is set before calling something on it? is it mentioned in any of the doc, probably a place i can reference or see where it is used in an example?

i had done everything mentioned in the docs when the error popped up.

if there is a step i am skipping i wouldnt know because i do not find any reference anywhere


@brentvatne can you provide an example?

**Comment by EphraimMwanda** [comment]
ooooh i figured out the error, and i fixed it. thanks to @brentvatne , i re-read the docs and it is said that,

 "Use this only with the top-level (root) navigator of your app."

turns out i was not doing that.

i fixed that and the error is gone

thank you very much for your help, i am not sure what exactly is going on, but if any one can explain that would be very helpful
