### ISSUE TITLE
Overriding getStateForAction in inner Navigator throws error.

### ISSUE THREAD

**Issue by paulpopiel** [react-navigation/react-navigation#4484]
### Current Behavior

When trying to customize navigation behaviour through overriding the `getStateForAction` method on an inner Navigator - throws an error.

```
const InnerNavigator = createBottomTabNavigator({
    Home,
    Menu,
    Settings,
});

const defaultGetStateForAction = InnerNavigator.router.getStateForAction;
InnerNavigator.router.getStateForAction = (action, state) => {
    console.log('action', action);
    return defaultGetStateForAction(action, state);
};

const TestNavigator = createStackNavigator({
    Main: InnerNavigator,
    Listing,
    Publication,
});

class Sample extends Component {
    render() {
        return <TestNavigator />;
    }
}

export default Sample;

```

Error:

TypeError: this.getInitialState is not a function

The offending line is in `SwitchRouter.js` 

```
    getStateForAction(action, inputState) {
      let prevState = inputState ? { ...inputState } : inputState;
      let state = inputState || this.getInitialState();
      let activeChildIndex = state.index;
```

### Expected Behavior

This error was not present prior to v2.

### How to reproduce

See sample code above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.0
| react-native     | 0.55.4

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
