### ISSUE TITLE
createStackNavigator inside createBottomTabNavigator freezes and shows old navigation only

### ISSUE THREAD

**Issue by vrautgit** [react-navigation/react-navigation#4485]
I have tabnavigator like this 

`const TabNav = createBottomTabNavigator({`
    `DashboardNavigation: {`
        `screen: DashboardNavigation,`
        `navigationOptions: {`
            `tabBarLabel: 'Home',`
            `tabBarIcon: ({ tintColor }) => (<IconFea name="home" size={iconHeight} color={tintColor} />),`
           `label: 'Dashboard',`
        `},`
    `},`
    `MoreNavigation: {`
        `screen: MoreNavigation,`
       `navigationOptions: {`
            `tabBarLabel: 'More',`
            `tabBarIcon: ({ tintColor }) => (<IconFea name="settings" size={iconHeight} color={tintColor} />),`
           ` label: 'More',`
       ` }`
    `},`
`});`
`export default TabNav;`

And Stack Navigations are following : 

`const DashboardNavigation = createStackNavigator({`
    `Dashboard: {`
        `screen: Dashboard,`
       `navigationOptions: {`
            `title: 'Dashboard'`
       ` },`
   ` }`
`});`
`export default DashboardNavigation;`

`const MoreNavigation = createStackNavigator({`
    `More: {`
       ` screen: More,`
        `navigationOptions: {`
           ` title: 'More'`
      `  },`
    `}`
`});`
`export default MoreNavigation;`

When i click on **More** tab **Home** tab opens and When i click on **Home** tab **More** tab opens.
Actually On Home tab click Home is opening but not visible on screen so it looks like other tab is being open same other way around.

**Version**
React-navigation  : 2.3.0
react-native : 0.55.4

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
