### ISSUE TITLE
How to start always from the same screen (SplashScreen)

### ISSUE THREAD

**Issue by fnicastri** [react-navigation/react-navigation#4486]
I need to force my app to start always from the same screen, on cold start, resume or switch.
In this screen I need to do some fetchs and manipulate some data and then navigate to the correct screen depending on these operations. 
I can start from the SplashScreen on a cold start but on resume the app remember the last screen and restart from there.

There is a pattern to do that?

**Comment by ericvicenti** [comment]
Are you using `persistenceKey`? If not, then the app should already have this behavior. If you want to persist navigation state but also start in the same place, you can write custom code to do that.

Next time when opening an issue, please follow the issue template and show us a minimal example of the bug, otherwise we won't be able to fix it

**Comment by fnicastri** [comment]
Thank you,
in the end was some old code left around while refactoring the navigation
