### ISSUE TITLE
React-navigation (v2) HEADER 

### ISSUE THREAD

**Issue by jadelmir** [react-navigation/react-navigation#4498]
## The issue tracker is reserved for bug reports only.
 

export const MainStack = StackNavigator(
	{
		MainView: { screen: Homepage },
		IdentitySceen: { screen: Identity },
		Profile: { screen: ProfileView },
		LoginSceen: { screen: Login },
		NewsSceen: { screen: News },
		HEBDOSceen: { screen: Hebdo },
		AgendaSceen: { screen: Agenda },
		ContactUsSceen: { screen: ContactUs }
	},
	{
		// headerMode: 'screen',
		//
		// navigationOptions: {
		// 	title: 'Profile'
		// }
	}
);

export const AppNavigator = StackNavigator(
	{
		// Login: { screen: LoginScreen },
		Main: { screen: MainStack },
		UserAddView: { screen: UserAddView }
	},
	{
		headerMode: 'none',
		mode: 'modal'
		// navigationOptions: {
		// gesturesEnabled: false
		// }
	}

this way should render a header in each of the mainstack but unfortunately, nothing has been shown 
and if I don't integrate header in each page it will crash 

![simulator screen shot - iphone 6 - 2018-06-13 at 12 23 43](https://user-images.githubusercontent.com/31207632/41342331-a5f80842-6f04-11e8-834a-64e8cfb22518.png)

this is shown when I remove header null 

HEBDO.navigationOptions = {
	title: 'Profile',
	headerMode: 'screen',
	// header: null
};

it is not a good way to customize a header for each  component is there any fixes or it is just a bug 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.04
| react-native     |0.55.4
| node             |8.9.3
| npm or yarn      |6.0.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
