### ISSUE TITLE
Unable to call navigation.dispatch(DrawerActions.openDrawer());

### ISSUE THREAD

**Issue by redstubble** [react-navigation/react-navigation#4507]
"react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-elements": "^0.19.1",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.3.0",

I have two navigation types that work at the same level. Within a TabNav view I am unable to call
` navigation.dispatch(DrawerActions.openDrawer());
`
Why is there no easy implementation for this popular use case?

```
const StckNav = createStackNavigator(
  {
    DrawerNav: {
      screen: DrawerNav,
    },
    TabNav: {
      screen: TabNav,
    },
  },
  {
    initialRouteName: 'TabNav',
  },
);
```

```
const TabNav = createBottomTabNavigator(
  {
    Home: {
      screen: (props) => <Home {...props} />,
      path: '/home',
      navigationOptions: {
        title: 'Home',
        tabBarLabel: 'Home',
      },
    },
    Profile: {
      screen: Profile,
      path: '/profile',
      navigationOptions: {
        title: 'Profile',
        tabBarLabel: 'Profile',
      },
    },
    Documents: {
      screen: Documents,
      path: '/documents',
      navigationOptions: {
        title: 'Documents',
        tabBarLabel: 'Documents',
      },
    },
  },
  {
    initialRouteName: 'Profile',
  },
);

```
```
const Profile = ({ navigation }) => (
  <SafeAreaView>
    <Text>Screen</Text>
    <Button
      onPress={() => navigation.dispatch(DrawerActions.closeDrawer())}
      title="Open drawer"
    />
  </SafeAreaView>
);
```

My understanding was that dispatching the actions would call any instance of Drawer. Do I need to initialise the Drawer item in any way to dispatch the action.

I could nest the TabNav inside the Drawer nav, but it seems like a hacky solution. I would need to hide the TabNav element from the drawer items.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
