### ISSUE TITLE
set tabBarLabel a function throw a warning.

### ISSUE THREAD

**Issue by Tomatoo** [react-navigation/react-navigation#4516]
in my case: the tabbarlabel show different text depend on user login or not.

this is my code:

```
tabBarLabel: ({ tintColor, focused }) => <BottomTabLabel tintColor={tintColor} focused={focused} />,
tabBarVisible: routeName === 'feed/home',
tabBarOnPress: ({ defaultHandler }) => {
    feedTabOnPress();
    defaultHandler();
 },
```

this is BottomTablabel:

```
@connect(store => ({
  guestOrNoSct: guestOrNoSctSelector(store),
}))
export default class BottomTabLabel extends React.Component {
  render() {
    return (
      <Text style={{ fontSize: 12, color: '#606062' }}>{this.getLabel()}</Text>
    );
  }

  getLabel() {
    if (guestOrNoSct) {
      return 'home'
    }
    
    return 'login'
  }
}
```

then throw a warning:

<img width="1024" alt="2018-06-15 3 12 29" src="https://user-images.githubusercontent.com/15502063/41455138-a854cafc-70ae-11e8-8b49-5a7ee308d4bc.png">

thanks~

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
