### ISSUE TITLE
Hot reload does not work

### ISSUE THREAD

**Issue by NicklausBrain** [react-navigation/react-navigation#4517]
### Current Behavior

Hot reload does not work for all the screens except the Root one.

### Expected Behavior

Changes made in code should be applied for any screen during hot reload

### How to reproduce

1. Navigate to any screen other than root one;
2. Make changes in code of that screen and save;
3. Hot reload takes place but no changes are reflected in the selected screen.

### Environment
react-navigation 2.3.1
react-native    0.55 
node            10.2.1
npm 5.6.0 
Clients: both iOS and Android

**Comment by brentvatne** [comment]
i guess you're using mobx or something.

nonetheless, as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
