### ISSUE TITLE
Header Background Color Issue

### ISSUE THREAD

**Issue by sofusskovgaard** [react-navigation/react-navigation#4527]
Hi. I'm currently working on an app and i'd like to change the background color of the header. Which i've done, and it works and all. But when i transition from a page to the last page i was on, the background color goes back to white. I can't seem to find anything about it.

![](https://im3.ezgif.com/tmp/ezgif-3-30c78fc286.gif)
Look at the header

![image](https://user-images.githubusercontent.com/24526844/41526606-019e5f3c-72e5-11e8-950d-eefd78605e12.png)
Here's the code

**Comment by sofusskovgaard** [comment]
If it helps i just realised that it doesn't change back to the original color when you swipe the screen. The gesture, if you get what i mean

**Comment by RockyF** [comment]
+1
The header bar reset to default color(white) when navigate to other screen which header is null,
or swipe back to last screen.
![qq20180618-230343](https://user-images.githubusercontent.com/1643017/41544693-ee31e3ee-734b-11e8-9374-b2b6e22e9927.gif)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
