### ISSUE TITLE
react-navigation@2.3.1 can not work in  react@16.4.1 

### ISSUE THREAD

**Issue by asyalas** [react-navigation/react-navigation#4532]
##  react-navigation@2.3.1 can not work in  react@16.4.1 
![simulator screen shot error](https://user-images.githubusercontent.com/25005604/41582570-95003940-73d4-11e8-83c7-b0e58b6d7380.png)
I guess the library 'create-react-context' cause the error in  react@16.3.0 ~ 16.4.1 , because it can work in  react@16.2.0

**Comment by brentvatne** [comment]
@asyalas - it works fine on 16.3.1 (the version used in react-native 0.55). can you provide a repro for this? please have it a minimal runnable repro that i can clone from github (https://stackoverflow.com/help/mcve)

**Comment by brentvatne** [comment]
closed because no repro

**Comment by fangkyi03** [comment]
https://github.com/nihgwu/react-native-dva-starter

**Comment by keyWung** [comment]
@asyalas hi, would you tell me what version of react-native when you got this problem?

**Comment by keyWung** [comment]
@brentvatne I got this problem too on react-native 0.52, can't this library compatible with react-native 0.52?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
