### ISSUE TITLE
Failed to jump properly

### ISSUE THREAD

**Issue by TrustTheBoy** [react-navigation/react-navigation#4534]
### Current Behavior

In Search Modal, using this.props.navigation.navigate("HomeTwo") to jump to the specified page will automatically return to Main, you can add multiple screens in Main in your case and try to jump

### Expected Behavior

After opening Search, you can jump to the HomeTwo in Main in the Search View.

### How to reproduce

```JavaScript
const MainStack = StackNavigator(
  {
    Home: {
      screen: Home
    },
HomeTwo: {
      screen: HomeTwo
    },
  },
  ...
);

const Navigation = StackNavigator(
  {
    Main: {
      screen: MainStack,
    },
    Search: {
      screen: SearchLayout
    },
  },
 ... 
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | all version
| react-native     | 0.55
| node             | v9.11.1
| yarn      |  1.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
