### ISSUE TITLE
Transitioner not working as expected when screen is createDrawerNavigator 

### ISSUE THREAD

**Issue by mikeynova** [react-navigation/react-navigation#4537]
I've been struggling with this for a few weeks now and haven't had any luck looking through issues or stack overflow. 

I'm trying to create a custom transition using the Transitioner component and haven't had any luck.

The issue seems to be related to my Drawer. Instead of navigating to my Drawer route it wants to navigate to my Drawers routes. 

RootNavigator.js
```js
class Test extends Component {
  renderScene = (transitionProps, scene) => {
    const { navigation, router } = this.props;
    const { key, route } = scene
    let Screen = CustomRouter.getComponentForRouteName(route.routeName)
    return (
      <Screen navigation={this.props.navigation} key={key}/>
    )
  }
  render () {
    return (
      <Transitioner
        configureTransition={() => ({
          timing: Animated.timing,
          duration: 1000,
          easing: Easing.linear(),
          useNativeDriver: true
        })}
        navigation={this.props.navigation}
        render={(transitionProps) => {
          return (
            <View style={{ flex: 1 }}>
              {transitionProps.scenes.map(scene => this.renderScene(transitionProps, scene))}
            </View>
          )
        }}
      />
    )
  }
}

const CustomRouter = StackRouter({
  Drawer,
  AnimatedPlayer
})

export const RootNavigator = createNavigationContainer(createNavigator(Test, CustomRouter))
```

DrawerRoutes.js
```js
export const DrawerRoutes = {
  Home: { screen: HomeStack },
  Messages: { screen: MessagesStack },
  Discussions: { screen: DiscussionsStack },
  Chat: { screen: ChatStack },
  Submissions: { screen: SubmissionsStack },
  Vote: { screen: VoteStack },
  History: { screen: HistoryStack },
  Settings: { screen: SettingsStack },
  Login: { screen: LoginStack }
}
```

error message
![screen shot 2018-06-19 at 4 22 04 pm](https://user-images.githubusercontent.com/8882783/41629172-f9c5db70-73dc-11e8-9872-1869153d5a18.png)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
