### ISSUE TITLE
Issue with createBottomTabNavigator and pagination library.

### ISSUE THREAD

**Issue by stevemanone** [react-navigation/react-navigation#4538]
Hey all!  I'm having an issue with how the createBottomTabNavigator is interacting with a pagination library (https://www.npmjs.com/package/rn-viewpager).  Some of the screens in the app use this pagination library to separate icons into several pages; for example: using the bottom navigation bar you can navigate to an 'icons' screen, in which you can scroll through grids of icons, which are grouped and separated onto their own pages (like how an iPhone home screen is organized).  The library is not behaving as expected (the library seems to freak out due to the fact that components always stay mounted.  When you navigate away from the 'icon' screen and then navigate back, the pages become one continuously scrollable page, instead of multiple distinct pages).  Basically, I wanted to ask:

Is there a better way to properly set up this UI without resorting to an outside library and instead directly using the react-navigation API?  Any thoughts/comments would be much appreciated, if this was at all unclear (or if this is not an appropriate question to pose here), please let me know! 

software | version
-- | --
react-navigation | 2.0.4
react-native | 0.55.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
