### ISSUE TITLE
React Navigation Disappearing when coming back to the same screen

### ISSUE THREAD

**Issue by barathkb** [react-navigation/react-navigation#4553]
### Current Behavior

Bottom Tab navigator doesn't appear when I move away from the scope of MainNavigator to AppNavigator and come back to the scope of  MainNavigator.

### My Code

`
const MainNavigator = TabNavigator({
  Train: {
    screen: TrainChapters,
    path: 'train',
    navigationOptions: () => ({
      title: 'Train',
      tabBarIcon: (tintColor) => {
        return <Image source={{ uri: 'asset:/img/train.png' }} style={[styles.iconStyle, { tintColor: tintColor.tintColor }]} />;
      },
    }),
  },
  Bookmarks: {
    screen: BookmarkScreen,
    path: 'bookmark',
    navigationOptions: () => ({
      tabBarIcon: (tintColor) => {
        return <Image source={{ uri: 'asset:/img/bookmark_dashboard.png' }} style={[styles.iconStyle, { tintColor: tintColor.tintColor }]} />;
      },
    }),
  },
  Report: {
    screen: HomeScreen,
    path: 'home',
    navigationOptions: () => ({
      tabBarIcon: (tintColor) => {
        return <Image source={{ uri: 'asset:/img/report.png' }} style={[styles.iconStyle, { tintColor: tintColor.tintColor }]} />;
      },
    }),
  },
  Profile: {
    screen: ProfileScreen,
    path: 'profile',
    navigationOptions: () => ({
      tabBarIcon: (tintColor) => {
        return <Image source={{ uri: 'asset:/img/profile.png' }} style={[styles.iconStyle, { tintColor: tintColor.tintColor }]} />;
      },
    }),
  },
}, {
  stateName: 'MainAppNav',
  contentComponent: props => <Drawer {...props} />,
  tabBarPosition: 'bottom',
  swipeEnabled: false,
  tabBarOptions: {
    upperCaseLabel: false,
    activeTintColor: '#445ee9',
    inactiveTintColor: '#7B797A',
    showIcon: true,
    style: {
      backgroundColor: 'white',
    },
    indicatorStyle: {
      backgroundColor: 'white',
    },
    labelStyle: {
      fontSize: 10,
      fontWeight: '100',
      margin: 5,
    },
  },
});

export default MainNavigator;
`
------
`
const AppNavigator = StackNavigator(
  {
    Splash: {
      screen: Splash,
      path: 'splash',
    },
    Main: {
      screen: MainNavigator,
      path: 'main',
    },
    Notification: {
      screen: NotificationScreen,
      path: 'notification',
    },
    BookmarkScreen: {
      screen: BookmarkScreen,
    },
  },
  {
    headerMode: 'none',
  },
);

export default AppNavigator;
`

### ScreenShots
![image](https://user-images.githubusercontent.com/12790300/41766719-563e2ed0-7625-11e8-8891-8a34fcf9d4a3.png)
![image](https://user-images.githubusercontent.com/12790300/41766723-58d11b58-7625-11e8-942d-018bb407a159.png)
![image](https://user-images.githubusercontent.com/12790300/41766726-5ad23a40-7625-11e8-9c00-6f2bc177d43a.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 0.51.0
| node             | v9.3.0
| npm or yarn      |5.6.0

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug - read https://stackoverflow.com/help/mcve.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
