### ISSUE TITLE
createMaterialTopTabNavigator tabBarOptions style height:0 inconsistency

### ISSUE THREAD

**Issue by yanush** [react-navigation/react-navigation#4556]
### Current Behavior
setting the tabBarOptions:style:{height: 0}, causes the indicator to fully disappear on android while on ios it's still shown.

### Expected Behavior
Retain consistency between operating systems - Keep it shown on both OS, unless indicatorStyle states otherwise

### How to reproduce
Just add a tab navigator using createMaterialTopTabNavigator with tabBarOptions:style:{height: 0} and run on both operating systems

### Your Environment
react-navigation: 2.3.0
react-native: 0.55.4
node: 9.8.0
npm: 6.1.0
yarn: 1.5.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
