### ISSUE TITLE
reactNavigation.getNavigation is not a function.

### ISSUE THREAD

**Issue by Amurmurmur** [react-navigation/react-navigation#4571]
Followed redux implementation exactly.
Everything worked just fine before 2.5.x releases.

```
AppNavigation:
const AppNavigation = createStackNavigator({
  LoadingScreen: { screen: LoadingScreen },
  LoggedInStack: { screen: LoggedInStack },
  NotLoggedInStack: { screen: NotLoggedInStack }
}, {
  // Default config for all screens
  headerMode: 'none',
  initialRouteName: 'LoadingScreen',
  navigationOptions: {
    headerStyle: styles.header
  }
})



    const AppWithNavigationState = reduxifyNavigator(AppNavigation, "root");
    return <AppWithNavigationState dispatch={dispatch} state={nav} />
```

Update:
Made it work by upgrading from 2.2.5 through 2.4.x and up to 2.5.2 which is the latest build.
Now the issue is that drawer shows but after a second it disappears and the whole root component gets remounted.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
