### ISSUE TITLE
goBack redirecting to Initial Screen instead of Previous Screen

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [react-navigation/react-navigation#4581]
Am using **SwitchNavigator** for Authentication flow. goBack redirecting me to initial screen instead of previous screen

below is my code,
```
const AppStack = createDrawerNavigator({
    Home: {
        screen: HomeScreen
    },
    About: {
        screen: About
    },
    Profile: {
        screen: ProfileScreen
    }
},
{
    initialRouteName: 'Home',
}
);
```
```
const AuthStack = createStackNavigator({
    Login: {
        screen: LoginScreen
    }
}, {
    headerMode: 'none',
    navigationOptions: {
        headerVisible: false,
    }
});
```

```
const MyApp = createSwitchNavigator({
    AuthLoading: AuthLoadingScreen,
    App: AppStack,
    Auth: AuthStack,
},
{
    initialRouteName: 'AuthLoading',
})
```

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

**Comment by KalaiselvanMahendran** [comment]
@vonovak I understand, go through my expo link https://snack.expo.io/S1Jrqxbz7, i have reproduced the issue
