### ISSUE TITLE
StackNavigator change to TabNavigator result is so bad

### ISSUE THREAD

**Issue by kuangyazhou** [react-navigation/react-navigation#4601]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.0
| react-native     | 0.51.0
| node             | 10.0.0
| npm or yarn      | 5.6.0

### Current Behavior
I have a StackNavigator and a TabNavigator, now switch from TabNavigator to StackNavigator, TabNavigator shut down first, and then StackNavigator, animation effect is not good, is there any way to improve, or is there a way to change this kind of switch effect

### Expected Behavior

Better animation switching effect

### How to reproduce
no reproduce

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
