### ISSUE TITLE
[createBottomTabNavigator] unable to navigate screen that not included in the order

### ISSUE THREAD

**Issue by SimoneLSK** [react-navigation/react-navigation#4624]
Hi Devs, 

Just wondering if it is possible to navigate to other screen that not inside the order in BottomTabNavigatorConfig? 

```
createBottomTabNavigator(
    {
        TabA: {screen: tabA},
        TabB: {screen: tabB},
        TabC: {screen: tabC},
    },{
        initialRouteName: 'TabA',
        order: ['TabA', 'TabB'],
    }
)
```

I could not navigate to TabC if it is not inside the [order] on above code. 
is there any solution instead of putting it into Order? 

Thanks in advance

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
