### ISSUE TITLE
Navigation gestures are interactable while the RN Modal is open

### ISSUE THREAD

**Issue by svbutko** [react-navigation/react-navigation#4633]
The issue exists for a long time and there were several other issues and discussions about it and the only answer about it is that the RN Modal is pretty bad itself.

I know that it's possible to create some sort of modal-like navigation page, but there are some limitations to it and it takes more time to implement.

Is it going to be addressed at some point of time? If not, then which repository is more "responsible" for this kind of behavior? Are there any plans for making a custom component which can behave nearly the same way as RN Modal does?

Thank you.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by amitv87** [comment]
Here is the code to reproduce this issue. The drawer is swipe able even when modal is open

index.js
```javascript
import React from 'react';
import { Text, View, Dimensions, Modal, Button, AppRegistry } from 'react-native';
import {createDrawerNavigator} from 'react-navigation';

class App extends React.Component {
  constructor(props){
    super(props);
    this.state = {showModal: false}
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>hello</Text>
        <Button title={"open modal"} onPress={() => this.setState({showModal: true})}/>
        <Modal transparent={true} visible={this.state.showModal} onRequestClose={()=>this.setState({showModal: false})}>
          <View style={{justifyContent:"center", flex:1}}>
            <View style={{backgroundColor: 'yellow'}}>
              <Text style={styles.paragraph}>world</Text>
              <Button title={"close modal"} onPress={() => this.setState({showModal: false})}/>
            </View>
          </View>
        </Modal>
      </View>
    );
  }
}

const Drawer = createDrawerNavigator({
  root: {screen: App}
},{
  gesturesEnabled: true,
  drawerWidth: Dimensions.get('window').width * 0.80,
  contentComponent: props => <Text style={styles.paragraph}>hello world</Text>,
});

const styles = {
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#34495e',
  },
};

AppRegistry.registerComponent('YourApp', () => Drawer);
```
