### ISSUE TITLE
React-navigation replace replaces the current component but re-renders the original component in the new component

### ISSUE THREAD

**Issue by yaoyingjiang** [react-navigation/react-navigation#4640]
i use this.props.navigation.replace to PayInSwipeCard  but LevyMoneyComponent  re-render  constructor  componentWillMount and componentWillUnmount 

![image](https://user-images.githubusercontent.com/19427456/42267910-cb98b3cc-7fac-11e8-89d0-f5d8ae9f37e6.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.12
| react-native     |0.55.3
| node             |v8.4.0
| npm or yarn      |1.7.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
