### ISSUE TITLE
tabBarIcon image not visible

### ISSUE THREAD

**Issue by TaiRise** [react-navigation/react-navigation#4648]
### Current Behavior

I wanted to customize my tabBar Bottom navigation with some image for each button instead of default icon. But it won't show up!

I tried everything i find on internet and documentation. And i don't find the solution.

This is my code 

```
export default createBottomTabNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: () => {
        tabBarIcon: () => (
            <Image style={{width: 50, height: 50}} src={require('./assets/images/home.png')}/>
        )
      }
    },

    Events: {
      screen: EventsScreen,
      navigationOptions: () => {
        tabBarIcon: <Image style={{width: 50, height: 50}} src={require('./assets/images/home.png')}/>
      }
    },

    Bot: {
      screen: BotScreen,
      navigationOptions: () => {
        tabBarIcon: <Image src={require('./assets/images/home.png')}/>
      }
    },

    Lieux: {
      screen: LieuxScreen,
      navigationOptions: () => {
        tabBarIcon: <Image src={require('./assets/images/home.png')}/>
      }
    },

    Atelier: {
      screen: AtelierScreen,
      navigationOptions: () => {
        tabBarIcon: <Image src={require('./assets/images/home.png')}/>
      }
    }

  }, {
    tabBarOptions: {
      showLabel: true,
      showIcon: true,
      style: {
        backgroundColor: APP_COLORS.white,
        borderTopWidth: 0
      }
    }
  }
);
```
as you can see, i've tried different way to put my Image on the tabBarIcon

| software         | version
|-----|------
| ios | 11.4
| react-navigation | 2.6.0
| react-native     |
| node             | 9.2.0
| npm or yarn      | 6.1.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
