### ISSUE TITLE
TabNavigator would make the stack pop to top even it was not focused.

### ISSUE THREAD

**Issue by PMExtra** [react-navigation/react-navigation#4663]
Reference: #3570 #3589 

For example like #3570
1. navigate to `SettingTab`/`Settings`/`Details`
2. jump to `HomeTab`
3. press SettingTab icon

Excepted behavior: Show the `SettingTab`/`Settings`/`Details`.
Actual behavior: Auto pop to top with animation, and showed `Settings` finally.

**Not only that, there is a more critical problem:**

**4. jump to HomeTab**
**5. press SettingTab icon**

**It would do nothing instead jumping to `SettingTab`!**

react-navigation version: 2.4.1, 2.6.1, 2.6.2
OS platform: iOS 11.4

**Comment by PMExtra** [comment]
And I have followed the comment to custom `tabBarOnPress`.
I find that the current API is completely different from what is described in the documentation. (https://reactnavigation.org/docs/en/tab-navigator.html#tabbaronpress)
The docs said there are `{ previousScene, scene, jumpToIndex }` in the param, but actually, I can only get `{ navigation }` from the param.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
