### ISSUE TITLE
If createDrawerNavigator's custom flatlist data is large, opening the drawer is very delayed. How can we solve this problem?

### ISSUE THREAD

**Issue by MsMayuaner** [react-navigation/react-navigation#4678]

**Comment by vonovak** [comment]
Hi, sorry you're having a problem. I have closed this issue because it's impossible to help you, given the information you have provided. We cannot tell why something is slow for you if you just give us one sentence that "describes" your problem. Please create a new issue with a proper reproduction if you want any help.
