### ISSUE TITLE
Support How can I override style in Header Components Props

### ISSUE THREAD

**Issue by tomzaku** [react-navigation/react-navigation#4691]
```
import { Header } from 'react-navigation'
```
I read the code in Header. And I saw that why we have to put both props scene and scenes in the same Header. That means if I want to override style in Header, I have to change both scene and scenes ?

Is there anyway simple to override style for header?

**Comment by neilhamilton** [comment]
You can pass a style object in the StackNavigator config:

https://reactnavigation.org/docs/en/stack-navigator.html#headerstyle

```
const MyStack = createStackNavigator({
  MyScreen: {
    screen: MyScreen,
    navigationOptions: {
      headerStyle: { backgroundColor: 'black' }
    }
  }, {
  initialRouteName: 'MyScreen'
})

**Comment by tomzaku** [comment]
@neilhamilton  @ericvicenti  I would like to inherit the Header Component rather than config in stack config. I saw 2 props scene and scenes props. If I would like to update style which props I need to override?

**Comment by neilhamilton** [comment]
@tomzaku what are your intentions? Maybe there is a better way?

I know that you can pass a custom component for the title, which you could use to pass an image or a TouchOpacity for some custom functionality.

I have never tried customizing the Header component like this but things like the scenes props, those are dynamic and there is a lot going on based on the React Navigation state. I have used a custom back button in the same way and in that case, you only need to add the props you want to override.

```
import { HeaderBackButton } from 'react-navigation'

const headerLeft = <HeaderBackButton tintColor='#fff' onPress={() => doSomething()} />
```

Of course, I have since found out that using a custom router and [getStateForAction](https://reactnavigation.org/docs/en/custom-routers.html#getstateforactionaction-state) is a better way to override back functionality.

Point being, if you let us know what you're trying to achieve, there might be a more documented way.
