### ISSUE TITLE
`navigation.pop` pop a new pushed screen instead of self

### ISSUE THREAD

**Issue by fatfatson** [react-navigation/react-navigation#4694]
I think it's a thread race problem.

in the current top screen , I press a button which should pop the screen,
but `BEFORE` the press event is post to JS thread, 
another screen is pushed to the nav stack,
so the `pop` operation is performed on the new coming screen, 
it's wrong!!

but wait, why the press event in a below screen could produce if there's another one above it?
that's maybe the thread problem.
in JS thread the nav stack(a js object) has modified, but the real UIView change would wait until the call message reaching the UI thread. between this gap, the below screen had been pressed!

so, how could I ensure the `pop` should exactly pop itself??

**Comment by ericvicenti** [comment]
It looks like you want an idempotent action, so that even if you manage to fire the action twice, the state will be correct. So instead of using the pop action, you can use `NavigationActions.goBack({ key })`. By specifying the `key` of the route (ie, `navigation.state.key` inside of the screen), we can be sure that the action can be fired twice safely.

This isn't a very clear issue so I'm going to close it. If you have a specific problem please post a simplified example of the bug, using expo snack or a standalone repo. Thanks!
