### ISSUE TITLE
how override header style justifyContent

### ISSUE THREAD

**Issue by warfrogsdf** [react-navigation/react-navigation#4716]
## The issue tracker is reserved for bug reports only.

i need show headerTitle at center of header

### Current Behavior

use 

static navigationOptions = ({ navigation }) => {
    return {
      headerStyle: {
        justifyContent: 'center'
      },
      headerTitle: <TabHeader
        ref={(t) => { _tab = t }}
        onChange={onChange}
      />
    }
  };

no work 

because of  //warnIfHeaderStyleDefined(justifyContent, 'justifyContent');

### Expected Behavior

can centerize headerTitle by config,

my question is this have some other method to centerrize headerTitle by config?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.5.5

**Comment by jinxac** [comment]
Looks like [https://github.com/react-navigation/react-navigation/blob/master/src/views/Header/Header.js#L491](https://github.com/react-navigation/react-navigation/blob/master/src/views/Header/Header.js#L491) line of code is throwing error. 

I think this might have been added due to layout constraints but maintainers can answer it a better way.

However [https://github.com/react-navigation/react-navigation/issues/1728#issuecomment-391525260](https://github.com/react-navigation/react-navigation/issues/1728#issuecomment-391525260) solution can help you out.

**Comment by brentvatne** [comment]
i'm working on making this easier in https://github.com/react-navigation/react-navigation/pull/4588 - with this you will be able to add `headerLayoutPreset: 'center'` or `headerLayoutPreset: 'left'` to a stack navigator config to get the behavior you want. to do this manually with just styles would be too awkward because there are a handful of things that need to change and we can't expect everyone to guess what those might be. keep an eye on that PR or feel free to pull it into your fork now to use it
