### ISSUE TITLE
[flow] Specifying Navigator as child of react-redux Provider causes type error

### ISSUE THREAD

**Issue by flbaue** [react-navigation/react-navigation#4722]
Example project: https://github.com/flbaue/TestProject

I just created a new react native project (0.56) and added react-navigation (2.7.0) and flow libdef `react-navigation_v2.x.x`.
As a result, I get a type error when I try to use the result of `createDrawerNavigator` (or the others).
 
``` bash
yarn flow status
yarn run v1.7.0
$ /Users/.../.../.../App/node_modules/.bin/flow status
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/app.js:18:13

Cannot instantiate React.Element because in type argument ElementType:
 • Either a callable signature is missing in statics of React.Component [1] but exists in
   React.StatelessFunctionalComponent [2].
 • Or a callable signature is missing in withRouter [3] but exists in
   React.StatelessFunctionalComponent [2].
 • Or a callable signature is missing in withOptionalNavigationOptions [4] but exists in
   React.StatelessFunctionalComponent [2].
 • Or React.StatelessFunctionalComponent [1] is incompatible with statics of React.Component [5].
 • Or withRouter [3] is incompatible with statics of React.Component [5].
 • Or withOptionalNavigationOptions [4] is incompatible with statics of React.Component [5].

     src/app.js
      15│ type Props = {}
      16│ export default class App extends Component<Props> {
      17│   render() {
      18│     return <Navigator />
      19│   }
      20│ }
      21│

     flow-typed/npm/react-navigation_v2.x.x.js
 [1] 571│   > = React$ComponentType<{
     572│     ...Props,
     573│     ...NavigationContainerProps<State, Options>
     574│   }> &
 [3] 575│     withRouter<State, Options> &
 [4] 576│     withOptionalNavigationOptions<Options>

     /private/tmp/flow/flowlib_34616c66/react.js
 [2] 160│   | React$StatelessFunctionalComponent<any>
 [5] 161│   | Class<React$Component<any, any>>;



Found 1 error

Only showing the most relevant union/intersection branches.
To see all branches, re-run Flow with --show-all-branches
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After some researching, I replaced the `React$` inside the libdef with `React.` plus `import * as React from "react"`. This is fixing the type error for me.

**Comment by Ashoat** [comment]
@flbaue, can you make a PR for this change on the `flow-typed` repo? If it goes through, we'll update it in this repo as well.

The reason I ask is because I remember that using `import`s in libdefs was discouraged for some reason. I'm not sure that's still the case, but presumably the folks at `flow-typed` will know more, and if you're still not supposed to use `import` they'll probably have a suggestion for a fix.

**Comment by flbaue** [comment]
OK, I will try over there

**Comment by Ashoat** [comment]
Context [here](https://github.com/flow-typed/flow-typed/pull/2522), but it turns out that the proposed solution above only silences the error because it `any`-types all of the React types.

I'm still not clear why `react-redux`'s `Provider` won't take a `NavigationNavigator` as a child. Open to other suggestions to address the issue.

**Comment by Ashoat** [comment]
I am seeing this issue now after updating the libdef for React Navigation 3.0. I'm going to put up a PR with the proposed fix from https://github.com/flow-typed/flow-typed/pull/2522/.
