### ISSUE TITLE
headerTitleStyle & headerBackTitleStyle not set when using push

### ISSUE THREAD

**Issue by AlirezaAkbarix** [react-navigation/react-navigation#4724]
when using `this.props.navigation.push('ScreenB');`, the `headerTitleStyle` and `headerBackTitleStyle` are not set as expected (`actually it does not set any style!`), while the navigator screen has the styles perfectly!

screenA(has style)->`navigate`->screenB(has style)->`push`->screenB(has **not** style)

Environment:
  OS: macOS High Sierra 10.13
  Node: 8.9.4
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4
  react-navigation: 2.3.1 (as 2.7.0 has drawer issue for me)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
