### ISSUE TITLE
static navigationOptions dosen't change title

### ISSUE THREAD

**Issue by if4lcon** [react-navigation/react-navigation#4727]
```   
static navigationOptions = ({ navigation }) => ({
        title: `Hello world`,
        headerRight: (<Icon name="cog" size={20} style={{marginRight: 1}} onPress={() => alert('hi')} />)
    });
```

It doesn't change title or headerRight

| software         | version
| ---------------- | -------
| react-navigation | 2.7.0
| react-native     | 0.52.0
| node             | 8.11.1
| npm or yarn      | 6.0.1

**Comment by brentvatne** [comment]
see: https://reactnavigation.org/docs/en/navigation-options-resolution.html

standard reply for malformed issue below:

<hr />

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
