### ISSUE TITLE
IOS locked drawer showing on back

### ISSUE THREAD

**Issue by kriskate** [react-navigation/react-navigation#4736]
Hey guys,

Given you have 
- a drawerNavigator inside a Stack
- ```drawerLockMode: locked-closed```

When navigating back on **IOS**, via swipe or back button, the drawer is semi-dragged on-screen, just to dissapear when the swipe (or back-button-press) animation ends.

I've created a [snack](https://snack.expo.io/HJIb1gxVX) for you.
This issue might be related to https://github.com/react-navigation/react-navigation/issues/4731, but hopefully it's easier to track it down with this barebones example.

If you have a solution for the following functionality, i'd be much grateful:
- *I want to both have a drawer as well as the ability to swipe-to-back on IOS*

**Comment by brentvatne** [comment]
indeed it is related to https://github.com/react-navigation/react-navigation/issues/4731, the fix is quite easy - someone just needs to implement this: https://github.com/react-native-community/react-native-drawer-layout/issues/50

closing because dup of those two issues but if you submit a pr to fix that on react-native-drawer-layout then let me know at brent@expo.io and i'll bump the dependency
