### ISSUE TITLE
Props Lazy in createMaterialTopTabNavigator not work

### ISSUE THREAD

**Issue by Donhv** [react-navigation/react-navigation#4737]
When I use createMaterialTopTabNavigator, props lazy work well. But now i want use tab with position :'top' so i use createMaterialTopTabNavigator  but props lazy not work.

My Environment: 
react-navigation | ^2.6.2
react-native | ~0.55.4
node |  
npm

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
oh also there is no `lazy` prop for that particular navigator, see this pr https://github.com/react-navigation/react-navigation-tabs/pull/9

**Comment by behiunforgiven** [comment]
I have the same issue, lazy not work

```
const TabStack = createMaterialTopTabNavigator({
  Home: HomeScreen,
  Stores: StoresScreen,
  Profile: ProfileScreen,
  Setting: SettingScreen,
}, {
  lazy: true,
  initialRouteName: 'Home',
  animationEnabled: true,
.....
```

**Comment by Donhv** [comment]
@brentvatne 
this pr done. but  PR is not included in react-navigation yet. :(

**Comment by brentvatne** [comment]
yeah it is in the latest version

**Comment by NasreenUstad** [comment]
[https://stackoverflow.com/a/63849938/942239](https://stackoverflow.com/a/63849938/942239)
