### ISSUE TITLE
Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by killynathan** [react-navigation/react-navigation#4743]
This issue was posted before (#4209), but the only resolution was to downgrade react-native or react-navigation.

### Current Behavior

Attempted to assign to readonly property.
popProvider
    C:\Users\natha\Documents\cs\todo\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:8624:10
unwindWork
    C:\Users\natha\Documents\cs\todo\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:10368:20
completeUnitOfWork
    C:\Users\natha\Documents\cs\todo\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:12288:31
renderRoot
    C:\Users\natha\Documents\cs\todo\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:12450:44
performWorkOnRoot
...

### Expected Behavior

Renders App with a drawer

### How to reproduce

```
const Test = ({ navigation: { navigate } }) => (
  <View>
    <Text>test</Text>
  </View>
)

const Testing = () => (
  <View>
    <Text>testingg</Text>
  </View>
)

const RootNavigator = DrawerNavigator({
  Test: { screen: Test },
  Testing: { screen: Testing },
}, {
  initialRouteName: 'Test',
});

export default class App extends Component<Props> {
  render() {
    return (
      <RootNavigator />
    );
  }
}
```

### Your Environment

"react": "16.3.1",
"react-native": "0.55.0",
"react-navigation": "^2.9.0"

**Comment by brentvatne** [comment]
hi! the code you provided does not reproduce the problem: https://snack.expo.io/BJPUDtQEQ

as i said in the last comment on the issue you referred to, i can't do anything about this because i can't reproduce it, but if you can provide an example where i can run it and get this error i'd be happy to investigate. until then all i can say is it's probably somehow related to your particular project setup

**Comment by agm1984** [comment]
This is occurring on my machine right now. It's blowing up on the same line of code.
```
node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:8624:10
```

I am trying to add `react-navigation` to an existing project with:
```
    "react": "^16.3.0-alpha.3",
    "react-native": "^0.54.2",
    "react-navigation": "^2.11.2",
```

I just added react-navigation and followed the tutorial https://reactnavigation.org/docs/en/hello-react-navigation.html and the app doesn't work.

Here are my files:

./index.js
```
import { AppRegistry } from 'react-native'
import App from './src/App'

AppRegistry.registerComponent('appName', () => App)

```

./src/App.js
```
import { createStackNavigator } from 'react-navigation'
import SignUp from '../components/auth/SignUp'
import Login from '../components/auth/Login'
import LoggedInApp from '../components/LoggedInApp'

export default createStackNavigator({
  // SignUp,
  // Login,
  LoggedInApp,
})
```

If I add an options object onto the `createStackNavigator` and put a bogus key, the error changes to "There is no route defined for key LoggedInAppasdf". If I put the correct key or omit the second parameter object, it throws that `assign to readonly property` error.

If I had to guess, I'd say react-navigation 2.11.2 is relying on something that doesn't exist in React 16.3.0 or RN 0.54.2.

Mine also explodes the same error with this code:
```
import React, { Component } from 'react'
import { createStackNavigator } from 'react-navigation'
import SignUp from '../components/auth/SignUp'
import Login from '../components/auth/Login'
import LoggedInApp from '../components/LoggedInApp'

const RootStack = createStackNavigator({
  // SignUp,
  // Login,
  LoggedInApp,
},
{
  initialRouteName: 'LoggedInApp',
})

class App extends Component {
  render() {
    return <RootStack />
  }
}

export default App
```
I downgraded to react-navigation 2.0.0 and it still does it.

I'm reasonably confident that react-navigation is relying on some data structure that is not possible in the described versions of React and/or React Native. That Expo Snack does not expose React or React Native versions, so I am not confident at all that it is using the correct versions to reproduce. I further suspect that because brentvatne made reference to "the code" and not "those versions of React".

**Comment by agm1984** [comment]
Update:

I upgraded my React Native project, and now react-navigation is working with it's most basic tutorial code.

If anyone encounters this, I recommend `react-native-git-upgrade`. It is a package that you install globally with npm, such as `npm install -g react-native-git-upgrade` and ten you run it from the root of your project.

I was surprised that it worked in mine because I am using some native code modifications, react-native-vector-icons and react-native-linear-gradient. It ran smoothly on mine upgrading from the versions shown at the top of my previous post.

After doing that, there were massive explosions in my project, but they were all due to babel. React Native 0.56 has upgraded to Babel 7, so you need to sort that out.

In mine, I had to basically remove everything babel, and install these packages:
```
"@babel/cli": "^7.0.0-rc.1",
"@babel/core": "^7.0.0-rc.1",
"babel-preset-react-native": "^5.0.2",
```

If you get the wrong package for the RN one, do `npm install --save-dev babel-preset-react-native@5`, notice the @5.

Keep in mind what you are doing is upgrading everything to Babel 7 which exports functions rather than objects, so it's easy to see which modules are failing and which are working. The errors are very clear.

I didn't have to touch ES Lint or `babel-eslint` (for Airbnb config).

Good luck to you.

**Comment by jjd314** [comment]
Thanks, @SnehalAgrawal.  I was experiencing the problem with RN 0.55.0, and upgrading to 0.55.2 solved it for me.  At some point I'll bite the bullet and upgrade to RN 0.56+, but I'm not ready to face the babel hassles yet.

**Comment by developer-ocansey** [comment]
Upgrading to "react-native": "0.55.2", solved the problem.

**Comment by Ahsanwarsi** [comment]
I was using npm primarily in my project & accidentally executed a yarn command. By diving deep, I observed two lock files. Deleting yarn-lock.json did the trick for me.
