### ISSUE TITLE
context is not effect

### ISSUE THREAD

**Issue by iamdurui** [react-navigation/react-navigation#4747]
I use the Higher order components in my code, and I use the context to pass navigation , but I don't get the navigation ,my code is following:
![image](https://user-images.githubusercontent.com/16399401/43069157-00e28d7c-8e9f-11e8-9d1b-81fb09f1af3d.png)
![second](https://user-images.githubusercontent.com/16399401/43069352-6fd254f6-8e9f-11e8-8fc8-984477e05161.jpg)
![third](https://user-images.githubusercontent.com/16399401/43069437-a35e782c-8e9f-11e8-8f73-e1997e9fcade.jpg)
the red line have the value every time ,but the third picture get the navigation is null in the header  , I use the react-navigation 1.x ,it is very ok, and this kind of situation only happen in the header , I didn't find the solution，Hope you'll give me provide some methods，thanks

| software         | version
| react-navigation |  2.6.2
| react-native     |  0.56.0
| node             |    v8.11.3
| npm or yarn      |  5.6.0

**Comment by brentvatne** [comment]
you need to wrap the component in the header with a consumer. header components are rendered in a different subtree than the components in the `render()` function for your component. additionally, the context provider needs to live around the entire navigator, otherwise it won't be an ancestor of the header component and won't be available there.

**Comment by NamSangMi** [comment]
Hello ,https://github.com/facebook/react-native/issues/16546 this issues has you solved?
