### ISSUE TITLE
Opening a screen in an outside stack navigator results in a flash of the initial screen in the stack

### ISSUE THREAD

**Issue by SvetlinStaev** [react-navigation/react-navigation#4766]
### Current Behavior

I have a main tab navigator which carries 5 tabs. In each tab I have placed stack navigators. In one of the stack navigator I am trying to navigate to a screen of the stack in another tab which is not the initial screen of the stack. It navigates fine but it flashes through the initial screen of the stack and then goes to the requested screen thus creating a back button behavior to the initial screen of the stack.

Example:

MainTabNavigator
  - Tab Home with HomeStackNavigator
     - HomeScreen
     - PrivacyPolicyScreen
     - UserAgreementScreen
 - Tab Register with RegistrationStackNavigator
    - RegistrationScreen
  ....

A call from the RegistrationScreen to the UserAgreementScreen goes through the HomeScreen. Back button on the top left brings back the user to the HomeScreen rather than the RegistrationScreen

### Expected Behavior

The screen of the stack should be displayed without a flash of the initial screen of the stack and creating a back button to that initial screen. Since the call is from outside the stack, the back button should not be displayed or be present to bring back to the caller which is in a different stack.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0
| react-native     | 0.5
| node             | 10.6
| npm or yarn      | 1.7

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by SvetlinStaev** [comment]
Understood, sorry about that. I have duplicated the ticket with a github reproducer at https://github.com/react-navigation/react-navigation/issues/4790
