### ISSUE TITLE
Params are not passed from Stack navigator to Stack navigator if they are children of SwitchNavigator

### ISSUE THREAD

**Issue by wzup** [react-navigation/react-navigation#4772]
## The issue tracker is reserved for bug reports only.

this is the bug only
previous same bugs that seem are not fixed yet
https://github.com/react-navigation/react-navigation/issues/143
https://github.com/react-navigation/react-navigation/issues/3787

### Current Behavior

Params are not passed from one screen to another. Screens are initial screens of different Stack navigators.

**Config**
```
SwitchNavigator
    LoadingScreen: Component
    App: StackNavigator
        ProfileScreen
        DashboardScreen
    SignInFlow: StackNavigator
        LoginScreen      // from this screen (and vice versa)
        LikeScreen
    SignUpFlow: StackNavigator
        SignUpScreen    // to this screen (and vice versa)
        TCScreen
```

**Flow**
From `LoginScreen` I try to navigate to `SignUpScreen` AND pass params.
As you can see above, these screens belong to different stacks.
Those stacks are children of `SwitchNavigator`.

**Issue**
Since `react-navigation v1` renders screen twice if I navigate from stack to stack (it is infamous bug of v1), I have to navigate to stack itself, not its particular screen.

```javascript
// params are passed OK, but RN renders screen twice. So it is not an option
this.props.navigation.navigate('LoginScreen', { ...this.state.data }) } 

// RN renders screen once as expected, but params are not being passed
this.props.navigation.navigate('SignInFlow', { ...this.state.data }) } 
```

### Expected Behavior

I get params in initial screen as if I was navigating to it, not to it's parent `Stacknavigator`

### How to reproduce

Same way

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     |0.54.2
| node             |8.11.3
| npm or yarn      |5.6.0

**Comment by brentvatne** [comment]
please see my comment on the issue you linked to:

> please create a new issue and *follow the issue template*, this one is old and before the current maintainers started working on it. i would be happy to look into this if you can do that, thanks!

we need a reproducible example that we can run on https://snack.expo.io. also you're using an old version of react-navigation so of course it wouldn't be fixed :P

**Comment by simonedavico** [comment]
@brentvatne I encountered the same bug and reproduced it in [this Snack](https://snack.expo.io/H1O1ubvSm). Let me know if you need any clarification, meanwhile I'll try to understand why this happens as well :)

**Comment by vsuryanarayanaraju** [comment]
@brentvatne i am also facing same issue.is there any solution for this

**Comment by eriveltonelias** [comment]
How about this https://snack.expo.io/@eriveltonelias/params-switch-to-stack . ?

**Comment by simonedavico** [comment]
I don't think closing this is appropriate, since you didn't find a solution, but a workaround (which won't work in case you can't assume what the initialRoute for the stack is).

**Comment by ccoeder** [comment]
@simonedavico I agree with you. 👍

**Comment by eriveltonelias** [comment]
Hi @simonedavico! 

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please, if the solution I sent doesn't work for you ( setting the `initialRoute`). You can send a PR to fix it, will be awesome :)

**Comment by simonedavico** [comment]
@eriveltonelias I am aware of the amount of reporters vs. maintainers/contributors. I have already contributed more than once to React Navigation myself. 

Nevertheless, I think that the primary use for issues should be to keep track of what works, and what doesn't. As of today, this library has this bug. This is not shameful, it is a complex piece of software and bugs happen. IMHO, the right thing to do is to keep the issue open until the bug is actually solved. 

Providing a workaround and closing the issue means that at some point in the future someone else will come and report the same thing. The rate at which issues get closed is not a metric for success anyway, I don't see why hurry :)

**Comment by eriveltonelias** [comment]
@simonedavico I know that you've contributed to react navigation and really thanks for that. :) But if you have time to submit a PR will be great! and I did not hurry, if you take a time to read all issues, you'll know what I'm talking about. :)

**Comment by ishigamii** [comment]
Got the same issue though didn't see your solution @eriveltonelias 
I found out in my app that if you try to push a view that is not the route of the stack the param is passed nicely, but as soon as it is the `initialRouteName` the param is just missing.

I also found out that trying to push the view to the stack that already has the same view active just show the same view again and by adding a `didFocus` I can see that even if I change the param in my new calling of `push` the params stays unchanged and keep the first value it was assigned. 

```
 this.didFocusSubscription = this.props.navigation.addListener('didFocus', () => {
      const parameters = this.props.navigation.state.params || {};
      console.log('params', parameters);
    });
```

**Comment by amites** [comment]
@eriveltonelias the snack you link to with a workaround is broken -- are there any new references?

**Comment by brentvatne** [comment]
@amites - you might find these discussions interesting:

https://github.com/react-navigation/rfcs/issues/68
https://github.com/react-navigation/rfcs/issues/43

**Comment by amites** [comment]
https://github.com/react-navigation/rfcs/issues/43 is where I found the workaround that actually *worked* thank you @brentvatne
