### ISSUE TITLE
there are some bug about android for mi2.

### ISSUE THREAD

**Issue by chenweigh** [react-navigation/react-navigation#4781]
there are some problem on android device .
 the device is all-screen.
 the error as is:
![screenshot_2018-07-28-17-33-46-910_com cxy61 kids](https://user-images.githubusercontent.com/15101298/43355341-24832182-928d-11e8-8388-28b9a54b75ec.png)

how to fix it ? I need help.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
