### ISSUE TITLE
Can not pass prop from Stacknavigator to DrawerNavigator in react-navigation

### ISSUE THREAD

**Issue by nikasvan** [react-navigation/react-navigation#4784]
### Current Behavior

Trying to pass props from Stacknavigator --> DrawerNavigator --> Tabnavigator deesn't work

### Expected Behavior

To pass props

### How to reproduce

https://stackoverflow.com/questions/51571285/can-not-pass-prop-from-stacknavigator-to-drawernavigator-in-react-navigation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 16.0
| node             | 9.11.1

| npm or yarn      |  npm 6.0.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
