### ISSUE TITLE
TypeError: The "listener" argument must be of type Function. Received type undefined

### ISSUE THREAD

**Issue by wm2zfei** [react-navigation/react-navigation#4805]
App.vue 
`export default createStackNavigator(
  {
    login: Login,
    content: Content,
  },
  {
    initialRouteName: 'login',
    mode: 'modal',
    headerMode: 'none',
    navigationOptions: {
      gesturesEnabled: false
    }
  });`

Content.vue

`import { createStackNavigator } from 'react-navigation';
import AMap from './AMap';
import Case from './Case';
import Setting from './Setting';

export default createStackNavigator(
  {
    map: AMap,
    case: Case,
    setting: Setting,
  },
  {
    initialRouteName: 'map',
    mode: 'card',
    headerMode: 'none',
  });
`

Login.vue 
run : this.props.navigation.navigate("login");
then :
 `TypeError: The "listener" argument must be of type Function. Received type undefined

This error is located at:
    in AMap (at SceneView.js:9)
    in Provider (at SceneView.js:8)
    in SceneView (at StackViewLayout.js:516)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:554)
    in RCTView (at View.js:71)
    in View (at StackViewLayout.js:462)
    in RCTView (at View.js:71)
    in View (at StackViewLayout.js:461)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in RCTView (at View.js:71)
    in View (at Transitioner.js:169)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:57).....`

software | version
-- | --
react-navigation | 1.10.0
react-native | 0.56.0
node | 10.5.0
npm or yarn

**Comment by eriveltonelias** [comment]
Hi @wm2zfei, 

Please post your code on https://snack.expo.io/  and then we can help you.

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
