### ISSUE TITLE
react-navigation 莫名其妙的报这个警告！

### ISSUE THREAD

**Issue by heshan-song** [react-navigation/react-navigation#4806]
<img width="363" alt="wx20180803-115056 2x" src="https://user-images.githubusercontent.com/22375125/43630061-b8691584-9731-11e8-8256-00b7f821c553.png">

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
