### ISSUE TITLE
Custom Transition giving error : Cannot call a class as a function

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-navigation/react-navigation#4812]
import React, { Component } from 'react'
import { Text, View, Image} from 'react-native';
import {createStackNavigator, createBottomTabNavigator,StackRouter, createNavigator, createNavigationContainer} from 'react-navigation'
import Ionicons from 'react-native-vector-icons/Ionicons';
import FontAwesome from 'react-native-vector-icons/FontAwesome';
import Intro from './screens/Intro'
import Home from './screens/Home'
import Home2 from './screens/Home2'
import Home3 from './screens/Home3'

const RouteConfigs = {
  Intro: {screen: Intro},
  Home: {screen: Home},
  Home2: {screen: Home2},
  Home3: {screen: Home3},
}

const StackNavigatorConfig = {
    headerMode: 'none',
    initialRouteName: 'Intro'
}

const Nav = StackRouter(RouteConfigs, StackNavigatorConfig)

class BubbleTransition extends React.Component {
  render () {
    return (<View style={{flex: 1}}>
    </View>)
  }
}

const Navigator = createNavigationContainer(createNavigator(Nav)(BubbleTransition))

export default class AppWithNavigationState extends Component {
  render () {
    return (
      <View style={{flex: 1}}>
        <Navigator/>
      </View>
    )
  }

The above code is giving error : Cannot call a class as a function

**Comment by eriveltonelias** [comment]
Hi @abhitheawesomecoder Can you reproduce this issue on https://snack.expo.io/ ? 
will be better for help you.

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

**Comment by yangsamuellu** [comment]
I meet this bug too.  Please help us, thanks.
My repository address:    https://github.com/samuelltk/RnDemo

@vonovak @eriveltonelias

**Comment by Ketn** [comment]
There were some breaking changes in react-navigation 2.x from 1.x.

Your code and the tutorial you followed is from react-navigation@1.4.x. You need to make appropriate changes as per the updated documentation: https://reactnavigation.org/docs/en/getting-started.html
