### ISSUE TITLE
createMaterialTopTabNavigator---BUG

### ISSUE THREAD

**Issue by qq329401134** [react-navigation/react-navigation#4818]
const TopTabNavigator = createMaterialTopTabNavigator (
  {
    社会: shehui,
    关注: guanhzu,
  },
  {
//    swipeEnabled: false,
//    animationEnabled: false,
    activeTintColor: '#f0edf6',
    inactiveTintColor: '#3e2465',
    barStyle: {
      backgroundColor: '#694fad',
    },
    tabBarOptions: {
      scrollEnabled: true,
      allowFontScaling: true,
    },
  }
);

const BottomTabNavigator = createBottomTabNavigator ({
  首页: TopTabNavigator,
  我的: UserInof,
});

export default createDrawerNavigator ({
  首页: BottomTabNavigator,
  我的: UserInof,
});

在BottomTabNavigator 中切换首页到我的，然后再切到首页，TopTabNavigator 的两个tab点击无效果，不会切换页面，当把 swipeEnabled: false和animationEnabled: false,以后可以恢复正常，但是没有了滑动切换的效果了，希望能有解决方案

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
