### ISSUE TITLE
BackHandler subscriber doesn't invoke after changing app state

### ISSUE THREAD

**Issue by denis-shostik** [react-navigation/react-navigation#4827]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4
```

## Description
My code https://pastebin.com/s0kZn4Rk
When I press home button, and then open app again, back button isn't listening, and pressing to back button doesn't invoke my handleBackButtonClick method.

## Reproducible Demo
To reproduce the error all one needs to do is try the request above.

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

**Comment by beisert1** [comment]
We are experiencing the same issue, does anyone have a solution?

**Comment by vonovak** [comment]
@beisert1 please open a new issue with a repro, thanks.
