### ISSUE TITLE
The unmount sequence should be reverse in StackNavigator.

### ISSUE THREAD

**Issue by PMExtra** [react-navigation/react-navigation#4837]
https://snack.expo.io/Bk5mLT9SQ

HomeScreen 
-> Navigate to FirstScreen
---> Navigate to SecondScreen
-----> Navigate to ThirdScreen
-------> StackActions.PopToTop()

Then we will see the log:
```
The fisrt screen will unmount.
The second screen will unmount.
The third screen will unmount.
```

But I expect sequence is reverse —— Unmount the ThirdScreen, then SecondScreen, unmount the FirstScreen at last. (Just like pop the stack one by one)

Now this unexpected behavior bothers me, I want to dispose some resources when unmount but they are sensitive to sequence.

So do you think about reverse the unmount sequence? Or give me some other advices?

**Comment by vonovak** [comment]
Thanks for reporting @PMExtra! Can you share a little more information about how your resources work / why they are unmount-sequence-sensitive? I'm just wondering what the use case is. I totally see your point about the expected order of unmounting, but I also think one may argue that the unmount sequence is an implementation detail - that's why I'm asking for your use case. Thanks!

**Comment by PMExtra** [comment]
I used mobx-state-tree, and I have a ListScreen and a DetailScreen.
ListScreen have a store that contains `data: types.array(Model)`, DetailScreen have a store that contains `data: types.reference(Model) // selected in ListScreen`. And I have to reset the store when unmount the screen, to prevent seeing the old data when next entered.
For now, if I `popToTop` from DetailScreen, ListScreen will be unmounted before DetailScreen. And then the DetailStore will be broken because of the reference.

**Comment by PMExtra** [comment]
I think the implementation should doing what like its name: `popToTop`, It means popping up one by one until the last of the stack.

**Comment by brentvatne** [comment]
moving to the stack repo. I think this makes sense but I don't have any plans to work on it. you'd need to look in the Transitioner and StackViewLayout. i suspect that all screens are removed at the same time and it's React that determines the order that componentWillUnmount fires in this case - see https://snack.expo.io/@notbrent/quiet-watermelon. i'm not sure that you'd want to change this behavior that is otherwise what you would expect in react.
