### ISSUE TITLE
Change navigationOptions/headerStyle(backgroundColor) on scroll

### ISSUE THREAD

**Issue by sani723** [react-navigation/react-navigation#4838]
Hi guys,  I am setting header style in  navigationOptions

static navigationOptions = ({ navigation, state }) => ({
        title: "Explore",headerStyle: {
            backgroundColor: state ? state.params.bgColor : 'transparent'
        },
        headerTintColor: '#fff'
    }) ;

Then on onScroll of View I am setting params bgColor to new value but its not updating the headerStyle.

const {setParams} = this.props.navigation;
        if(nativeEvent.contentOffset.y > 20) {

            setParams({ bgColor: "#fff" })
         }
---

### Current Behavior

It is not changing jeaderStle background color

### Expected Behavior

After setting params `bgColor` it should update backgroundColor of header

### How to reproduce

class Home extends React.Component {

    static navigationOptions = ({ navigation, state }) => ({
        title: "Explore",
        drawerLabel: "Home",
        headerLeft: <Icon style={{paddingLeft: 27, backgroundColor: '#f00'}} name="ios-menu" size={30} color="#fff" onPress={ () => navigation.openDrawer() } />,
        headerRight: <Icon style={{paddingRight: 27}} name="md-person" color="#fff" size={30} onPress={ () => navigation.navigate("Login") } />,
        headerStyle: {
            backgroundColor: state ? state.params.bgColor : 'transparent'
        },
        headerTintColor: '#fff'
    })

    _handleScroll = ({nativeEvent}) => {
        const {setParams} = this.props.navigation;
        if(nativeEvent.contentOffset.y > 20) {
            setParams({ bgColor: "#fff" })
         } else {
            setParams({bgColor: 'transparent'});
        } 
    }

    render() {
        const {navigation} = this.props;
        return (
            <Container style={{backgroundColor: '#444', position: "absolute", top: -62, left: 0, right: 0, bottom: 0}}>
                <Content onScroll = { (event) => this._handleScroll(event) }>
                    <View style={StyleSheet.container}>
                        <Text>Home page</Text>
                    </View>
                    <View style={{height: 600}}>
                        <Text>Campaigns {navigation.getParam('bgColor', '#f00')}</Text>
                    </View>
                </Content>
            </Container>
            
        );
    }
}

export default Home;

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.11.2
| react-native     | 0.56.0
| node             | 8.9.4
| npm or yarn      | 5.6.0

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

**Comment by mohanlar96** [comment]
Same Issue here .

**Comment by dev-neeraj** [comment]
same issue here
