### ISSUE TITLE
createBottomTabNavigator not work correctly on iOS 6 - 11.2 and react-navigation 2.1.2

### ISSUE THREAD

**Issue by kimthangatm** [react-navigation/react-navigation#4843]
I follow the document from https://reactnavigation.org/docs/en/tab-based-navigation.html
Android worked but on iOS: When I click Home, the content display the content of Settings screen, and when I click Settings, the content display the content of Home screen.

Emulator: iOS 6 - 11.2
react-navigation 2.1.2
xCode: Version 9.2 (9C40b)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
