### ISSUE TITLE
Requiring unknown module "717",If you are sure the module is there try restarting Metro Bundler

### ISSUE THREAD

**Issue by RideShi** [react-navigation/react-navigation#4849]
![simulator screen shot - iphone x - 2018-08-13 at 17 38 55](https://user-images.githubusercontent.com/15190511/44024839-06e61d5a-9f21-11e8-995b-89f96dfcc822.png)

**Comment by RideShi** [comment]
请问这个怎么解决呢，不太懂什么原因呢，add之后运行报的错误

**Comment by eriveltonelias** [comment]
Hi @RideShi! 
 looks like this problem isn't related with react-navigation.

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
