### ISSUE TITLE
react navigation goBack animation show error

### ISSUE THREAD

**Issue by oneroundseven** [react-navigation/react-navigation#4862]
## The issue tracker is reserved for bug reports only.

- Create a navigation using createStackNavigator and createBottomTabNavigator
- createBottomTabNavigator => header: null
- When you navigate from StackNavigator to TabNavigator, StackNavigator's default headerStyle will disappear during the process of clicking goBack, while using the side-sliding goBack function is normal.
- check the source code Header.js 574 lines safeHeaderStyle will automatically be set to empty {} Object during the execution of the animation goBack

---

### Current Behavior

- Excessive animation exception
![image](http://thyrsi.com/t6/357/1534410589x-1566687389.gif)

[http://thyrsi.com/t6/357/1534410589x-1566687389.gif](url)

### Expected Behavior

- Header header=null should not be placed before the over-animation does not disappear the header style

### How to reproduce

```
const MainTab = createBottomTabNavigator(
    {
        Home: {
            screen: HomeStack,
            navigationOptions: {
                tabBarLabel: 'Home',
            },
        },
        Categories: {
            screen: CategoriesScreen,
            navigationOptions: {
                tabBarLabel: 'Categories',
            },
        },
        Cart: {
            screen: CartStack,
            navigationOptions: {
                tabBarLabel: 'Cart',
            },
        },
        Account: {
            screen: AccountScreen,
            navigationOptions: {
                tabBarLabel: 'Account',
            },
        },
    }
);
let StackNav = createStackNavigator(
        {
            MainTab: {
                screen: MainTab,
                navigationOptions: {
                    header: null,
                    headerStyle: {
                        backgroundColor: 'red'
                    }
                },
            },
            sample: {
                screen: sample,
                navigationOptions: {
                    headerStyle: {
                        backgroundColor: 'green'
                    }
                }
            },
    })
```

Ps: If the default headerStyle.backgroundColor of the MainTab is set, the default backgroundColor of the sample will turn red during the end of the sample execution of the goBack animation.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     |  0.55.4
| node             |  8.9.1
| npm or yarn      |  6.3.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug. additionally, *you should try this against the latest version of react-navigation as it's probably already been resolved!*

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by oneroundseven** [comment]
@brentvatne  please reopen this issues

https://snack.expo.io/@roundseven/blessed-chips

i add the example 
you can see the issues description question

**Comment by oblank** [comment]
same error before.
update your react-navigation to latest, it  has be fixed
