### ISSUE TITLE
when  jump to Login then Dismiss automatically. when call  delay or network in   componentDidMount 

### ISSUE THREAD

**Issue by kaixiniOSTT** [react-navigation/react-navigation#4876]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/40654700/44383292-ddac0000-a54a-11e8-8955-5d914b7a6609.png">

if click some Button , every thing is ok 
if call in componentDidMount, you must delay more than 1 second to Jump to Login Page, otherwise
when jump to Login Page, automatically Unmounted the Login Page

**Comment by brentvatne** [comment]
hello kind traveler! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
