### ISSUE TITLE
getParam returning undefined when navigating to a stack instead of a stack screen

### ISSUE THREAD

**Issue by zedtux** [react-navigation/react-navigation#4877]
### Current Behavior

Given a stack :

```javascript
  // ...
  Debug: createStackNavigator({
    AppInfoView: AppInfoScreen,
    DebugZone: DebugScreen,
    Navigator: NavigatorScreen,
    RNConfig: RNConfigScreen,
    SensitiveInfoExplorer: SensitiveInfoExplorerScreen
  }, {
    initialRouteName: 'DebugZone'
  }),
  // ...
```

When navigating to `Debug` passing the params `{ backTo: 'Home' }`, `this.props.navigation.getParam('backTo')` will return `undefined` because we went to the `Debug` stack, which didn't forwarded the params, and then we navigated to the `DebugZone`.

Navigating to `DebugZone` instead of `Debug` makes `this.props.navigation.getParam('backTo')` to return the right value.

### Expected Behavior

Navigating to a stack should forward the given params.

### How to reproduce

It is explained in `Current Behavior`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1 |
| react-native     | 0.55.4 |
| node             | ?? |
| npm or yarn      | yarn |

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by zedtux** [comment]
Thank you @brentvatne for you automatic response, I'll see when I can do an example repo ... even if the reported issue looks really easy to reproduce (I really understand your point of view to get reproducing example, but here, come on ... 😄).

At least, this issue could help some people if they are lucking to find it ...

**Comment by ejferg-rylabs** [comment]
Yup, having the same problem.

**Comment by delavago** [comment]
same issue

**Comment by santanapaulo** [comment]
same issue

**Comment by brentvatne** [comment]
`this.props.navigation.dangerouslyGetParent().getParam(/* your stuff here */)`

why? because the param is provided to the stack route, not a specific route on the stack. if you want it to be available to a specific route on the stack without getting the parent navigation then navigate to it directly
