### ISSUE TITLE
uriPrefix for Universal Links

### ISSUE THREAD

**Issue by albinekb** [react-navigation/react-navigation#4887]
### Current Behavior

Setting uriPrefix to `myapp://` works, but when implementing Universal Links, this needs to be the website URL too.

### Expected Behavior

I can handle both Deep links `myapp://page` and Universal Links `https://myapp.com/page`, either by:

Setting multiple uriPrefix, `myapp://` and `https://myapp.com/` to handle both myapp://page and https://myapp.com/page in my app.

Providing a function to clean the URI manually, then I could do it dynamically depending on how the link looks.

### How to reproduce

Create an app with universal links, set uriPrefix to myapp://, then try to open https://myapp.com/page, app will open but not on the correct page.

to fix, change uriPrefix to `https://myapp.com/`, but then links like `myapp://`
 will not work.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest
| node             | 10
| npm or yarn      | 1.9.4

**Comment by albinekb** [comment]
After looking trough the code, I saw that this prop is used with `.split`, which also takes RegExp. this means a workaround is specifying uriPrefix as regex: `/https:\/\/myapp.com\/|myapp:\/\/myapp\/|myapp:\/\//` will work. Is this the suggested way to handle this?

**Comment by ericvicenti** [comment]
Oh interesting! Maybe we should make uriPrefix accept an array of valid prefixes, that will be matched in order? I think that would be a good contribution, if you want to take a shot at it.

**Comment by albinekb** [comment]
Sure! That sounds like a better approach rather than using the regex. I will try to create a PR.

**Comment by jangerhofer** [comment]
> `/https:\/\/myapp.com\/|myapp:\/\/myapp\/|myapp:\/\//` will work

Clever hack-around!! @albinekb: have you begun your PR? 

If not, I'll likely pick this up.  If so, let me know if I can be useful.

**Comment by petrogad** [comment]
Was this something you ever successfully implemented?

I was just looking at doing this and hit an issue when deep linking into an un-auth section while being auth'd.  I had custom handled linking then attempted to manually fire dispatch actions on my own.. however as you can imagine; it didn't handle well.

**Comment by albinekb** [comment]
@jangerhofer Sorry, I've been busy 😃 Haven't had time to look at this. If you want to do it go ahead, I will probably have time in some weeks to do it otherwise.

The regex workaround works well for now so it's not a blocker.

**Comment by albinekb** [comment]
Yes @kashishgrover the regex variant works well. I have had it deployed since I opened this issue without problems.

**Comment by DISKONEKTeD** [comment]
Strange, when I attempt this, it doesn't work for me, the regex that is. Is this for react-navigation 2 or 3? I tried it in 2.18.2 and it doesn't seem to work, aside from just opening the app (trying to open it with other paths).

**Comment by niteshgrg** [comment]
For universal link this would look more like /https:\/\/www.myapp.com\/|myapp:\/\/myapp\/|myapp:\/\//

difference of www, right ?
For me it doesn't work with above anything i am missing ?

**Comment by DISKONEKTeD** [comment]
> For universal link this would look more like /https://www.myapp.com/|myapp://myapp/|myapp:///
> 
> difference of www, right ?
> For me it doesn't work with above anything i am missing ?

this is what i use, with and without www:

`const PREFIX = /https:\/\/www.myapp.com\/|https:\/\/myapp.com\/|myapp:\/\/myapp\/|myapp:\/\//;`

**Comment by kashishgrover** [comment]
yep, same in our use case. Works like a charm now. We went to prod with just a few minutes ago. :)

`const uriPrefix = /https?:\/\/treebo.com|https?:\/\/www.treebo.com|treebo.com|treebo:\//;`

**Comment by Ury18** [comment]
Hi! I'm trying to do this in expo. 

I've used the regex adapting it to my domain: `/https:\/\/click-clock.com\/|click-clock:\/\/click-clock\/|click-clock:\/\//`

The thing is it is not working, do I have to do something on the app.json for it to work? 

```json

"android": {
      "package": "com.whads.clickclcock"
    },
    "scheme": "click-clock"
  }
```

**Comment by leesolway** [comment]
Any luck with this in expo?

**Comment by quachsimon** [comment]
Are there any updates to this? We are adding universal links to our app and the links open up the app but, do not navigate to the correct path. We had set URL schemes prior and that is still working fine.

**Comment by winzazx** [comment]
> Are there any updates to this? We are adding universal links to our app and the links open up the app but, do not navigate to the correct path (does not navigate at all). We had set URL schemes prior and that is still working fine.

Same here,universal links open up the app but, do not navigate at all :(

**Comment by DISKONEKTeD** [comment]
So what exactly have you guys done? It's hard to say.

I have universal links working (if i recall that is ios related yes? mine)

my app works with https://www.myapp.com or myapp:// etc

I can't recall the specifics so i'm just gonna point out everywhere relevant:

```
const Layout = createAppContainer(Switch);
const PREFIX = /https:\/\/www.myapp.com\/|https:\/\/myapp.com\/|myapp:\/\/myapp\/|myapp:\/\//;

import { createAppContainer } from 'react-navigation';

    <Layout
       ref={(navigatorRef) => {
       NavigationService.setTopLevelNavigator(navigatorRef);
       }}
       uriPrefix={PREFIX}
       enableURLHandling={false}
     />
```

then in a stack file i have this:


```
    Post: {
      screen: Post,
      path: 'p/:uri',
      navigationOptions: ({ navigation }) => ({
        headerTitle: 'Post',
      }),
    },
```

so this would route to https://myapp.com/p/myRandomUriLOL

anything prior to that i have, something like this, so say this is from a drawer navigator in which i place my stack screen in (aka the navigator where my post screen lives):
```
 {
    Option1: {
      screen: MainStackNav,
      path: '',
    },
  },
```

making sure path is set to: **''** in order to pass through/ignore the drawer navigator area/screen section

I have this somewhere in my android manifest file:
```

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:exported="true"
        >
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" android:host="www.myapp.com" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" android:host="myapp.com" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="myapp" />
        </intent-filter>
      </activity>
```

For ios:

Under the info tab in xcode, i ahve two URL Types ([more info see "Register Your URL Scheme"](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app)): 

Identifier: myapp URL schemes: myapp
Identifier: https URL schemes: https

What else. I have, under capabilities in xcode:

Associated domains: applinks:myapp.com

and i have the apple-app-site-association file hosted at: myapp.com/apple-app-site-association

more info here: https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

but basically i have in the file:

```
{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "dfaFD43544fsd.com.myapp",
        "paths": [
          "/p/*"
        ]
      }
    ]
  }
} 
```

I also have this helping me handle when notifications come in (as it would navigate the application without being tapped, automatically, this prevents it, if you are using notificaitons): https://github.com/react-navigation/react-navigation/issues/5504

And i'm using onesignal, and I think one of the tricky bits that i found out was that it was either android or ios that didn't open using https://myapp.com. So what I resorted to using was for the url field:

`'url': myapp://p/randomURILOL`

when a user tapped on a notification etc

I think that's most of it, unless I'm overlooking something

**Comment by quachsimon** [comment]
After some digging, I found that we have to add in this for **universal links** to work. I don't remember where it was from but, it was from an older issue a while back that someone commented.

It may be a good idea to have the docs updated to include this for universal links instead of url schemes. 

```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
```

**Comment by DISKONEKTeD** [comment]
I knew there was something I had overlooked :) Yeah there is a lot to cover when working with deep links, it's hard to say when there are various things to account for.

But it is noted in the documentation: https://reactnavigation.org/docs/en/deep-linking.html#ios-1

**Comment by devtanc** [comment]
@ericvicenti I created the above https://github.com/react-navigation/core/pull/66, trying my best to follow the contribution guidelines. It should add support for an array being passed in for `uriPrefix`. I just haven't been sure where to request a review for it.

**Comment by jordangrant** [comment]
thanks guys love you all

**Comment by neemssoni** [comment]
@DISKONEKTeD ,  **apple-app-site-association file** is must?
