### ISSUE TITLE
React native app crashing in production mode 

### ISSUE THREAD

**Issue by arshidkv12** [react-navigation/react-navigation#4889]
### Current Behavior

App crashing in production mode

 

### How to reproduce

DrawerNavigator is not working but StackNavigator is working.
 

React Native Environment Info:
    System:
      OS: Linux 4.13 Ubuntu 16.04.4 LTS (Xenial Xerus)
      CPU: x64 Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz
      Memory: 511.93 MB / 9.60 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/bin/node
      npm: 6.2.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

##code 
````
const Drawer = DrawerNavigator(
  {
    Home: { screen: HomeScreen },
    GolfList: { screen: GolfList },
    Login: { screen: Login },
    Profile: { screen: Profile },
  },
  {
    contentComponent: props => <SideBar style={{paddingLeft:0,  margingLeft:0}} {...props} />
  }  
);

const AppNavigator = StackNavigator({
  Drawer: { screen: Drawer },
  Register: { screen: Register },
},
{
  initialRouteName: "Drawer",
  headerMode: "none"
});

export default () =>
  <Root>
    <AppNavigator />
  </Root>;`
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
