### ISSUE TITLE
Header does not Hide

### ISSUE THREAD

**Issue by firashamila33** [react-navigation/react-navigation#4891]
##  Description 
I am cuurently using the  createStackNavigator to create an Ath flow
The problem is that even when I disable the header , a gray transparent header is always appearing 

---

### Current Behavior
yes the header is hided but **left behind a transparent grey header**
![40006389_289277435208168_7194192605893099520_n](https://user-images.githubusercontent.com/25459498/44547271-704acb80-a712-11e8-87cd-b3bd353b3370.png)

### Expected Behavior

 the header is hided 

### How to reproduce
I tried to reproduce this but couldn't , I have not using redux neither Mobx or any library in top of react-navigation 
Here My navigator file 
```
import React from 'react'
import {
    createStackNavigator,
} from 'react-navigation'
import AuthScreen from '../screens/AuthScreen'
import RegisterScreen from '../screens/RegisterScreen'

export default class App extends React.Component {
    render() {
        const MainNavigator = createStackNavigator(
          {
            auth: { screen: AuthScreen },
            register: { screen: RegisterScreen },
          },
          {
            navigationOptions: {
              header: null,
            },
          }
        )
        return (
            <MainNavigator />
        )
      }
}
```

###  Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.3
| react-native     | 0.56.0
| node             | 8.11.3
| npm or yarn      | 6.2.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by elanpang** [comment]
I also met this issue on RN 0.56（0.55.4 works）
set headerStyle={} and header=null in the page works for me
