### ISSUE TITLE
initialRouteName always mounted in StackNavigator?

### ISSUE THREAD

**Issue by vendramini** [react-navigation/react-navigation#4892]
I do have a `DrawerNavigator` which every item is a `StackNavigator`.

StackNavA: some screens...
StackNavB: some screens...
etc...

When I go from `StackNavB` to some screen on `StackNavA` the index screen is always mounted.

Is this expected? If so, why? How to avoid?

```javascript
"react-navigation": "^2.11.2",
"react": "^16.3.1",
"react-native": "^0.55.4",
```

**Comment by brentvatne** [comment]
I have no idea why it was implemented like this, presumably it is expected behavior for drawers, but I think it's not very good. Unfortunately we can't change t without it being a breaking change until v3. You can fork react-navigation-drawer and change it if you like, code is here: https://github.com/react-navigation/react-navigation-drawer/blob/f914ffe92c4813c565ee886bab00ec4a2254a7fc/src/views/DrawerSidebar.js#L46-L68

**Comment by vendramini** [comment]
For those who came here with the same problem:
```javascript
this.props.navigation.dispatch(
            NavigationActions.navigate(
                {
                    routeName: 'Order', //the name of the stack navigator inside drawer
                    action: StackActions.reset(
                        {
                            index: 0,
                            actions: [
                                NavigationActions.navigate(
                                    {
                                        routeName: 'OrderWithdraw', //the only screen that you wanted to be mounted
                                    }
                                )
                            ]
                        }
                    )
                }
            )
        );
```
