### ISSUE TITLE
this.navigation.push is not function

### ISSUE THREAD

**Issue by anehkumar** [react-navigation/react-navigation#4900]
I have a navigation drawer which has a dynamic list of category when we click on any category it will open category screen with the specific id, Now when first time i click on category it will load data but for next time it will not load data or not make any change and if i use push method of react navigation it will give me error

`this.props.navigation.push('Category', {query: id})`
It give me push is not function and when i use

`this.props.navigation.navigate('Category', {query: id})`
Screen data is not update can you please help me how to fix this I am using react navigation

**Comment by eriveltonelias** [comment]
Hi @anehkumar 

Can you reproduce a minimal example on https://snack.expo.io ? 

Follow issue template please.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by anehkumar** [comment]
Hi, Thanks for your reply please check 
https://github.com/anehkumar/NavigationCategorySample

And help me to do this.

Thanks.
