### ISSUE TITLE
How any way to sync data when update redux and navigate

### ISSUE THREAD

**Issue by ducvu91** [react-navigation/react-navigation#4931]
### Current Behavior
- I have Screen A & B
- In screen A have action when submit will to save data to redux and navigate to B.
- Screen B get data from screen A update to redux and display.
- But Screen B sometimes get data is null, i think when save data to redux and navigate not sync
- when i setTimeout 1s, it run good ~80% but when i set time 2s and it work perfect.
=> i spend 2s for one submit save and navigate, if i have many screen it loss of time for users
- i try use promise and wait but it not usefull
### How to reproduce
// action redux to update
export function updateInfoRegistration(data, callback) {
    return (dispatch) => {
        dispatch({type: t.UPDATE_INFO_REGISTRATION, data: data });
        callback();
    }
}

in screen A 
// not good
this.props.updateInfoRegistration(infoBookportSuccess, () => {
                this._loading(false);// hide loading
                    NavigationService.navigate('CustomerInfo'); // navigate 
 });
// is good with my
this.props.updateInfoRegistration(infoBookportSuccess, () => {
                setTimeout(() => {
                    this._loading(false);
                    NavigationService.navigate('CustomerInfo');
                }, 2000);

            });
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.6.1
| react-native     | 0.55.4
| node             | v10.8.0
| npm or yarn      | 6.2.0

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
