### ISSUE TITLE
Deep linking not working using switch navigator or nested navigators

### ISSUE THREAD

**Issue by Tatvanish** [react-navigation/react-navigation#4993]
const UnauthorizedScreenNavigator = createStackNavigator(
  {
    LingueeView: {
      screen: LingueeViewContainer
    },
    UserManagementLoginView: {
      screen: UserManagementLoginViewContainer
    },
    SignUpView: {
      screen: SignUpViewContainer
    },
    SignInView: {
      screen: SignInViewContainer     
    }
  },
  {
    headerMode: "screen",
    initialRouteName:"LingueeView"
  }
);
 const MainScreenAuthorizedNavigator = createBottomTabNavigator(
  {
    HomePageView: {
      screen: HomePageViewNavigator
    },
    YourAdsView: {
      screen: YourAdsViewNavigator,
      path: 'yourads'
    },
    ProfileManagementView: {
      screen: ProfileManagementViewNavigator
    }
  },
  {
    initialRouteName: "HomePageView"   
  }
);
const AppNavigator = createSwitchNavigator(
  {
    UnauthorizedScreen: { screen: UnauthorizedScreenNavigator, navigationOptions: { header: null } },
    MainScreenAuthorized: {
      screen: () => (<MainScreenAuthorizedNavigator uriPrefix={prefix} />),
      navigationOptions: { header: null }
    }
  },
  {
    headerMode: "screen",
    initialRouteName: "UnauthorizedScreen"    
  }
);
when i logout, path broken and switch navigator not working and also used with nested navigators, it breaks the path with swtich navigator, and error given with nested navigator "there is no route defined for key"

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
