### ISSUE TITLE
I've tried all the options and I've noticed that the react library in my package.json is @16.3.2 and I've rolled it back to @16.2.0 which is required by react-native and miraculously it started working. Any idea I've missed something from the documentation? Please let me know

### ISSUE THREAD

**Issue by xutm** [react-navigation/react-navigation#5018]
_Originally posted by @karthikpala in https://github.com/react-navigation/react-navigation/issues/4570#issuecomment-399928481_

**Comment by xutm** [comment]
### ENV
- react-native 0.50.4
- react-navigation 0.2.16
- react 16.4.1
### QUESTION
Have a similar problem# [4570 (comment)](https://github.com/react-navigation/react-navigation/issues/4570#issuecomment-399928481)

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

The problem likely is that you're using react 16.4.1 with react-native 0.50.4 - you cannot mix and match the versions! Use version of React which shipped with with react-native 0.50.4. Thanks.
