### ISSUE TITLE
Cannot define a background color on a SwitchNavigator

### ISSUE THREAD

**Issue by jakallergis** [react-navigation/react-navigation#5019]
I was wondering if it is possible to add a background color to a switch navigator just like you do when you create a Stack Navigator.
The SwitchNavigator comes with a black background so if i want to define a background that should be applied application wide, I will have to add a backgroundColor to every screen in the SwitchNavigator.

### How to reproduce

- Create a Switch Navigator and try to define a backgroundColor just like you do when you use the CardStyle prop in a StackNavigator configuration.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.55.4
| node             | 8.9.1
| npm or yarn      | yarn 1.7 , npm 5.5.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
