### ISSUE TITLE
Replace dispatch using StackActions does do nothing

### ISSUE THREAD

**Issue by iagorm** [react-navigation/react-navigation#5022]
The replace dispatch does not replace a desired screen with any custom one, the only replace that works is that with this.props.navigation.

```JS
    componentDidMount() {
        const { navigation } = this.props;

        const replaceAction = StackActions.replace({
            key: 'ScreenA',
            newKey: 'ScreenB',
            routeName: 'ScreenB'
        });

        navigation.dispatch(replaceAction);
    }

```

section related: https://reactnavigation.org/docs/en/stack-actions.html#replace

---

### Current Behavior

- It doesn't replace the screen

### Expected Behavior

- If I add a key with ScreenA and newKey with ScreenB, it should replace the screenA with ScreenB

### How to reproduce

- On a screen add the a StackActions.replace with key of ```ScreenA``` and newKey with ```ScreenB```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.13.0(latest)
| react-native     | 55.4
| node             | 8.11.3
| npm or yarn      | 1.9.4(yarn)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
