### ISSUE TITLE
Can't jump back two screens from nested navigator

### ISSUE THREAD

**Issue by facuescobar** [react-navigation/react-navigation#5026]
### Current Behavior

Structure
```
-- AppNavigator (stack-navigator)
  -- navigatorOne (stack-navigator)
    -- screenOne
    -- screenTwo
    -- screenThree
  -- navigatorTwo (stack-navigator)
    -- screenFour
    -- screenFive
```

**Screen Flow 1:**
From screenOne, I can navigate to:

`screenOne --> navigate --> screenTwo --> navigate --> screenThree`

and then from screenThree, I can navigate back directly to screenOne using screenTwo key (received in navigation params)

`screenThree --> navigation.dispatch(NavigationActions.back({key: screenTwoKey })) --> screenOne`

**Screen Flow 2:**
From screenOne, I can navigate to navigatorTwo screens:

`screenOne --> navigate --> screenFour --> navigate --> screenFive`

but, I have two problems here:

- screenFour does not show a "back button"
- once I navigate to screenFive, I'm not able to navigate back to screenOne using the previous screen key, in this case: screenFour key.

### Expected Behavior

- For nested navigators screens, they should be able to show a **Back Button** if they were called from another screen from another navigator.
- We should be able to jump back to previous screens even when we are trying to return to an screen from another navigator.

### How to reproduce

https://snack.expo.io/@facuescobar/navigateback-issue

### Your Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.11.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by dandax** [comment]
Sound like this is related to #88. Still no solution

**Comment by brentvatne** [comment]
> For nested navigators screens, they should be able to show a Back Button if they were called from another screen from another navigator.

I think the behavior you expect here is not what we actually want. They are part of separate stacks and the back button should not be visible. If you disagree please open a RFC https://github.com/react-navigation/rfcs/issues

> once I navigate to screenFive, I'm not able to navigate back to screenOne using the previous screen key, in this case: screenFour key.

this is just how goBack works, when you provide a key it looks for the route matching that key in the current stack state then goes to that screen index - 1. see: https://github.com/react-navigation/react-navigation-core/blob/a06f602b7170adf8918c78d0c068c180b4074405/src/routers/StackRouter.js#L492-L515

i agree we should improve ergonomics of the back action as it can be a little confusing sometimes. i'd recommend just passing around the routename&key of the route you want to go back to, then using navigate. here i just changed your example to use navigate rather than goBack (but didn't bother passing around routename/key) and it works fine: https://snack.expo.io/@notbrent/navigateback-issue
