### ISSUE TITLE
Pass screenProps width to tabBarOptions scrollEnabled

### ISSUE THREAD

**Issue by ryanjayford** [react-navigation/react-navigation#5033]
render() {
        return (
                   <AppTopTabNavigator screenProps = {{navigation: this.props.navigation, screenWidth: 
                      this.state.dimensions.width }}  />
                )
        }
...

const AppTopTabNavigator =  createMaterialTopTabNavigator   
(
    { New: NewScreen ...
    ...
},
{ 
initialRouteName: 'New',
tabBarOptions: {
        scrollEnabled: ( {screenProps.screenWidth  value here} < 412),
...

My condition is to check if screen width is less than 412 then scrollEnabled: true  (for phone portrait)
if not scrollEnabled: false (for phone landscape /tablets 7" up )

My srceenWidth already changing when you rotate device, I just need to set the condition to scrollEnabled.

Thanks in Advance!

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by ryanjayford** [comment]
I'm just asking on how to pass screenProps property to tabBarOptions
scrollEnabled. It's just checking if your device is small then
scrollEnabled is true if its big enough then scrollEnabled is false.

**Comment by brentvatne** [comment]
you can't do that. it's unclear why you would want to even use screenProps here - you need to provide tabBarOptions when you create the navigator. if this doesn't help you, i'd repost this to stackoverflow and try to be as clear as possible in what you're trying to accomplish.
