### ISSUE TITLE
Add drawer header before createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by anehkumar** [react-navigation/react-navigation#5047]
Hi I want to add header before createMaterialTopTabNavigator bar like shown bellow in image
![screenshot_20180928-131621](https://user-images.githubusercontent.com/6602106/46195071-dd104180-c320-11e8-9847-782958cc6672.png)

But my tab look like as shown below image 
![screen shot 2018-09-28 at 1 19 04 pm](https://user-images.githubusercontent.com/6602106/46195151-1ba5fc00-c321-11e8-9ca7-7bd9ea17d7f0.png)

can you please help to add drawer navigation header in this

My Drawer Navigation and TabNavigation code

```
const MyAppointmentTabs = createMaterialTopTabNavigator(
  {
    Upcoming: UpCommingAppointmentTab,
    Requested: RequestedAppointmentTab,
    History: HistoryAppointmentTab
  },
  {
    tabBarOptions: {
      activeTintColor: 'white',
      inactiveTintColor: '#f7f7f7',
      indicatorStyle: {
        backgroundColor: '#fff',
      },
      style: {
        backgroundColor: '#f4511e',
        marginTop: 20
      }
    },
  }
)



const MainApp = createDrawerNavigator(
  {
      Home: HomeScreen,
      BookAppointment: {screen: BookingStack},
      MyRepots: MyReportScreen,
      MyAppointment: {
        screen: MyAppointmentTabs,
      },
      Notifications: NotificationScreen,
      Settings: SettingScreen,
      Feedbacks: FeedbackScreen
  },
  {
    initialRouteName: 'Home',
    contentComponent: CustomDrawerComp,
    navigationOptions: {
      drawerLockMode: 'locked-open',
    }
  }
)
```

**Comment by ARDcode** [comment]
```
navigationOptions: {
      drawerLockMode: 'locked-open',
    }
```
Change to (for example):
```
navigationOptions: {
      drawerLockMode: 'locked-open',
      title: "Статьи/Новости",
    }
```

**Comment by anehkumar** [comment]
Hi thanks for reply @ARDcode  it was not working.

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by vonovak** [comment]
@anehkumar I recommend you ask usage questions on stackoverflow. At any rate, to have a header, you need to have your screens in a stack navigator.

**Comment by take** [comment]
@anehkumar did you check this out? https://readybytes.in/blog/how-to-integrate-tabs-navigation-drawer-navigation-and-stack-navigation-together-in-react-navigation-v2

**Comment by Bethel-Eyo** [comment]
@take thank you so much for your recommendation. it worked well for me
