### ISSUE TITLE
android release createSwitchNavigator flash back

### ISSUE THREAD

**Issue by js1121302139** [react-navigation/react-navigation#5048]
"react": "16.3.1",
"react-native": "0.55.4",
"react-navigation": "^2.6.2"

const Routers = createSwitchNavigator({
    Loding: Loding,
    Auth: AuthStacks,
    App: AppStacks
}, {
      initialRouteName: 'Loding'
 })

It works fine under debug, but there is a flash back under release

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
