### ISSUE TITLE
The iOS simulator hangs on navigating to a nested screen in development mode

### ISSUE THREAD

**Issue by jarvisluong** [react-navigation/react-navigation#5055]
### Current Behavior

I think this only happens on XCode 10's iOS simulators

I'm having a TabNavigator that one tab is a nested Stack Navigator and one screen inside that Stack Navigator is another Stack Navigator (I did it since I need a custom transition mode for the nested screens). When I try to navigate to one of the nested screen inside the deepest Stack Navigator, the whole simulator just freeze, I can't go to the home screen, I can't take screenshots, ... This does not happens when I run the app in production mode or running the app in a real device

When I open the mac's Activity Monitor to see what's wrong, I can see the process ```backboardd``` is taking up 600 -> 1000% CPU 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.16.0
| react-native     | 0.55.4
| expo | SDK 29
| node             | 9.4.0
| npm or yarn      | yarn 1.9.4
| XCode | 10

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
