### ISSUE TITLE
Bug tabBarTop scroll position

### ISSUE THREAD

**Issue by shiroze** [react-navigation/react-navigation#5057]
is there a way to resolve the scroll position indicator focus when scroll enable ? this happen when tab is clicked.

![scrollbug_1](https://user-images.githubusercontent.com/6022114/46337064-db16ed00-c656-11e8-9c21-77474c30ad9f.png)

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
