### ISSUE TITLE
NavigationEvents creates an infinite loop if it changes the state

### ISSUE THREAD

**Issue by gclems** [react-navigation/react-navigation#5058]
Hi everyone !

I believe the title speaks for itself, but here's a little context

## Current behavior
When using a NavigationEvents component to call a function, and if this function changes the screen's state, then an infinite loop calls it endlessly.

## How to reproduce 
I created an example project with the issue, here's the [GitHub repo](https://github.com/ElsanLab/react-native-navigation-events-loop). 
Everything is in the the App.js file. There's a `console.log('loadData')` so you can see the loop in action.

Maybe I am doing something wrong, but I have another RN project where it works fine. The only difference is that the other project uses RN 0.56. So that might be a clue.

## Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.1
| node             | 10.0.0
| yarn      | 1.9.4

**Comment by brentvatne** [comment]
@slorber ping

**Comment by slorber** [comment]
@brentvatne I looked at this bug and there's effectively an infinite loop

This happens when we provide unstable callbacks. The workaround is to provide stable callbacks:

```js
        <NavigationEvents onDidFocus={() => this.loadData()} />
```


When using unstable callbacks, the callbacks are removed/added to the event system on every update.

And when doing `navigation.addListener("didFocus",listener)`, if the current screen has focus, the listener will be called immediately (but async), leading to an infinite loop. I guess this behavior is on purpose?


I suggest that I put back my initial implementation, which was to register all navigation.addListener on mount, only once, and then wire the props listeners inside the stables listeners. This should allow users to use both stable and unstable callbacks, without firing onDidFocus everytime the prop onDidFocus changes

**Comment by slorber** [comment]
just created a PR on react-navigation-core for 3.x, as 2.x has a decent workaround to use
