### ISSUE TITLE
navigating back with swipe gesture

### ISSUE THREAD

**Issue by tonmanayo** [react-navigation/react-navigation#5060]
### Current Behavior

when I enabled the swipe back area to be 1/4 of the screen and then navigated into a stack and went two screens down it would sometimes take me to the root of the stack instead of the previous screen.
example - home(screen 1) navigated to screen 2 then to screen 3, all in the same stack. when swiping back it took me to the home screen instead of screen 2 

## code

const InboxStack = createStackNavigator(
  {
    InboxRequestsScreen: { screen: InboxScreen },
    PaymentRequestPinScreen: { screen: PaymentPinScreen },
    ContactRequestScreen: { screen: ContactScreen },
    ReceiveRequestScreen: {screen: ReceiveRequestScreen},
    PaymentRequestConfirmScreen: { screen: PaymentRequestConfirmScreen },
    BlockUserSubmitScreen: {screen: BlockUserSubmitScreen}
  },
  {
    headerMode: 'none',
    initialRouteName: 'InboxRequestsScreen'
  }
)

InboxStack.navigationOptions = ({ navigation }) => {
  return {
    drawerLockMode: 'locked-closed',
    gestureResponseDistance: {
      horizontal: SCREEN_WIDTH / 4
    }
  }
}

const HomeStack = createStackNavigator(
  {
    HomeScreen: {screen: HomeScreen},
    WalletScreen: { screen: WalletStack },
    PaymentContactScreen: { screen: PaymentContactStack },
    ReceiveScreen: { screen: ReceiveStack },
    InboxScreen: { screen: InboxStack },
    DirectPaymentAmountScreen: {screen: PaymentDirectStack},
    CardTopUpScreen: {screen: DepositAgainStack}
  },
  {
    initialRouteName: 'HomeScreen',
    headerMode: 'none',
    transitionConfig,
    gesturesEnabled: true
  }
)

const NavigationDrawer = createDrawerNavigator(
  {
    HomeScreen: { screen: HomeStack },
    UserAccountScreen: { screen: UserAccountStack },
    TransactionScreen: { screen: TransactionScreen },
    BankAccountScreen: { screen: BankAccountStack },
    ManageCardScreen: {screen: ManageCardStack},
    ContactAndFeedbackScreen: { screen: ContactAndFeedbackStack },
  },
  {
    initialRouteName: 'HomeScreen',
    contentComponent: props => <DrawerContent {...props} />,
    drawerOpenRoute: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle'
  }
)

export default NavigationDrawer

### Your Environment

| software         | version
| ---------------- | -------
    "react-navigation": "^2.14.2",
    "react-native": "0.57.1",

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
