### ISSUE TITLE
There is no route defined for key X - two StackNavigators

### ISSUE THREAD

**Issue by smemamian** [react-navigation/react-navigation#5064]
I'm using `react-navigation` library to navigation.

but when I want to use two `StackNavigator`s I got this error:

> There is no route defined for key X must be one of ....

this error when appear that I want navigation `Screen1` from first `StackNavigator` to `Screen2` from second `StackNavigator`.

my `router.js`:

    export const LoginStack = StackNavigator({
      Splash: {
        screen: Splash,
      },
      Login: {
        screen: Login,
      },
      
    },
    {
      
      initialRouteName: 'Splash',
      
    });
    
    
    
    export const HomeStack = StackNavigator({
    
      KasianServices:{
        screen:KasianServices,
      },
      SpecialOffers:{
        screen:SpecialOffers,
      },
    
    },
    {
      initialRouteName: 'KasianServices',
      
    });
    
    
    
    
    export const RootNavigator = StackNavigator({
      LoginStack: {
        screen: LoginStack,
      },
      HomeStack:{
        screen: HomeStack,
      },
    },{
      mode: 'modal',
      headerMode: 'none',
      initialRouteName: 'LoginStack',
    }
    
    );
    
    export const Drawer = DrawerNavigator({
      Stack: { screen: RootNavigator },
    },{
        contentComponent: RightSideMenu,
        drawerPosition: 'right',
    })

for example:

    Splash ==> navigation('KasianServices') ==> I got this error.

**Comment by pzatorski** [comment]
Hey @smemamian. Can you create an example on https://snack.expo.io to demonstrate this? Thanks a lot!

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io or in a project i can clone from github, without any extraneous code


hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
