### ISSUE TITLE
{"state":{"routeName":"screen","key":"id-1538647994028-5"},"actions":{}} when navigating

### ISSUE THREAD

**Issue by alankarsaini** [react-navigation/react-navigation#5065]
I am sending my data like following:
**const navigateAction = NavigationActions.navigate({
      routeName: 'MyScreen',
      params: { isFromUpComing:true},
      action: NavigationActions.navigate({ routeName: 'MyScreen' })
    })
    const nav = WSManager.getTopLevelNavigator()
    nav.dispatch(navigateAction)**

and then in componentDidMount of Myscreen
**var isFromUpComing = this.props.navigation.getParam('isFromUpComing', false)
   console.log('did Item ' + JSON.stringify(this.props.navigation))**

so getting the following output on console don't know why because for other classes its working perfect: 
**{"state":{"routeName":"screen","key":"id-1538647994028-5"},"actions":{}}**

Is there any who ca help regarding this

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
