### ISSUE TITLE
Wrapping the navigator doesn't allow navigate

### ISSUE THREAD

**Issue by dengue8830** [react-navigation/react-navigation#5069]
### Current Behavior

If i use the navigator component inside a wrapper, the `this.props.navigation.navigate` function doesn't work inside the screen component. It doesn't throws error, just does nothing

### Expected Behavior

I should be able to navigate normally from screens components that are handled by a navigator that are wrapped in a custom component

### How to reproduce

check [this](https://snack.expo.io/@dengue8830/createbottomtabnavigator-with-style-from-server) demo, run it, follow the steps commented in the code

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.55.4
| node             | 8.11.3
| npm or yarn      | 5.6.0

**Comment by vonovak** [comment]
hi @dengue8830, thanks for the question. This is the expected behavior: react-navigation needs to know all your routes beforehand. This is also covered in the docs: https://reactnavigation.org/docs/en/limitations.html#dynamic-routes

You'll need to apply extra styling to your navigator, as you asked in #5003 

Thanks!
