### ISSUE TITLE
Android - Hide bottom navigation bar

### ISSUE THREAD

**Issue by truongluong1314520** [react-navigation/react-navigation#5070]
### Current Behavior

- I cannot hide status bar and the bottom navigation bar for Android 

<img width="441" alt="screen shot 2018-10-06 at 11 13 26 am" src="https://user-images.githubusercontent.com/32918401/46567184-e3be3a80-c958-11e8-81a3-027040e2adc8.png">

<img width="435" alt="screen shot 2018-10-06 at 11 11 27 am" src="https://user-images.githubusercontent.com/32918401/46567176-99d55480-c958-11e8-9690-b5311d510831.png">

### Expected Behavior

- There should be an attribute to hide it.

Note: I implement a native module to do it. However when I integrate the module with react-navigation, my full screen mode disable.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.0
| node             | v8.11.4
| npm or yarn      | 6.4.0

Please let me know if there a way to do it. Thank you in advance!

**Comment by iagorm** [comment]
this is related to core native feature, React Navigation only build a native feeling in pure javascript, if React Native Modules don't have it, you should create a Native Modules to control that.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by truongluong1314520** [comment]
Hi @iagorm , thank you for your reply. Now I know "React Navigation only build a native feeling in pure javascript". I did try to build a native module like you said. The native module runs well on completely new react native project but fail to run on the project which have React Navigation. I am still researching why it happens.

Hi @brentvatne , thank you for your kindness. If I am not able to find out why my native module does not work. I will upload everything to git repo. In that case, please take a look for me ^^ thank you in advance!
