### ISSUE TITLE
Send params to TabNavigator when initialize app

### ISSUE THREAD

**Issue by kortirso** [react-navigation/react-navigation#5076]
### Current Behavior

- What code are you running and what is happening?
I have TabNavigator with 4 tabs and icons

### Expected Behavior

- What do you expect should be happening?
I need to add localization to labels in tabs

### How to reproduce

I created root navigation like
```
<RootNavigation localization={localization} />
```

then in root navigation
```
const RootStackNavigator = StackNavigator(
  {
    Main: {
      screen: MainTabNavigator
    }
  },
  {
    navigationOptions: () => ({
    }),
    headerMode: 'none'
  }
);
```

and in main tab navigator
```
export default TabNavigator(
...
tabBarLabel: ({ focused }) => {
        const { routeName } = navigation.state
        let iconText
        switch (routeName) {
          case 'Taxi':
            iconText = 'Taxi'
            break
...
```

So, how to pass localization prop to TabNavigator and set text for icons based on localization prop?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.55.3
| node             | 8.12.0
| yarn      | 1.10.0

**Comment by vonovak** [comment]
hello and thanks for asking. This issue tracker is reserved for bugs only, and since this seems more like a usage question, I'd recommend asking on StackOverflow. That being said, as the docs say https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbarlabel

> tabBarLabel: string of a tab displayed in the tab bar or React Element or a function that given { focused: boolean, tintColor: string } returns a React.Node, 

so you have a choice of what you can return.

You want to use some localization library. There are several of these. For example, with [js-lingui](https://lingui.js.org/tutorials/react.html#introducing-internationalization) you'd use the `<Trans>` component. Hope this helps.
