### ISSUE TITLE
Error in TabBarBottom.js SyntaxError: \node_modules\react-navigation-deprecated-tab-navigator\src\views\TabBarBottom.js: Support for the experimental syntax 'classProperties' isn't currently enabled (26:23):

### ISSUE THREAD

**Issue by ketanvault** [react-navigation/react-navigation#5078]
I have the latest versions for all packages like : 
react: 16.5.0
react-native: 0.57.1
react-navigation: 2.17.0

./node_modules/react-navigation-deprecated-tab-navigator/src/views/TabBarBottom.js
SyntaxError: \node_modules\react-navigation-deprecated-tab-navigator\src\views\TabBarBottom.js: Support for the experimental syntax 'classProperties' isn't currently enabled (26:23):

  24 | class TabBarBottom extends React.PureComponent {
  25 |   // See https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/UIKitUICatalog/UITabBar.html
> 26 |   static defaultProps = {
     |                       ^
  27 |     activeTintColor: '#3478f6', // Default active tint color in iOS 10
  28 |     activeBackgroundColor: 'transparent',
  29 |     inactiveTintColor: '#929292', // Default inactive tint color in iOS 10

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

Please help me with this issue. I'm searching from last 3 hours for this issue.

**Comment by maieonbrix** [comment]
Hey there,

The error says that you need to : 

'Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.'

Did you try that ? If not : 

- Install the babel plugin by doing : yarn add @babel/plugin-proposal-class-properties --dev
- then, open your .babelrc file and add in the 'plugins array' the 'plugin-proposal-class-properties'

```
{
  "presets": ["react-native"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

Here is a detailed guide with alternatives : https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html

It's still weird that **you** need to do that since the code raising the error seems to be from react-navigation itself so..

**Comment by ketanvault** [comment]
Yes. I already added it in the .babelrc file. Still getting the same error. What should i do now?

**Comment by hareeqi** [comment]
Hello, I am having the same error, i'm using it with create react app, Any hints on how to fix it ?
