### ISSUE TITLE
Reset stack from another stack

### ISSUE THREAD

**Issue by clementino36** [react-navigation/react-navigation#5084]
This issue is very similar to https://github.com/react-navigation/react-navigation/issues/2291 but for react navigation v2. 
I'm trying to reset the stack and navigate to a route of another stack this way:
``` javascript
export const resetStack: Function = StackActions.reset({
    actions: [NavigationActions.navigate({ routeName: 'Home' })],
    index: 0,
});
```

This gives me 
> Invariant Violation: There is no route defined for key Home. Must be one of *routes in the other stack*

If I simply `navigate('Home')` from the other stack, it works, only the `reset` does not work.
I've tried setting `key: null` as suggested in the issue above but it didn't do the trick.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by clementino36** [comment]
Hi, very sorry about that, here's the new issue with a snack https://github.com/react-navigation/react-navigation/issues/5114
