### ISSUE TITLE
React Context Consumer not re-rendered on context value change

### ISSUE THREAD

**Issue by artus9033** [react-navigation/react-navigation#5121]
### Current Behavior

I use a component that has Context.Provider mounted in the root and a component that implements a Context.Consumer. If I mount the consumer component as a child of the provider component, everything works fine and the child component is re-rendered every time the context provider's value changes. Now, when I create a navigation component created using createBottomTabNavigator, place it inside the context provider and mount the context consumer inside the RootStack, the context is accessible, but when the context value changes, views inside the consumer are not re-rendered.

### Expected Behavior

The consumer component's children components are re-rendered every time the context value changes.

### How to reproduce

Initialize a navigator container:

	const RootStack = createBottomTabNavigator({
		Home: {
			screen: HomeScreen
		},
		Messages: {
			screen: MessagesScreen
		},
		Calendar: {
			screen: CalendarScreen
		},
		MatchStatistics: {
			screen: MatchStatisticsScreen
		},
		MyMatches: {
			screen: MyMatchesScreen
		}
	},
	{
		initialRouteName: "Home",
		animationEnabled: true,
		backBehavior: "initialRoute",
		swipeEnabled: "true",
		order: ["Calendar", "Messages", "Home", "MatchStatistics", "MyMatches"],
		navigationOptions: ({ navigation }) => ({
			tabBarOptions: {
				activeTintColor: materialColors.green["500"],
				inactiveTintColor: materialColors.grey["900"]
			}
		})
	});

create a context provider & consumer, mount the RootStack as a child of the provider and the consumer as a child of RootStack. You will notice that if the context changes after the initial render, the consumer will not be re-rendered.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | tried 2.17.0, 2.18.0 & 3.0.0-alpha.4
| react-native     | tried 0.55.4 & 0.55.2
| node             | 10.12.0
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by gino8080** [comment]
any news on this?
