### ISSUE TITLE
Can't change Drawer initial root via props at run time.

### ISSUE THREAD

**Issue by Biplovkumar** [react-navigation/react-navigation#5123]
### Current Behavior

1. err:- Props not found.
2. err:- this.props.navigation not found.

### Expected Behavior

Change Screen when getting initial root via props in Drawer.

## Heading ##

I want to Change via initial root of Custom Drawer Navigator, 
i have called two functions, function is calling from login Screen.
1. st function call on normal login.
2. nd function called when enter in app via notification click,please 
help, thanks in advance.
3. Default_drawer navigator code.this is custom Drawer.

LoginScreen Code :-

1. // function for going to Default_drawer

gotonextScreen() {
this.props.navigation.replace('Default_drawer', { Screen: 'CourseLists' })
}

2. // function for going to Default_drawer

gotoinboxScreen() {
this.props.navigation.replace('Default_drawer', { Screen: 'Inbox' })
}

3. Drawer Code : -

const CustomDrawer = createDrawerNavigator(

{

CourseLists: {
path: '/courselists',
screen: CourseLists,
},

Profile: {
path: '/profile',
screen: Profile,
},
//ratings
Leaderboard_Screen: {
path: '/leaderboard',
screen: Leaderboard_Screen,
},

//Inbox
Inbox: {
path: '/inbox',
screen: Inbox,
},

Logout: {
path: '/logout',
screen: Logout,
},
},
{

initialRouteName: this.props.navigation.getParam("Screen") === 'inbox' ? 'Inbox' : "CourseLists"
contentOptions: {
activeTintColor: 'rgba(228, 90, 30,0.7)',
activeBackgroundColor: 'transparent',
inactiveTintColor: '#ffffff',
inactiveBackgroundColor: 'transparent',
},
// drawerWidth: 250,
drawerWidth: SCREEN_WIDTH * 0.6,
contentComponent: CustomDrawerContentComponent,
drawerOpenRoute: 'DrawerOpen',
drawerCloseRoute: 'DrawerClose',
drawerToggleRoute: 'DrawerToggle'
}
);

const styles = StyleSheet.create({
container: {
flex: 1,
},
});

export default CustomDrawer;

### Your Environment

{
  "name": "*************************
![err](https://user-images.githubusercontent.com/30401136/46911429-efbd8400-cf78-11e8-86bb-e67394f12f31.png)
",
  "version": "1.0.2",
  "description": "*****************",
  "author": "Biplov Kumar",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "@expo/vector-icons": "6.3.0",
    "@expo/videoplayer": "^0.4.0",
    "axios": "^0.18.0",
    "expo": "^28.0.0",
    "firebase": "^5.5.1",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "radio-button-react-native": "^1.1.6",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-circular-progress": "^1.0.1",
    "react-native-countdown-component": "^1.7.3",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-snap-carousel": "^3.7.4",
    "react-navigation": "^2.16.0"
  },
  "scripts": {
    "postinstall": "git submodule update",
    "clean-install": "rm -rf node_modules && npm cache clean --force && watchman watch-del-all && npm install"
  }
}

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!


please check this link, maybe can help you.
https://reactnavigation.org/docs/en/auth-flow.html#docsNav

**Comment by Biplovkumar** [comment]
okk sure i will.
thanku
