### ISSUE TITLE
TabNavigator with a youtube player : unauthorized_overlay

### ISSUE THREAD

**Issue by Kisepro** [react-navigation/react-navigation#5127]
Hello,

There is a bug using react-navigation **createBottomTabNavigator** with the Youtube player from react-native-youtube.
The youtube player does not accept any layer on top of the player and it seems that the tab navigator mechanism create transparent layers.

Changing createBottomTabNavigator by createStackNavigator make it works again ... But of course I would like to keep the tab navigator behaviour.

Although the transparent layer seems to be a problem only with an external package, **only react-navigation** can do something on it.

You can find more information on this issues https://github.com/inProgress-team/react-native-youtube/issues/161

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
