### ISSUE TITLE
Dispatching openDrawer from outside of drawerNavigator forces return to screen inside of drawer navigator

### ISSUE THREAD

**Issue by jasongaare** [react-navigation/react-navigation#5129]
**Snack: https://snack.expo.io/Hkv4A8zjm**

_Follow these steps to replicate:_
1. Press "Open Drawer" button on Page 1
2. Select page2 in the drawer menu
3. Press "Go to Page 3" on Page 2
4. Press "Open Drawer" on Page 3

### Current Behavior
Currently, when you press "Open Drawer" on Page 3, the drawer opens as expected, however the navigator takes you back to Page 2, rather than leaving you on Page 3 where you opened the drawer from.

### Expected Behavior
Perhaps this is less _expected_ and more _desired_ but I'd like to be able to open the menu without navigating back to Page 2. The use case is when I have pages that are _not top-level_, thus are not included in the drawer menu. However, I'd like the user to always have access to the drawer if they'd like to navigate elsewhere -- but if they close the menu without selecting another page, it should return them to where they left off, not navigate them back up the stack.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.0
| node             | 10.8.0
| npm or yarn      | 1.10.1

**Comment by jasongaare** [comment]
Navigator setup, copied from [snack](https://snack.expo.io/Hkv4A8zjm) for convenience

```
const Navigator = createStackNavigator({
  drawerVisiblePages: createDrawerNavigator({
    page1: { screen: Page1 },
    page2: { screen: Page2 }
  }),
  page3: { screen: Page3 }, 
}, {
  initialRouteName: 'drawerVisiblePages',
  headerMode: "none"
});
```

**Comment by vonovak** [comment]
linking the question on SO: https://stackoverflow.com/questions/53000622/react-navigation-how-to-prevent-stack-from-popping-when-dispatching-opendrawer/53009094#53009094 where I answered how to get it working the way the OP would like.

imho, this is the expected behavior, but I'll keep it open for someone else to assess.

**Comment by eriveltonelias** [comment]
@vonovak, I think that commit https://github.com/react-navigation/react-navigation-core/commit/2f2329f33b0a35af1ccc460a85d268e255886e2b will fix this and also is related with https://github.com/react-navigation/react-navigation/issues/5146 

What do you think about ?

**Comment by brentvatne** [comment]
this behavior changed in 3.0 and it does what you expect now @jasongaare - https://snack.expo.io/@notbrent/shallow-cake

@vonovak - i think you're right that this would usually be expected however having the drawer behave this way led to some other unexpected issues like this https://github.com/react-navigation/react-navigation/issues/5146, at least on close. we could make it so that opening the drawer is different than closing and does trigger navigating to that screen, but perhaps the least surprising thing here is to make people navigate there manually if they want to.

**Comment by AnandaRafaele** [comment]
What did was include the screen in the drawer navigation and omit the item from the drawer screen, just like that: 

screenComp: {
    name: 'drawer item text',
    screen: (props) => <Component {...props} />,
    navigationOptions: { // This makes the item invisible
      drawerLabel: () => null,
      title: null,
      drawerIcon: () => null,
    },
  },
