### ISSUE TITLE
RNGestureHandlerModule.State

### ISSUE THREAD

**Issue by Evangelione** [react-navigation/react-navigation#5136]
2.17.0升级到Release 3.0.0-alpha.6 红屏报错

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by MacKentoch** [comment]
@Evangelione there is always a solution 😊.

- You either create a snack project to help maintainers (*we can't blame them this is so much work a such important library in mobile*) 
- or if you are in a hurry, just revert as I did : `yarn add react-navigation@2.17.0`

**Comment by brentvatne** [comment]
2.18.0 is the latest, sorry I accidentally published the alpha version as the latest

**Comment by appa3151** [comment]
only install react-native-gesture-handler
