### ISSUE TITLE
Transition config

### ISSUE THREAD

**Issue by JosephMulder** [react-navigation/react-navigation#5140]
I'm trying to make the transitions stop. I have looked at the documentation and [this post](https://github.com/react-navigation/react-navigation/issues/1254) but it isn't working. The documentation isn't very clear about what you should be returning the method transitionConfig. Can anyone help me understand what is going on or if this is even still working. 

```
import { createStackNavigator } from 'react-navigation';
import MainScreen from './MainScreen';
import CallScreen from './CallScreen';
import SelectScreen from './SelectScreen';
import HelpScreen from './HelpScreen';

const Navigation = createStackNavigator(
    {
        Home: MainScreen,
        Call: CallScreen,
        Select: SelectScreen,
        Help: HelpScreen
    },
    {
        initialRouteName: 'Home',
        headerMode: 'none',
        navigationOptions: {
            headerVisible: false,
        },
        transitionConfig : () => ({
            transitionSpec: {
                duration: 0,
                easing: Easing.step0,
                timing: Animated.timing,
            },
        }),
    },
);

export default Navigation;
```

| software         | version
| ---------------- | -------
| react-navigation |2.17.0
| react-native     |0.57.1
| node             |v10.10.0
| npm or yarn      |6.4.1

**Comment by brentvatne** [comment]
https://github.com/brentvatne/pahdcast/blob/cc6344b90db68be8835997eb21509139e63bebc6/navigation/AppNavigator.js#L17-L23

if this doesn't work for you then please share a full runnable example as requested by the issue template and will reopen

**Comment by kalraneeraj24550** [comment]
Do you have an example where I can use these custom transitions inside a Custom navigator created using the createNavigationContainer(
createNavigator(AppStackRouter)(StackView)
);

This is based off of CustomTabs example in react-navigation examples. Here I am confused as to how do I pass my transitionConfig inside createNavigator.

here is how I defined my StackRouter( which seems to take the stackConfig which in turn seems to take a StackConfig param as per here .

export const AppStackRouter = StackRouter(defaultMap, {
initialRouteName: 'StartScreenView',
transitionConfig: TransitionConfiguration,
});

But still the console.log (), I wrote inside the screenInterpolator of the transitionConfig is not hit :(. Any thoughts on what I am doing wrong?

UPDATE 2:
Tried a different approach by passing the transition config to teh createNavigator 3rd argument
createNavigationContainer(
createNavigator(AppStackRouter, {}, {transitionConfig: TransitionConfiguration})(StackView)
);

still the console.log inside my screenInterpolator did not get hit . I am officially out of ideas now in trying to get animations to work inside a Custom navigator. I would expect the default stack animations would exist even if we create a custom stack navigator, but turns out it is not the case

**Comment by kalraneeraj24550** [comment]
transitionconfig working with stackNavigator but not with StackRouter , anyone knows. plz help

**Comment by brentvatne** [comment]
@kalraneeraj24550 - stackrouter doesn't have any views associated with it, it's just a reducer...
