### ISSUE TITLE
React-navigation + nativeBase error!!

### ISSUE THREAD

**Issue by bachlongkocanh** [react-navigation/react-navigation#5145]
My app using nativeBase with react-navigation like diagram:
```sh
- Login
- Drawer
-- MaterialTopTab
--- Tab1
--- Tab2
-- Other Page
```
In file Tab1 use nativeBase,
```sh
<Form>
   <Item floatingLabel >
      <Label>Username</Label>
      <Input />
   </Item>
</Form>
```
Then Input can't handle `select/copy/paste`. Please check my issues. <Error only on android>

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
