### ISSUE TITLE
The style of container in stackViewLayout overflow: hidden will affect the screen

### ISSUE THREAD

**Issue by evanyuanvip** [react-navigation/react-navigation#5166]
Since Android doesn't support container shadows, I want to make a shadow image that I can see when I switch between screens to achieve the same effect as iOS. So the use of shadowImg: {position: 'absolute', width: 8, height: '100%', left: -8} such a style, will be affected by the container, due to overflow: hidden.
Thank you!

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
you probably want to use elevation on the container instead

**Comment by evanyuanvip** [comment]
> you probably want to use elevation on the container instead

Elevation does not show when sliding in Android. In Android I used SlideFromRightIOS
