### ISSUE TITLE
Application is frozen after calling Keyboard.dismiss() and pressing Back hardware Android

### ISSUE THREAD

**Issue by tconns** [react-navigation/react-navigation#5180]
## Application is frozen after calling Keyboard.dismiss() and pressing Back hardware Android.
---

### Current Behavior

- Application is frozen after calling Keyboard.dismiss() and pressing Back hardware Android.

### Expected Behavior

- The application works normally.

### How to reproduce

- After calling Keyboard.dismiss() .
- Pressing Back hardware Android.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.0
| react-native     | 0.57.1
| node             | 10.4.1
| npm or yarn      | 6.4.1
| platform   | android

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
