### ISSUE TITLE
React Navigation Tabs does not Working when nested

### ISSUE THREAD

**Issue by PauloKeller** [react-navigation/react-navigation#5185]
So I has: 

 - SwitchNavigator
     - StackNavigator
       - MaterialTopTabNavigator

Current Behavior: When I click in the icons in tab navigator nothing happen, but when I slide between then it works. And I can navigate between other screens.

Expected Behavior: I want to change between the screens with the click and the slide.

React native: 57.3
React navigation: 2.17.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
