### ISSUE TITLE
App slows when push many screens

### ISSUE THREAD

**Issue by lightnguyen** [react-navigation/react-navigation#5187]
I have a StackNavigator with a screen called ProductDetail. User can view another product (recommended products) within ProductDetail. In order to achieve this, I use this.props.navigation.push('ProductDetail'). The more I push new screens to StackNavigator, the slower my app gets and eventually it freezes. I wonder if anyone faces the same issue? How can I solve this? 

### Environment
react-navigation: 2.18.0
react-native: 0.57.3
node: 8.12.0
npm: 6.4.1

**Comment by phamhaibkit** [comment]
same issue +1

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by albullington** [comment]
I'm facing the same issue

**Comment by abstruse9** [comment]
I'm facing the same issue too

**Comment by sergiupris** [comment]
Same issue here. So anyone found any solutions?
