### ISSUE TITLE
Props not pass in tab navigation

### ISSUE THREAD

**Issue by crzycoder** [react-navigation/react-navigation#5188]
import React, { Component } from "react";
import { View, ActivityIndicator, Dimensions } from "react-native";
import { createMaterialTopTabNavigator } from "react-navigation";
import VideoScreen from "../screens/tabScreens/VideoScreen";
import AlbumScreen from "../screens/tabScreens/AlbumScreen";
import AboutScreen from "../screens/tabScreens/AboutScreen";

const TabNavigator = createMaterialTopTabNavigator({
  Video: VideoScreen,
  Album: AlbumScreen,
  About: AboutScreen
});

export default class TabInfoScreen extends Component {
  constructor(props) {
    super(props);
    //this._navigation.bind(this);
    this.state = {
      video_id: this.props.navigation.state.params.video_id,
      _isMounted: true,
      dataSource: [],
      fetchData: false,
      isLoading: true
    };
  }

  componentDidMount() {
    if (this.state._isMounted) {
      /*  *****Loading Indicator Timout***** 
    setTimeout(() => {
      this.setState({
        isLoading: false
      });
    }, 3000);*/

      fetch(` http://www.tvsheevi.com/api/celebrity/${this.state.video_id}`, {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json"
        }
      })
        .then(response => response.json())
        .then(responseJson => {
          console.log("video_video");
          console.log(responseJson["data"]);
          console.log("video_video");
          this.setState({
            dataSource: responseJson["data"],
            fetchData: true,
            isLoading: false
          });
        })
        .catch(error => {
          console.log("dani3");
          alert(error);
        });
    }
  }
  /*
  componentWillUnmount() {
    this.setState({
      _isMounted: false
    });
  }*/

  render() {
    if (this.state.isLoading) {
      return (
        <View style={{ paddingTop: Dimensions.get("window").height / 2 }}>
          <ActivityIndicator size="large" color="red" />
        </View>
      );
    } else {
      return <TabNavigator data={this.state.dataSource} />;  <== here data is not passing
    }
  }
}

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
