### ISSUE TITLE
getParam returns undefined when called in navigationOptions

### ISSUE THREAD

**Issue by resting** [react-navigation/react-navigation#5215]
Trying `navigation.getParam('backOptionalText')` in `navigationOptions` it returns undefined.  
But inspecting the `navigation.state.routes`, I do see the param there.

Am I using `getParam` right?  
Is there any disadvantage to accessing the params via `navigation.state.routes[2]` directly?

`console.log(this.props.navigation.getParam('backOptionalText'))` returns correct value if called in a class method or `componentDidMount`.

```
class DealsDetailsScreen extends Component {
  static navigationOptions = {
      header: ({ navigation }) => {
          console.log(navigation) // navigation.state.routes[2].params has backOptionalText
          console.log(navigation.getParam('backOptionalText')) // returns undefined
          return <Header navigation={navigation} 
              backOptionalText={navigation.getParam('backOptionalText')} 
          />
      }
  }
  ..
}
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
