### ISSUE TITLE
Unable to refresh the page in react-navigation

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#5277]
I am using react-navigation to navigate home page to many child pages. Here navigation works fine with TabNavigator. Inside the TabNavigator I have used StackNavigator and many screens to navigate from one to other screens.

Here I got an error as below after upgrading the react-navigation

**You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator. Full details at: https://reactnavigation.org/docs/common-mistakes.html#explicitly-rendering-more-than-one-navigator** 

I have used **this.props.navigation.navigate('HomeScreen==> StackNavigation')** to navigate the home page and it will refresh the page.  But it not get refreshing now.  Now it not working

Now I am using the react-navigation@2.18.2

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
