### ISSUE TITLE
 Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.  Check the render method of `NavigationContainer`.

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#5278]
I am using the latest version of react-navigation 3.0.0.

I am getting the error as

```
"Possible Unhandled Promise Rejection (id: 0):
Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `NavigationContainer`.

```
![screen shot 2018-11-24 at 5 13 20 pm](https://user-images.githubusercontent.com/36992338/48967830-794a8200-f00c-11e8-970d-7690930e89d1.png)

**Comment by kesha-antonov** [comment]
@nihp show how you import component

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by nihp** [comment]
@kesha-antonov 
I have imported as below

**`import {createBottomTabNavigator, TabBarPosition, createAppContainer, createStackNavigator, NavButton, TabBarBottom, } from 'react-navigation';`**
