### ISSUE TITLE
Pass initial params to screens

### ISSUE THREAD

**Issue by zRelux** [react-navigation/react-navigation#5285]
## The issue tracker is reserved for bug reports only.

I tried to implement a drawerNavigator with a stackNavigator inside, I wanted to pass some initial params to the routes in the drawerNavigator but I can't seem to access them when it gets rendered. I need to get those params and pass them to the stack navigator that is inside the drawerNavigator

### Current Behavior

I'm not able to pass the params to the stackNavigator. I want to access the params in the Content screen but I can't since they don't get passed from the drawerNavigator.

### Expected Behavior

Access the initial params.

### How to reproduce

```
//SerieNavigaton.js
const SerieStack = createStackNavigator(
  {
    Content: {
      screen: SearchScreen
    },
    Serie: SearieScreen,
    Episode: EpisodePage
  },
  {
    headerMode: "none",
    navigationOptions: {
      headerVisible: false
    }
  }
);
SerieStack.navigationOptions = {};
export default SerieStack; 

//MainNavigator
const MyDrawerNavigator = createDrawerNavigator({
  Anime: {
    screen: SerieNavigation,
    params: { type: "anime" },
    path: "anime/:anime"
  },
  Tv: {
    screen: SerieNavigation,
    params: { type: "tv-show" },
    path: "tv/:tv"
  },
  Film: {
    screen: SerieNavigation,
    params: { type: "film" },
    path: "film/:film"
  }
});

const AppContainer = createAppContainer(MyDrawerNavigator);

export default AppContainer;
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
| node             | v10.8
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
