### ISSUE TITLE
TextInput context menu doesn't appear inside nested StackNavigator to TabNavigator

### ISSUE THREAD

**Issue by AlexeyVlasenko** [react-navigation/react-navigation#5297]
**Current Behavior**
**_ANDROID_** Context menu of TextInput with multiline (also sometimes without) using architecture from official [docs ](https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens) unable to call.

**Expected Behavior**
Context menu should appear

**How to reproduce**
I've created example on [Snack](https://snack.expo.io/S1A0eJ30X)  **Don't forget to choose Android!**

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.0
| react-native     | 0.57.5

**Comment by MoudiZd** [comment]
I could not reproduce the issue from the snack you provided as you see in these pictures

![screenshot_20181128-123540](https://user-images.githubusercontent.com/11831354/49146266-77353b80-f30a-11e8-8976-86959231b915.png)
![screenshot_20181128-123559](https://user-images.githubusercontent.com/11831354/49146295-85835780-f30a-11e8-86cb-15a99ec7166b.png)
![screenshot_20181128-123456](https://user-images.githubusercontent.com/11831354/49146318-959b3700-f30a-11e8-98ea-6421c4c53b85.png)


I think the problem is not depending on react-navigation library but on android version or device model

Best regards

**Comment by vonovak** [comment]
@MoudiZd this is indeed reproducible, on an android device, as described

**Comment by AlexeyVlasenko** [comment]
> I could not reproduce the issue from the snack you provided as you see in these pictures
> 
> ![screenshot_20181128-123540](https://user-images.githubusercontent.com/11831354/49146266-77353b80-f30a-11e8-8976-86959231b915.png)
> ![screenshot_20181128-123559](https://user-images.githubusercontent.com/11831354/49146295-85835780-f30a-11e8-86cb-15a99ec7166b.png)
> ![screenshot_20181128-123456](https://user-images.githubusercontent.com/11831354/49146318-959b3700-f30a-11e8-98ea-6421c4c53b85.png)
> 
> I think the problem is not depending on react-navigation library but on android version or device model
> 
> Best regards

Please, use Android device instead.

**Comment by MoudiZd** [comment]
@AlexeyVlasenko  
The issue is just within `createBottomTabNavigator` try to change it to `createMaterialTopTabNavigator` or event to `createStackNavigator` resolved the issue for me at least

But is still a bug it seems related to [https://github.com/react-navigation/react-navigation/issues/1992](https://github.com/react-navigation/react-navigation/issues/1992)

**Comment by AlexeyVlasenko** [comment]
Also RN 58 have this issue ;(

**Comment by brentvatne** [comment]
grouping this into https://github.com/react-navigation/react-navigation/issues/5476
