### ISSUE TITLE
invariant violation:Element type is invalid: expected a string(for built-in components) or a class/function (for composite components) but got undefined 

### ISSUE THREAD

**Issue by Aravind137** [react-navigation/react-navigation#5298]
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import {ScrollView,ScrollViewChild } from 'react-native-directed-scrollview';
import GridContent from './GridContent';
import RowLabels from './RowLabels';
import ColumnLabels from './ColumnLabels';
import { getCellsByRow } from './data';

export default class Grid extends Component {
  render() {
    const cellsByRow = getCellsByRow();

    return (
      <ScrollView
        bounces={true}
        bouncesZoom={true}
        maximumZoomScale={1.5}
        minimumZoomScale={0.75}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.contentContainer}
        style={styles.container}
      >
        <ScrollViewChild scrollDirection={'both'}>
          <GridContent cellsByRow={cellsByRow} />
        </ScrollViewChild>
        <ScrollViewChild scrollDirection={'vertical'} style={styles.rowLabelsContainer}>
          <RowLabels cellsByRow={cellsByRow} />
        </ScrollViewChild>
        <ScrollViewChild scrollDirection={'horizontal'} style={styles.columnLabelsContainer}>
          <ColumnLabels cellsByRow={cellsByRow} />
        </ScrollViewChild>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    height: 1080,
    width: 1080,
  },
  rowLabelsContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 100,
  },
  columnLabelsContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    height: 30,
  },
});

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
