### ISSUE TITLE
NavigationActions.reset is bug?

### ISSUE THREAD

**Issue by fadeli1** [react-navigation/react-navigation#5316]
### Current Behavior

run app.js ->Login.js->console.log(1)->click login->NavigationActions.reset->console.log(1)

### Expected Behavior

run app.js ->Login.js->console.log(1)->click login->NavigationActions.reset->not print console.log(1)

### How to reproduce

app.js
```
const Navigator = StackNavigator({
    Login: { screen: LoginScreen },
    IndexScreen: { screen: IndexScreen },
	WaterContainer: { screen: WaterContainer },
}, {
    navigationOptions:{
        headerStyle : {backgroundColor: '#00b8b0'},
        headerTintColor: '#fff'
    }
});

export default class App extends Component<Props> {
    constructor (props) {
	}
	render() {
        return (
            <Navigator />
        );
    }
}
```
Login.js
```
export default class LoginScreen extends React.Component {
	constructor (props){
        super(props);
	}
	componentDidMount() {
		console.log(1)
	}
	login(){
		let resetAction = NavigationActions.reset({
			index: 0,
			actions: [
				NavigationActions.navigate({routeName: 'IndexScreen'}),
			]
		});
		this.props.navigation.dispatch(resetAction);
	}
	render() {
        return (
                <View style={{flex: 1}}>
					<TouchableOpacity onPress={()=>{this.login()}}>
						<Text >login</Text>
					</TouchableOpacity>
				</View>
		)
	}
}
```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native         | 0.55.2
| node                    | 9.5.0
| npm                     | 6.4.1
| android                | 7.1.2

**Comment by fadeli1** [comment]
Supplementary explanation:
NavigationActions.reset  Change to:
```
let resetAction = NavigationActions.reset({
			index: 1,
			actions: [
				NavigationActions.navigate({ routeName: 'IndexScreen', params:{true_name:tempUserConfig.true_name}}),
				NavigationActions.navigate({ routeName: JGPUSH_INFO.extras.page, params: JGPUSH_INFO.extras}),
			]
		});
		this.props.navigation.dispatch(resetAction);
```
result-> app.js ->Login.js->console.log(1)->click login->NavigationActions.reset->not print console.log(1)

**Comment by fadeli1** [comment]
I hope not to print the console.log, what should I do?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
