### ISSUE TITLE
Stack transition must complete before nested switch can navigate

### ISSUE THREAD

**Issue by maxschmeling** [react-navigation/react-navigation#5318]
### Current Behavior

When I have a `SwitchNavigator` as a screen in a `StackNavigator`, the switch is unable to transition from a `Navigation/NAVIGATE` action until after the stack's card has fully transitioned (and the `_onTransitionEnd` method is called in `Transitioner`.

In my specific case, I have a modal stack that has this switch screen whose initial route checks granted permissions and switches to the appropriate route based on what permissions the app has (similar to the root level app auth flow example in the docs). Before I updated to the latest, this worked fine. But now the switch doesn't happen visually until the modal card is all the way up and finished transitioning.

I believe it is caused by this PR: https://github.com/react-navigation/react-navigation-stack/pull/49

### Expected Behavior

I expect the previous behavior of immediately switching the route on the switch navigator during the transition so that it's a seamless transition (in my case the async permissions check is basically instant). This way, as the modal slides up, the user only sees the appropriate screen they're going to be interacting with and not the initial route of the switch navigator.

### How to reproduce

Reproduction: https://snack.expo.io/@maxschmeling/switchnestedinstackissue

To reproduce on your own:
1. Create a stack navigator with two routes
2. Make the second screen a switch navigator with two routes
3. Make the initial route in the switch navigator immediately dispatch a navigate action to the second screen in the switch (in componentDidMount)
4. Add a button to the first screen in the stack that navigates to the second screen in the stack
5. Run the code and click the button to navigate to the second screen in the stack. You'll see it not update the switch to the second route until after the stack transition is complete

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.0.2
| react-native     |0.57.7
| node             |v11.1.0
| npm or yarn      |v1.12.3

**Comment by maxschmeling** [comment]
It's possible that this isn't an appropriate use of the `SwitchNavigator`, but it seems so similar to the auth example in the docs. The main difference being that the root switch navigator isn't part of a transition from a parent so it doesn't have to wait on anything.

**Comment by brentvatne** [comment]
what's the use case for this? why not just navigate directly to 'Final'?

**Comment by brentvatne** [comment]
hi @maxschmeling! thanks for the detailed report.

I think that the behavior from the PR you referenced is generally desirable (the old behavior causes a good number of bugs) but maybe we can add some more nuance to it so that this type of flow is possible. I believe this is the same root cause as https://github.com/react-navigation/react-navigation/issues/5299. I don't have time to work on this right now but there are ways you can work around this like by checking permissions outside of the switch and navigating to the appropriate switch screen directly

**Comment by maxschmeling** [comment]
Yeah, I think it's generally desirable for it to work how it is now as well. I think the nuance might be that subsequent route changes that don't actually require a transition (animated transition) maybe should be rendered immediately during the transition. I'm not sure though, and I'm just getting familiar with the internals of `react-navigation` so you'll have a better feel for that than me.

I'm happy to work around it for now. I guess the reason I wanted to do it this way is that it's a standard way to encapsulate the logic for routing to the right flow instead of having to call a helper or something built more custom for the situation before sending the navigation action. Maybe it's not a good pattern though and it makes more sense to keep that out of the screens and navigation logic.

**Comment by brentvatne** [comment]
@sonaye - if you'd like to write up a rfc to explain what needs to change to satisfy your use case, the implications of the change, etc, that would be appreciated

**Comment by sonaye** [comment]
@brentvatne I'm still debugging this issue, I have a feeling there is a way around it already, will update here if I figure it out.

Not an expert in react-navigation internals (yet), the gist is that we would have a stack navigator without any animated transitions (screen A -> screen B in 0ms). We can actually achieve this now, but the pushed screen waits for `onTransitionEnd` before it becomes active (around ~300ms of unresponsiveness), the expected behavior is that it would become active instantly.

Here is an example to reproduce with a spring https://snack.expo.io/HyqjDdLN4, you will find that you have to click the buttons multiple times before they work.
