### ISSUE TITLE
dynamicModalTransition not work on v3

### ISSUE THREAD

**Issue by z98361** [react-navigation/react-navigation#5330]
| software         | version
| ---------------- | -------
| react-navigation | 3.0.5
| react-native     | 0.7.5
| node             | 8.11.3
| npm      | 5.6.0

I follow guide on lib to implement stack nav but this code always open modal

```
import { createStackNavigator, StackViewTransitionConfigs } from 'react-navigation';

/* The screens you add to IOS_MODAL_ROUTES will have the modal transition.  */
const IOS_MODAL_ROUTES = ['OptionsScreen'];

let dynamicModalTransition = (transitionProps, prevTransitionProps) => {
  const isModal = IOS_MODAL_ROUTES.some(
    screenName =>
      screenName === transitionProps.scene.route.routeName ||
      (prevTransitionProps && screenName === prevTransitionProps.scene.route.routeName)
  )
  return StackViewTransitionConfigs.defaultTransitionConfig(
    transitionProps,
    prevTransitionProps,
    isModal
  );
};

const HomeStack = createStackNavigator(
  { DetailScreen, HomeScreen, OptionsScreen },
  { initialRouteName: 'HomeScreen', transitionConfig: dynamicModalTransition }
);
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by cylim** [comment]
There is an issue for this code
```
screenName === transitionProps.scene.route.routeName 
|| (prevTransitionProps && screenName === prevTransitionProps.scene.route.routeName)
```

It doesn't know whether the order of the screen mounted, so when you `navigate` or `goBack` from one screen to another, it might have another behaviour instead of the behaviour you expected.

e.g.
A(modal) to B(card) => card transition
B(card) back to A(modal) => modal transition

Unfortunately, I can't come up with a better algorithm to solve the problem, my current checking code is hardcoded each screen and compare with next screen manually.

**Comment by cylim** [comment]
@z98361 

The easy way for doing this is to have something like this
```
const dynamicTransition = (transitionProps, prevTransitionProps) => {
  const nextScreen = transitionProps.scene.route.routeName
  const currentScreen = prevTransitionProps ? prevTransitionProps.scene.route.routeName : null

  let isModal = true
  if ((nextScreen === 'MentorSelection' && currentScreen === 'AskQuestion')
    || (nextScreen === 'AskQuestion' && currentScreen === 'MentorSelection')) {
    isModal = false
  }

  return StackViewTransitionConfigs.defaultTransitionConfig(
    transitionProps,
    prevTransitionProps,
    isModal
  )
}
```

You can do the manual checking for Modal or Card transition depends on which one it the majority, you can write another function to return isModal true or false to reduce duplicated code.

This is not a perfect solution.

**Comment by 101abhishekgoel** [comment]
NOT ABLE TO IMPORT StackViewTransitionConfigs IN LATEST VERSION
