### ISSUE TITLE
Unable to pass parameter to DrawerNavigator

### ISSUE THREAD

**Issue by rochebleue** [react-navigation/react-navigation#5332]
### Current Behavior

I cannot manage to pass parameters from my root navigator to a screen in my drawer navigator.
I'm trying to pass the 'test' prop to the screen inside my drawer Navigator (HomeScreen). It doesn't work, the variable stays undefined in the HomeScreen.

Login Screen
```
  login() {
      this.props.navigation.navigate( 'Home', { test: 'titi' });
  }
...
        <Button
          title="Login"
          onPress={ () => this.login() }
        />
```
HomeScreen
```
  render() {
    const  test  = this.props.navigation.getParam('test', 'undefined');
    return (
      <View style={{ flexDirection: "column", flex: 1}}>
       <Text>{test}</Text>
      </View>
    )
  }
```
On testing, the variable test is undefined.

App.js : 
```
const SubStacks = createStackNavigator(
  {
    BeastList: HomeScreen
  }
);

const Drawers = createDrawerNavigator(
  {
    SubStacks: SubStacks
  },
  {
    contentComponent: DrawerMenu
  }
);

const Root = createStackNavigator(
  {
    Login: LoginScreen,
    Home: Drawers
  },
  {
    headerMode: 'none'
  }
);

const AppContainer = createAppContainer(Root);

export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
}
```

### Expected behavior

The 'test' prop should be passed to the HomeScreen.

### Reproduce 

Here is a minimal version of the problem : 

https://snack.expo.io/@audrade/navigation-bug-demo

**Comment by brentvatne** [comment]
this is not a bug, it's how params behave. you navigated to the drawer route, so that route has the param. if you want another route to have the param, navigate there instead:

```
  login() {
      this.props.navigation.navigate( 'BeastList', { test: 'titi' });
  }
```

it's unclear exactly what you are trying to accomplish here. if your goal is to make a value available in several places then using a param is not the right way to do this, you should use redux or context or something.

**Comment by rochebleue** [comment]
Thanks. Unfortunately, if I directly navigate to BeastList, then my drawer won't get the 'test' prop.

I would like both BeastList and the drawer to be able to get this prop.

**Comment by brentvatne** [comment]
redux or screenProps would work

**Comment by Dror-Bar** [comment]
Hi, sorry that I misguided you. Like I said in earlier version you could pass params to the parent Drawer and and the first screen would also receive the prop. I guess they changed that behaviour. Glad you managed to do it with context, myself I'm using redux and it does requires quite a bit of code.

**Comment by rochebleue** [comment]
There is absolutely no problem, you actually helped me a lot. Thank you.

**Comment by incorelabs** [comment]
So did you use Context or some else for this? I'm having a similar issue but with createBottomTabNavigator. I'm using the [Authentication flow Guide](https://reactnavigation.org/docs/en/auth-flow.html) and when implementing the [AuthLoadingScreen](https://reactnavigation.org/docs/en/auth-flow.html#implement-our-authentication-loading-screen), I want the user id (which i get from an API in the _bootstrapAsync method) to be available to the entire App Stack. Suggestions?

**Comment by Dror-Bar** [comment]
@incorelabs 
I'd like to mention there is a quick and easy solution, which is using the global variable.
It's very simple to use. In your root you can declare the variable `global.userID = '';`.  After getting the user id, write `global.userID = 'USER_ID';`. You can access this variable from anywhere in the app, for example `if (global.userID = '1234') { // ...code }`.

Using global is considered anti-pattern and not recommended, because it lacks a controlled environment. But it depends on your use case. If you just need the user id for ajax request for example, storing it in global might be okay. Obviously, if you need your UI to change dynamically according to it you cannot do it with global, since unlike redux for example, when the value changes it doesn't notify components that are subscribed to it.

**Comment by renatosistemasvc** [comment]
@incorelabs Thank you for sharing this alternative. Solved my problem.
