### ISSUE TITLE
Release Build: undefined is not an object (evaluating 'e.default')

### ISSUE THREAD

**Issue by mxmtsk** [react-navigation/react-navigation#5333]
### Current Behavior
When running my app on iOS during development it runs fine, but when I build for release it shows the following error in X-Code:

```
[tid:com.facebook.react.JavaScript] TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in RCTView
    in n
    in t
    in inject-t-with-app-user
    in RCTView
    in t
    in RCTView
    in t
    in RCTView
    in RCTView
    in n
```

I have tried to narrow the error down as the error message is cryptic and as soon as I use a stack navigator this happens. When I use `createSwitchNavigator` and the initialroute is just a component it shows, but as soon as I navigate to a stack navigator the error comes up.

When I leave out react-navigation and only export the component that should be displayed within the stacknavigator it works fine aswell. It fails "silently", meaning I see the error in the console, the app does not crash though.

Code is as simple as this:
```Javsascript
export default createStackNavigator(
  {
    Welcome: {
      screen: Welcome
    },
    Login: {
      screen: Login
    },
    SignUp: {
      screen: SignUp
    }
  },
  {
    initialRouteName: "Welcome"
  }
);
```
### Expected Behavior
It should work.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.56.1
| node             | 8.9.4
| yarn      | 0.17.8

**Comment by brentvatne** [comment]
i don't see any way you have proven here that this issue is at all related to react-navigation, and you have no provided a reproducible example, so here is the usual template response!

<hr />

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by guruprakash119** [comment]
@mxmtsk what was the problem and how did u solve it can u please help,even im stuck in here
