### ISSUE TITLE
Double Tap with Swipe

### ISSUE THREAD

**Issue by brunoandradebr** [react-navigation/react-navigation#5371]
There is a bug where you get stucked.

Scenario :

tap a BottomTabNavigator button, transition - will take you to the next screen (it's ok) once you got there, if you tap it's current screen BottomTabNavigator button, AND back to previous screen WITH SWIPE, then if you try to navigate back tapping the first button nothing happens! Swipe is somehow not changing active flag, and you get stucked.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brunoandradebr** [comment]
lol so just ignore it and keep it bugged.

**Comment by brentvatne** [comment]
@brunoandradebr - don't use this library if you can't follow the issue template to report bugs, thanks!
