### ISSUE TITLE
How to change tabs size individually 

### ISSUE THREAD

**Issue by appify-waheed** [react-navigation/react-navigation#5374]
I am using react-navigation version "1.0.0-beta.11" and i am implementing a tabNavigator component with scrollEnabled but i when pass property scrollEnabled tabs size become bigger i want to reduce tab size as show you can see in the image below i tried with this but this code changes the width of the tabs container.
`tabBarOptions: {
style: {
width: 100
 }
}`

<img width="313" alt="screen shot 2018-12-13 at 3 04 53 pm" src="https://user-images.githubusercontent.com/45425486/49934111-4dc20580-feef-11e8-9d9f-4d01fa5ae1d9.png">

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

and also you're using a too old version of react-navigation.
