### ISSUE TITLE
Add animagion to reset route stack to a new route

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-navigation/react-navigation#5387]
Great library with lack of animated transitions:
e.q. on SwitchNavigator or in this case when we reset the stack.

This is simple a must. Please vote here: https://react-navigation.canny.io/feature-requests/p/reset-route-stack-to-a-new-route-with-animation

**Comment by brentvatne** [comment]
https://github.com/elyalvarado/react-navigation-switch-transitioner is a navigator that you can use animate transitions in switch. if you'd like to implement some kind of animations when resetting stack you're welcome to open a rfc to describe how to implement this but we don't plan on building this right now because it's low priority compared to some other work
