### ISSUE TITLE
Drawer navigation back returns to first page

### ISSUE THREAD

**Issue by vatex** [react-navigation/react-navigation#5390]
I used the latest version of react-navigation demo: https://expo.io/@react-navigation/NavigationPlayground
This is the result, so I will describe what I did and what it should do.
Video: https://photos.app.goo.gl/qBvX9D2XYKwBDHEr7

1) I opened the app and clicked on "Drawer Example"
2) Then I clicked "OPEN OTHER SCREEN" button and moved on next screen.
3) Then I clicked "GO BACK" button and instead of moving from that page to the previous one, I returned to the first page

I don't know which version is used on that example, so I think someone will guess it, I don't know...

I have that problem in my project, I use DrawerNavigation and when I run "go back" function, it doesn't move to the previous page.

**Comment by brentvatne** [comment]
only in this example because it explicitly does that in code: https://github.com/react-navigation/react-navigation/blob/4fb6b163acc4e57bb9d0be169b90b07a7d9bf4a8/examples/NavigationPlayground/js/Drawer.js#L25

if you just call `goBack()` then it works as you'd expect here. we could change the button title in navigationplayground to make that more clear, like "Go back to index", but either way this isn't a bug

**Comment by vatex** [comment]
@brentvatne Wow, it's really interesting, but I am sure that I use this code: "this.props.navigation.goBack();" to go back but it returns me at the first screen, not previous. I use "createDrawerNavigation" to make screens.

**Comment by brentvatne** [comment]
create a new issue that includes a repro then, the example you linked to / showed a video of in your original post works as expected
