### ISSUE TITLE
createDrawerNavigator does not handle open/close gestures

### ISSUE THREAD

**Issue by AssafMalki** [react-navigation/react-navigation#5426]
### Current Behavior

I'm using React-Navigation V3, this is my code

```
import React from "react";
import { StyleSheet, TouchableOpacity } from "react-native";
import { createStackNavigator, createDrawerNavigator } from "react-navigation";
import MaterialIcon from "react-native-vector-icons/MaterialIcons";
import FontAwesome5Icon from "react-native-vector-icons/FontAwesome5";
import Home from "../Home";
import Profile from "../Profile";
import DrawerContainer from "../common/DrawerContainer";
import Colors from "../../helpers/Colors";

const styles = StyleSheet.create({
  drawerButton: {
    paddingRight: 20,
    paddingTop: 4
  },
  alertButton: {
    paddingLeft: 15,
    paddingTop: 2
  }
});

const DrawerStack = createDrawerNavigator(
  {
    Home: { screen: Home },
    Profile: { screen: Profile }
  },
  {
    // contentComponent: DrawerContainer,
    drawerPosition: "right",
    drawerWidth: 200
  }
);

const drawerButton = navigation => (
  <TouchableOpacity onPress={navigation.toggleDrawer}>
    <MaterialIcon
      name="menu"
      size={27}
      color="white"
      style={styles.drawerButton}
    />
  </TouchableOpacity>
);

const AlertButton = () => (
  <TouchableOpacity>
    <FontAwesome5Icon
      name="bell"
      size={21}
      color="white"
      light
      style={styles.alertButton}
    />
  </TouchableOpacity>
);

const AppStack = createStackNavigator(
  {
    DrawerStack: { screen: DrawerStack }
  },
  {
    defaultNavigationOptions: ({ navigation }) => ({
      headerStyle: { backgroundColor: Colors.primary },
      title: "Title",
      headerTitleStyle: {
        fontFamily: "casual",
        marginTop: 5,
        textAlign: "left",
        flex: 1
      },
      headerTintColor: "white",
      headerLeft: drawerButton(navigation),
      headerRight: AlertButton()
    })
  }
);

export default AppStack;

```

When I try to open/close the drawer using a slide gesture, it doesn't work.

### Expected Behavior

Slide gesture should open/close the drawer

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 10.14.2
| npm | 6.4.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
here's some info on how to make a minimal reproducible example: https://stackoverflow.com/help/mcve
