### ISSUE TITLE
tabBarOnPress in BottomTabNavigator Bug

### ISSUE THREAD

**Issue by lzdyes** [react-navigation/react-navigation#5435]
In Android

tabBarOnPress does not work. if you tap label, tabBarOnPress  work. if you tab icon or space around, is not callback tabBarOnPress.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by alainib** [comment]
same bug for me 

		const MyTabView = createBottomTabNavigator(
		  {
			FeedObservations: { screen: FeedObservations },
			Projects: { screen: Projects },
			NewObservation: { screen: NewObservation },
			Explorer: { screen: Explorer },
			Profil: { screen: Profil }
		  },
		  {
			swipeEnabled: false,
			initialRouteName: initialRouteName,
			tabBarPosition: "bottom",
			tabBarOptions: {
			  showLabel: false
			}
		  }
		);
		
		
		
		
		class FeedObservations extends React.PureComponent {
		  static navigationOptions = ({ navigation }) => {
			return {
			  tabBarIcon: ({ tintColor }) => <IconFA name="users" size={Config.iconSize.m} color={tintColor} />,
			  tabBarOnPress: (tab, jumpTo) => {
				//!!!! never called if showLabel is set to false ! 
				console.log("feed tabBarOnPress");
				 
				navigation.navigate("FeedObservations");
			  }
			};
		  };

react-navigation 3.3.2
react-native  0.58.6

any tips ? thanks

**Comment by alainib** [comment]
a partial fix with touchableOpacity 

	import React from "react";

	import { TouchableOpacity } from "react-native";
	import IconIonic from "react-native-vector-icons/Ionicons";
	import Config from "plantnet/src/Config";
	import AddObservation from "plantnet/src/stacknavigator/AddObservation";

	export default class NewObservation extends React.PureComponent {
	  static navigationOptions = ({ navigation }) => {
		return {
		  tabBarIcon: ({ tintColor }) => (
			<TouchableOpacity
			  underlayColor={Config.colors.touchOpacity}
			  onPress={() => {
				navigation.navigate("AddObservation");
			  }}
			>
			  <IconIonic name="md-camera" size={Config.iconSize.xxl} color={tintColor} />
			</TouchableOpacity>
		  )
		};
	  };

	  render() {
		return null;
	  }
	}

**Comment by brentvatne** [comment]
hey @alainib - if you are still having this issue please create a new issue and follow the template, thanks!
