### ISSUE TITLE
Navigating to current route in Drawer sidebar doesn't close the drawer.

### ISSUE THREAD

**Issue by kodayashi** [react-navigation/react-navigation#5439]
---

### Current Behavior

The drawer in a DrawerNavigator doesn't close when trying to navigate to the route the drawer is already on. So, if you :

1. Create Screens 1, 2 and 3 and add them to a sidebar component that's in a Drawer (w/ Screen 1 being the default)
2. Toggle the drawer on screen 1 (which shows the sidebar with buttons to navigate to screens 1, 2 or 3
3. Click on Screen 1

Then nothing happens and the drawer stays open. Clicking on any *other* button to go to a new route works, and the drawer is closed.

### Expected Behavior

The drawer should just close, leaving you on the same route.

### How to reproduce

Steps above provided

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest
| node             | 10.x stable
| npm or yarn      | yarn

**Comment by kodayashi** [comment]
Sounds like I'm basically hitting #4342, but again this only happens if I'm clicking on the link that's the current route (which I can see under the sidebar that comes out).

FWIW, since the sidebard is a separate component, I'm using the new `NavigationService` approach documented to navigate. I could just force call `closeDrawer` but I would be calling that for every link since there's not an easy way for me to understand whether or not I should call it (i.e. which route I'm on and which route I'm trying to go to).

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by baaluo** [comment]
@kodayashi Thanks, your solution works for me as well :)

**Comment by didac-wh** [comment]
Facing this too, but the currently loaded view with new parameters doesn't update (not even passing a unique 'key'). So 2 issues that I see:

- The drawer won't close when trying to navigate to same route.
- The screen constructor(), componentDidMount() or render() won't be executed (hence nothing changes). componentDidUpdate() seems to be executed, but forcing a forceUpdate() inside creates a looping error.

**Comment by dennisclementino** [comment]
Who is looking for a quick fix.

this.props.navigation.openDrawer();
this.props.navigation.closeDrawer();

https://reactnavigation.org/docs/en/drawer-based-navigation.html
