### ISSUE TITLE
Deep link not Updating Props to screen already in the Stack

### ISSUE THREAD

**Issue by tehjnito** [react-navigation/react-navigation#5452]
When I open a deep link that routes to a screen that is currently active or already in the stack - the props sent to the screen doesn't change (works perfectly if said route wasn't already in the stack).

I've checked the react lifecycle methods and the 'nextProps' that is provided in 'componentWillReceiveProps' has the same value as the initial props sent to the screen the first time I navigated to it.

I know that navigating to the same route even with different params will only bring me back to the same screen with the old data, and I know that this behavior can be avoided by providing a unique value to the 'key' argument to the navigate function (or by using push()...) and that is how Ive been handling this situation within the app....HOWEVER...since I've not seen anywhere in the docs that tell me I can override this behavior by passing a 'key' or use push() for the deep links opened.

Also, side note...I also tried using the Linking module that comes with react native and do the navigation myself without using the 'path' thingy.....but this doesnt work for me as Ive wrapped my root thing in a HOC and it just keeps screaming about my screenProps (which I cannot do without)

---

### Current Behavior

opening a deep link that routes to a screen already in the stack, doesn't update the props of that screen

### Expected Behavior

I expected it to push a new instance of that route to the stack with the new props

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1
| react-native     | 0.55.4
| node             | 10.11.0
| npm or yarn      | yarn (1.10.1)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by diamont1001** [comment]
try this:
```js
componentDidUpdate() {
    const blogId = this.props.navigation.getParam('blogId', 0);

    ...
  }
```

**Comment by tlow92** [comment]
Issue still exists in v5.
e.g. Call ```adb shell am start -W -a android.intent.action.VIEW -d "app://tasks/1" com.app.app``` and when routing finished call ```adb shell am start -W -a android.intent.action.VIEW -d "app://tasks/2" com.app.app```. The component does not rerender so useEffect is not even called.
