### ISSUE TITLE
After 2 forward navigations in DrawerNavigator the first goBack() goes back to the first screen instead the second one

### ISSUE THREAD

**Issue by LucasBrazi06** [react-navigation/react-navigation#5475]
### Current Behavior

```
// My Drawer Navigator
const DrawerNavigator = createDrawerNavigator(
  {
    Sites: { screen: Sites },
    SiteAreas: { screen: SiteAreas },
    Chargers: { screen: Chargers }
  },
  {
    navigationOptions: {
      swipeEnabled: true,
    },
    drawerWidth: Dimensions.get("window").width / 1.5,
    initialRouteName: "Sites",
    drawerPosition: "right",
    contentComponent: props => <Sidebar {...props} />
  }
);
```
My initial screen is Sites and then I navigate:

Sites -> navigation.navigate("SiteAreas") -> SiteAreas -> navigation.navigate("Chargers") -> Chargers -> navigation.goBack() -> Sites (I would expect to go back to SiteAreas)

When I use push() instead of navigate() it works but I cannot open the Drawer, it dumps!

### Expected Behavior

goBack() method should go back to the previous screen and not the first one in the stack.

### How to reproduce

Create a stack with 3 screens, perform two calls to navigate() and one go back and you end up in the first screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.3
| react-native     | 0.57.8
| node             | 8.11.3
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by LucasBrazi06** [comment]
Hi guy, what is difficult to navigate to 3 screens and do one goBack() !!!
You should have that even in your unit test !?

**Comment by LucasBrazi06** [comment]
Nevertheless I understand your point of view.
Here is my snack!
https://snack.expo.io/@lucasbrazi06/navigation-goback-issue
Thanks for investigating.
