### ISSUE TITLE
 createMaterialTopTabNavigator add tab bar label dynamically based on API response  

### ISSUE THREAD

**Issue by KeerthanaManoharan** [react-navigation/react-navigation#5490]
Hi 

In my case I need **3 tabbar label to be static**   and 2 should be added dynamically based on API reponse flag Please give the solution how can I do ..

Thanks in advance

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!

**Comment by vikramkh** [comment]
Did you solve this? Is seems to be an issue because you have to take in props in order to create something dynamically, but if you take in props, you have to return a react component. You can't return a tab navigator as a component so you have to create a new app container, which then causes a warning.
