### ISSUE TITLE
Empty header when nesting StackNavigator and TabNavigator

### ISSUE THREAD

**Issue by dnish** [react-navigation/react-navigation#5502]
After upgrading from 1.0.0-beta13 to the latest version, I'm having a little issue with nesting StackNavigator and TabNavigator. On top of our routes, we have a navigator which defined the routes for "logged in" users:

```
const LoggedIn = createStackNavigator({
    Dashboard: {
        screen: Dashboard
    },
    Player: {screen: Player}
});
````

The dashboard contains a TabBar navigator, which is defined like this:

```
const DashRoutes = createBottomTabNavigator({
    DashboardHome: {screen: Home},
    DashboardMusic: {screen: Music},
    DashboardSearch: {screen: Search},
    DashboardPlaylists: {screen: Playlists},
    DashboardAccount: {screen: Account}
});
```

All header information are saved within the DashRoutes, so for example, the Search component has a static variable:

```
static navigationOptions = {

        tabBarIcon: ({tintColor}) => (<Icon name="md-search" style={{color: tintColor}}/>),
        tabBarLabel: i18n.t('search.tabTitle'),
        headerTitle: <HeaderSearch/>,

    };
```

If I open the app, the header stays white and empty, on all routes. I can modify the header when I set defaultNavigationOptions within the LoggedIn navigator, but this doesn't solve my issue. Any idea what has changed and how we can nest both navigators again?

BTW: I already found a solution, telling that we need to create a StackNavigator for each route within the TabNavigator, f.e.:

    DashboardHome: {screen: createStackNavigator({Home})}

This let me show a header, but creates a new issue: Properties like <code>tabBarIcon</code> are not 
available anymore and so the TabBar doesn't render any icons.

Version: 3.0.9
RN: 0.57.8

Tested on iOS 12 / iPhone 6s.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
