### ISSUE TITLE
Stack Navigator, resetting last stack screen, to first.

### ISSUE THREAD

**Issue by shubhamdeol** [react-navigation/react-navigation#5505]
my createDrawerNavigator looks like this:

```javascript
 {
    Home: HomeStackNavigator,
    Orders: OrdersStackNavigator,
  }
```
HomeStackNavigator flow is like:  Home => Products => Cart => placeOrder 

after placeOrder screen I navigate user to Orders i.e **OrdersStackNavigator**.

Now comes the issue, 
when hardware android back buttun is pressed user goes to **placeOrder** again, I want user to be navigated to Home Screen.

Is this possible to navigate for orders screen and resetting previous stack to index 0

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by alexsergeev** [comment]
@shubhamdeol - Have you found any solution to this issue?
