### ISSUE TITLE
invariant violation element type

### ISSUE THREAD

**Issue by jasuno** [react-navigation/react-navigation#5507]
Invariant Violation: Element Type is Invalid: expected a string

![simulator screen shot - iphone xs - 2019-01-22 at 04 29 09](https://user-images.githubusercontent.com/29812661/51525433-5535d200-1dfe-11e9-9354-49a469f81ce9.png)

here is my code

import React, { Component } from 'react';
import { Provider } from 'react-redux';
import store from './app/store';
import { Auth, NavBar } from "./app/config/routes";
import SplashScreen from "./app/screens/splashScreen";
import {Font} from "expo"
import AuthStore from "./app/stores/authenticate"
import {observer} from "mobx-react/native" 

@observer

export default class index extends Component  {

  state = {
    fontLoaded: false
  }
  async componentDidMount() {
    await Font.loadAsync({
      'OpenSansBold': require('./app/assets/fonts/OpenSans-Bold.ttf'),
      'OpenSans': require('./app/assets/fonts/OpenSans-Regular.ttf'),
      'OpenSansItalic': require('./app/assets/fonts/OpenSans-Italic.ttf'),
      'OpenSansLight': require('./app/assets/fonts/OpenSans-Light.ttf'),
    });
    this.setState({ fontLoaded: true });
  }

  render() {
    const MainScreen = AuthStore.isAuthenticated ? NavBar : Auth;
    return (
      <Provider store={store}>
      {this.state.fontLoaded ? <MainScreen /> : <SplashScreen /> }
      </Provider>
    );
  }
 
}

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
