### ISSUE TITLE
Back transition from custom header screen to non header screen looks broken

### ISSUE THREAD

**Issue by jeremyscatigna** [react-navigation/react-navigation#5520]
### Current Behavior

In some screens of my StackNavigator I use a custom header, when I go back from a screen with the custom header to a screen without during the transition it shows the Native IOS header

here is a video of it: 
![ezgif com-crop](https://user-images.githubusercontent.com/15782436/51692542-6d277480-1ffd-11e9-942c-e94d97affb46.gif)

### Expected Behavior

It should not remove my custom header

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.1
| node             | 10.13.0
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by matheusbaumgart** [comment]
I'm having the same issue. The custom header is removed while the transition is happening :(
You can use `headerTransparent: true` to minimise the "flickering" but it's still a big problem depending on how you design your custom header and if the next or previous views have the same header.

**Comment by acoutts** [comment]
Has anyone found a solution to this? I've been having the same thing happen as well.

**Comment by rexlow** [comment]
I am still facing this issue with `v5.0.5`. Only way I can fix this is by disabling the header and manually displaying it as a view in every view.
