### ISSUE TITLE
createDrawerNavigator showing Black Screen

### ISSUE THREAD

**Issue by anurbecirovic** [react-navigation/react-navigation#5527]
### Current Behavior
- NOTE: Everything is working perfectly on my last project 5 weeks ago.

- createDrawerNavigator is not working.
Few minutes ago I followed documentation and installed react-navigation. I used example from my previous project where I use createDrawerNavigator. When applied the screen is completely back. I tried everything to make it work. And found out that stack navigator is only working. Please help

![simulator screen shot - iphone x - 2019-01-26 at 17 04 00](https://user-images.githubusercontent.com/24942592/51790882-430bb900-219b-11e9-912f-321d213e9960.png)

### Expected Behavior
Main page showed with text in the middle with hamburger menu in right corner. 

### How to reproduce

> import { createDrawerNavigator } from 'react-navigation';
import Main from '../components/Main';
import Profile from '../components/Profile';

> const LoggedInNavigator = createDrawerNavigator(
  {
    Main: {
      screen: Main,
      navigationOptions: {
        title: 'Main Screen'
      }
    },
    Profile: {
      screen: Profile
    }
  },
  {
    drawerPosition: 'right',
    initialRouteName: 'Main'
  }
);

export default LoggedInNavigator;

### Your Environment
everything is latest npm and raact native project etc.

**Comment by anurbecirovic** [comment]
Same issue is on createTabNavigator 
<img width="388" alt="screenshot 2019-01-26 at 20 51 15" src="https://user-images.githubusercontent.com/24942592/51792020-2b88fc00-21ac-11e9-90ab-2c25ba13a52a.png">

- navigation/index.js: 
```
import React from "react";
import { createBottomTabNavigator, createAppContainer } from "react-navigation";

import Login from "../components/Login";
import Profile from "../components/Profile";

export const Tabs = createAppContainer(
  createBottomTabNavigator(
    {
      Login: {
        screen: Login
      },
      Profile: {
        screen: Profile
      }
    },
    {
      initialRouteName: "Login"
    }
  )
);
```
- App.js: 
```
import React, { Component } from "react";
import { Platform, StyleSheet, Text, View } from "react-native";
import { Tabs } from "./src/navigation";
export default class App extends Component {
  render() {
    return <Tabs />;
  }
}

```
Simplest example but still not working..

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
