### ISSUE TITLE
When pop (back from screenA to screenB) i can see a blue back button flash by,how to hide it.

### ISSUE THREAD

**Issue by zaxayn** [react-navigation/react-navigation#5533]
### Current Behavior

i find when i click back button from screenA (that use customized header) pop to screenB (that set header to null and add header in render),i can see a blue back button flash by.

### Expected Behavior

how to hide the default button.

### How to reproduce
```
        screenB: {
            screen: screenB,
            navigationOptions: ({ navigation }) => ({
                header: null,
            }),
        }
        screenA: {
            screen: screenA,
            navigationOptions: ({ navigation }) => ({
                header: <TitleBar .../>
            }),
        }
```

### Your Environment
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 10.13.0
| npm or yarn      | npm 6.5.0
![image](https://user-images.githubusercontent.com/11364809/51902918-130c2200-23f6-11e9-8640-bc97bfe2cecb.png)
![image](https://user-images.githubusercontent.com/11364809/51902924-169fa900-23f6-11e9-9f6a-e7a951432515.png)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by jrounsav** [comment]
For anyone else seeing this, I'm finding that this only occurs when going back to a screen with a null header.
Here's a dumb fix

```
Home: {
    screen: Home,
    navigationOptions: {
      header: () => {
        return <View></View>
      }
    }
  },
```

**Comment by mitulsavani** [comment]
is there any other reference to this issue?

**Comment by sorakrisc** [comment]
I also have this trouble agree with @jrounsav when going toward or back from a screen with null header the back button will flash


In my case: My screen header was a custom component
`Home: {
        screen: HomeTabs,
        navigationOptions: ({navigation})=>({
            header: <Header navigation={navigation}/>,
            headerStyle:{elevation:0,  borderBottomWidth: 0, backgroundColor:"#FFFFFF"},
            gesturesEnabled: false,
            headerLeft: null           <-------------------------------------- SOLUTION
        })
    },`

SOLUTION :  add `headerLeft:null` to navigationOption on the page where you messed with the header
