### ISSUE TITLE
Back pops to wrong screen

### ISSUE THREAD

**Issue by inpendio** [react-navigation/react-navigation#5547]
### Setup
```
const WorkNav = createStackNavigator({
Start,
Shop,
Food
},{initialRoute:'Start'})
const MainNav = createBottomTabNavigator({
HomeNav:createStackNavigator({...}),
OtherNav:createStackNavigator({...}),
Work:WorkNav,
},{initialRoute:'Work'})
```

### Current Behavior

So I start on WorkNav->Start, then I navigate to either Shop or Food. When I go back ( with header back button or with android back button) I end up on the initialRoute of the OtherNav.

### Expected Behavior

I should be back on the initialRoute of the WorkNav.

### How to reproduce
Combine several stack navigators in similar fashion as presented above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.2
| react-native     | 0.57.8
| react  | 16.7.0
| android             | 25(emulator)
| npm or yarn      | yarn

I also inspected the whole stack with dangerouslyGetParent().state, and at first the route is ok (Start), but once I navigate to screen the first route in array changes to Other ( initialRoute of OtherNav).

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
