### ISSUE TITLE
Background color for statusbar doesn't work in StackNavigator

### ISSUE THREAD

**Issue by berpcor** [react-navigation/react-navigation#5548]
```
"react-native": "0.57.7",
"react-navigation": "^3.0.1",
```
```
const BottomMenuStack = createBottomTabNavigator({
    Tab1: {
            screen: Tab1Stack,
            navigationOptions: ({ navigation }) => {
                return {
                    title: "Title",
                    tabBarIcon: <Icon name="heart" size={20} color="#FF0000" />,
                
                };
            }
        },
})
```

If Tab1Stack is component itself:

```
class Tab1 extends React.Component {

    constructor(props){
        super(props);
    }

    render(){
        return(
            <SafeAreaView style = {{ flex: 1, backgroundColor: 'red' }}>
            
            
            <View style = { styles.container } >
                <StatusBar
                        backgroundColor="red"
                        barStyle={'dark-content'}
                />
                <Text
                    style={styles.title}
                    onPress={() => { }}
                >
                    Tab 4
                </Text>
            </View>

            </SafeAreaView>
        )
    }

}
```
then color of status bat is red (iphone X), but if it will be another stack like:

```
const Tab1Stack = createStackNavigator({
    T1S: {
        screen: Tab1,
        navigationOptions: ({ navigation }) => {
            return {
                title: "Title",
                tabBarIcon: <Icon name="align-justify" size={20} color="#FF0000" />
            };
        }
    }
});
```

coloring doesn't work. Why?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
