### ISSUE TITLE
Undefined is not an object(evaluating this._setComponentRef.bind)

### ISSUE THREAD

**Issue by musti-91** [react-navigation/react-navigation#5551]
### I cannot navigate or push to this tabs screen.

---

### Current Behavior

```typescript 
const Dummy = createSwitchNavigator({
  SignIn,
  SignUp
})

const Tabs = createBottomTabNavigator({
  main: {
    screen: MainContainer
  },
  comp: {
    screen: MyComponent
  }
})

const MainStackNavigator = createSwitchNavigator({
  auth: Dummy,
  tabs: Tabs
})
export default createAppContainer(MainStackNavigator)
```
<img width="373" alt="screenshot 2019-02-01 at 14 54 31" src="https://user-images.githubusercontent.com/36855525/52127146-8e0d4c80-2631-11e9-8f24-8035f4115d74.png">

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native        |   0.58.3 typescript
| node                    |    v10.9.0
| npm or yarn        | 6.5.0 & 1.9.4

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
