### ISSUE TITLE
Switch navigator: half screen rendered as previous screen, half screen as current (tab navigator)

### ISSUE THREAD

**Issue by DimitryDushkin** [react-navigation/react-navigation#5556]
May be someone have a clue what is happening? I'll provide full functional example a bit later.
So structure is simple:

- Switch navigator
  - App loading screen
  - Tab navigator
    - Tab with feed screen
    - Tab with other screen

When navigating from "App loading screen" to "Tab with feed screen"  sometimes (1 of 10) we've got this bug:  
<img width="407" alt="screenshot 2019-02-03 at 18 25 27" src="https://user-images.githubusercontent.com/361327/52178575-88eeff80-27e1-11e9-850f-f191fddf26ea.png">
For some reason "Tab with feed content" takes only half of screen!

The most interesting thing that this bug only reproduces with **"modern" build for ios 12+ as target** and only on real device. Babel config for this build is here — https://gist.github.com/DimitryDushkin/2016a41971b598634a7d16a78c3bb492

Turning on and off _react-native-screens_ has no effect. Bug is still here.

We've done lots of research, but still have no clue.

React Navigation: 3.0.7
React Native: 0.57.8

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
