### ISSUE TITLE
metro bundler can not find my components only in react-navigation's Navigator

### ISSUE THREAD

**Issue by Oz-on** [react-navigation/react-navigation#5586]
Hi!

I am facing with strange issue and I can not find answer for that.
I searched many issues with problems about resolving modules and I tried to take suggested steps, but unfortunately didn't work. Furthermore, my problem is occurs only when I want to import my own components not modules from npm. I double checked correctness of paths and everything is correct. Before creating and adding `AppNavigator` to `App` component everything worked fine.

### Current Behavior
During starting app, and loading dependency graph, error message shows up like below:

Error: Unable to resolve module `../screens/authentication/authLoadingScreen` from `[path_to_project]/src/routes/AppNavigator.js`: The module `../screens/authentication/authLoadingScreen` could not be found from `[path_to_project]/src/routes/AppNavigator.js`. Indeed, none of these files exist:
 `[path_to_project]/src/screens/authentication/authLoadingScreen(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`

### Expected Behavior

- App should load and AuthLoadingScreen (component) from authLoadingScreen.jsx should be launched because, this component is set as `initialRouteName: 'AuthScreen'`

### How to reproduce

As it is written in console, problem is here
Code of AppNavigator.js file
```
import { createSwitchNavigator } from 'react-navigation';
import AuthStack from './AuthenticationNavigator';
import AppStack from './MainTabNavigator';
import AuthLoadingScreen from '../screens/authentication/authLoadingScreen';


const AppNavigator = createSwitchNavigator(
  {
    AuthScreen: {
      screen: AuthLoadingScreen
    },
    App: {
      screen: AppStack,
    },
    Auth: {
      screen: AuthStack,
    },
  },
  {
    initialRouteName: 'AuthScreen',
  }
);

export default AppNavigator;
```

And I am using above AppNavigator in App.js file

```
import React, { Component } from 'react';
import { createStore, applyMiddleware } from 'redux';
import { Provider } from 'react-redux';
import createSagaMiddleware from 'redux-saga';
import rootReducer from './src/redux/reducers';
import rootSaga from './src/redux/saga';
import { composeWithDevTools } from 'redux-devtools-extension';
import { createAppContainer } from 'react-navigation';
import AppNavigator from './src/routes/AppNavigator';

const sagaMiddleware = createSagaMiddleware(rootSaga);
const middlewares = [sagaMiddleware];

const AppContainer = createAppContainer(AppNavigator);

export const store = createStore(
  rootReducer,
  composeWithDevTools(
    applyMiddleware(...middlewares)
  )
);

export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <AppContainer/>
      </Provider>
    );
  }
}

sagaMiddleware.run(rootSaga);
```

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.2.1
| react-native     | 0.57.4
| node             |  10.15.0
| npm or yarn      | 6.7.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
