### ISSUE TITLE
强烈要求中文翻译格式走点心

### ISSUE THREAD

**Issue by youngjuning** [react-navigation/react-navigation#5587]
https://reactnavigation.org/docs/zh-Hans/stack-navigator.html#%E7%94%A8%E4%BA%8E%E5%AF%BC%E8%88%AA%E5%99%A8%E5%86%85%E9%83%A8%E9%A1%B5%E9%9D%A2%E7%9A%84-navigationoptions

请问如何参与翻译，这个是严重影响阅读

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
