### ISSUE TITLE
Deep linking host issue in React Native

### ISSUE THREAD

**Issue by saurabh-nandan** [react-navigation/react-navigation#5593]
## I am using Deep linking in React Native

While i am using scheme in Manifest file its working perfectly but i need to use host for my App its can't fulfill my request.

<intent-filter >
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <category android:name="android.intent.category.LAUNCHER" />
            <data android:scheme="peopleapp" 
                  android:host="www.people.com"
            />
        </intent-filter>

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |"^3.2.1"
| react-native     |"0.58.4",
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
