### ISSUE TITLE
Screen getting stuck when navigate

### ISSUE THREAD

**Issue by rochapablo** [react-navigation/react-navigation#5598]
This is basically the scructure of my files, where in home I list the products. And I have another screen which gives the detail of each product, by id.

The problem is that somethimes navigating between those products the screen get stuck in a blank screen (android) or black screen (ios) and worse, without error.

**app.tsx**

```
const RootStack = createDrawerNavigator(
  {
    About: { screen: AboutScreen },
    ...
  },
  {
    backBehavior: 'none',
    contentComponent: DrawerComponent,
    drawerLockMode: 'locked-closed',
    initialRouteName: 'Home',
  },
);

const AppContainer = createAppContainer(RootStack);

export default class App extends React.Component {
  public render() {
    return (
      <Provider store={store}>
        <PersistGate loading={<Loading />} persistor={persistor}>
          <AppContainer />
        </PersistGate>
      </Provider>
    );
  }
}
```

**home.tsx**

```
class HomeScreen extends React.Component<IProps, IState> {
    ...
}

export default connect(mapStateToProps, mapDispatchToProps)(HomeScreen);
```

This is the normal screen, when rendered

![ok](https://i.imgur.com/8g7wcid.png)

And this is when stuck

![nok](https://i.imgur.com/5PpNvRS.png)

Could be this *ResourceSavingScene* the problem? If so, why? I'm not using *TabNavigator*.

I understand that react-navigation lib will not support Redux issues, but I'll leave this here in case of some could help.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.2.3
| react-native     | 0.58.4
| node             | 10.15.0
| npm or yarn      | 6.4.1 (npm)

**Comment by rochapablo** [comment]
I may have found something, but still having a problem.

Since I was already using older versions, to navigate between the same screen but with different id, I did some workaround like

```
const options = {
    params: { action: 'Detail', params: { id: item.id } },
    routeName: 'Redirect',
};
props.navigation.navigate(options);
```

Meaning that every time that I wanted to change to another product the view `Detail` would redirect to `RedirectScreen` passing a new ID and the `RedirectScreen` would do

```
const navigation = this.props.navigation;
const getParam = navigation.getParam;
const action = getParam('action');
const params = getParam('params');
navigation.navigate(action, params);
```

All this, because `key` attribute from react-navigation, never worked to navigate to same screen. Even now using `push` (newest react-navigation version) it says that it's undefined function.

That said, the problem seems that sometimes RedirectScreen it's not receiving the parameters.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by shariq93** [comment]
I have used an alternative approach to solve this issue
https://medium.com/@shariq93/screen-getting-stuck-when-navigate-react-navigation-e6d2561a3381?sk=09f48fbd5175dce1886846e015d1da07
