### ISSUE TITLE
Force navigation to a ab stack when clicking the bottom icon

### ISSUE THREAD

**Issue by vinoa-team** [react-navigation/react-navigation#5641]
### Current Behavior

Hi, I have a React Native application, with three menu items: 
- Home
- Login
- Competition

Each of these tabs is a stack of several screens, and some screens are shared across stacks:
- Home stack: HomeView, EventListView, LoginView, EventBookingConfirmationView
- Login stack:  LoginView, SignupView, MyProfileView
- Competition stack: LoginView, CompetitionView

The reason we duplicated the login screen in several stacks is to keep the navigation within one stack: if you start from the Home stack to find events around you (using a list view) you can then go to an event detail page. Clicking the "Book this event" you are directed to a login page. From there you login, and then go to the Event Booking Confirmation. 
Having all the screens in the same stack makes it visually unified because the active tab at the bottom stays on the "Home" icon and doesn't "switch" to the Login Stack when on the Login Page, and then back to "Home" on the Event confirmation page

However one issue we now have, is that the click on the bottom "Login" icon in the menu bar "doesn't work"
It pulls up the LoginView from within the HomeStack instead of "switching" tab and setting the "Login" icon to active and pulling up the oginStack

### How to reproduce

If you create the nested structure described, you will be able to reproduce the issue.

what I would like is a way to say" when clicking on the Login Icon menu item, and that stack is not the current focused one, then switch to LoginStack and make it the active one

### Your Environment

    "react-native": "0.57.5",
    "react-navigation": "^3.0.0",

**Comment by brentvatne** [comment]
please provide a reproducible example so that we can help you by updating the code directly

**Comment by vinoa-team** [comment]
Hi @brentvatne - thanks for the reply. I've attached my Stack Config file, I think this will help to reproduce the issue.

If you try and implement the structure (or reproduce with a similar list of shared screens across stacks, you should see that when clicking the bottom nav items, the tint colour doesn't change over to the stack you want, and the screen animation also clearly shows that the screen is pulled form the "wrong" stack.

[routes.txt](https://github.com/react-navigation/react-navigation/files/2925723/routes.txt)

**Comment by brentvatne** [comment]
@vinoa-team - sorry we don't have time to try to reproduce your issue, you're welcome to provide a [mcve](https://stackoverflow.com/help/mcve) and we can look. see our standard reply for these situations below for more info

<hr />

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by vinoa-team** [comment]
Hey Brent,
Sure, have made a new project from scratch, using create-react-native-app, and then created the structure below:
homeStack: HomeView and LoginView
loginStack: LoginView and ProfileView

You can see the full code here: [https://snack.expo.io/@greg_frileux/react-nav-bug-bottom-bar](https://snack.expo.io/@greg_frileux/react-nav-bug-bottom-bar)

The issue is completely reproduced:
- When you are on the Home Stack, the bottom nav bar is correctly showing the "HomeStack" as being active.
- You then click in the bottom nav, on the Login label
- At this point, you would expect the bottom nav bar to update, and to show the "loginStack" as the active stack. You would also expect to see the login View, with no animation between the two screens (jumping fro one tab to the next happens without animation by default)
However this is not what happens: the login view slides in from the right, and is pulled from the homeStack. The bottom nav bar is still showing the "Home" as being the active tab, when it should really have jumped to the "Login"

So why is this an issue?
=> we add the login screen to the home stack, so that when it is needed for a user flow within the home stack (e.g. you see something on the home page, say an event, you click to go to the event detail, and let's say that on that screen there is a "login to register" button. When you click, you want to login and all the while "stay within the home stack" with the correct animation, the correct "Back" buttons in the header, etc.
=> Nonetheless, you still expect and need the bottom nav bar to do it's job and correctly take the user between stacks, and display the correct focus colour in the correct stack. Otherwise it's very confusing for the user.

Also, maybe I've missed it, but if stacks need to be completely mutually exclusive in terms of screens present in each stack, that should perhaps be made very clear early on in the documentation.

I hope that helps ? 

Please let me know your thoughts, and thanks again for looking into it !

**Comment by brentvatne** [comment]
so i'm unsure about how i feel about the naming of the tabs here and i agree it can be confusing and we should document something about route naming in fundamentals section of docs.

that said, i think this pattern that you're using is probably not ideal. what happens if someone is on the first tab and go to the login screen, then switch to the other tab with the login screen? it's always strange to have the same screen open in two places at the same time like that. i think a better pattern for that is to use a modal stack and navigate to it: https://snack.expo.io/@notbrent/react-nav-modal-stack

**Comment by vinoa-team** [comment]
Hi Brent,
Thanks so much for spending some time on this. It seems like the route name isn't the issue as much as the screens that are present in each stack. I've tried changing the routeNames to be exclusive in each stack, but that doesn't do the trick. The library seems to recognise that the screens are the same, and it will pull the screen that it thinks is relevant. he weird thing is that even when the loginStack has a unique screen as initialRoute, it still won't display it when you click the login label in the bottom bar. If you check my udpated snack, you'll see that now I have 
homeStack: HomeView and LoginView
loginStack: WelcomeView, LoginView and ProfileView

If I load the app > Home is focused > click Login in the bottom bar > it shows the LoginView instead of the WelcomeView ?!

This whole thing also has ramifications on the "Back" button in the header: if I stick to completely mutually exclusive stacks, I have the below issue:
- Load the app, and start on the Home stack. Let's say it's a list of events.
- I click an event and navigate to the EventDetail
- I see a button "login to attend this event"
- I click this button, it goes to the loginStack, and shows the LoginView
- There is no back button in the header, as we have now swicthed stacks. This is a bit of a problem: I'd like the user to be able to go back to his event detail page

The Modal solution you describe is helpful, but I  really do feel that something is missing in the library, in terms of being ale to say "when I click on the bottom bar, I want to force this stack to load". This is all it would take to solve my issue.

If this can be done in anyway, that would help massively. It means you could have screens in any stack you want, which helps with back buttons, etc. At the same time, the bottom menu acts as  a"normal menu" i.e. when I click on it takes me to the correct stack.

Please let me know your thoughts,
Thanks
Greg

**Comment by brentvatne** [comment]
hi greg, i'm not sure i understand your issue. i think you might have unrealistic expectations for how things should work - if you switch to another tab, there is not a back button to go back to the other tab because that is just not how tab navigation works on any platform. you would need to add a back button yourself. usually this would be in a modal instead and in that case there would be a back button like in my example. if you have a route in both tabs with the same name, it'll go to the one in that tab. see: https://snack.expo.io/@notbrent/react-nav-bug-bottom-bar.

if this doesn't help, you will want to describe what you would like to change in react-navigation in the form of a rfc. please follow the rfc template here: https://github.com/react-navigation/rfcs

**Comment by vinoa-team** [comment]
Ho Brent - I don’t not want the back button to work across tab, I want the click on a tab to switch to the stack associated to that tab - I think that’s fair enough

Let me perhaps te-explain again. Imagine this:
Tab A : EventList, EventDetail, Login, EventBookingConfirmation
Tab B: Login, Profile

Now consider this flow:
- load the app
- tab A is active, EcentList is shown
- click to go to EventDetail
- click to Login (in order to sign up to the event)
So far: 
-> all the screens are pulled from Tab A (good)
-> on the Login screen, you have a back button in the header to go back to EventDetail (good)
So far so good

However consider this flow:
- user loads the app
- tab A is active, EventList is shown (good)
- click on Tab B in the bottom bar (in order to login and check something in your profile)
 Expected:
- Tab B becomes active and Login screen is shown

Actual:
- Tab A remains active, Login is shown

Now this is not unrealistic : I would just want Tab B to be shown that’s all

The example above is very very basic, of course our app has many more screens, many more flows. We also use SwitchNavigator to handle logins etc
So I’m not able to convey all the intricacies and different uses cases , but trust me this eemingly small issue is really quite frustrating. 
While the modal kind of helps, it’s doesnt work when you start layering up the sign up flow, with APIs to other systems etc

So once again , the only request is: is there a way to « force » a stack to be loaded when you click it’s corresponding tab in the bottom bar ?

If not, I will complete the feature request

Thanks again for all your help !!

**Comment by brentvatne** [comment]
the code i shared above does exactly what you ask for - https://snack.expo.io/@notbrent/react-nav-bug-bottom-bar

**Comment by vinoa-team** [comment]
Hi Brent - awesome - you're a star.

So as it turns out (just in case anyone reads this in the future), the issue was that I had the same name for the tab in createBottomTabNavigator 
`const MainTabNavigator = createBottomTabNavigator(
  {
    Home: loggedOutHomeAndHappeningsStack,
    Login: loggedOutLoginStack,
    Competition: loggedOutcompetitionStack,
  },
  tabBarDefaultOptions
);
` 
tabName === 'Login'

and for the LoginView in my stack : 
`const loggedOutLoginStack = createStackNavigator(
  {
    [WELCOME_VIEW_SCREEN]: { screen: WelcomeView },
    [LOGIN_SCREEN]: { screen: Login },
    [FORGOT_PASSWORD_SCREEN]: { screen: ForgotPassword },
    [SIGNUP_SCREEN]: { screen: Signup },
    [SIGNUP_ENTER_PERSONAL_DETAIL]: { screen: SignupPersonalDetail },
  }
)
`
because the variable LOGIN_SCREEN = 'Login'

This makes the whole thing trip up and created all the issues.

So simply renaming the LOGIN_SCREEN variable to 'LoginView' solved all the issues

Many thanks !! 
Greg
