### ISSUE TITLE
hardware back button does not work after app goes on background mode.

### ISSUE THREAD

**Issue by MrRoot99** [react-navigation/react-navigation#5650]
Hi,
react-native version 0.55.4
react-navigation 2.18.2
when i go to some screen then i press a button and go to browser and then when i back to app
the hardware back button does not work. but it works with custom go back icon.

**Comment by MrRoot99** [comment]
and this problem in the first screen
when i move another screen its work

but in the first screen has problem

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
