### ISSUE TITLE
With  infinite loop animation in previous page, the next page with VirtualizedList + getItemLayout only renders initialNumToRender items

### ISSUE THREAD

**Issue by coolguy001tv** [react-navigation/react-navigation#5652]
### Current Behavior

- When there is a page with some infinite loop animation
- Then navigateTo the 2nd page with VirtualizedList like FlatList or SectionList which has getItemLayout method
- Finally you can see only the initialNumToRender items to be rendered.

### Expected Behavior

-  When scroll this list, the other unseen items should be rendered.

### How to reproduce
- The demo is [here with expo](https://snack.expo.io/@coolguy/section-list-test) .
- If I comment the line 57 in PageA.js (// this.animateCollect();), the SectionList in PageB shows OK; but if I uncomment the line 57 in PageA.js, the bug happens.
**Attention:** If you want to test this in your phone, after commenting line 57, please exit the app and reenter, the hot reload seems to be wrong after commenting.

The bug is previously discussed [here in React-Native issues ](https://github.com/facebook/react-native/issues/22194) , and it seems it's a react-navigation issues, so I put it here.

And furthermore, this bug will disappear if the SectionList has no getItemLayout method. But I need this method to scroll into somewhere. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.0
| react-native     | 0.58.1
| node             |  v10
| yarn      | 1.13

**Comment by brentvatne** [comment]
this isn't an issue with react-navigation, the same issue would exist if you had the animation on the same screen. VirtualizedList uses InteractionManager - https://github.com/facebook/react-native/blob/ddd5b257685caaf3411273da3e1ba4ec275de3e5/Libraries/Interaction/Batchinator.js#L65-L71 - you need to use `isInteraction: false` in your animation config (see https://facebook.github.io/react-native/docs/animated for some vague documentation on it), or disable the animation when you leave the screen (https://reactnavigation.org/docs/en/function-after-focusing-screen.html).

**Comment by brentvatne** [comment]
also the example that you provided does not seem to reproduce the issue that you described. nonetheless the comments i mentioned above still apply

**Comment by brentvatne** [comment]
oh i see on android - but this also has nothing to do with react-navigation because if you just do `export default PageB` in App.js it will show the same behavior you described. this is independent of any animation too.. but it works if you remove your `getItemLayout` function. so i'd look into that if i were you

**Comment by dbarth** [comment]
Just to exonerate react-navigation further: the bug happens with a loop animation in one of the item inside a FlatList. isInteraction: false need to be set on all animated elements, and that's not possible on A.delay() inside a sequence and loop for example. Otherwise running happily with a complex navigation setup here.
