### ISSUE TITLE
Bottom Tab Navigator suddenly not responding to taps anymore

### ISSUE THREAD

**Issue by schumannd** [react-navigation/react-navigation#5661]
Our App has been up and running for close to a year now on RN v51.

From one day to another deleting the node_modules folder and reinstalling caused the Bottom Tab Nav to not respond to clicks anymore.

react-navigation version installed: 2.18.3

Has there been any changes made lately that might have caused an old version to break? I can't think of any other reason for our build to break as we have not changed any package versions. 

node: v9.8.0
npm: 6.8.0

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

if you're on android, make sure you use latest gesture handler dep
