### ISSUE TITLE
NavigationEvents onWillBlur and onDidBlur not called on swipe back on iOS

### ISSUE THREAD

**Issue by miclaus** [react-navigation/react-navigation#5669]
### Current Behavior

I create a Stack Navigator like so:
```js
const AppNavigator = createStackNavigator({
  ListView, DetailView,
})
```

I try to catch the `onWillBlur` and `onDidBlur` events when I swipe Back from `DetailView` to `ListView` on iOS with help of the `NavigationEvents` component as mentioned in the docs:
```js
<NavigationEvents
  onWillBlur={payload => console.log('will blur',payload)}
  onDidBlur={payload => console.log('did blur',payload)}
/>
```

### Expected Behavior

I expect to firstly receive the `will blur` and then the `did blur` logs. However I get no logs at all. Also when I use the Back Button in the `DetailView` I only receive the `will blur` event. So something must be wrong, right?

### How to reproduce

https://snack.expo.io/BymsfYWw4

### Environment

| software         | version
| ---------------- | -------
| react-navigation | `3.3.2`
| react-native     | `0.58.6`
| node             | `10.15.0`
| npm      | `6.4.1`

Thanks for looking into this. In the meantime I plan to disable gestures with `gesturesEnabled: false`.

**Comment by xiongcaichang** [comment]
the same problem with me

**Comment by FeXd** [comment]
Same issue with swipe down to close modal.

**Comment by buoyad** [comment]
Any update? This makes it hard to write custom cross-platform back behavior. We are working around it with `componentWillUnmount`, but it's easy to think of situations where that wouldn't work.

**Comment by chrisnojima** [comment]
@brentvatne @ericvicenti I believe most of the plumbing in here actually works. 

What happens is the app container dispatchActionEvents (https://github.com/react-navigation/native/blob/master/src/createAppContainer.js#L261) happens a frame too late so by that time the navigationEvents componentWillUnmount (https://github.com/react-navigation/core/blob/master/src/views/NavigationEvents.js#L33) gets called and unregisters right before so it misses all of these events.

It does handle the gesture and do the animation and the completion callback does dispatch the right actions

Hope this helps!

**Comment by ericvicenti** [comment]
When swiping back, react-nav dispatches the will-blur/focus and did-blur/focus at the end of the transition, to avoid extra JS work at the time of gesture end/animation start, which causes ugly frame drops.

I think you're right @chrisnojima that most things are working, the blur events did happen, but the component was unmounted too early. I think this happens almost always for the didBlur event, but when swiping back it happens for willBlur as well.

Unfortunately it my be tricky to fix without breaking other things. For example, if we fire the events before applying the new state, the willFocus event will be missed because the event will fire before the screen mounts. In theory we could fix this by doing an extra render pass in the stack transitioner, leaving the screens mounted for another frame. But it is not the most pleasant solution.

**Comment by chrisnojima** [comment]
Yeah, it seemed like some difficult choice would have to be made so I didn't want to propose a PR. This is a painful open issue as it affects the correctness of the lifecycle. This means we can't use these events at all in our project.
Would it be horrible to defer the unregistering so the callbacks happen on the component after its been unmounted (aka setImmediate in the unmount or similar)? You wouldn't be able to do `setState` etc but you could do other bookkeeping (for us doing other reduxy stuff)

**Comment by ericvicenti** [comment]
Ive been thinking about this, and I think it makes sense for events to fire after rendering has happened. So if the state change result in a unmount of your component, you won't receive those events (if you unsubscribe on unmount). The focus events still may be useful if you push another screen and you want to unsubscribe from redux on the background screen.

For your use case I think you should be able to use componentWillUnmount to do your bookkeeping.

We could just call willBlur/didBlur from `<NavigationEvents>` when unmounting.. which would be a reasonable workaround that I'd be in support of.. but we should only change `<NavigationEvents>`

Once @satya164 implements the reanimated swipe-back, we will be able to fire the willBlur right away when the gesture releases, because the main thread will be performing the gesture.

**Comment by chrisnojima** [comment]
We are using componentWillUnmount now but it's tricky as we have to use navigationEvents plus that to ensure it works in all cases. The willBlur in navigationEvents seems fine to me short term

**Comment by alexfoxy** [comment]
Has this been resolved? I am having an issue where the back or triggering `navigator.dispatch(NavigationActions.back())` does not trigger a willFocus / didFocus but only when building in production.

**Comment by epurban** [comment]
It is still a bug.

**Comment by smaudd** [comment]
Same bug here

**Comment by art1373** [comment]
I am getting the same bug also when someone slowly closes the modal Route the on will blur not getting called

**Comment by nicotroia** [comment]
I'm experiencing an issue where `onWillBlur` and `onDidBlur` do not fire when the user clicks back or swipes the screen back in the stack. These events WILL fire when changing navigation tabs into a different stack, however.

running `"react-navigation": "^4.3.9"`

**Comment by iHamzaaK** [comment]
> I'm experiencing an issue where `onWillBlur` and `onDidBlur` do not fire when the user clicks back or swipes the screen back in the stack. These events WILL fire when changing navigation tabs into a different stack, however.
> 
> running `"react-navigation": "^4.3.9"`

I am having the same issue as well.

**Comment by ShepSims** [comment]
Why is this issue closed? The issue is very much still preset, I am not receiving onDidBlur or onWillBlur events when swiping or pressing the top left back button
