### ISSUE TITLE
React Navigation Error - null is not an object (evaluating 'RNGestureHandlerModule.Direction')

### ISSUE THREAD

**Issue by jin-benben** [react-navigation/react-navigation#5688]
```js
import React from "react";
import { View, Text } from "react-native";
import { createStackNavigator, createAppContainer } from "react-navigation"; 
class HomeScreen extends React.Component {
   render() {
      return ( 
        <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}> 
          <Text>Home Screen</Text>
        </View>
       )
    } 
}
const AppNavigator = createStackNavigator({ Home: { screen: HomeScreen } });
const AppContainer = createAppContainer(AppNavigator);

export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
}
```

| software         | version
| ---------------- | -------
| react-navigation | 3.4.0
| react-native     |  0.59.1
| react-native-gesture-handler | 1.1.0
| node             |
| npm or yarn      |

**Comment by eriveltonelias** [comment]
Hi @jin-benben,
this happens if you haven't installed RNGH properly. be sure to follow the steps from here: https://reactnavigation.org/docs/en/getting-started.html#installation

https://snack.expo.io/@eriveltonelias/basic-setup

**Comment by hitunes** [comment]
Have you tried this? This solved my problem

1. Right Click Libraries "Add Files to Project"
2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
3 .Go to build phases and add libRNGestureHandler.a
Run

**Comment by gregblake** [comment]
@hitunes This resolved the problem for me, as well. For others who may be encountering the same issue, [the docs](https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking) provide helpful screenshots for manual linking.

**Comment by Tmac90301** [comment]
If you are integrating RN into your native projects, maybe you can try this.

1. Open your Podfile and add `pod 'RNGestureHandler', :path => "../node_modules/react-native-gesture-handler"`
2. Execute `pod install` and restart your native projects again.

This works for me and I find that when I'm adding `react-navigation` into a completely RN project and execute `pod install` in the `ios` project directory, it will automatically add a `RNGestureHandler` lib and this will not happen when I'm integrating RN into my native projects and do the same `pod install` in my native projects.

The error log for my case is not absolutely same with yours but I think they are caused by the same reason.

**Comment by biranchi2018** [comment]
> Have you tried this? This solved my problem
> 
> 1. Right Click Libraries "Add Files to Project"
> 2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
>    3 .Go to build phases and add libRNGestureHandler.a
>    Run

Tried in RN60 but still not working

**Comment by Sanan4li** [comment]
Facing the same problem with react-navigation version 5.
Any solution?

**Comment by varunsdcet** [comment]
run this command
cd Projectname then cd ios then pod install
