### ISSUE TITLE
Can't validate propTypes when passing vars through screenProps to a pure component

### ISSUE THREAD

**Issue by sschenk** [react-navigation/react-navigation#5693]
### Current Behavior

- What code are you running and what is happening?
```
`const SomeStatlessComponent = ({someFunc, someProp, screenProps}) =>
   <SomeOtherComp someHandler={screenProps.someHandler}... /> `
```

### Expected Behavior

- What do you expect should be happening?
I would like to validate the props in screenProps per prop with PropTypes like so:
`someStatelessComp.propTypes = {
  someHandler: PropTypes.func.isRequired
}`
I would also like to use the props in screenProps without writing screenProps.someHandler each time.
### How to reproduce
Pass props through stack or switch navigation to a route using the screenProps.
 

##Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.5
| node             | 10.14.2
| npm or yarn      |

I've seen the following thread but the solution there refers to class components not pure fucntion ones:
https://github.com/react-navigation/react-navigation/issues/935

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
