### ISSUE TITLE
NavigationActions / StackActions is undefined in jest unit tests

### ISSUE THREAD

**Issue by hxiongg** [react-navigation/react-navigation#5695]
I just upgraded from 2.4.x to the latest 3.4.1. All my jest unit tests that tests NavigationActions / StackActions are complaining that they can't be found.

```ts
TypeError: Cannot read property 'navigate' of undefined

      31 |   navigate(routeName: string, params = {}) {
      32 |     this.getNavigatorRef().dispatch(
    > 33 |       NavigationActions.navigate({
         |                         ^
      34 |         routeName,
      35 |         params,
      36 |       }),
```

```ts
TypeError: Cannot read property 'reset' of undefined

      65 |
      66 | export const someFunction= (name: string) => {
    > 67 |   return StackActions.reset({
         |                       ^
      68 |     index: 1,
      69 |     actions: [
      70 |       NavigationActions.navigate({ routeName: 'ScreenOne' }),
```

```ts
TypeError: react_navigation_1.createStackNavigator is not a function
```

I have tried mocking react-navigation module by placing under the root \_\_mocks\_\_  folder
**\_\_mocks\_\_/react-navigation.js**
```js
export default {
  createAppContainer: jest.fn().mockReturnValue(function NavigationContainer(props) { return null; }),
  createDrawerNavigator: jest.fn(),
  createMaterialTopTabNavigator: jest.fn(),
  createStackNavigator: jest.fn(),
  StackActions: {
    push: jest.fn().mockImplementation(x => ({ ...x, "type": "Navigation/PUSH" })),
    replace: jest.fn().mockImplementation(x => ({ ...x, "type": "Navigation/REPLACE" })),
    reset: jest.fn(),
  },
  NavigationActions: {
    navigate: jest.fn().mockImplementation(x => x),
  }
}
```

jest.config.js
```js
"transformIgnorePatterns": [
    "node_modules/(?!(jest-)?react-native|react-navigation|@react-navigation/.*|rn-placeholder|@expo)"
  ],

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.4.1
| react-native     | 0.57.5

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by sawyer3273** [comment]
`jest.mock('react-navigation', () => {
  return {
    createAppContainer: jest.fn().mockReturnValue(function NavigationContainer(props) { return null; }),
    createDrawerNavigator: jest.fn(),
    createMaterialTopTabNavigator: jest.fn(),
    createStackNavigator: jest.fn(),
    StackActions: {
        push: jest.fn().mockImplementation(x => ({ ...x, "type": "Navigation/PUSH" })),
        replace: jest.fn().mockImplementation(x => ({ ...x, "type": "Navigation/REPLACE" })),
        reset: jest.fn(),
    },
    NavigationActions: {
        navigate: jest.fn().mockImplementation(x => x),
    }
  }
})`

adding this to setup file worked for me
