### ISSUE TITLE
DeepLinking is not working when it has sub-menu

### ISSUE THREAD

**Issue by kristoff2016** [react-navigation/react-navigation#5697]
**Current Behavior**

Type command `xcrun simctl openurl booted app-tribe://auth/policyPrivacy` will open `PolicyPrivacy` .

```
const AuthStack = createAppContainer(createStackNavigator({
	Workspace: {
		screen: Workspace,
		navigationOptions: { navOptions },
		path: 'workspace',
	},
	LogIn: {
		screen: Authenticate,
		navigationOptions: { navOptions },
		path: 'login',
	},
	SignUp: {
		screen: SignUp,
		navigationOptions: navOptions,
		path: 'signup/:token',
	},
}, options));

const AuthRootStack = createAppContainer(createStackNavigator({
	AuthStack: {
		screen: AuthStack,
		navigationOptions: {
			header: null,
		}
	},
	// modal route for auth
	PolicyPrivacy: {
		screen: PolicyPrivacy,
		navigationOptions: navOptions,
		path: 'policyPrivacy',
	},
	EditText: {
		screen: EditText,
		navigationOptions: navOptions,
		path: 'EditText',
	},
}, {
	mode: 'modal',
}));

const AuthRootStackApp = () => <AuthRootStack uriPrefix={`${prefix}auth/`} />

export default AuthRootStackApp;

```
---

### Expected Behavior

Type command `xcrun simctl openurl booted app-tribe://auth/login` will open `LogIn`  but it does not works because `AuthStack` is sub in `AuthRootStack`

**Your Environment**

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz
      Memory: 28.45 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.2 => 16.3.2 
      react-native: 0.56.1 => 0.56.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

Thank you for your help!

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
