### ISSUE TITLE
TabBarTop component unable to override in v3

### ISSUE THREAD

**Issue by zapzero** [react-navigation/react-navigation#5719]
### Current Behavior
- What code are you running and what is happening?
I like to create a dynamic hide/show tab bar depends on user mode.
 
when i am using createBottomTabNavigator + BottomTabBar ,  the code work fine, but after i change in to createMaterialTopTabNavigator + TabBarTop, the problem happened . This code works in V2 , but not V3. No idea why.

        tabBarComponent: ({ navigation, ...rest }) => {
            console.log('navigation', navigation);
            console.log('rest', rest);
            const restrict = ['Yamaha', 'Honda'];
            const filteredTabNavigatorRoutes = navigation.state.routes.filter(
                route => restrict.indexOf(route.key) === -1
            );
            return (
                <TabBarTop
                    {...rest}
                    navigation={{
                        ...navigation,
                        state: { ...navigation.state, routes: filteredTabNavigatorRoutes },
                    }}
                />
            );
        },
        tabBarOptions: {
            activeTintColor: Colors.tab_bar.active_tint,
            activeBackgroundColor: Colors.tab_bar.active_background,
            inactiveTintColor: Colors.tab_bar.inactive_tint,
            inactiveBackgroundColor: Colors.tab_bar.inactive_background,
            indicatorStyle: { backgroundColor: Colors.tab_bar.active_tint },
            tabStyle: { height: Layout.tabBar.height },
            style: { backgroundColor: Colors.tab_bar.background },
        },
        tabBarPosition: 'top',
        animationEnabled: true,

- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/11909846/54747231-46567a80-4c09-11e9-8c3d-6dafd76324a7.png)

either i am using `tabBarComponent: (props) => <TabBarTop {...props} />`, still come out a same error

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^3.5.1
| react-native     | React Native 0.57 - Expo SDK v32.0.0   
| node             | v10.9.0
| npm or yarn      | 6.8.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
