### ISSUE TITLE
Cannot read property Direction of undefined.

### ISSUE THREAD

**Issue by yesIamFaded** [react-navigation/react-navigation#5724]
### Current Behavior

Very simple : 

const Tabs = createBottomTabNavigator({
  MainFeed: MainFeed,
  Camera: Camera,
    Profile: Profile
})
const MainStack = createSwitchNavigator({
    Login: AuthStack,
    Main: Tabs
})

THIS works fine and I want to have a StackNavigator on the Login(AuthStack) so I create it :

const AuthStack = createStackNavigator({
  Login: {screen: Login},
  Register: {screen: Register}
})

THEN I GET : **Cannot read property 'Direction' of undefined** 

But with createSwitchNavigator it works but I need the Stack for the back button.

I got react-native-gesture-handler installed properly and all my imports are good ... everything works fine when I swap the createStackNavigator to createSwitchNavigator so I cant get my head around why it doesnt work.

Ty in advance :100:

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by olinations** [comment]
I have the same issue and can't find an answer anywhere. Anytime I add createStackNavigator to my project I get the same error, all other navigators work with no problem. Not quite sure why you need a production app to understand the problem, the code couldn't be more simple. Same as @yesIamFaded

**Comment by brentvatne** [comment]
@olinations - you need to ensure that react-native-gesture-handler is installed correctly in the project. if you're not comfortable installing native libraries you could use expo-cli instead - expo projects have react-native-gesture-handler installed automatically: https://docs.expo.io/versions/v32.0.0/introduction/installation/

**Comment by olinations** [comment]
Hi @brentvatne, thanks for the reply, but I actually figured out a simple solution. 

This appears to happen when you install and link the library while running the project. 

To fix you have to shut it down and start it back up again. 

OR, if that doesn't work, it may be fixed by creating a new react native project and installing and linking libraries before running any simulator. Then you can just copy over your files to the new project.

**Comment by GaetanB999** [comment]
I had the same error and exact behavior (for Android).
After digging I found that it was missing code in MainApplication.java :


`import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;  <-- this import was missing`

```
  @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNGestureHandlerPackage()  <-- this line was missing
      );
    }
```
Don't know why it was not there after installing and linking package ... but maybe it will help someone.

**Comment by MalikFaizanZafar** [comment]
> I had the same error and exact behavior (for Android).
> After digging I found that it was missing code in MainApplication.java :
> 
> `import com.swmansion.gesturehandler.react.RNGestureHandlerPackage; <-- this import was missing`
> 
> ```
>   @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>             new RNGestureHandlerPackage()  <-- this line was missing
>       );
>     }
> ```
> Don't know why it was not there after installing and linking package ... but maybe it will help someone.

Facing the same issue.....Where in the file I can place this code? Wherever I place this code, I get error

**Comment by JordanBCX** [comment]
> I had the same error and exact behavior (for Android).
> After digging I found that it was missing code in MainApplication.java :
> 
> `import com.swmansion.gesturehandler.react.RNGestureHandlerPackage; <-- this import was missing`
> 
> ```
>   @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>             new RNGestureHandlerPackage()  <-- this line was missing
>       );
>     }
> ```
> 
> Don't know why it was not there after installing and linking package ... but maybe it will help someone.

The import was there for me, but the package list entry was not. The link worked for MainActivity.java worked but not for MainApplication.java.

**Comment by 1036850584** [comment]
My import entries are all there, and import dependencies are also there, but there will also be such errors, I do not know how to solve.

**Comment by 1036850584** [comment]
My import entries are all there, and import dependencies are also there, but there will also be such errors, I do not know how to solve.

**Comment by edgardong** [comment]
> I had the same error and exact behavior (for Android).
> After digging I found that it was missing code in MainApplication.java :
> 
> `import com.swmansion.gesturehandler.react.RNGestureHandlerPackage; <-- this import was missing`
> 
> ```
>   @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>             new RNGestureHandlerPackage()  <-- this line was missing
>       );
>     }
> ```
> 
> Don't know why it was not there after installing and linking package ... but maybe it will help someone.

yeah! great!!!
