### ISSUE TITLE
Slider deprecation warning from react-native-gesture-handler in react-native@0.59

### ISSUE THREAD

**Issue by Steffi3rd** [react-navigation/react-navigation#5729]
<img width="977" alt="Capture d’écran 2019-03-22 à 22 35 05" src="https://user-images.githubusercontent.com/814410/54854329-dcb29b00-4cf2-11e9-8585-d8de7ccc9963.png">

**Comment by brentvatne** [comment]
this is coming from react-native-gesture-handler, cc @kmagiera @osdnk perhaps we can backport removing slider to 1.0.x line of releases and cut 1.0.18?

**Comment by Steffi3rd** [comment]
https://github.com/react-navigation/react-navigation/issues/5730

**Comment by chest233** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/535#issuecomment-475554520

**Comment by eriveltonelias** [comment]
this should fix on `react-native-gesture-handler@1.2.1` can you confirm @Steffi3rd and @chest233 ?

**Comment by giacomocerquone** [comment]
@eriveltonelias I don't think the fix should come from gesture-handler (anyway on my rn project this is a warning and not an error).
I think there should be a change in how react-navigation uses gesture-handler since if you on gesture-handler's package.json, you won't read listed as a dependency "ViewPagerAndroid" but you can find it here, in an example of gesture-handler: https://github.com/kmagiera/react-native-gesture-handler/blob/ff74e0edadd62518b45d85f251f527307457ab9e/Example/pagerAndDrawer/index.js#L8

Do you see what it does? 

```
const WrappedViewPagerAndroid = createNativeWrapper(ViewPagerAndroid, {
  disallowInterruption: true,
});
```

So must be changed react-navigation (actually one of its subpackages that uses viewpager)

**Comment by YajanaRao** [comment]
I am getting the same warning in my application. Is there any solution for this?

**Comment by bmeverett** [comment]
Based on the [comment](https://github.com/react-navigation/react-navigation/issues/5684#issuecomment-473159635)t in #5684 upgrading to react-tabs alpha 2.0 fixed the issue. It looks like react-tabs has release v 2.1.3 so upgrading `react-navigation` to use v 2.1.3 of `react-navigation-tabs` should resolve the issue

**Comment by gbalduzzi** [comment]
I fixed the issue by upgrading react-native-gesture-handler to version 1.0.16

**Comment by cwilby** [comment]
So.. we have a temporary solution, how do we get to a permanent working solution?
