### ISSUE TITLE
header tabbar keyboard-up (android)

### ISSUE THREAD

**Issue by faustoct** [react-navigation/react-navigation#5739]
When the application combines a `createBottomTabNavigator` and `Header` in any views. It's getting tricky to handle: `keyboard, header and tabbar`.

My case:
- Search: I have a view in the tab bar for searching. It got the tabbar displayed when the keyboard showed up. I fixed it adding adjustPan on AndroidManifest. It caused a side effect.
- Direct: I have a view to chat. I got the header overflowing when the keyboard is up.

Probably, in my case I have to choose on solution and fix other on my own. 

Is there a way to fix both? `tabbar + keyboard` and `header + keyboard` :)

**Comment by faustoct** [comment]
Is there a solution to fix both ?

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by fungilation** [comment]
Try `android:windowSoftInputMode="adjustResize|stateAlwaysHidden|adjustPan">`. Workaround in our app
