### ISSUE TITLE
Status Bar color is not working .. 

### ISSUE THREAD

**Issue by forestfuture89** [react-navigation/react-navigation#5745]
I am using  react-navigation: 1.00-beta.13 

`import {DrawerNavigator} from 'react-navigation';

export default (DrawNav = DrawerNavigator({
        Dashboard: {screen: Dashboard},
        Statistics: {screen: Statistics}
    },
       {
        contentComponent: props => <SideBar {...props} />
    }
));`

In the dashboar.js I am using Header like this .. 

`<Header style={s.menuHeader} barStyle={'light-content'}>
<Left>
<Button transparent onPress={() => this.props.navigation.navigate("DrawerOpen")}>                                   <Icon name="md-menu" style={s.menuIcon}/>
 </Button>
</Left>
<Body>
<Title style={{width: 230,color: '#ffffff'}}>Dashboard</Title>
</Body>
<Right/>
</Header>`

I want to use custom status bar color .. so i changed it .. but if i use above header code , and then this color is not working .. 

When i remove it , status bar color is working well .. 

I am not sure what is bugs .. Do you have any solution ?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
