### ISSUE TITLE
Glitch with hiding header and bottom bar (when bridged camera view is mounted)

### ISSUE THREAD

**Issue by scortumee** [react-navigation/react-navigation#5750]
### Current Behavior

- What code are you running and what is happening?
![IMG_6231](https://user-images.githubusercontent.com/18318832/55102878-9bb8de80-5084-11e9-83f9-ed6d44a37413.jpg)

I have 3 tab sections which was populated using `createBottomTabNavigator`. Each section is a `stackNavigator` that contains 2 or three screens.

Inside `AddCards` section, I have successfully bridged a native camera using `requireNativeComponent` onto my app. It is simple video stream line which was tunneled through `UIView`. 

However, when I alter a header bar like `header:null` or bottom bar like `tabBarVisible:false`on `AddCards`, camera starts glitching:

Transiton from Collection to AddCards or AddCards to Collection becomes painfully slow like 2 or 3 seconds. And then, later camera freezes or whole app crashes

*** If I don't mess with header and bottomTabBar, my app runs smoothly. No glitch no slowing down or something. 

*** Camera also starts behaving weirdly when I change header or bottomTabBar on other sections of the app(like `Collection` or `Me`)

### Expected Behavior

--- I expect an app to run smoothly even if there is no header or bottomTaBar

I do not know if this is something to do with bridging camera view or react-navigation related. I am pretty sure messing with header bar or bottomTabBar definitely triggers some unwanted action that conflicts the camera. 

Thanks in advance

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.5.1
| react-native     | 0.57.7
| node             | v10.13.0
| npm or yarn      | 6.4.1
platform: IOS

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
