### ISSUE TITLE
Attempted to invoke `3` (method ID) on `UIManager` (NativeModule name) with an invalid bridge

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#5760]
**🐛 Bug Report**

I am facing lot of warnings which not allowing me to make any event in the app.
Attempted to invoke 3 (method ID) on UIManager (NativeModule name) with an invalid bridge. Refer the attached image

**To Reproduce**

I am facing this issue in latest version of "react-navigation": "^3.2.3" (v3)

**Expected Behavior**

Need to remove all the warnings (Attempted to invoke 3 (method ID) on UIManager (NativeModule name) with an invalid bridge.)

**Environment**

npmPackages:
react: 16.8.1 => 16.8.1
react-native: ^0.58.4 => 0.58.6
npmGlobalPackages:
react-native-cli: 2.0.1

![Screenshot 2019-04-01 at 4 14 35 PM](https://user-images.githubusercontent.com/36992338/55322548-3f95f600-549a-11e9-9a88-3d015d3b07a7.png)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
