### ISSUE TITLE
Cannot hide default header in android

### ISSUE THREAD

**Issue by ananth10** [react-navigation/react-navigation#5764]
Hi team ,

Header is not hiding after upgraded to new react-navigation version 3.6.0, please check below details to reproduce it.

**Package.json**

"dependencies": {
    "@react-native-community/async-storage": "^1.2.2",
    "@react-native-community/netinfo": "^1.4.1",
    "axios": "^0.18.0",
    "crypto-js": "^3.1.9-1",
    "react": "^16.8.6",
    "react-native": "0.59.3",
    "react-native-cache-image": "^1.0.0",
    "react-native-camera": "^1.3.0",
    "react-native-gesture-handler": "1.1.0",
    "react-native-snackbar": "^0.4.6",
    "react-native-super-grid": "^2.1.0",
    "react-navigation": "3.6.0",
    "react-navigation-backhandler": "1.1.1",
  },
  "devDependencies": {
    "babel-jest": "^24.6.0",
    "jest": "^24.6.0",
    "metro-react-native-babel-preset": "0.53.1",
    "react-test-renderer": "^16.8.6"
  },

**Router.js**

export const AppNavigator = createStackNavigator(
    {
        Splash: {
            screen: Splash,
            headerMode: 'none',
            header: null,
            defaultNavigationOptions: {
                statusBarHidden: true,
                header: null,
            }
        },
      

    {
        initialRouteName: 'Splash',
    },

);

const AppNavigation = createAppContainer(AppNavigator);

export default AppNavigation;

**App.js**

import React,{ Component } from 'react';
import AppNavigation from './config/Router';

class App extends Component{

    render()
    {
        return <AppNavigation/>
    }
}

export default App;

**Index.js**

import { AppRegistry } from 'react-native';
import App from './src/index';

AppRegistry.registerComponent('VastharaApp', () => App);

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
