### ISSUE TITLE
GestureEnabled : false, little bug in stack

### ISSUE THREAD

**Issue by ZsKLiQuid** [react-navigation/react-navigation#5766]
### Current Behavior

```javascript 
const OnBoardingStack =  createStackNavigator(
    {
        OnBoardingScreen : {
            screen : require("../containers/OnBoarding").default,
        }
    },
    { 
        headerMode: 'none',
        defaultNavigationOptions: {
            gesturesEnabled: false,
          },
        initialRouteName: 'OnBoardingScreen',
    }
) 
```
![ScreenRecording_04-03-2019 11-30-55](https://user-images.githubusercontent.com/16732818/55468763-5bb5a680-5604-11e9-88bc-af7a5f1b7b3f.gif)

I have this behavior when i swipe from left to right with gesturesEnabled : false.

Maybe i do something wrong, but i think it's a bug.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.59 
| node             | 10.15.1
| npm or yarn      | 6.4.1

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
