### ISSUE TITLE
White flash during Screen navigation  

### ISSUE THREAD

**Issue by jigaryadav** [react-navigation/react-navigation#5767]
### Current Behavior

when you navigate to one screen to another with stack routing then white screen will appear for a mili sec 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/22216148/55476148-6a678200-5633-11e9-9219-5c41d3a1f2a5.gif)

### Expected Behavior
no white flash during navigation 

### How to reproduce

- created a new project and installed navigation package with gesture dependence and created two route with black background for better visibility  

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.6.1
| react-native     | ^0.59.2
| node             | 8.10.0
| npm or yarn      | 3.5.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by nihp** [comment]
@brentvatne 
I am experiencing the same issue while navigating from one screen to another screen. Did you have any solution?
