### ISSUE TITLE
Deep linking not working properly

### ISSUE THREAD

**Issue by german970814** [react-navigation/react-navigation#5779]
### Current Behavior

I'm trying to run my application including DeepLinking.  I've setted the needed on `AndroidManifest.xml` to work with Linking, and when I run my app is possible to see which url is called with `Linking.getInitialURL().then(console.log)`. It works good, but when I want to navigate to an specific screen, it just does not work. This is my code

    const Main = createStackNavigator({
       Home: { screen: Home },
       Pets: { screen: Pets, path: 'spidersecurity://terque/pets' },
    });

### Expected Behavior

The expected behavior is that app navigate successfully to specific screen

### How to reproduce

This is the only code that I'm testing now, it does not work.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.1.5
| react-native     | 0.58
| node             | 8.10
| npm or yarn      |  1.13

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

**Comment by german970814** [comment]
@vonovak I can't test it on expo, it's a deep link, I need to change the `AndroidManifest.xml` file

**Comment by vonovak** [comment]
@german970814 in that case, please provide a link to a runnable repro in a github repo, thanks.

**Comment by german970814** [comment]
I've found this https://github.com/react-navigation/react-navigation/issues/1189#issuecomment-339268524 on #1189. This is not the best solution for me, but it works
