### ISSUE TITLE
HeaderBackButton not showing title prop.

### ISSUE THREAD

**Issue by djorkaeffalexandre** [react-navigation/react-navigation#5780]
### Current Behavior
Hello, I'm working in Rocket.Chat.ReactNative Project and I'm implementing count of unread messages on headerBackButton, but my app does not show the title of HeaderBackButton Component.

![](https://i.imgur.com/cDXPdh6.png)
![](https://i.imgur.com/KvOR2M2.png)

If I change HeaderBackButton to another Component this work's fine.

![](https://i.imgur.com/S4nOURi.png)
![](https://i.imgur.com/89SQ05L.png)

### Expected Behavior

I want to show the prop 'Title' in the right of the button.

### Your Environment

| software | version
| ---------------- | -------
| react-navigation | 3.3.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by djorkaeffalexandre** [comment]
If i comment this reopen?
