### ISSUE TITLE
Issue with transition of 2 screens inside Stack Navigator

### ISSUE THREAD

**Issue by spyshower** [react-navigation/react-navigation#5804]
### Current Behavior

When I transition from one screen that has a header to a screen that has a transparent header, when this transition begins the components (all the screen actually) of the first screen is being moved up a few pixels. I believe it's exactly the same amount of pixels that the header has.

I had this problem in the past on other screens of my app but I fixed it with `headerMode: 'float'` . I am not sure if this is a problem with a new version of React Navigation, or it was there the entire time and I didn't notice it. Also, it happens only on iOS.

![rnnavigationbug](https://user-images.githubusercontent.com/7046283/55983499-f3ba2c80-5ca3-11e9-94e3-1fadd9167c60.gif)

```
const RootNavigator = createStackNavigator(
  {
  ...
   EditProfilescreen: {
      screen: EditProfile,
      navigationOptions: {
        headerTitle: 'Edit profile',
      },
    },

    ViewPicturescreen: {
      screen: ViewPicture,
      navigationOptions: {
        headerTransparent: true,
        headerTintColor: 'rgb(210,210,210)',

        headerTitleStyle: {
          flex: 1,
          fontSize: 19,
          color: 'rgb(210,210,210)',
          fontFamily: 'medium',
          alignSelf: 'center',
          textAlign: 'center',
        }
      },
    },

  },

  {
    initialRouteName: 'Homescreen',
    headerLayoutPreset: 'center',
    headerBackTitleVisible: false,
    headerMode: Platform.OS === 'android' ? 'screen' : 'float',
    defaultNavigationOptions: {

      headerForceInset: Platform.OS === 'android' ? { top: 'never', bottom: 'never' } : {},
      headerStyle: {
        borderBottomWidth: 0,
        margin: 0,
      },

      headerTintColor: '#a649f2',
      headerTitleStyle: {
        flex: 1,
        fontSize: 19,
        color: 'black',
        fontFamily: 'medium',
        alignSelf: 'center',
        textAlign: 'center',
        // backgroundColor: 'red',
        // fontWeight: 'bold',
      },
    },
  }
);
```

### Expected Behavior

The components should not move at all.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.7.1
| react-native     | expo (latest)
| node             | 10.15.3
| npm or yarn      | 6.8.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
