### ISSUE TITLE
Issue with transition of 2 screens inside Stack Navigator 

### ISSUE THREAD

**Issue by spyshower** [react-navigation/react-navigation#5805]
### Current Behavior

When I transition from one screen that has a header to a screen that has a transparent header, when this transition begins the components (all the screen actually) of the first screen is being moved up a few pixels. I believe it's exactly the same amount of pixels that the header has.

I had this problem in the past on other screens of my app but I fixed it with `headerMode: 'float'` . I am not sure if this is a problem with a new version of React Navigation, or it was there the entire time and I didn't notice it. Also, it happens only on iOS.

![rnnavigationbug](https://user-images.githubusercontent.com/7046283/55983499-f3ba2c80-5ca3-11e9-94e3-1fadd9167c60.gif)

Snack: https://snack.expo.io/S1F5Q76t4

### Expected Behavior

The components should not move at all.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.7.1
| react-native     | expo (latest)
| node             | 10.15.3
| npm or yarn      | 6.8.0

Of course I won't miss this chance to ask how does this bug exist, and how can I be the only one that has it. Also, snack.expo.io is bugged as well. Commented lines (grayed out) are actually not commented, half of the console window is hidden behind file explorer and the project doesn't update unless I switch devices. But let's pretend it works ok for now.

**Comment by brentvatne** [comment]
> Of course I won't miss this chance to ask how does this bug exist, and how can I be the only one that has it.

it's not a bug. when you use `headerMode: 'float'` along with `headerTransparent: true` in only some of the screens in a stack this is what happens because `float` means that the header floats along the top of your app and if it's transparent then the layout for screens in the stack moves up under the header. if it did not move up then a transparent header would be meaningless because you could not render anything under it. so, use `headerMode: 'screen'` when you have different `headerTransparent` values on different screens in your stack. 

>  Also, snack.expo.io is bugged as well. Commented lines (grayed out) are actually not commented, half of the console window is hidden behind file explorer and the project doesn't update unless I switch devices. But let's pretend it works ok for now.

i do not know what you are referring to with respect to snack as it works perfectly fine. if you can describe what you did leading up to it not updating then that is something we can discuss, but usually if you are fairly new to programming in a certain environment and you think that there is a bug in a tool you are using, it is probably actually an issue with your own code or something that you did :)

**Comment by spyshower** [comment]
Hey @brentvatne, my hero

> so, use `headerMode: 'screen'` when you have different `headerTransparent` values on different screens in your stack. we should document this better.

Do you mean for the whole stack navigator (ie. for all the screens in the stack)?

**Comment by brentvatne** [comment]
yep, if you use screen then the header is attached to each screen and so the layout never changes

**Comment by spyshower** [comment]
@brentvatne I am trying instead of making the header color transparent, to make it the same color as the background. I see a white line though that I don't know how to change it's color:

<img width="276" alt="Screenshot 2019-04-12 at 23 02 26" src="https://user-images.githubusercontent.com/7046283/56063190-4284c680-5d77-11e9-8028-f81bf5da019d.png">

Any way to change that?
