### ISSUE TITLE
Bottom Tab Navigator with Tab to Open Drawer Not Working

### ISSUE THREAD

**Issue by olinations** [react-navigation/react-navigation#5816]
I am trying to create a 'more' button to open up a drawer from the bottom tab navigator. I started with this code...

```
const MoreStack = createDrawerNavigator({
  More: { screen: More }
})

const MainTabNavigator = createBottomTabNavigator({
    Home: { screen: HomeStack }
    ...
    More: { screen: MoreStack }
})

const MainStackNavigator = createStackNavigator({
    MainTabNavigator: MainTabNavigator,
})

const AppSwitchNavigator = createSwitchNavigator({
  Welcome: { screen: WelcomeScreen },
  Home: { screen: MainStackNavigator }
})

const AppContainer = createAppContainer(AppSwitchNavigator)
```

That just allowed me go to the MoreStack where a drawer was available, but I wanted the 'More' to open a drawer, not go to a page, so I went to Stack Overflow and got an answer and that is where this possible bug has come in to play. I changed above to this code...

```
           const MainTabNavigator = createBottomTabNavigator({
                   Home: { screen: HomeStack },
                   More: { screen: MoreStack }
           })             

           const MainStackNavigator = createStackNavigator({
              MainTabNavigator: MainTabNavigator,
            })

           const MoreStack = createDrawerNavigator({
              SomePage:{screen:MainTabNavigator},   //<<<<<<<<
               SomeOther:{screen:MainStackNavigator},   //<<<<<<<<<<
               More: { screen: More }

               })

           const AppSwitchNavigator = createSwitchNavigator({
                  Welcome: { screen: WelcomeScreen },
                  Home: { screen: MoreStack }//<<<<<<<<<<<<<<<<<<<<<<
             })

          const AppContainer = createAppContainer(AppSwitchNavigator)
```

I then get the error 'component route for 'More' but be a React Component'.  I have tried many of the fixes brought up in previous issues and none have fixed this. I don't even know if this will work for my intention because I can't past this point.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by olinations** [comment]
I have read this comment so many times on so many of your threads. It is very frustrating. 

How about you just lead us to an answer that explains how to open a drawer navigator when a user clicks a tab?

**Comment by brentvatne** [comment]
@olinations - you've read it so how about do what it says? :P
