### ISSUE TITLE
How to access redux store in createDrawerNavigator component

### ISSUE THREAD

**Issue by shubhamdeol** [react-navigation/react-navigation#5821]
I have drawer setup as following
```javascript
const drawer = createDrawerNavigator({
  Orders: OrdersStackNavigator,
  Settlement: ManageCreditsStackNavigator,
  Products: ProductStackNavigator,
  Reports: ReportsStackNavigator,
  Categories: FoodMenu,
  'Missed Orders': MissedOrdersStack,
  'Past Orders': PastOrdersStack,
  Pilots: PilotsStackNavigator,
  Profile: ProfileStackNavigator,
}

```

I want to render few Screens conditionally based on some user permissions, which are stored in my redux store in userProfile object.

As this is not a react component, I can not use connect here.

**Comment by kgnadinger** [comment]
One solution is to create separate drawers for each level of permissions and nest each draw inside a stack suited for that level of permission.

**Comment by matthamil** [comment]
You can [extend a navigator](https://reactnavigation.org/docs/en/custom-navigators.html#extending-navigators) and create a `getStateForAction` for the router. The custom navigator can be wrapped with react-redux's `connect` which will let you access the fields from state that you need to determine if the user can navigate to that screen. 

If you don't want to show the routes at all (instead of prevent the default navigation behavior), you can still use a custom navigator, but return a filtered set of `routes` from [`getStateForAction`](https://reactnavigation.org/docs/en/custom-routers.html#getstateforactionaction-state).
