### ISSUE TITLE
Callback fcm and navigation not working

### ISSUE THREAD

**Issue by bpdarlyn** [react-navigation/react-navigation#5824]
### Current Behavior

- What code are you running and what is happening?
```javascript
componentDidMount(){
        this._catchFirebaseMessage();
    }
_catchFirebaseMessage(){
        this.messageListener = firebase.messaging().onMessage(this._processFirebase);
    }
_processFirebase = ({data}) => {
        console.log('MESSAGE FIREBASE');
        this.props.navigation.navigate('Profile') // the navigation not working
    };
```

### Expected Behavior

- What do you expect should be happening?
In my code I have `this.props.navigation.navigate('Profile')` but It doesn't navigate to another Screen when firebase message arrive, but I can navigate between screen successfully but into callback firebase I can't

### How to reproduce

```javascript
componentDidMount(){
        this._catchFirebaseMessage();
    }
_catchFirebaseMessage(){
        setTimeout(this._processFirebase,6000)
    }
_processFirebase = ({data}) => {
        console.log('MESSAGE FIREBASE');
        this.props.navigation.navigate('Profile') // the navigation is success
    };
```

Do you know what is the problem ?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.1
| node             | 10.15.0
| npm or yarn      | yarn 1.14.0-20181221.0548

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
