### ISSUE TITLE
tabBarOnPress only works in iOS?

### ISSUE THREAD

**Issue by rakibtg** [react-navigation/react-navigation#5833]
### Current Behavior
Here is a simple `tabBarOnPress` callback to be used with `createStackNavigator`
```javascript
const notificationsStack = createStackNavigator({
  notificationScreen: setScreen(notificationScreen, {}, false),
})

notificationsStack.navigationOptions = {
  tabBarLabel: 'Notifications',
  tabBarIcon: ({ focused }) => (
    <TabBarIcon
      focused={focused}
      name={Platform.OS === 'ios' ? 'ios-notifications' : 'md-notifications'}
    />
  ),
  tabBarOptions: {
    style: {
      ...globalTabBarStyle,
    }, 
    showLabel: false,
  },
  tabBarOnPress: () => {
    console.log('clicked in notifications')
  }
}
```
But it only works in iOS as expected; it will prevent the navigation and will do that console log, but for android the `tabBarOnPress` has no effect. Am i missing something? or we have different implementation for android?

Edit: On long press it doesnt work in iOS as well, it will just redirect the user to notifications screen instead. 

### Expected Behavior
When the click on the navigation button it should console log something.

### How to reproduce
Pass a call back function that console something in `tabBarOnPress`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     |
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Neha0595** [comment]
Same Problem here tabBarOnPress has no effect in Android

**Comment by KingAmo** [comment]
> Same Problem here tabBarOnPress has no effect in Android

i came to the same problem, any solution?

**Comment by KingAmo** [comment]
#5708

by the way, when i build release APK, `tabBarOnPress ` is called correctly。 so this problem only happens in debug mode in my case.

**Comment by vfa-namth** [comment]
The same
