### ISSUE TITLE
Pushing Stack Screen Params Changes Previous Screen

### ISSUE THREAD

**Issue by DISKONEKTeD** [react-navigation/react-navigation#5842]
### Current Behavior

So I'm at a stack screen, called 'Post'. I then have a "link" inside that post that points to another post that uses the same screen called 'Post', but different params. In my case, they use a unique URI param (different ones respectively). When i click the "link" it runs this code:

`    navigator.dispatch(StackActions.push({
      routeName: 'Post',
      params: { uri }
    }));`

It takes me to the new stack screen, and everything is received fine, but when i press the back button, or swipe back, the previous 'Post' screen is an exact replica of the screen I had just navigated to (so they are now the same screens with the same information)

### Expected Behavior

I expected that the previous screen would remain intact. I didn't expect the previous screen to become the screen I had just navigated away from. I wanted the original screen i had tapped the linked from.

Is there a way to prevent this from happening? Preventing the original screen re-rendering with the new params that was given to the new screen? Or they just share the same state/params? What am I overlooking?

### How to reproduce

It's just a stack router, stacking the same screen on top of another etc, just changing the params when being pushed. 

componentDidMount() is used to retreive the data (once the screen receives the params)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.5
| npm or yarn      | npm

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by DISKONEKTeD** [comment]
but the data is retrieved from a database

**Comment by DISKONEKTeD** [comment]
What's the recommended way to debug for react-navigation?

**Comment by brentvatne** [comment]
no different from how you would debug other libraries in react-native

**Comment by adnanaliarshad** [comment]
@DISKONEKTeD did you find any solution?
