### ISSUE TITLE
BackgroundColor of header container of custom component can't be changed

### ISSUE THREAD

**Issue by JaWoGit** [react-navigation/react-navigation#5850]
### Current Behavior

- Background color of container of custom header component won't change to specified value.

**On HomeScreen:**
`
 static navigationOptions = {
    header: <OverviewHeaderBar />,
    headerStyle: {
      backgroundColor: 'white'
    }
  };`

<img width="440" alt="Bildschirmfoto 2019-04-25 um 17 58 32" src="https://user-images.githubusercontent.com/16936560/56750444-18be9d00-6784-11e9-8d62-315b65d72930.png">

### Expected Behavior

- Container of custom header should be apply color which is specified through headerStyle prop

### How to reproduce
Add borderRadius to bottom of custom header component and set background color of container via navigationOptions. 
--> Background color of container won't change.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
