### ISSUE TITLE
drawer menu doesnt scroll while opened

### ISSUE THREAD

**Issue by alemkhodadadi** [react-navigation/react-navigation#5862]
### Current Behavior

drawer menu items hardly scrolls after tens of efforts

### Expected Behavior

scroll perfectly (as it expected)
### How to reproduce

![WhatsApp Image 2019-04-30 at 15 01 23](https://user-images.githubusercontent.com/46085041/56956291-fd270e00-6b58-11e9-8b92-99bea1af8bf4.jpeg)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.6.1
| react-native     | 6.5.0
| node             | 10.15.0
| npm or yarn      | sdk-30.0.0 (expo)

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
