### ISSUE TITLE
State params getting undefined

### ISSUE THREAD

**Issue by birendra-90** [react-navigation/react-navigation#5896]
When I am trying to setParams it's not setting the value and getting undefined in `static navigationOptions = {}`
Here is my code sample

`**ManTabNavigator.js**
```
const HomeStack = createStackNavigator({
  Home: { screen: HomeScreen },
  Service: { screen: ServiceListScreen },
}, {
  initialRouteName: 'Home',
});

HomeStack.navigationOptions = {
  tabBarLabel: 'Home',
  tabBarIcon: ({ focused }) => (
    <TabBarIcon
      focused={focused}
      type={'MaterialIcons'}
      name={'home'}
    />
  ),

export default createBottomTabNavigator({
  HomeStack,
  LinksStack,
  SettingsStack,
}, {
  initialRouteName: 'HomeStack',
  activeColor: '#19CF86',
  inactiveColor: 'rgba(0, 0, 0, 0.3)',
  barStyle: { backgroundColor: '#ffffff' },
});
};
````

**ServiceListScreen.js**

```
class ServiceListScreen extends Component {
  static navigationOptions = {
    header: ({ navigation }) => {
      return (
        <Header>
          <ServiceTab
            services={{}}
          />
        </Header>
      )
    }
  };

  _setNavigationParams() {
    let title = 'Form';
    this.props.navigation.setParams({
      title,
    });
  }

  componentDidMount() {
    this._setNavigationParams();
  }
  
  render() {
    const { selectedService } = this.props;
    return (
      <KeyboardAwareScrollView>
        <SafeAreaView
          // style={styles.container}
          forceInset={{ top: 'always' }}
        >
          <View style={{ flex: 1 }}>
            <SubServiceList
              selectedService={selectedService}
            />
          </View>
        </SafeAreaView>
      </KeyboardAwareScrollView>
    );
  }
}

ServiceListScreen.propTypes = {
  services: PropTypes.object,
  selectedService: PropTypes.object,
  // actions
};

const mapStateToProps = (state, ownProps) => {
  return {
    services: getAllServices(state),
    selectedService: getSelectedServices(state),
  };
}
export default compose(
  withNavigation,
  connect(mapStateToProps),
)(ServiceListScreen);

```

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | Using with EXPO SDK 32.0
| node             | 8.14.0
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by birendra-90** [comment]
@brentvatne Can you look into this -> https://snack.expo.io/@chanchal02/demo-app
