### ISSUE TITLE
Make navigator.dispatch async or fix StackActions.reset

### ISSUE THREAD

**Issue by atrauzzi** [react-navigation/react-navigation#5897]
I discovered today that calling code akin to the following:

```typescript
const firstAction = actions.shift()!;

navigator.dispatch(StackActions.reset({
    index: 0,
    actions: [ firstAction ],
}));

actions.forEach((action) => navigator.dispatch(action));
```

...results in a race condition where I'm forced to only get as far as route index `0`.  I was able to "solve" my issue with the code above by changing it to:

```typescript
        const firstAction = actions[0];

        navigator.dispatch(StackActions.reset({
            index: 0,
            actions: [ firstAction ],
        }));

        const deferred = createDeferred();
        setTimeout(deferred.resolve, 5);
        await deferred.promise;

        actions.forEach((action) => navigator.dispatch(action));
```
Unfortunately -- and trust me, I'm under no illusions about the jankyness of it -- the only way I've been able to work around this at the moment is by kludging a `setTimeout` and then hitting the router again after it's had a chance to settle.

The reason why I'm doing this is because I need a way to reset a fairly nested routing layout.  Unfortunately, the `index: 0` above prevents even the one action (which the API forces me to include, despite it being overridden by the mandatory `index` in the same structure 😵) in my `reset()` above from working.  Let alone if I tried to pass my entire `actions` array to it.

So, what would be better?  Well, I think we can see above that there are two options, both of which might be worth considering:

- Fix `StackActions.reset` to
  - Not require an index parameter
  - Actually perform all the navigation options in order so that nested routes don't error out.
- Make `navigator.dispatch` return a `Promise` so that `async` fanatics like myself have the option to intuit when our routing library has completed its work.

**Comment by matthamil** [comment]
For context, the "reset from index" behavior was originally added added [in this PR](https://github.com/react-navigation/react-navigation/pull/789). Feel free to check out the tagged issues in that PR for more info around the motivations behind the "reset from index" behavior. If you want to reset to the original position in the stack, you could check out [popToTop](https://reactnavigation.org/docs/en/stack-actions.html#poptotop) and see if that is useful for your situation.

Check out [this issue](https://github.com/react-navigation/rfcs/issues/11) for a possible solution to your problem.

I am going to close this issue since the issues in this repo are meant only for bug reports. If you believe you have found a bug, please open a new issue and follow the issue template. If you are suggesting changing a change instead,I think it would be best to open an [RFC](https://github.com/react-navigation/rfcs) in the RFC repo.

**Comment by atrauzzi** [comment]
I think you know this codebase well enough to not require an issue template. Unless the issue template is just a convenient tool to punt on otherwise complete issue reports?

This is definitely a poorly designed and confusing API. I urge you to reconsider, something is not right here.

**Comment by matthamil** [comment]
Hello again! The issue template has nothing to do with community volunteer/maintainer knowledge of the code base. The issue template helps contributors/maintainers/community members to best understand the bug that you are experiencing since issues are reserved for bug reports. 

Issues that are **not** bugs are strongly encouraged to be opened as a pull request, an RFC, or must be actionable in some way. Asking volunteers to "fix" a "poorly designed and confusing API" is neither actionable nor is it constructive feedback :). 

This project is supported by many community volunteers, and in the spirit of OSS, we would love to support you in the best ways we can to help you to contribute. 

I [linked a closed RFC](https://github.com/react-navigation/rfcs/issues/11) in my last comment that proposed converting `dispatch` into an `async` operation--I recommend digging through that RFC (and others) to understand the implications of such a change (and why `dispatch` is not async currently).
