### ISSUE TITLE
initialRouteName of createMaterialTopTabNavigator auto be set to a screen that has components contain autoFocus props 

### ISSUE THREAD

**Issue by tungduonghgg123** [react-navigation/react-navigation#5910]
Before I start, I don't know whether or not It is a bug or someone else have already found out before.
### My environment and package version
```
"react-navigation": "^3.9.1",
"react-navigation-material-bottom-tabs": "^1.0.0",
 "react-navigation-tabs": "^2.1.2",

```
```
 React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 18.18 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
### Current Behavior
The title tells it all.
My app have 3 tabs. Despite of the fact that I have set the `Initial Route Name` to the first tab (first screen), when I launch the app, it always jump to the 3rd tab (well not all of it). It stuck like this until i touch the screen.
![image](https://user-images.githubusercontent.com/32666311/57619326-dc76a380-75af-11e9-94f6-dce5c0cf0d5c.png)

### Expected Behavior
It should focus on the route that I have declared in  `Initial Route Name`

### I found out where the bug is.
In the 3rd Screen, there is a component:
```
<SearchBar
          placeholder="Search Youtube Music"
          containerStyle={{ backgroundColor: null, borderTopWidth: 0, borderBottomWidth: 0, paddingTop: 10, paddingBottom: 2 }}
          inputContainerStyle={{backgroundColor: 'white'}}
          inputStyle={{color: '#4F0645'}}
          placeholderTextColor= '#4F0645'
          round={true}
          /**
          this  line leads to bug!!!!!!! 
           */
          autoFocus={true}
          autoCorrect={false}
          autoCapitalize="none"
          
        />
```
`autoFocus` leads to unexpected behavior . When I remove it, everything works fine.

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by tungduonghgg123** [comment]
> hi! please make your code runnable either on https://snack.expo.io without any extraneous code

I'm afraid that I can't. But because i already pointed out the cause, I think you can quickly reproduce to see the bug.

**Comment by brentvatne** [comment]
@tungduonghgg123 - if it's quick to reproduce then you do it :)

here is my standard reply for more context:

<hr />

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
