### ISSUE TITLE
Re-rendering not happening

### ISSUE THREAD

**Issue by arpitjain-in** [react-navigation/react-navigation#5919]
Hi,
Purposely, We've three `homescreen` in our app which contains exactly same children components but passing different data based on some condition thru props.

Issue which we're facing is -
T1 - Open app with Homescreen 1.
T2- Navigate to Homescreen 2.
T3 - Navigate to Homescreen 3.

```[BUG]Then come back to `homescreen 1`, we are seeing the data from `homescreen 3`.```

Question - How to re-render `homescreen 1` with proper respective data when user navigate from `homescreen 3` or `homescreen 2`.

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
