### ISSUE TITLE
How can I fetch per Apollo client to create dynamic drawer routes?

### ISSUE THREAD

**Issue by donni106** [react-navigation/react-navigation#5935]
**1. I create my Apollo stuff and return**
```
<ApolloProvider client={client}>
  <AppContainer />
</ApolloProvider>
```

**2. `AppContainer` is in a separate file**
```
createAppContainer(AppDrawerNavigator)
```

**3. `AppDrawerNavigator` is in a separate file**
```
createDrawerNavigator(
  {
    HomeStack: {
      screen: HomeStackNavigator
    },
    ...drawerRoutes
  },
  {
    initialRouteName: 'HomeStack',
    drawerPosition: 'right'
  }
);
```

**4. `drawerRoutes` is an hard coded object**
```
const drawerRoutes = {
  First: {
    screen: IndexStackNavigator
  },
  Second: {
    screen: IndexStackNavigator
  }
};
```

Now I want to dynamically create the `drawerRoutes` after querying the Apollo client.
But I did not manage to access the client inside `createDrawerNavigator`.
Also I cannot pass something down to the `createDrawerNavigator`. Is there a tricky way to do that?
Best would be to create the `drawerRoutes` in the 1. step an than pass down the route object to the 3. step.

When I put everything in one file, it is working. But the file gets messy.

Can anybody help? Do you need more information?

**Comment by matthamil** [comment]
Hello! Issues are reserved for bug reports. I am going to close this issue since this is not a bug report.

I'd recommend joining the [Reactiflux](https://www.reactiflux.com/) community and asking in one of the channels there and also creating a post on [Stack Overflow](https://stackoverflow.com/).

----

With that being said, here's my two cents that may or may not be helpful:

If you are wanting to create dynamic routes inside a drawer, you could set up the drawer navigator such that it is aware of all routes when it is first instantiated. That is, use a regular drawer navigator. I suggest creating a custom component to be rendered as the drawer itself by using the `contentComponent` field in the `DrawerNavigatorConfig` (see `[DrawerNavigatorConfig](https://reactnavigation.org/docs/en/drawer-navigator.html#drawernavigatorconfig)` in the docs).

Inside this custom component, you have access to the `navigation` prop which contains all routes inside the navigation state:

```js
// All routes that the custom drawer is aware of
const { routes } = this.props.navigation.state;
```

With access to all available drawer routes, you can filter the list of routes based on some dynamic configuration:

```js
class MyCustomDrawerComponent extends React.Component {
  async componentDidMount() {
    const routes = await getDrawerConfig();
    this.setState({ isLoading: false, routes });
  }

  render() {
    const { navigation } = this.props;
    const { isLoading } = this.state;

    if (isLoading) {
      return <LoadingIndicator />
    }

    const routes = navigation.state.routes.filter(route => /* route filter logic */);

    return routes.map((route => <DrawerItem />); // with whatever appropriate props that the component you render needs
  }
}
```

One downside to this approach is that there are no checks stopping a user from accessing a removed route with `navigation.navigate('RouteThatWasFilteredOut');`. A few possible remedies for this downside is to either:

1. rely on feature flags/toggles throughout your app where ever you are calling `navigation.navigate('RouteForSpecificUsersOnly')`
1. use a [custom router](https://reactnavigation.org/docs/en/custom-routers.html) and/or [custom navigator](https://reactnavigation.org/docs/en/custom-navigators.html)
1. hope you don't call `navigation.navigate('RouteForSpecificUsersOnly')` for the wrong user 🤷‍♂

**Comment by vikramkh** [comment]
Is this possible to do for Tabs as well?

**Comment by matthamil** [comment]
Yes @vikramkh . We use a similar approach to dynamically show/hide tabs in the tab bar in our app. I should probably open source it.

**Comment by vikramkh** [comment]
It says in the react-navigation docs that this is a limitation though: 
"React Navigation requires that you define your routes statically, like so:"
"Let's say that when a user signs in to the app, you want to get a list of the user's friends and add a route for each friend in the FriendsNavigator. This would make it so there is a button with each of their names in the drawer. React Navigation does not currently provide an easy way to do this. "

**Comment by matthamil** [comment]
Yep, dynamic routes are not supported out of the box with react-navigation. Check out the comment I posted earlier w/ the code snippet and the downsides I listed. That should get you started to implementing one way to work around this limitation.

**Comment by vikramkh** [comment]
I did something similar to what you said to create routes for a createMaterialTopTabNavigator, but in order to return the entire component, I had to make a new AppContainer. Is this one of the drawbacks you were referring to?

**Comment by vikramkh** [comment]
@matthamil is it any at all possible that you could release the open source of your app? It would be very helpful as I can't seem to get it to work unless I create an entirely new app container with a reduced array of values containing each route?
