### ISSUE TITLE
static navigationOptions tabBarlabel not work

### ISSUE THREAD

**Issue by craigcosmo** [react-navigation/react-navigation#5943]
## The issue tracker is reserved for bug reports only.

---

### Current Behavior

// home page
static navigationOptions = {
		header: null,
		tabBarLabel:'home page'
	};

this should set label to `home page` but it doesn't

### Expected Behavior

tab label show text `home page`

### How to reproduce

class HomeScreen extends React.Component {

	static navigationOptions = {
		header: null,
		tabBarLabel:'home page'
	};
	render() {
		return (
			<View style={css.container}>

			</View>
		);
	}
}
### Your Environment

"react-navigation": "^3.0.9",

  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
      Memory: 141.31 MB / 24.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

**Comment by craigcosmo** [comment]
I put the sample code on github https://github.com/craigcosmo/AwesomeProject

check for the home tab. The tab label should be `moon` instead of `home`

**Comment by craigcosmo** [comment]
got update?  did you run the demo code?

**Comment by satya164** [comment]
The behavior is correct. You're setting this option on a nested screen inside the stack navigator which doesn't affect what's rendered in the root tab navigator.

https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

**Comment by Davepn16** [comment]
> The behavior is correct. You're setting this option on a nested screen inside the stack navigator which doesn't affect what's rendered in the root tab navigator.
> 
> https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

This link is broken.
