### ISSUE TITLE
ComponentDidMount in other stacks are called

### ISSUE THREAD

**Issue by tiniki** [react-navigation/react-navigation#5944]
### Current Behavior

I have the following code:

```
...
const AuthStack = createStackNavigator({
        ...
	SignUpScreen,
	SignUpAboutScreen,
	SignUpGoalScreen,
	SignUpSuccessScreen,
}, stackNavigatorConfig)

const MainStack = createStackNavigator({
	MainScreen,
        ...
	SignUpGoalScreen,
}, stackNavigatorConfig)

const SettingStack = createStackNavigator({
	...
}, stackNavigatorConfig)

const AppNavigator = createDrawerNavigator({
	MainStack,
	SettingStack,
}, {
	contentComponent: DrawerContent,
	drawerWidth: sizes.drawerWidth,
})

const RootNavigator = createSwitchNavigator(
	{
		AuthLoadingScreen,
		Auth: AuthStack,
		AppNavigator,
	},
	{
		initialRouteName: 'AuthLoadingScreen',
	}
)

const AppContainer = createAppContainer(RootNavigator)

export default AppContainer
```

If I navigate from `SignUpAboutScreen` to `SignUpGoalScreen`, the ComponentDidMount in `MainScreen` and `DrawerContent` are called. If I remove SignUpGoalScreen from MainStack, they is not called.
### Expected Behavior
The ComponentDidMount in `MainScreen` and `DrawerContent` is NOT called.

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.6.0
| react-native     | 0.59.2
| node             | 8.12.0
| yarn      | 1.9.4

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
