### ISSUE TITLE
undefined in not a object(evaluating'_RNGestureHandlerModule.default.Direction')

### ISSUE THREAD

**Issue by akhiljasrotia** [react-navigation/react-navigation#5949]
I'm trying to integrate a native android app with a react native app. And I'm getting this error after linking it with the android app. Is it possible to fix this error?

**Comment by eriveltonelias** [comment]
Hi @jin-benben,
this happens if you haven't installed RNGH properly. be sure to follow the steps from here: https://reactnavigation.org/docs/en/getting-started.html#installation


https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=Cannot+read+property+%27Direction%27+of+undefined+

https://github.com/react-navigation/react-navigation/issues/5724#issuecomment-480506198

**Comment by niranjan1990** [comment]
@akhiljasrotia  Got it Working ??

**Comment by akhiljasrotia** [comment]
No, I'm not able to integrate it with the native app. I'll be glad to get
some help.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/30/19,
3:58:17 PM

**Comment by niranjan1990** [comment]
Even im stuck there..waiting for the update

**Comment by fearlessfe** [comment]
On iOS, to complete the linking, make sure you have Cocoapods installed. Then run:
* cd ios
* pod install
* cd ..
I have the same problem. do exact as the docs solve my problem
