### ISSUE TITLE
Text in drawerlabel causes huge spaces

### ISSUE THREAD

**Issue by nirjack** [react-navigation/react-navigation#5967]
This is causing huge spaces 

### Current Behavior
![Screenshot_20190603-155019](https://user-images.githubusercontent.com/12936751/58795223-bcb72600-8617-11e9-802d-c3714c05d5d4.png)

Code:
`navigationOptions: {
      drawerLabel:
        <View>
          <Text>
            Label 1
          </Text>
          <Text>
            Label description text
          </Text>
        </View>,
      drawerIcon: () => (
        <Icon type='Entypo' name='home' />
      ),`

### Expected Behavior
![Screenshot_20190603-155540](https://user-images.githubusercontent.com/12936751/58795532-8cbc5280-8618-11e9-8ccb-2b6b32cbc723.png)

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17
| react-native     | 0.59.8
| node             | 8.11.2
| npm or yarn      | npm

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
