### ISSUE TITLE
BottomTab doesn't navigate to first tab from last tab

### ISSUE THREAD

**Issue by sercanov** [react-navigation/react-navigation#5974]
I was about to open this issue to `react-navigation-tabs` repo but v2.1.3 doesn't have this issue. I see `react-navigation` v3.11.0 using `react-native-tabs` v1.1.4 So updating dependency could fix it. 

### Current behaviour

The app has 3 tabs; Tasks, Feed and User. Initial tab is the Tasks tab. 

When navigated to User tab, pressing Tasks tab doesn't navigate.
But, when on Feed tab, it does navigate to Tasks tab. It's a weird one.

### Expected behaviour

It should navigate to Tasks tab.

### What have you tried

- Added `tabBarOnPress` handler and logged `navigation.state`. The state actually changes to next tab when pressed.
- Tried both `createBottomTabNavigator` and `createMaterialBottomTabNavigator` they behave the same.

### Code sample

```javascript
const appStack = createBottomTabNavigator(
  {
    Tasks: {
      screen: taskStack,
      navigationOptions: {
        tabBarIcon: tabBarIcon('assignment'),
        title: 'Tasks',
        tabBarOnPress: ({ navigation, defaultHandler }) => {
          console.log(navigation.state);
          defaultHandler();
        },
      },
    },
    Feed: {
      screen: feedStack,
      navigationOptions: {
        tabBarIcon: tabBarIcon('view-stream'),
        title: 'Feed',
        tabBarOnPress: ({ navigation, defaultHandler }) => {
          console.log(navigation.state);
          defaultHandler();
        },
      },
    },
    User: {
      screen: profileStack,
      navigationOptions: {
        tabBarIcon: tabBarIcon('person'),
        title: 'User',
        tabBarOnPress: ({ navigation, defaultHandler }) => {
          console.log(navigation.state);
          defaultHandler();
        },
      },
    },
  },
  {
    tabBarOptions: {
      activeTintColor: 'white',
      inactiveTintColor: theme.colors.disabled,
      style: { backgroundColor: theme.colors.primary },
    },
  }
);
```

### How to reproduce

- Just create a bottomTabNavigator with 3 tabs and try to navigate to first tab from last tab.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.11.0
| react-native          |0.59.8
| node             |10.15.3
| npm or yarn      |yarn v0.15.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by exondus** [comment]
Hi, I appreciate that this issue was closed due non-responses however, I have a similar issue. My navigation is set up similar to @sercanov with 5 tabs. I tried reducing my tabs to four but the issue persists. I would really appreciate your suggestions or fixes.
