### ISSUE TITLE
Not rendering

### ISSUE THREAD

**Issue by armandoarmando** [react-navigation/react-navigation#5986]
Hi everyone.. I'm trying to push a new page inside the tab (I'm in Home tab, and I want to open Detail Page in the same tab), the page it's called (i can see the logs) but  the render never happen. Thanks

The code:

```
const HomeStack = createStackNavigator({
    Home: {
        screen: HomeList
    },
    Hello: {
        screen: Hello
    },
    Detail: {
        screen: Detail
    },
    }
);

const SourcesStack = createStackNavigator({
    SourceList: {
        screen: SourceList
    }
});

const TabNavigator = createBottomTabNavigator({
    Home: HomeStack,
    Settings: SourcesStack
});

const AppContainer = createAppContainer(TabNavigator)

export default () => <View style={{flex: 1}}><AppContainer/></View>
```

| software         | version
| ---------------- | -------
| react-navigation |  3.11.0
| react-native     | 0.59.8
| node             | 8.9.4
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by edudoda** [comment]
Hi @armandoarmando, did u solve this issue? 

I'm facing the same problem and my environment is very similar as yours. The app works fine in Android simulator but screen never change in iOS  =/

**Comment by gibo77** [comment]
Hi,
I have same issue. When I go back to home screen, it does not render.

**Comment by brentvatne** [comment]
hey there if an issue is closed you should create a new issue and follow the issue template!
