### ISSUE TITLE
Navigation Issue and back button display

### ISSUE THREAD

**Issue by Karanp13** [react-navigation/react-navigation#5987]
### Current Behavior
![Screenshot_1560148838](https://user-images.githubusercontent.com/19575772/59177155-cb05c480-8b78-11e9-89c8-b019ba60c223.png)

I used stack navigator and bottom navigator both.
First Some screen with stack navigator and in one screen i initialized bottom navigator.
I saw that show me back button. How to remove that one. 

I already put -
```
static navigationOptions = {
    headerTitle: '',
    headerLeft: <View></View>,
  };
```
### Expected Behavior

Back button should not be display. 

### How to reproduce

I initialize the Stack navigator In App.js and In one Screen of Stack navigator i initialized Bottom Navigator. 
All screens are different.
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.9

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Hatko** [comment]
I've encountered the same issue and [re-created it](https://github.com/react-navigation/react-navigation/issues/5998). There is also a link to snack
