### ISSUE TITLE
Drawer opens itself when calling Share component.

### ISSUE THREAD

**Issue by adriancuco** [react-navigation/react-navigation#5997]
### Current Behavior
Drawer opens itself background when calling Share component.

### Expected Behavior
Drawer remains closed  when calling Share component.

### How to fix but not work
I thought to close it by using router.getStateForAction, but not triggered.

### Your Environment
 "react-navigation": "^3.11.0",
"react": "16.6.0-alpha.8af6728",
 "react-native": "0.57.3",

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by adriancuco** [comment]
Hi there,

Sure. No problem
Understood. Sorry about it.

Thx

Regards

________________________________
De: Brent Vatne <notifications@github.com>
Enviado: jueves, 13 de junio de 2019 19:25
Para: react-navigation/react-navigation
Cc: adriancuco; Author
Asunto: Re: [react-navigation/react-navigation] Drawer opens itself when calling Share component. (#5997)


hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by syedayesh** [comment]
+1

**Comment by syedayesh** [comment]
Hi I am having the same issue is there any other thread where this issue is discussed. Thanks in advance.

**Comment by lindboe** [comment]
We ran into this as well on RN 0.61.5, but we're using react-native-gesture-handler's DrawerLayout directly. I also didn't see it on every device, only a Samsung Galaxy S8, but not on an iPhone 6, or an emulated Pixel 3a.

Adding this comment as a reminder to @lindboe to look into a minimal reproduction case later.
