### ISSUE TITLE
AndroidX support?

### ISSUE THREAD

**Issue by AyushG3112** [react-navigation/react-navigation#6017]
The upcoming RN 0.60.0 release adds androidX as a breaking change. Is there any timeline for AndroidX in react-navigation?

**Comment by satya164** [comment]
react navigation doesn't include any native code. Android x isn't relevant. If you're talking about one of the dependencies, please open issues on their repos.

**Comment by rumax** [comment]
@satya164 Technically you are not right. Because indeed it is dependency of the `react-native-gesture-handler`, which is required by react-navigation! You can check [Getting started](https://reactnavigation.org/docs/en/getting-started.html) where it is clearly stated:

> Next, install react-native-gesture-handler and react-native-reanimated.

So, because, `react-navigation` forces us to use these dependencies, the issue with request to support AndroidX is valid. Which means that we are blocked with this issue. 

As an alternative, you can update the documentation and explain how to solve the dependency issue.
