### ISSUE TITLE
runAfterInteractions callback never called!

### ISSUE THREAD

**Issue by ramon90** [react-navigation/react-navigation#6043]
### Current Behavior
  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      this.setState({navigated: true})
    })
  }
callback from runAfterInteractions never get called, and as a result the component never renders.

### Expected Behavior

The callback from runAfterInteractions to be called.

### How to reproduce

In a Stack navigator, just have the above componentDidMount code on the second screen, and something to be rendered.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.9

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
