### ISSUE TITLE
React-navigation athentication flow shows an error as "You can also use a navigator" 

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#6061]
I am using react-navigation to navigate inside the App. Here I have used a route.js file and added all stack, tab and Drawer navigation, and used a separate component to authenticate the app as Authentication.js.

Now I need to add the authentication inside the react-navigation. I followed [this](https://reactnavigation.org/docs/en/auth-flow.html) document.

But it failed to login inside my app and I got an error as 

```
You can also use a navigator:

import MyNavigator from './MyNavigator';
...
Authentication: MyNavigator,
}
Unhandled JS Exception: The component for route 'Authentication' must be a React component. For example:

import MyScreen from './MyScreen';
...
Authentication: MyScreen,
}


```

**This is my code sample of that part authentication in routes.js screen**

```
const AppAuth = createStackNavigator(
{
    Authentication:{
      screen: Authentication
    },
    UserSignUp:{
      screen: UserSignUp
    },
}
);


export default  createAppContainer(createSwitchNavigator(
  {
  AppNavigator: MyAppNavigator, ==> Here I have drawer navigator screens 
  Auth: AppAuth, ==> Auth screens
  BottomTabNavigator: BottomTabNavigator ==> Here I have tab annd stack navigator(i.e) nested navigator
},
{
    initialRouteName: 'Auth',
  }
));

```

**Comment by andrewtelkamp** [comment]
Exact same problem, and my exports are fine. Tried flipping between named and default exports with no success.

**Comment by ericvicenti** [comment]
The main part of the error is: `Unhandled JS Exception: The component for route 'Authentication' must be a React component.`

Go make sure that `Authentication` is a valid react component for your screen, or it is a navigator created with something like `createStackNavigator()`.

Next time you file an issue, please provide an Expo snack or a standalone repo to demonstrate the entire bug. The problem is not within the code snippet you provided!
