### ISSUE TITLE
Performance Issue using react-native-collapsible

### ISSUE THREAD

**Issue by Albert0405** [react-navigation/react-navigation#6121]
I notice a major performance issue while using react-native-collapsible with react navigation.
Im using createMaterialTopTabNavigator to display tabs on one of my app's screen. 
RN Collapsible works perfectly fine if its rendered inside the tabs (the JS stays from 50-60fps) but if its rendered outside the tabs for example in header, the JS drops to 20-40fps. 

You can watch it here for the actual problem
vid 1 - https://imgur.com/a/FnCs0Xb
vid 2 - https://imgur.com/VvSkLZ9

Note: I tested that in release mode, i posted an issue to their github but they dont have answer yet and just wanna know if you can help with this problem
Link: https://github.com/oblador/react-native-collapsible/issues/297#issue-470790826

**Comment by satya164** [comment]
The library animates height which isn't performant because it'll be JS based. I assume when you're rendering on top of the tab view, `onLayout` is being fired in tab view several times in quick succession due to the height animation, and this causes frame-drops.

I'd suggest to implement a custom solution where you translate the view below to reveal your content rather than animating height. Or use something like react-native-reanimated which can animate height natively.

**Comment by Albert0405** [comment]
@satya164 Thanks, using react-native-reanimated increases the performance. From 20-40fps its now 40-60fps
