### ISSUE TITLE
React Navigation stale

### ISSUE THREAD

**Issue by Rebsos** [react-navigation/react-navigation#6126]
Currently I'm trying to upgrade React Native from Version 57 to 59 to meet the Google Play requirements for 2019 e.g. [64 bit (August)](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) and [target API 28 (November)](https://developer.android.com/distribute/best-practices/develop/target-sdk). But I'm stuck due some bugs in React Navigation. First I got this [issue (tab lazy bug)](https://github.com/react-navigation/react-navigation/issues/6098), because React Navigation uses an old version of react-native-tabs. By manually upgrading just the tabs, it could be resolved. But it seems somehow incompatible with react navigation and I got this [issue (tab press delay)](https://github.com/react-navigation/tabs/issues/150), but there's currently no response. 

I heard that React Navigation is getting splitted into multiple packages to improve maintainability. OK, but it now feels like a car that wheels turn with different speed. It would be nice if they get more synchronized in the future or a info what to expect from React Navigation in the next months. 

I'm a long-term user of react-navigation and saw a lot of ups and downs e.g. abandoning navigation-experimental (best navigator version imo), removing lazy tabs, removing redux support. In the meantime I spend months for workarounds until there would be a solution. I think the next down is coming, cause react-navigation is not uptodate like the faster wheels e.g. react-native-tab-view.

This should not be seen as a criticism, I'm thankful for the work of all contributors and maintainers. This is just a view of one random user.

### Current Behavior

React Navigation not working good with RN 59. E.g. [Lazy Tabs](https://github.com/react-navigation/react-navigation/issues/6098), [Tab Delay](https://github.com/react-navigation/tabs/issues/150)

### Expected Behavior

Working with RN 59

### How to reproduce

git@github.com:Rebsos/react-navigation-lazy-bug.git
git@github.com:Rebsos/react-navigation-tabs-delay-demo.git

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.59.10
| node             | 8.12
| npm or yarn      | npm

**Comment by matthamil** [comment]
Hello! It looks like this is a meta issue about another issue you have open (https://github.com/react-navigation/tabs/issues/150). I am going to close this since there is nothing new and actionable within this issue itself. 

If you are experiencing an issue with tabs, I strongly encourage you to investigate and PR a fix! I'd be happy to help you if you had any specific questions along the way. With any open source project, the best fixes/additions come from community contributors (like you!) who experience a particular pain point with the library and share their fix with the rest of the community.
