### ISSUE TITLE
TypeError: undefiend is not an object (evaluating 'this._callListeners.bind')

### ISSUE THREAD

**Issue by MS-Harine** [react-navigation/react-navigation#6154]
### Current Behavior

I am developing app with expo, react-native, and react-navigation. Some times goes on, the error (which is title) occurred. It looks like same with issue #5825 and #5244 . However, any answers in that issues doesn't work for me. When I give up after 3 days, it work without any problem suddenly. I don't know why it works.

After few days, this problem occurred. And the stack trace is different.

![image1](https://user-images.githubusercontent.com/29691372/62514798-49ba6d80-b85b-11e9-8c65-1e080699804f.png)

This stack trace looks like 'uglify js'. I can't develop anymore. Please help me..

### How to reproduce

1. This problem occurred when I use `createStackNavigator()`.
2. I create a new project through expo and install all dependencies and copy&paste the code.
3. It works (????)
4. So, I copy & paste all working code into my project, and reinstall all dependencies manually.
5. It doesn't work (???????)
6. I try to run 'git diff', but the result saying they are same.
7. What can I do...

Someone says that "Then change your project to working project which you make a few minutes ago!", but I think maybe problem will occurred when the times go on..

Help..

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1 
| react-native     | 0.59.8
| node             | 10.16.1
| npm or yarn      | 6.4.1

**Comment by vanthanh84vn** [comment]
I have the same problem. 
It happens when we try to use createStackNavigator.
I copy code from url: https://reactnavigation.org/docs/en/hello-react-navigation.html 
Someone please help us

My dependencies:
    "expo": "^34.0.1",
    "expo-font": "^6.0.1",
    "native-base": "^2.13.4",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "^0.59.10",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-reanimated": "~1.1.0",
    "react-native-unimodules": "~0.5.2",
    "react-navigation": "^3.11.1",

**Comment by satya164** [comment]
As mentioned in the issue, this crash happens when you change your Babel configuration to something other than what React Native uses by default.

https://github.com/react-navigation/react-navigation/issues/5825#issuecomment-496560834
https://github.com/react-navigation/react-navigation/issues/5854#issuecomment-493775447

So you need to remove any such Babel plugins from your config and then run `expo start -c` (if using expo) or `react-native start --reset-cache`.

If you're still having an issue, please post a **reproducible example**. No one can help without looking at your code just from an error message.
