### ISSUE TITLE
Pass function to navigationOptions in functional component

### ISSUE THREAD

**Issue by crees1** [react-navigation/react-navigation#6196]
Trying to pass a method to update state using setParams inside of a functional component. The method gets called but unfortunately the count is never updated. Does anyone have insight in how you might do this? 

Code for reference:

```

import React, { useState, useEffect } from 'react';
import {
  Text,
  View,
  Button
} from 'react-native';

import Ionicons from 'react-native-vector-icons/Ionicons';
import styles from './styles';

const IconComponent = Ionicons;

export default function HomeScreen({ navigation }) {
  const [count, setCount] = useState(0);

  const updateCount = () => {
    setCount(count + 1);
  };

  useEffect(() => {
    navigation.setParams({ increaseCount: updateCount });
  }, []);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text style={styles.yellow}>Hello!</Text>
      <Text>{count}</Text>
      <Button
        onPress={() => navigation.navigate('Details', { itemId: count })}
        title="Navigate To Page"
        style={styles.yellowButton}
      />
    </View>
  );
}

HomeScreen.navigationOptions = ({ navigation }) => ({
  title: 'Home',
  tabBarLabel: 'Title',
  headerRight: (
    <IconComponent
      onPress={() => navigation.getParam('increaseCount')()}
      name="ios-add"
      size={25}
      color="#fff"
      style={styles.test}
    />
  ),
});


```

**Comment by wilhelmeek** [comment]
Not sure if this solves your issue, but since you're only setting the param once (on mount), the setter will always `setCount(count+1)` which is `setCount(1)`. You'll need to update the setter functions once for every time that count is increased.

```
  useEffect(() => {
    navigation.setParams({ increaseCount: updateCount });
  }, [count]);
```

**Comment by douglaslondrina** [comment]
I'm struggling with something similar. Is there a way now with functional components, by pressing a button in the navigation bar, to change a variable or state inside my component instance?

It looks like @crees1 was trying to do this, set a value in his HomeScreen component by a button press inside the navigation area.

**Comment by filiphosko** [comment]
@crees1 You should refactor it as @wilhelmeek suggested otherwise the count value would be 1 all the time. Also you could refactor the `updateCount` method using useCallback and put the `count` variable there as a dependency. That way you could put `updateCount` callback as a dependency of useEffect. The added benefit would be that the `updateCount` method wouldn't be re-created on every render of the component but only when `count` will change. Other way around could be that you'll use an anonymous function inside of `setCount`, like this `setCount((prevCount) => prevCount + 1)`, that way you wouldn't need to put a dependency anywhere. I haven't tried it but it could help.

**Comment by satya164** [comment]
@filiphosko is right.

Closing since this issue isn't a bug in React Navigation and more of a confusion regarding usage of hooks. Usage of `navigationOptions` is the same in function components as it is in class components.

For an easier way of updating options, we're working on a new version of React Navigation: https://github.com/react-navigation/navigation-ex
