### ISSUE TITLE
Missing types for some options for SwitchNavigatorConfig 

### ISSUE THREAD

**Issue by sadeghhosseini** [react-navigation/react-navigation#6240]
I installed `react-navigation` `v4 `from both `npm `and `yarn `but the version 4 as apposed to the documentation, seems to miss some features like two of the options from `createSwitchNavigator`'s  `SwitchNavigatorConfig `which are` backBehavior: [history, order]`.
I would appreciate it if you could fix this.

**Comment by satya164** [comment]
PR welcome

**Comment by Transfusion** [comment]
Seems to be fixed as of https://github.com/react-navigation/react-navigation/commit/c828050ba193c30a4a685936585278282eb8b429? `CreateNavigatorConfig` is now an intersection including `NavigationSwitchRouterConfig` which has `backBehavior?: 'none' | 'initialRoute' | 'history' | 'order'; // defaults to 'none'` instead of the original `SwitchNavigatorConfig`
