### ISSUE TITLE
Screen mount twice when go back and quickly re navigate to same screen

### ISSUE THREAD

**Issue by danmdinu** [react-navigation/react-navigation#6242]
This issue has been first described here https://github.com/react-navigation/react-navigation/issues/2396 and it's the same. For some reason it was closed although people encounter the same issue. 

It's reproducible with "react-navigation": "3.5.1"

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public repo or as a [Snack](https://snack.expo.io/)?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
