### ISSUE TITLE
react-navigation-stack undefined is not an object (evaluating '_core.ThemeColors.light')

### ISSUE THREAD

**Issue by 1512751361** [react-navigation/react-navigation#6249]
---

### Current Behavior

1. APP引入一下代码
![image](https://user-images.githubusercontent.com/24776858/64102879-6f2b9000-cda3-11e9-82ac-09af594ac1d3.png)
报错
![F2D85744A071699B79A1B4744177470B](https://user-images.githubusercontent.com/24776858/64102917-836f8d00-cda3-11e9-989a-e09e1fe1e151.jpg)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.0
| react-native     | 0.60.5
| node             | 10.15.3
| npm or yarn      | npm 6.4.1

**Comment by satya164** [comment]
cc @brentvatne

**Comment by 1512751361** [comment]
> cc @brentvatne

报上面那个错误是问什么？如果我不引入上面那个代码是不会报这个错的？？？求解决！！！

**Comment by orhanveli** [comment]
same here please help!

**Comment by MoOx** [comment]
Facing this when trying RN 0.61 RC

**Comment by MoOx** [comment]
Not sure why this error popped up just at this moment (probably a weird install?), but updating to latest version of /core fixed the issue.

**Comment by orhanveli** [comment]
removing node_modules folder and reset react-native solved my problem

```
rm -rf node_modules
npm i
npm start -- --reset-cache
```

**Comment by plexdk** [comment]
> removing node_modules folder and reset react-native solved my problem
> 
> ```
> rm -rf node_modules
> npm i
> npm start -- --reset-cache
> ```

same result here :/

**Comment by MoOx** [comment]
@orhanveli @plexdk are you using a lock file?

**Comment by orhanveli** [comment]
yup!

**Comment by plexdk** [comment]
yep.. also tried to remove that one

**Comment by brentvatne** [comment]
if you're using 3.x then make sure its on the latest version, and as @MoOx suggested, delete your lockfile and delete node_modules

**Comment by alexpchin** [comment]
For me, it seemed to fix by downgrading from `^2.4.0` to `2.3.0`.

**Comment by emilieserre** [comment]
> removing node_modules folder and reset react-native solved my problem
> 
> ```
> rm -rf node_modules
> npm i
> npm start -- --reset-cache
> ```

ca ne fonctionne pas pour moi. Mon terminal ecrit 👍

**Comment by emilieserre** [comment]
Remove-Item : Impossible de trouver un paramètre correspondant au nom « rf ».
Au caractère Ligne:1 : 4
+ rm -rf node_modules
+    ~~~
    + CategoryInfo          : InvalidArgument : (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by netgfx** [comment]
Any word on this, why this is happening?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
