### ISSUE TITLE
HeaderBackButton error

### ISSUE THREAD

**Issue by lahin31** [react-navigation/react-navigation#6263]
## Problem

I was trying to make a search component in the header(using headerRight in navigationOptions), when I click the search icon it went to Seach component, this only worked successfully in IOS device not in Android device.

I followed this [search-layout](https://github.com/react-navigation/search-layout)

---

![photo_2019-09-06_00-46-01](https://user-images.githubusercontent.com/12637865/64370755-ea5da200-d040-11e9-8d5a-557dd464d5a5.jpg)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.0
| react-native     | 0.59.8
| react-native-gesture-handler | ~1.3.0
| react-navigation-addon-search-layout | ^0.13.1
| react-navigation-stack | ^1.5.1

**Comment by vonovak** [comment]
hi!
Thanks for reporting. The problem is probably that `HeaderBackButton` in [here](https://github.com/react-navigation/search-layout/blob/a134c5516e5d7cb0f52bfe886e662d0226fd7a38/src/Header.js#L10) results into [this](https://github.com/react-navigation/react-navigation/blob/97016c4498019477fe9878d41b66b47c02f3be84/src/deprecations.js#L111). You just need to change that import as advised.

**Comment by lahin31** [comment]
@vonovak Thank you for your kind reply. I just solved it. :)
