### ISSUE TITLE
Header Component unmounted while navigating in a stack on IOS

### ISSUE THREAD

**Issue by MrTrush95** [react-navigation/react-navigation#6268]
### Current Behavior

The component rendered in the header of a screen, who is inside a stack navigator, is beeing unmounted when navigating to other page of the stack. This only happens on IOS.

### Expected Behavior

It should be the same thing as on Android. The component rendered in the header should not be unmounted when navigating to other page in the stack.

### How to reproduce

Main Screen : Search.js
```
class Search extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
        ...
      }
    };
  }

  static navigationOptions = ({ navigation }) => {
    return {
      header: () => (
        <HeaderWithSearch
          onSearchSubmit={(filters, immediate) =>
            navigation.getParam("handleSearchChange")(filters, immediate)
          }
        />
      )
    };
  };
}
```
Then lets say I navigate from Search to SearchDetails with : 
`this.props.navigation.navigate("SearchDetails");`

And then back from SearchDetails to Search : 
`this.props.navigation.goBack()`

The HeaderWithSearch component is unmounted after I do the first navigation. Only happens on IOS like I said.

The state of the component is lost in the process. So if I had an input with text inside of it, I lose it when the component is unmounted.
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| expo     | 34.0.1
| node             | 8.11.1
| npm      | 5.6.0

**Comment by landryalexandre** [comment]
I'm interested in this item

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
