### ISSUE TITLE
Is it possible to show the page title on scroll?

### ISSUE THREAD

**Issue by danielfein** [react-navigation/react-navigation#6300]
_I have no idea where to post this, it's not a good question for StackOverflow and not sure who checks the Discord._

Is it possible to achieve Apple's currently used (used in all of their apps) header animations that only show the title on scroll?

This is an example of the animation: https://i.imgur.com/442utlh.mp4

With the amount of real estate on phones now, the legacy headers are becoming less important to have visible on initial load. It's much nicer to have a large font title with the ability to have the title animate to the header and persist on screen when scrolled out of view.

**Comment by nihp** [comment]
@satya164

**Comment by pzatorski** [comment]
Hey @danielfein! Yes it is possible, because I tried to develop this behaviour before. You can fade-in/fade-out on scroll the headerTitle Component from react-navigation. The fun part is that you need to add the bigger title by yourself and animated in the same time while animating headerTitle Component from react-navigation.
