### ISSUE TITLE
In HeaderBackButton 'scene' and 'layoutPreset' should be optional props

### ISSUE THREAD

**Issue by shamilovtim** [react-navigation/react-navigation#6340]
In HeaderBackButton 'scene' and 'layoutPreset' should be optional props

Both of these props are optional and causing type errors when they're omitted. Furthermore, even if scene **were** a required prop it's not intuitive from any docs what's supposed to be passed into this prop.

**Comment by satya164** [comment]
They are required props because the header needs to pass those props. You can use those props inside your component or not, it shouldn't give any error. React Navigation will always pass those props regardless.

If you're using the back button outside the context of React Navigation header, then I'm not sure about the solution.

**Comment by shamilovtim** [comment]
Hi @satya164 if I replace the standard back button in my headerLeft with HeaderBackButton it works just fine without these two props but it still complains about a type error. See screengrab. 

Also to note I never got this type error before upgrading to v4 
<img width="1020" alt="Screen Shot 2019-09-30 at 11 57 36 PM" src="https://user-images.githubusercontent.com/3495974/65933091-38668b00-e3de-11e9-95db-e2086f6e1611.png">

**Comment by satya164** [comment]
Make it a function and forward the props if you're gonna use the built in back button

```js
header left: props => <HeaderBackButton {...props} />
```

**Comment by shamilovtim** [comment]
Thanks!!!
