### ISSUE TITLE
Params must not be provided to .navigate() when specifying an object

### ISSUE THREAD

**Issue by tatva-hiral** [react-navigation/react-navigation#6413]
Getting error "Params must not be provided to .navigate() when specifying an object" when pass params using react-hooks with functional components.

`const navigateToMain = useCallback(() => {
    navigation.navigate("Main", { isSetFlag: true });
  }, [navigation]);`

**Comment by vonovak** [comment]
`navigation.navigate("Main", { isSetFlag: true });` is the correct usage form. You're probably calling it the wrong way somewhere else in your code: see https://github.com/react-navigation/core/blob/86fb82a5faf77b94354f98b1f3201b4fac08c074/src/routers/getNavigationActionCreators.ts#L35

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
