### ISSUE TITLE
Automatically navigates back to previous screen when store updates

### ISSUE THREAD

**Issue by jedhelmers** [react-navigation/react-navigation#6435]
## React Navigation pops back a screen or two when services return and update store

I'm probably going to get scolded for not providing reproducible code, but here I go...

---

### Current Behavior

- `this.props.navigation.navigate("NextScreen")`
when service requests return and the store updates, often times the screen will navigate back to the previous screen. Sometimes it will navigate back two screens.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     | 0.59.9
| node             | v11.4.0
| npm or yarn      | 1.17.3

**Comment by vonovak** [comment]
> I'm probably going to get scolded for not providing reproducible code, but here I go...

if you know a repro is needed, why don't you provide it?

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
