### ISSUE TITLE
Quickly navigating between screens causes unknown 'state' crash

### ISSUE THREAD

**Issue by EctoChris** [react-navigation/react-navigation#6436]
### Current Behavior

I currently have created two stacknavigators (one for all normal screens, and one for screens in mode: 'modal'). 

They have been combined together like so:
export default createStackNavigator({
  content: normalScreens,
  modal: modalScreens
},
modalConfig
)

In both android + IOS simulators and devices, if I dismiss the modal screen and very quickly navigate back again, this crash occurs: 

TypeError: Cannot read property 'state' of null at Object.getScreenOptions (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:134575:30) at blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:133390:34 at Array.forEach (<anonymous>) at getDerivedStateFromProps (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:133382:18) at applyDerivedStateFromProps (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:25766:28) at updateClassInstance (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:26287:11) at updateClassComponent (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:29162:26) at beginWork$1 (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:30041:22) at beginWork$$1 (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:33594:20) at performUnitOfWork (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:32802:18)
message: "Cannot read property 'state' of null"
stack: "TypeError: Cannot read property 'state' of null↵    at Object.getScreenOptions (blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014328:134575:30)↵    at blob:http://localhost:8081/0af69659-0a53-440b-a104-5a6e1a014

![Screen Shot 2019-11-06 at 5 13 14 pm](https://user-images.githubusercontent.com/57429962/68273077-9a8b6d80-00b9-11ea-9758-6bbe5dd61dae.png)

I have tried cancelling modal animation in transitionConfig: () however the crash still occurs. 

### Expected Behavior

- When I navigate quickly, between screens no crash is experienced.

### Your Environment

  "react-native": "0.60.5",
   "react-navigation": "^3.11.1",
   yarn

**Comment by EctoChris** [comment]
The first navigate back is via this method:

<img width="547" alt="Screen Shot 2019-11-06 at 5 33 27 pm" src="https://user-images.githubusercontent.com/57429962/68273908-cdcefc00-00bb-11ea-9452-f937b98da357.png">


The following click is via the default navigation back button in header

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
