### ISSUE TITLE
Error The component for the router must be an react component 

### ISSUE THREAD

**Issue by subashchandru** [react-navigation/react-navigation#6442]
Environment:
React native: 0.61
react-native navigation:4.0
Deployed os : Android 9 pie 

```
import {createAppContainer} from 'react-navigation';
import {createStackNavigator} from 'react-navigation-stack';
import Signup from './Signup';
import React, { Component } from 'react';
import Home from './Home';
import EditProfile from './Editprofile';
import Payments from './Payments';
import Refer from './Refer';
import { createDrawerNavigator } from 'react-navigation-drawer';

export default class App extends React.Component {
  render() {

    return <Appcont />;
  }
}
const appi = createStackNavigator(
  {
    signup: {
      screen: ()=><Signup/>
    },
     home: {
        screen: ()=><Home/>
      },
      editProfile:{
        screen:()=><EditProfile/>
      },
      payments:{
        screen:()=><Payments/>
      },
      refer:{
        screen:()=><Refer/>
      }
    },
    {
      initialRouteName:'signup'
    }

);


const MyDrawerNavigator = createDrawerNavigator(appi,{
  initialRouteName: 'signup',
    headerMode:'float',
  contentOptions: {
    activeTintColor: '#e91e63',
  }
});

const Appcont = createAppContainer(MyDrawerNavigator);
```

Home.js
```
import React, { Component } from 'react';
import { Text, View,Image } from 'react-native';


 class Home extends Component {
  static navigationOptions = {
    title:'Home',
  drawerLabel: 'Home',
  drawerIcon: ({ tintColor }) => (
    <Image
      source={require('./img/Homepng.png')}
      style={{width:20,height:20}}
    />
  ),headerShown:'true'
};
  render() {

    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>Hello, home</Text>
      </View>
    );
  }
}
export default Home;

```
When I run the above code it throws me an error !!! 
**Error The component for the router must be a react component** 

I have seen all the issues related to this and rectified as much I can but I am still getting this error I don't know why?

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
