### ISSUE TITLE
React Navigation - DeepLink & initialRouteName conflict

### ISSUE THREAD

**Issue by RatFou** [react-navigation/react-navigation#6450]
I try to use DeepLink with React Navigation, but I'm facing to an issue with my InitialRoute.

Here my navigator:

createSwitchNavigator({
    Home: HomeScreen,
    App: NavigationStack,
    DeepLinkScreen: {
      screen: IntermediateScreen,
      path: 'myview/:myparam',
    },
}, { initialRouteName: 'HomeScreen', })
Here my NavigationStack:

const NavigationStack = createStackNavigator({
    CameraScreen: { screen: CameraScreen },
});
In "HomeScreen" screen I have a function that redirect to "CameraScreen" if user is already connected. In "IntermediateScreen" screen I have a function that redirect to "CameraScreen" with params.

My scenarios (I'm already logged):

I manually open the App, I'm redirected to "CameraScreen" without params => Everything is fine.
I use a QR Code to launch the App (myApp://myview/1234) => I go to the "HomeScreen" first, then I'm redirected to "CameraScreen" without params, then I'm redirected to "CameraScreen" with params. => Problem: I don't want to have the "CameraScreen" without params, I want to be redirected directly to the "CameraScreen" with params.
I tried "getActionForPathAndParams" but I reproduce the same scenario.

I used the ReactNavigation auth flow to create my navigators: https://reactnavigation.org/docs/en/auth-flow.html and the React Deep link process: https://reactnavigation.org/docs/en/deep-linking.html

How do you manage Auth Flow & Deep link in your apps?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0
| react-native     | 0.61

**Comment by RatFou** [comment]
Nobody use AuthFlow with DeepLink?

**Comment by ArthurBrum** [comment]
Any updates here? Im facing similar problem...
With iOS everything routes as expected, but on Android it just loads default initial route.

**Comment by ArthurBrum** [comment]
I found a hotfix: 
If you think about it, a correctly configured [deep linking](https://reactnavigation.org/docs/en/deep-linking.html) should route your application to the paths as you configured in your StackNavigators, SwitchNavigatiors, etc. But using the
[auth flow](https://reactnavigation.org/docs/en/auth-flow.html) you prevent navigation from doing his job. Since we are calling navigation.navigate() before it can decide which route the app sould go to, the app never shows the desired link page.

With that in mind, all you have to do is check whether is the user or a link that launched the app. To do this, we will use the [Linking library](https://facebook.github.io/react-native/docs/linking). 
We first call the method Linking.getInitialUrl() - that is async, so you should use await (or handle the promise). And if it returns null, you know that the app was launched normally by the user. Otherwise, you know its coming from a link.

Therefore, we should do this to our authLoading class:

```
import React from 'react';
import { Linking } from 'react-native';

export default class authLoading extends React.Component {

    componentDidMount() {
        this._bootstrapAsync();
        
    _bootstrapAsync = async () => {
        const urlToOpen = await Linking.getInitialURL();
        if(urlToOpen != null) {
            /* In my case, stopping the auth code form being called was enough because the 
                path that Im calling through deep linking need no authentication. 
               If its not the case for you, you can always navigate using [navigation params](https://reactnavigation.org/docs/en/next/params.html#docsNav)... 
            */
            return;

        }else{
            /* Do things normally as your code is already doing now */
        }
    }
}

```

**Comment by satya164** [comment]
Closing since solution is posted by @ArthurBrum
