### ISSUE TITLE
ReferenceError: Can't find variable: RouteConfigs

### ISSUE THREAD

**Issue by deksmond** [react-navigation/react-navigation#6499]
I moved my react native codebase to my mac to continue building my application, after installing all the necessary packages it returns this "ReferenceError: Can't find variable: RouteConfigs" error when I load the JavaScript Bunndle.
<img width="454" alt="Screenshot 2019-12-09 at 1 41 04 PM" src="https://user-images.githubusercontent.com/31316656/70436693-2feb9a00-1a8a-11ea-9a2c-16c0e02b9ff0.png">

Please help.

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!

**Comment by vonovak** [comment]
try debugging your app - run it in the chrome debugger and have the "pause on caught exceptions" option enabled. Hope this helps.
