### ISSUE TITLE
withNavigation not getting screen params

### ISSUE THREAD

**Issue by joelworsham** [react-navigation/react-navigation#6518]
### Current Behavior

Setting params in the navigator is not passed through to components wrapped with `withNavigation()`. The param will come up `undefined`.

```
// app navigator
createStackNavigator({
  Dashboard: {screen: DashboardScreen, params: {myParam: 'test'}},
})

// nested component (not page) in app
class LayoutAuto extends React.Component {
  render() {
    const myParam = this.props.navigation.getParam('myParam')
    return (
      <Text>My Component {myParam}</Text>
    )
  }
}
export default withNavigation(LayoutAuto)
```

### Expected Behavior

I expect the param to not be `undefined` in my nested component using `withNavigation`

**Comment by vonovak** [comment]
By the looks of it, it seems like you're providing those params to `DashboardScreen` but reading them somewhere else? It's hard to say without a runnable repro.

hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
