### ISSUE TITLE
Passing variable from Stack to BottomTab navigator 

### ISSUE THREAD

**Issue by aasalshehhi** [react-navigation/react-navigation#6526]
### Current Behavior
When I navigate from home screen (stack navigator) to one of the pages, it passes the variable. However, when I click on a different page from the BottomTop navigator it does not pass the variable. 

### Expected Behavior
To pass variables from page to another when choosing them from the BottomTap navigator 

### Code

From HomeScreen (stack) 
                    <TouchableOpacity
                    onPress={()=> this.props.navigation.navigate("Screen1", {loggedInUser: loggedInUser, Role: Role})}>
                    </TouchableOpacity>
** I am getting loggedInUser and role from the login page

In Screen 1 (bottomTab) 
    const { navigation } = this.props;  
    const loggedInUser = navigation.getParam('loggedInUser');  
    const Role = navigation.getParam('Role');  

It gets these variable (loggedInUser & Role) on the first navigation from homepage to screen 1, but when I navigate from screen 1 to screen 2 (through BottomTab navigator) it doesn't pass the variables.   
I read about AsyncStorage, keys & dangerouslyGetParent and didn't honestly know how to utilize them in my code. 

### Environment 
| software         | version
| ---------------- | -------
| react-navigation |  4.0.10
| react-native     | 0.60.5
| node             | v10.16.0
| npm or yarn      | 6.12.0

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
