### ISSUE TITLE
App keeps crashing on loading

### ISSUE THREAD

**Issue by freewebwithme** [react-navigation/react-navigation#6591]
**Current Behavior**

I am using bare react native project. My project create with
```
npx react-native init myProject
```
And followed react navigation docs.
```
npm install react-navigation
npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
```
I am using React native 0.61.5 so skip the linking. And I skipped the step for iOS.

This is dependencies section of android/app/build.gradle 
```
dependencies {
     implementation fileTree(dir: "libs", include: ["*.jar"])                                                                                       
     implementation "com.facebook.react:react-native:+"  // From node_modules
     // Added this for react navigation
     implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
     implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
 
     if (enableHermes) {
         def hermesPath = "../../node_modules/hermes-engine/android/";
         debugImplementation files(hermesPath + "hermes-debug.aar")
         releaseImplementation files(hermesPath + "hermes-release.aar")
     } else {
         implementation jscFlavor
     }
 }
```
And MainActivity.java from android/app/src/main/java/com/myApp
```
 package com.reactnavigation.myApp;                                                                                                                 
 
 import com.facebook.react.ReactActivity;
// added for react nativation
 import com.facebook.react.ReactActivityDelegate;
 import com.facebook.react.ReactRootView;
 import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
 
 public class MainActivity extends ReactActivity {
 
   /** 
    * Returns the name of the main component registered from JavaScript. This is used to schedule
    * rendering of the component.
    */
    @Override 
    protected String getMainComponentName() {
      return "myApp";
    }
  // added for react nativation
    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
      return new ReactActivityDelegate(this, getMainComponentName()) {
        @Override
        protected ReactRootView createRootView() {
          return new RNGestureHandlerEnabledRootView(MainActivity.this);
         }
      };
   }
  }
```

And index.js file looks like this.
```
 import {AppRegistry} from 'react-native';
 import App from './App';                                                                                                                           
 import {name as appName} from './app.json';
 import 'react-native-gesture-handler';
  
 AppRegistry.registerComponent(appName, () => App);
```

**Expected Behavior**
App launches in emulator/device successfully

**Your Environment**

| software         | version |
| ---------------- | ------- |
|  Android   |
| react-navigation | 4.1.0
| react-native     | 0.61.5
| expo             | no expo
| node             | 13.7.0
| npm or yarn      | 6.13.6

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
