### ISSUE TITLE
Header Mode Float causes poor animation while navigating

### ISSUE THREAD

**Issue by mdfateh** [react-navigation/react-navigation#6845]
Issue in animation when using any custom header component (like React Native Paper Header or Nativebase Header) and headerMode set to 'float'. Now when we navigate to a screen it jerks a little and that causes poor ux.

However react navigation header works just great. 
Please let me know any what i need to fix in my code.

**Comment by gapgag55** [comment]
Any suggestion on this?
I also face this problem? 
How can I improve "Float Header Mode" performance?

**Comment by satya164** [comment]
> When using a custom header, it's recommended set the `headerMode` prop on the navigator to `screen` so that you don't have to implement animations.

https://reactnavigation.org/docs/en/stack-navigator.html#header

**Comment by blueprintChris** [comment]
I don't see how this is a solution. `float` allows us to keep the same header fixed in position and doesn't move as part of the following screens, but using float causes the header to flash/flicker when switching screens, How can we fix the header in place so it doesn't move as part of the screen and stop the flashing from happening?

**Comment by satya164** [comment]
@blueprintChris did you read the linked documentation?

**Comment by blueprintChris** [comment]
Yes, but I'm struggling to understand what it's trying to accomplish. I just want the header to stayed fixed while applying some simple styles to it.. Can you shed any further light on it?

**Comment by satya164** [comment]
> I just want the header to stayed fixed while applying some simple styles to it.. Can you shed any further light on it?

If you want some simple styles, then use the default header which already handles it. Otherwise if you want to use a completely custom header and want "float" then you need to implement the animations yourself.

**Comment by blueprintChris** [comment]
I am only using simple styles with the default header, but this is my problem - the header is still flashing.

**Comment by satya164** [comment]
@blueprintChris how is that related to this issue which is talking about custom headers? please open a different issue

**Comment by abelyeupear** [comment]
@satya164 It seems like `float` changed behavior from either v3/v4 to v5. `float` used to have a single header for all screens, now it has a header per screen **even if it looks like it stays in place.**

The reason people are seeing "flashing" (not only in this issue, but in several other issues that you have closed), is because headers are rendering on top of each other when you transition from one screen to another. There is a limit to how many headers are rendered though, and that is 3 headers. I'm not entirely sure, but I think the limit to the headers is due to this line: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/views/Header/HeaderContainer.tsx#L53

Was this change in behavior expected? I went through the upgrade guides and have read all the documentation, and this is the closest i've found to explain this behavior. From https://reactnavigation.org/docs/stack-navigator/#set-headermode-to-float-for-custom-header-animations:

> By default, there is one floating header which renders headers for multiple screens on iOS for non-modals. These headers include animations to smoothly switch to one another.

Here, it mentions that it "renders headers", but that is not how `float` used to behave.
