### ISSUE TITLE
lazyLoadDistance property not working

### ISSUE THREAD

**Issue by conleymon** [react-navigation/react-navigation#6873]
please refer to issue #6861 
try different values for lazyPreloadDistance and you will see that there is no value that will allow the loading of a single screen in isolation. 

Important because of 
case 1: What if I have a navigator with 25 screens, and the intermediate screens all make network calls
case 2: What if I have hidden intermediate screens that require parameters that are not known yet?

Unless I have misunderstood the function of lazyPreloadDistance, may I ask what it is intended to do? Does it only apply forward? If that is the case,, then it is not loading ALL the intermediate screens, as you will see in the snack.

**Comment by satya164** [comment]
> how many adjacent routes should be preloaded with this prop

It's for **preloading** screens in advance in addition to the screen that's being loaded by lazy.

> What if I have a navigator with 25 screens, and the intermediate screens all make network calls

Use [`useFocusEffect`](https://reactnavigation.org/docs/en/use-focus-effect.html) or [focus listener](https://reactnavigation.org/docs/en/function-after-focusing-screen.html#triggering-an-action-with-a-focus-event-listener) instead of `useEffect`/`componentDidMount`

> What if I have hidden intermediate screens that require parameters that are not known yet?

Pressing tabs will render those screens without params as well, so it's up-to you on how to handle that.
