### ISSUE TITLE
onStateChange is missing previous state

### ISSUE THREAD

**Issue by luisnaranjo733** [react-navigation/react-navigation#6911]
react-navigation@4 had a ```handleNavigationChange``` callback you could pass to the app container that had a nicer API than the equivalent ```onStateChange``` has in react-navigation@5.

The primary advantage of the former API is that it provided you the previous navigation state **and** the current navigation state AFTER a navigation state change. This comes in handy when you want to trigger side effects in response to navigation events.

Hypothetical scenario to illustrate the point
1) Have a RN app that uses react-navigation
2) You want to dispatch some kind of telemetry event in response to a navigation event. In the payload, you want to include which route you navigated from and which route you navigated to, along with the params.

With react-navigation@4, you could use ```handleNavigationChange``` to dispatch a redux action (say "NAVIGATON/CHANGED" for instance) that includes the previous and the current navigation state in the redux action. You could then use a side effect (sagas or epics for example) to emit telemetry events based on the navigation event that just took place.

Since react-navigation@5 removes this API from the internal navigation state, this gets harder to do. In order to achieve the same thing, now the app has to manage navigation state to "remember" what the previous navigation state was.

Could we consider bringing this previous navigation state back?

**Comment by geovannimp** [comment]
Also, I didn't find a way do get the action that changed the state. This was a parameter provided by this method in the react-navigation@4.

**Comment by satya164** [comment]
> In the payload, you want to include which route you navigated from and which route you navigated to, along with the params.
> Also, I didn't find a way do get the action that changed the state.

State can change due to a multitude of things. With dynamic config, route configuration change will change state. There's not always an action that changes state. Also similar state change an happen due to different types of actions.

Your side effects should rely on what changed (for example, did the focused route change), rather than which action changed it. Otherwise it makes your side effects coupled to the implementation details of components which dispatch actions. Changing `navigation.pop()` to `navigation.goBack()` shouldn't break your code which is doing side effects.

> this gets harder to do. In order to achieve the same thing, now the app has to manage navigation state to "remember" what the previous navigation state was.

You can store the previous state in a ref in only one place if you need it, it's not really adding much cost since it's a one time thing you can do. Always generating full state unnecessarily for people who don't even need it adds extra cost. You still have the flexibility to do it if you need it.
