### ISSUE TITLE
GestureHandler already initialized for root view

### ISSUE THREAD

**Issue by ethantran** [react-navigation/react-navigation#7148]
I will occasionally get this error, but I am not sure how to reproduce it. All I know is that it is related to the stack navigator and how it implements react native gesture handler. When I switch it to another navigator like bottom tab, it does not throw error. I can only prevent the error temporarily by closing the app and opening it back up.

Platform: Android
```
"react": "16.8.3",
"react-native": "0.59.5",
"react-native-gesture-handler": "^1.2.1",
"react-navigation": "3.9.1"
```

```
const MainNavigator = createBottomTabNavigator({
  Home: {
    screen: HomeScreen
  }
});
export const AppContainer = createAppContainer(MainNavigator);
```

**Comment by grantgeorge** [comment]
I'm getting this error in production builds so looking for a suggestion beyond "restart Metro Bundler"

**Comment by danmaas** [comment]
@grantgeorge I too have been fighting this in production. It's been affecting ~1% of sessions among my Android users on recent production builds.

I am not 100% sure, but my investigation so far points to a possible bad interaction between react-native-gesture-handler and the default behavior of the Android hardware back button in React Native (which destroys the app's MainActivity, while leaving much of the Java and JavaScript context intact, and results in a second instance of MainActivity spawning when the app is brought to the foreground again). I have noticed several bugs in various React Native libraries where the root cause lies in code that does not handle this scenario properly, and I suspect that might be the case here too.

I am currently testing this possible fix, which prevents the app's MainActivity from being destroyed and re-created as often: https://stackoverflow.com/a/60360452
(though I'm using `launchMode="singleTask"`, not `"singleTop"`)

Note, I am still on react-navigation 3.13, so I'm not 100% sure this applies to more recent versions.

**Comment by grantgeorge** [comment]
@danmaas thanks for sharing that. Glad I'm not alone!

If it's helpful, I've found that this crash and similarly related crashes to gesture handler and/or react-navigation occur after a user has downloaded a CodePush update and the sync at least started. That's about as far as I've gotten with this and I'm doing some more digging later.

From your example, my hypothesis is that users are downloading & syncing the CodePush update which shows a white screen and trying to exit that flow by clicking hardware back.

**Comment by danmaas** [comment]
Interesting, thanks for the info. I am also using CodePush, although only in "ON_NEXT_RESTART" install mode, so the bundle update doesn't happen during normal app usage.

I haven't seen any new crashes since deploying the MainActivity changes above, but it's a little too early to be sure.

**Comment by danmaas** [comment]
It's been a couple more days and I have not seen any more cases of this GestureHandler crash after making the changes to MainActivity as above.

**Comment by grantgeorge** [comment]
thanks @danmaas . Followed your suggestion and haven't seen the error since. Cheers!

**Comment by vthunetcompany** [comment]
Although folks above have been saying that restarting the Metro Bundler would fix itself, I had to take it further and rebuild Android/iOS apps with npx to actually see it being fixed

**Comment by faisalakram381** [comment]
> 

Just restart the Metro Bundler

**Comment by namchinn** [comment]
Exit from everything and restart all again. This fixed my error.

**Comment by NewCoder2023** [comment]
This fixed my error: **npm install --save react-native-gesture-handler**
