### ISSUE TITLE
Hide item from Tabbar

### ISSUE THREAD

**Issue by aleks63** [react-navigation/react-navigation#717]
How to hide an item from tabbar?

**Comment by ericvicenti** [comment]
We should add a `showTab` option to TabNavigator: https://reactnavigation.org/docs/navigators/tab

**Comment by ferrannp** [comment]
@aleks63 do you want to hide/show it dynamically? Because the problem with `static navigationOptions` is that once is set up, it cannot dynamically change so even if we add `showTab`, that value will be constant.

**Comment by satya164** [comment]
You can wrap the default tab bar inside another component and filter the routes from `navigation.state.routes`

**Comment by bmcmillan** [comment]
Like @satya164 said, to dynamically add options to my DrawerNavigator, I wrapped it in a component, and construct a new DrawerNavigator in the render() method, passing in routes as the first parameter from that component's state.

**Comment by bmcmillan** [comment]
I'm doing this with DrawerNavigator, which should be pretty much the same thing:

`
class MainNavigatorContainer extends Component {
    state: State = {
      Routes: {    
      }
    };

    componentWillMount() {
        User.getNavOptions().then((options) => {          
            this.setState({
               Routes: {
                 ... this.state.Routes, 
                 Home: { screen: Home }                 
               }
             });
            if (options.foo != undefined) {
              this.setState({
                Routes: { ... this.state.Routes, Foo: { screen: Foo }} 
              });              
            }
            if (options.bar != undefined) {
              this.setState({
                Routes: { ... this.state.Routes, Bar: { screen: Bar }}
              });
            }
            this.setState({
              OptionsLoaded: true,
              Routes: { ... this.state.Routes, SignOut: { screen: SignOut }}
            });
        }).catch((err) => {
            console.warn(err);
        })
    }

    render() {           
        if (this.state.Routes == undefined || this.state.Routes.Home == undefined) 
        {
           return (<View></View>)
        } 
        else 
        {
          var MainNavigator = DrawerNavigator(this.state.Routes, {
              contentComponent: Drawer,
              drawerWidth: 250,
              initialRouteName: 'Home'              
            });     
          return (          
              <MainNavigator screenProps={{ rootNavigation: this.props.navigation }} />
          )
        }
    }
}

const AppNavigator = StackNavigator({
  Login: { screen: Login },  
  HomeMain: { screen: ({ navigation }) => <MainNavigatorContainer navigation={navigation} /> } 
}, {
  headerMode: "none"
});
`

**Comment by joshualcoffee** [comment]
@satya164  Will that work correctly with redux?  What I noticed the state index will not match the order index.  I have not experimented with wrapping the tab navigator inside of a stack navigator to see if that helps.  Just looking over the source I dont see how that would help my case.  Here are my findings.

I think for this to work we would need to change `!!order.find((tabId: string, i: number) =>`  in  https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js#L132 to use `state.routes` instead.  That still woldn't work if you passed in the order param.  Im guessing that changing the order constant to a function that will accept the state instead may work.  Im not sure the side effects it could have though. 

Here is a scenario I have right now.  I have 2 tabs that are based on a users permissions that are fetched after a user logs in.  

For admins they see one tab and for non-admins they see another.   When I use the above solution you receive a message `cannot read property 'key' of undefined'.  This makes sense because the state.routes != the routes passed in the config.  So the index is wrong.  

I have toyed with creating a factory that will return the navigator but that could lead to a circular dependency since reduce relies on the navigator.  

Hopefully Im just have a stupid moment and have overthought this.

**Comment by bmcmillan** [comment]
@joshualcoffee Try my solution, since it's basically the same type of thing I'm doing (only loading certain Drawer nav tabs based on permissions). If you think of something better, I'd be curious to know how.

**Comment by joshualcoffee** [comment]
@bmcmillan You are correct this would work but goes down the same path as creating a factory.  Im kind of worried about side effects.  Also it feels like a work around more than built in functionality.  

If the supported method to show / hide tabs is to replace the nav state then the library needs to address this.  Right now the library seems to check the route config instead of the state.  

Looking at the tabrouter it looks like it would be better to check for a key rather than an index. Im not sure right now the amount of work this would take though to open a PR or not.  Also I'm not sure if this is the route that the react-navigation team wants to go.  

I will keep brainstorming to see if I can come up with something to submit in the next few days.

**Comment by bmcmillan** [comment]
@joshualcoffee Completely agree. Definitely a work-around. Consider this my +1 vote for native support. I may have time to do a PR, but not sure how soon.

**Comment by joshualcoffee** [comment]
Looking more in to this there doesn't seem to be a way to make this work if you are using redux.

Here are a few things I have tried today.  

- Create a factory that will render a new navigator
- Create 2 separate navigators with different route configs

The problem I see with these solutions is the redux store is coupled to the router.  So the navigator has to be initialized before the first screen loads if you use redux to be able to pass in the store.  So changing out the router / navigation after permissions have been fetched or even pushed is not an option.  You will get an error stating `There is no route defined for key`.  Again this makes sense because the state and the routes do not match up.   

There is the option to create a factory that would create the store + navigation but you would run in to a circular dependency.  

Im kind of at a stand still here. The only possible solution I can think of is to modify the tabrouter to check the state vs the route config.

**Comment by cooperka** [comment]
@joshualcoffee I'm running into the exact same issue right now trying to migrate from ex-navigation.  I'm trying to make the redux integration work with dynamic drawer and tab items.

Ex-navigation has a fairly [nice setup](https://github.com/expo/ex-navigation#integrate-with-your-existing-redux-store) where they expose their own `NavigationReducer` and redux `createStore` wrapper (called `createNavigationEnabledStore`) with no customization needed.

The only thing you need to do is define a static list of all possible routes and pass it in to a top-level component (simplified here for readability):

```jsx
<NavigationProvider context={{ allRoutes, store }}>
  <MyApp />
</NavigationProvider>
```

You don't need to decide which routes you actually want to render until runtime. Maybe we can take some learnings from that setup and try to apply it here.

I'm still trying to hack around it with react-navigation; I'll update here if I have any success.

**Comment by joshualcoffee** [comment]
Well I feel like and idiot.  I was too busy trying to solve this problem in the library when I needed to take a step back and solve it in my state.

So here is the solution I came up with.

In my `NavContainer` (attaches redux store to the tab navigator) I am filtering authenticate route like this: 
```javascript
const authRoutes = isLimited() ?
       navigationState.routes.filter(r => r.routeName !== 'contactsNav') :
       navigationState.routes.filter(r => r.routeName !== 'companyNav')
```

In my navigator Im passing the navigation prop with my dispatch and my filtered routes like so:
```javascript
<Navigator
          navigation={
            addNavigationHelpers({
              dispatch: dispatch,
              state: { ...navigationState, routes: authRoutes}
            })
          }
        />
```

Ok so we know where this get's us.  The state does not match up with the state that is in the TabNavigator.  So I set another constant as my active index that searching my authenticated routes to get the index instead of getting using the index from the state that is passed by react-navigation.  

Example: 

```javascript
const authRoutes = isLimited() ?
       navigationState.routes.filter(r => r.routeName !== 'contactsNav') :
       navigationState.routes.filter(r => r.routeName !== 'companyNav')
    let activeIndex
    authRoutes.find((r, i) => {
      if(r.routeName == navigationState.routes[navigationState.index].routeName){
        activeIndex = i
      }
    })
```

```javascript
<Navigator
          navigation={
            addNavigationHelpers({
              dispatch: dispatch,
              state: { ...navigationState, routes: authRoutes, index: activeIndex}
            })
          }
        />
```

This should not cause side effect and keeps our state intact without modifying the true navigation state.

**Comment by cooperka** [comment]
FWIW, I got it working without filtering (I can't seem to find any info about that in the docs). Here's the full diff showing how I integrated with redux while still using dynamic tab items.

I added a wrapper around my `Drawer` component called `RootNavigator`, so when I render a different `Drawer` component after its props change, the `RootNavigator` is still the same. That way I can use it to expose `getStateForAction` (in `navigation/reducers.js`).

It's possible this could be simplified even more, but I've banged my head against the wall too long to continue fiddling with it. This works for me:

```diff
diff --git a/my-app/src/components/Drawer/component.js b/my-app/src/components/Drawer/component.js
index c9425691..b858ccd1 100644
--- a/my-app/src/components/Drawer/component.js
+++ b/my-app/src/components/Drawer/component.js
@@ -333,4 +333,10 @@ class Drawer extends Component {
 
 }
 
-export default connect(Drawer.mapStateToProps, Drawer.mapDispatchToProps)(Drawer);
+const ConnectedDrawer = connect(Drawer.mapStateToProps, Drawer.mapDispatchToProps)(Drawer);
+
+// Also create a navigator with this drawer as the only component.
+// This is needed to create a consistent component to use for the redux reducer.
+export const RootNavigator = StackNavigator({ Root: { screen: ConnectedDrawer } }, { headerMode: 'none' });
+
+export default ConnectedDrawer;

diff --git a/my-app/src/components/SplashOrDrawer/SplashOrDrawer.js b/my-app/src/components/SplashOrDrawer/SplashOrDrawer.js
index 159f2a7f..b5f0920d 100644
--- a/my-app/src/components/SplashOrDrawer/SplashOrDrawer.js
+++ b/my-app/src/components/SplashOrDrawer/SplashOrDrawer.js
@@ -1,8 +1,9 @@
 import React, { Component, PropTypes } from 'react';
 import { connect } from 'react-redux';
 import SplashScreen from 'react-native-splash-screen';
+import { addNavigationHelpers } from 'react-navigation';
 
-import Drawer from '../Drawer';
+import { RootNavigator } from '../Drawer';
 import Splash from '../scenes/Splash';
 
 /**
@@ -27,9 +38,16 @@ class SplashOrDrawer extends Component {
   }
 
   render() {
-    const { isSplashLoading } = this.props;
-
-    return isSplashLoading ? <Splash /> : <Drawer />;
+    const { isSplashLoading, nav, dispatch } = this.props;
+
+    return isSplashLoading ? <Splash /> : (
+      <RootNavigator
+        navigation={addNavigationHelpers({
+          dispatch,
+          state: nav,
+        })}
+      />
+    );
   }
 
 }

diff --git a/my-app/src/components/navigation/reducers.js b/my-app/src/components/navigation/reducers.js
new file mode 100644
index 00000000..d975fff4
--- /dev/null
+++ b/my-app/src/components/navigation/reducers.js
@@ -0,0 +1,8 @@
+import { RootNavigator } from '../Drawer';
+
+const navReducer = (state, action) => {
+  const newState = RootNavigator.router.getStateForAction(action, state);
+  return newState || state;
+};
+
+export { navReducer };

diff --git a/my-app/src/reducers.index.js b/my-app/src/reducers.index.js
index fa36de30..0300244e 100644
--- a/my-app/src/reducers.index.js
+++ b/my-app/src/reducers.index.js
@@ -2,6 +2,7 @@ import { combineReducers } from 'redux';
 
 import appActionTypes from './components/App/actions';
 
+import { navReducer } from './components/navigation/reducers';
 import { SyncStatusReducer } from './components/SyncStatus/reducers';
 import { ConnectionStatusReducer } from './components/ConnectionStatus/reducers';
@@ -28,6 +29,7 @@ import { TicketsReducer } from './components/scenes/Tickets/reducers';
 // new-imports-here
 
 export const reducersMap = {
+  nav: navReducer,
   syncStatus: SyncStatusReducer.reduce,
   connectionStatus: ConnectionStatusReducer.reduce,
```

Note that it currently doesn't seem possible to **listen** for redux events, but at least now I can dispatch them using my regular `dispatch` object (through `redux-saga` in my case).

**Comment by manjeets12** [comment]
I was trying the same yesterday, but it was looking too complex to me and then I came across [react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view) and it seems it is pretty easy to do such complex thing with that library, I may be missing out on something for not using Tabs from react-navigation, but that library seems pretty fine to me performance wise too

**Comment by aleks63** [comment]
Whatsup? :) I'm waiting yet

**Comment by cooperka** [comment]
@aleks63 I think four people have already given you their methods of successfully doing this -- anything in particular you're still looking for?

**Comment by SamMatthewsIsACommonName** [comment]
@bmcmillan thanks a lot your idea gave me a great guide. I ended up using a selector / redux to basically add the routes as props (maybe that breaks the 'serialisable' rule haha). Declaring the router in the render method as you are, do you not run into problems with the whole thing resetting every time the props of your parent component change? Or does it not have props above it?

**Comment by santiagopoli** [comment]
@SamMatthewsIsACommonName I'm having the same issue as you, as described in https://github.com/react-community/react-navigation/issues/1126

Basically, I have a 'TabBar' component which receives its tabs as props, but every time the props change, the whole TabNavigator is resetted.

`javascript
const getTabFor = (listItems) => () => <View><FlatList items={listItems} .../>...</View>

const FavoritesView = ({ movies, tvShows }) =>
  <View style={{ flex:1 }}>
       <FavoritesTabBar moviesTab={getTabFor(movies)} tvShowsTab={getTabFor(tvShows)} />
  </View>
`

And the code in FavoritesTabBar is something like this:

`javascript
const tab = (tabContent, iconName) => ({
    screen: tabContent,
    navigationOptions: {
        tabBarIcon: ({ tintColor }) => <Icon name={iconName} size={24} color={tintColor} />
    }
});

const tabs = (moviesTab, tvShowsTab) => ({
    Movies: { ...tab(moviesTab, MOVIES_ICON) },
    Shows: { ...tab(tvShowsTab, TVSHOWS_ICON) }
})

const tabProperties = {
    animationEnabled: true,
    tabBarOptions: {
        activeTintColor:  platformSpecific({ ios: '#0d9958', android: 'white' }),
        labelStyle: { fontWeight: platformSpecific({ ios: '400', android: 'bold' }) },
        style: { backgroundColor: platformSpecific({ ios: '#ecf0f1', android: '#0dbb58' }) },
        indicatorStyle: { backgroundColor: '#0d9958', height: 3.5 }
    }
}

export default ({ moviesTab, tvShowsTab }) => {
    let Component = TabNavigator(tabs(moviesTab, tvShowsTab), tabProperties);
    return <Component/>
}
`

A demonstration of the problem:

![bug](https://cloud.githubusercontent.com/assets/759695/25210249/7db8a52a-2555-11e7-9438-22ff9f750892.gif)
![bugandroid](https://cloud.githubusercontent.com/assets/759695/25210250/7dd29f98-2555-11e7-8acd-421f49a9b379.gif)

(As you see, every time the props changes, the TabBar goes back to the first tab)

The issue may have to do with the fact I'm creating a new navigator on every render, but I don't know how to solve that.

**Comment by SamMatthewsIsACommonName** [comment]
@santiagopoli I got over this by creting it in componentWillMount, because in my case the props that determine which items are available won't change while the related component is open. So maybe if you can isolate a parent component in such a way where the route determining props won't change during it's lifecycle

**Comment by santiagopoli** [comment]
@SamMatthewsIsACommonName Yeah, but in my case the items can change while the component is open. I've solved it by letting the screens receive no params at all be connected with the redux store instead, but I don't like that approach. I think it should be possible to change the content of the navigator without recreating it.

If you think about it from a clean code-separation of concerns- perspective, it seems that the NAVIGATOR should only be concerned about HOW to navigate screens, not WHAT is navigating, so I think this feature is much needed. 

Apart from that, this is one of the best navigation libraries out there.

Thanks though :)

**Comment by acomito** [comment]
I need something like this too. I want to only show a tab if a person has a certain role, so I need to be able to do this somewhere I have access to the relevant props holding my user data.

It would be nice to maybe do this at a top level:

const NAVIGATOR_OPTIONS = { };

const ADMIN_ROUTES = {
  home: { screen: HomeNavigator },
  listings: { screen: ListingsNavigator }, // admin only screen/tab
  account: { screen: AccountNavigator }
};

const REGULAR_ROUTES = {
  home: { screen: HomeNavigator },
  account: { screen: AccountNavigator }
};

const AppNavigator =  isAdmin() 
? TabNavigator( ADMIN_ROUTES, NAVIGATOR_OPTIONS)
: TabNavigator( REGULAR_ROUTES, NAVIGATOR_OPTIONS)

**Comment by joshualcoffee** [comment]
That's basically the same thing I had to do.  You can check out https://github.com/react-community/react-navigation/issues/717#issuecomment-290823960 to see how I was able to achieve that.

I switched over to another tab navigator as this one is still maturing for the time being.  So things could have changed since that comment.

**Comment by acomito** [comment]
Thanks @joshualcoffee for taking a minute to point me in the right direction. I'll check it out.

**Comment by augustoabreu** [comment]
@joshualcoffee i'm trying to implement your solution but it isn't working. I have a TabNavigator inside a StackNavigator and it seems that `navigationState.routes` doesn't exist. Have you tried something like this scenario?

**Comment by MrHubble** [comment]
@augustoabreu Did you figure out how to access `.routes`? with a TabNavigator inside a StackNavigator?

**Comment by denizaydemir** [comment]
I know It's not the best way but a **static** solution to this issue is to put a route name checker in the TabBar.js component of `yourproject\node_modules\react-navigation\node_modules\react-native-tab-view\src`. 
Modification of render will be inside `map` function,
`{routes.map((route, i) => {
	if(route.key === 'Screen1'){			
		return null;
	}
   . . .
}`

**Comment by joshualcoffee** [comment]
Routes are just stored in the app's redux store.  So you should be able to access your routes anywhere in the app. When you are using a top level nav and sub navs inside of those you should be passing down your state in to the sub navs.  So you should have access to the routes.

**Comment by koenpunt** [comment]
@denizaydemir no need to modify the library, see @satya164's comment: https://github.com/react-community/react-navigation/issues/717#issuecomment-287392565

**Comment by koenpunt** [comment]
@satya164 any idea how I can make your suggestion (https://github.com/react-community/react-navigation/issues/717#issuecomment-287392565) work for a `TabNavigator` with `swipeEnabled: true`? Because by only removing the tab it's still possible to swipe to the view.

**Comment by denizaydemir** [comment]
@koenpunt I saw @satya164's comment. However, I couldn't make it work. Can you a provide an example wrapped up navigator?

**Comment by Tom29** [comment]
@satya164 it's incorrect syntax

**Comment by kelset** [comment]
Pinging OP @aleks63 since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by aleks63** [comment]
Did u add showTab option?

**Comment by kelset** [comment]
Not as an option, but [this solution](https://github.com/react-community/react-navigation/issues/1872#issuecomment-309014735) is the way to do it without a dedicated option; which at the moment I think it wouldn't even work, since the tabs are handled via `react-native-tab-view`.
I also know for a fact that @satya164 is working on a new version.

**Comment by tibbus** [comment]
I have tried @satya164 solution and it kinda works but now you need to import TabBarBottom directly without TabView. ....

And it kinda works as it hides the specified TAB, but for example if you have routes 1,2,3,4 and you hide the route 3, when you click on route 4 it will navigate to route 3, so the TAB is hidden but the navigation logic is broken.
Also there probably will be issues when swipe is enabled.

**Comment by nikasvan** [comment]
Any Progress with this? This is very useful feature request

**Comment by ajhenri** [comment]
> I have tried @satya164 solution and it kinda works but now you need to import TabBarBottom directly without TabView. .... 
And it kinda works as it hides the specified TAB, but for example if you have routes 1,2,3,4 and you hide the route 3, when you click on route 4 it will navigate to route 3, so the TAB is hidden but the navigation logic is broken.

I can volunteer a solution to that issue. It will keep the navigation logic intact, however it is not an elegant solution.

Say we have two types of users: MEMBER and CONTRIBUTOR. You have a tab that should be hidden from view for CONTRIBUTOR users. You used @satya164's solution to hide this tab, and it is successfully hidden. However, Tab 4 is somehow navigating to that hidden tab, and Tab 5 is navigating to Tab 4.

The solution is to do the following:
1) pass `screenProps` (https://reactnavigation.org/docs/navigators/stack#Navigator-Props). 
2) use `tabBarOnPress` to control the tab press behavior for the messed up tab items (Tab 4 and 5), based on the `screenProps` you set in 1 (https://reactnavigation.org/docs/navigators/tab#tabBarOnPress).

If you are using Redux, you can do something like:

App.js
```javascript
    getUserType(){ 
        return store.getState().user.type; 
    }

    render() {
        return (
            <Provider store={store}>
                <AppStackNavigator screenProps={ { getUserType: this.getUserType } }/>
            </Provider>
        );
    }
```

and **in each file** of the messed navigation screens (e.g ... Tab 4, Tab 5):


```javascript
class Tab4Screen extends React.Component {
    static navigationOptions = ({navigation, screenProps}) => {
        return {
            tabBarOnPress: ({ previousScene, scene, jumpToIndex }) => {
                const userType = screenProps.getUserType();
                if(userType == 'CONTRIBUTOR'){
                    jumpToIndex(4); //corrected index, original index + # of hidden tabs before it
                } else {
                    jumpToIndex(scene.index);
                }
            }
        };
    }
}
```

It may not be an optimal solution but it worked for me.

**Comment by nikasvan** [comment]
Found this solution which is was very helpful [.](https://github.com/react-navigation/react-navigation/pull/2909) But unfortunately pull request was closed. You can edit TabBarBottom.js(TabbarTop.js) and the add the `hideIndex : [ index of the tab you would like to hide ],` inside TabBarOptions. I know it's a dirty solution but hey, what has been a clean solution so far :)

**Comment by kevinPMK** [comment]
@ajhenri 

This solution appears to work for the most part on paper, but the tintColor misbehaves because the index is still funky. I also tried to use @joshualcoffee's solution but I'm working with a Tab Navigator nested inside of a Stack Navigator, where the permissions aren't actually defined until after the first navigation is bypassed, aka:

(Login Screen) StackNavigator
     (AppIndex) Tab Navigator w/ Filtered Tabs

Is there a way to maintain the integrity of the default index while using @satya164's solution with redux and a nested tabbed navigation? I'm struggling to connect the dots.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by drash-course** [comment]
[Here](https://react-navigation.canny.io/feature-requests/p/hiding-tab-from-the-tabbar) is a feature request on canary for this issue. Vote if you like it.

A working fork is also proposed, feel free to give feedback!

**Comment by alenia** [comment]
@kevinPMK I got @joshualcoffee's solution to work in a Tab Navigator in a Stack Navigator like this:

```
const tabScreens = {
  Home: { screen: Home },
  Conditional: { screen: Conditional, featureName: 'flagName' },
}

const Navigator = TabNavigator(tabScreens)

class FilteredNavigator extends Component {
  render() {
    const { navigation, features } = this.props
    const navState = navigation.state
    const filteredRoutes = navState.routes.filter((r) => {
      const featureName = tabScreens[r.routeName].featureName
      return !featureName || features[featureName]
    })
    const activeIndex = filteredRoutes.findIndex((r, i) => (
      r.routeName === navState.routes[navState.index].routeName
    ))

    return (
      <Navigator
        navigation={{
          ...navigation,
          state: {
            ...navigation.state,
            routes: filteredRoutes,
            index: activeIndex,
          },
        }}
      />
    )
  }
}

FilteredNavigator.router = Navigator.router

const mapStateToProps = (state) => ({
  features: getFeatures(state)
})

export default connect(mapStateToProps)(FilteredNavigator)
```

**Comment by kevinmercier** [comment]
@alenia That appears fairly straight forward, thanks! 

I just have one issue. How would you structure the filter if "tabScreens" was nested in a stack navigator (in my case, Login || tabScreens)?

**Comment by alenia** [comment]
@kevinmercier the example I used is just what the nested tab navigator looks like. In our app it's nested in one or two stack navigators, don't recall which

**Comment by kevinmercier** [comment]
@alenia Awesome!

That is exactly what I needed. I appreciate the help!

**Comment by gingerbeardstudios** [comment]
Is there anything supported by `react-navigation` yet because this is entirely confusing. I have to do all of this nesting already to get the library to work for my app and now this is another layer of complexity when really it should be trivial to have some type of prop to pass to a tab that determines its visibility.

We shouldn't need weird work arounds to hide/show a tab. I have a TabNavigator embedded in a stack navigator and I need to only show an "Admin" tab for admin users. What do I need to do to get a solution for my scenario? 

    const SignedIn = StackNavigator({
        MainTabNavigator: { screen: MainTabNavigator },
        ModalAddResident: { screen: AddResidentStack }
    }, {
        headerMode: 'none',
    })
    
    const MainTabNavigator = TabNavigator({
        Default: {
            screen: DefaultStack,
            navigationOptions: {
                title: 'Search'
            }
        },
        AddResident: {
            screen: AddResidentStack,
            navigationOptions: {
                title: 'Add Resident'
            }
        },
        Admin: {
            screen: AdminStack,
            navigationOptions: {
                title: 'Admin'
            }
        }
    }, {
        tabBarPosition: 'bottom',
        tabBarComponent: ({jumpToIndex, ...props, navigation}) => (
            <TabBarBottom
                {...props}
                jumpToIndex={index => {
                    if (index === 1) {
                        navigation.navigate('ModalAddResident')
                    }
                    else {
                        jumpToIndex(index)
                    }
                }}
            />
        )
    });

**Comment by koenpunt** [comment]
Hiding the tab can be done like @satya164 says in [his comment](https://github.com/react-navigation/react-navigation/issues/717#issuecomment-287392565). But using that method requires you to disable swiping between the tab screens, because only the tab is hidden, not the screen, and thus would mean that you still can swipe to the screen, even when the tab isn't visible.

I don't know what the conditions of an admin are, but I can imagine that using a different instance of the `TabNavigator` for admins might work more reliable, but this means you have to recreate the structure when the admin state changes.

**Comment by gingerbeardstudios** [comment]
@koenpunt You know, I didn't even consider creating a different instance for admins. I think that would be ideal. I have code in my app.js that checks whether the user is logged in and then renders the appropriate navigation component. I could just do it there. Thanks for the suggestion!

**Comment by giacomocerquone** [comment]
Sorry to interrupt but this is just madness... it should be trivial in such a big library to do a thing like this.

Again, sorry if I sound like an heretic, but to me it seems that all these problems are due to some bad decision took at the foundation of react-navigation, like for example the impossibilty to define dynamically a navigator. Before the switchnavigator (that I have still to implement) I had to hack on things like this to make my nested navigators work, also the impossibility of adding dynamic components/icons to the header (the only way is actually binding it to the redux store directly, but this sounds like an hack too)
Does someone feel like me about all this? Am I wrong?

**Comment by brentvatne** [comment]
hi @giacomocerquone - feel free to upvote on https://react-navigation.canny.io/feature-requests and we will get to this when we have time. if that doesn't work for you, you can submit a RFC at https://github.com/react-navigation/rfcs and/or open a PR to resolve your issue. this is not a priority for the maintainers at the moment so you may want to use a different library if it is a key use case for you.
