### ISSUE TITLE
replace queryString with urlsearchparams?

### ISSUE THREAD

**Issue by jimmywarting** [react-navigation/react-navigation#7632]
make it less dependent on node stuff and use the urlsearchparams instead <sup>[[1](https://github.com/cross-js/cross-js#dont-use-nodes-url-or-querystring)]</sup>

**Comment by KuSh** [comment]
Could that be revised now that URLSearchParams is available in RN [since v0.81](https://github.com/facebook/react-native/commit/9b1a8ffac4368b9304939359917c7cfd0a9501bf), the oldest RN version with [active support](https://reactnative.dev/docs/releases) ?
It's also available in node, since v10, and bun and deno since v1. So SSR should be covered too.

See [mdn browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#browser_compatibility)
