### ISSUE TITLE
Write docs for the Web

### ISSUE THREAD

**Issue by brunolemos** [react-navigation/react-navigation#782]
Give [web](https://reactnavigation.org/docs/guides/web) more ❤️ 

[![image](https://cloud.githubusercontent.com/assets/619186/24217364/5c41fb0a-0f1e-11e7-8870-0947cedf2643.png)](https://reactnavigation.org/docs/guides/web)

[![image](https://cloud.githubusercontent.com/assets/619186/24217545/f7e63e68-0f1e-11e7-9f8c-346efb5866d0.png)](https://github.com/react-community/react-navigation/commits/ede9dc766c33203bb20972a704f3865e51995488/docs/guides/Web-Integration.md)

**Comment by joncursi** [comment]
Really looking forward to the release of more documentation around this. The ecosystem of libraries that are focused on bringing react-native's APIs to web applications is getting really strong.

**Comment by brunolemos** [comment]
I'm not sure anymore of this is just about documentation and what pieces of implementation (if any) are missing

**Comment by MovingGifts** [comment]
@joncursi @brunolemos hey guys, I noticed you on react-native-web as well as here. I am wondering if you can share if you were able to get react-navigation working with react-native-web and if so how?

**Comment by joncursi** [comment]
I did get it to work. I didn't write anything unique, I just copy/pasted code that runs reactnavigation.org. Check out [BrowserAppContainer](https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js)

**Comment by MovingGifts** [comment]
Yup, I saw that file but I don't really understand it much, and the docs are almost non existent (the thorough walk through mentioned in the docs never happened...).

So I'll try to break it down to steps, so others can use it as well:
1. Copy [BrowserAppContainer](https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js)
_Any other reproducible steps to add below?_
2. (Use same router file as your RN project, or create X file)?
3. (Navigate this way for web vs native)?

I will edit the above if you can provide any additional steps to get it to work 👍

**Comment by kelset** [comment]
Hey guys quick update - since the new roadmap for v1.0 is already quite "loaded" the support for web will transition to "being experimental", meaning that it will be properly integrated & maintained after v1.

That said, feel free to add as much documentation / examples as possibile via PRs, we will want people to be able to at least get an idea on how to try it out :)

**Comment by remon-georgy** [comment]
I realise you guys are doing some ticket cleanup, now that 1.0 out of the door. However, I think everyone here could appreciate a statement about the future of react navigation on web.

Is web support on the roadmap? Is react navigation even intended to run on web any time in the future? A clear statement will help us all make an educated decision while picking a navigation solution for mild/long-term projects.

Thanks

**Comment by brentvatne** [comment]
hi @remon-georgy,

we are not actively working on it, but it should be supported. if someone would like to join the project as a collaborator who is the owner of web integration, that would be great. at the moment we are more focused on ios and android.

hope that helps!

**Comment by jacquesdev** [comment]
@brentvatne - is there any chance you can create a couple of issues with regards to documentation of the web that could perhaps be done as part of hacktoberfest? My team is about to start spending some time on contributing to open source, and since we actually use it for, it will give us a great opportunity to improve things for all web users.

Any pointers/guidance from your side as to generally what is available would be very useful to get us started.
