### ISSUE TITLE
headerTitle not scaling properly

### ISSUE THREAD

**Issue by Bohmaster** [react-navigation/react-navigation#7846]
**Current Behavior**

In react navigation v4 I used this code and worked just fine. It did adjust my logo image (300x80) to fit perfectly and scale into my 80px header.

Now after migrating to v5 it no longer scale. It's just like the 'resizeMode' stopped working.

`const navigationOptions = {
    headerTitle: <Image style={{height: 45}} resizeMode="contain" source={require('../assets/images/encabezado-1.png')}/>,
    headerStyle: {
        backgroundColor: 'white',
        shadowColor: 'none',
    },
    headerTitleAlign: 'center',
    headerTitleStyle: {
        fontWeight: 'normal',
        fontFamily: 'Montserrat-SemiBold',
    },
}
`

[Actual behavior v5 image](https://i.stack.imgur.com/KFDO3.jpg)

**Expected Behavior**

I expect my image to be contained and scaled properly.

[Proper behavior v4 image](https://i.stack.imgur.com/zhEaJ.jpg)

**How to reproduce**

Add an image to headerTitle and try resizeMode.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 9
| @react-navigation/native       | 5.2.2
| @react-navigation/stack        | 5.2.3
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.5
| node                           | 12.6.1
| yarn                    | 1.21.1

**Comment by WoLewicki** [comment]
You can try to change it to `headerTitle: props => <Image ... />` and see if it aligns correctly.

**Comment by whiteHatCip** [comment]
The same is happening to me in my own app. On iOS the headerTitle shows perfectly, whereas on Android the app logo that is to be shown as headerTitle appears as if cut in the middle. trying to change resizeMode or height did nothing to solve the problem.

**Comment by WoLewicki** [comment]
@whiteHatCip can you provide a snack that shows the issue?

**Comment by whiteHatCip** [comment]
> @whiteHatCip can you provide a snack that shows the issue?

Here is the code for the creation of the stackNavigator that has the issue.
```
const Main = createStackNavigator();
function MainStack() {
  return (
    <Main.Navigator
      initialRouteName="Home"
      screenOptions={{
        gestureEnabled: true,
        headerStyle: {
           borderBottomWidth: 0,
           backgroundColor: Colors.primary,
           height: (isIOS ? 80 : 60) + statusBarHeight() + (isIOS ? -10 : 0),
           elevation: 0,
        },
        headerTitleAlign: 'center',
      }}>
      <Main.Screen
        name="Home"
        component={Home}
        options={{
          headerTitle: <HeaderLogo />,
          headerLeft: () => (
            <SideMenuButton drawerPosition="left" btnImage={MenuBtn} />
          ),
          headerRight: () => (
            <SideMenuButton drawerPosition="right" btnImage={rightMenuBtn} />
          ),
        }}
      />
    </Main.Navigator>
  );
}

```
HeaderLogo is actually just a functional component that contains an Image:
```
import {LogoTestoYellow} from '../../../assets/images';
const HeaderLogo = () => (
  <Image source={LogoTestoYellow} resizeMode="contain" />
);
```

Just to clarify, I also tried to use directly the Image component, instead of HeaderLogo and tried to  specify the image size in both image style and image props, but id did nothing.
I also tried to pass headerlogo component to the `title` screenOption instead of `headerTitle`, but of course it didn't work.
With react navigation 4 the logo was appearing fine on both Android and iOS.
don't know if this may be useful, but the stack navigation MainStack is put inside a right-positioned DrawerNavigator, which is inside another left-positioned DrawerNavigator (I need to show drawers on both sides of the screen at the same time).

my current dependencies related to this issue are:
```
"@react-navigation/drawer": "^5.4.1",
"@react-navigation/native": "^5.1.5",
"@react-navigation/stack": "^5.2.10",
"react": "16.13.1",
"react-native": "0.62.2",
```

If you need anything else to help us,  please, let me know. Thanks a lot.

**Comment by whiteHatCip** [comment]
> @whiteHatCip can you provide a snack that shows the issue?

Just checking in...Are there any updates about this issue? is this being investigated at least?
thanks

**Comment by Bohmaster** [comment]
I fixed it using this new library for scaling images:

https://github.com/vivaxy/react-native-auto-height-image#readme

It works like a charm.

**Comment by whiteHatCip** [comment]
> I fixed it using this new library for scaling images:
> 
> https://github.com/vivaxy/react-native-auto-height-image#readme
> 
> It works like a charm.

just tried to use the library you suggested but it didn't have any effect...any advice on how you used it, to fix the issue? thanks

**Comment by whiteHatCip** [comment]
I just fixed my issue in another way:
As a summary, my issue was that only on Android, the app logo I am using as headerTItle in the Stack navigator appeared cut along the middle height line.
To fix the issue I had to set the height in the headerTitleStyle to a value which is the double of the original logo height. Since this issue was occurring only on Android, I had to set this style value only on Android, to avoid having the opposite issue on iOS, with the logo image taking up too much space.
I guess that this means the issue is closed because of this workaround, even though, the need to set the titleStyle to avoid an image cut in half I guess is not the desired default behavior.

**Comment by Bohmaster** [comment]
> > I fixed it using this new library for scaling images:
> > https://github.com/vivaxy/react-native-auto-height-image#readme
> > It works like a charm.
> 
> just tried to use the library you suggested but it didn't have any effect...any advice on how you used it, to fix the issue? thanks

It just worked the first time I used it. Can you show an example of your implementation?

I notice that you fixed it using the double height. You could try again using my solution but I think is important that this bug gets fixed by the manteiners.

**Comment by whiteHatCip** [comment]
I have to say that reporting my implementation of react-native-auto-height-image is really basic since I just imported the package in my file, and simply passed the image as a prop to the component, together with the desired width of the image. But the result was the same as the one using the Image component. Using the headerTitleStyle to set the height to the double image height value solved the problem. I am sure that this clarifies to the maintainers where the problem is. thanks for your support @Bohmaster

**Comment by JulianKingman** [comment]
I noticed that compared to <v4, v5 doesn't have a default width for the header title container, so you could try adding something like this:
```javascript
headerTitleContainerStyle: {
  width: '75%',
},
```
75% leaves some space for buttons on either side, and then I can apply percent styles to the image like so:
```javascript
<Image
  source={images.logoHorizontal}
  style={{
    height: '60%',
    width: '100%',
  }}
  resizeMode="contain"
/>
```

**Comment by whiteHatCip** [comment]
> Hey! Thanks for opening the issue. Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible. The easiest way to provide a repro is on [snack.expo.io](https://snack.expo.io). If it's not possible to repro it on [snack.expo.io](https://snack.expo.io), then you can also provide the repro in a GitHub repository.

here is the minimal repro for my issue:

https://snack.expo.io/@fabiocip89/react-navigation-stack-header-cut-android

**Comment by satya164** [comment]
@whiteHatCip this works for me on both iOS and Android:
```js
headerTitle: () => <Image source={require('./assets/snack-icon.png')} style={{resizeMode: 'contain', height:56}} />
```
