### ISSUE TITLE
The transition preset ModalPresentationIOS showing a gap at the top for the second layer of a stack navigation

### ISSUE THREAD

**Issue by igibliss00** [react-navigation/react-navigation#7877]
I'm using React Navigation 5x's ModalPresentationIOS preset.  All my other screens are working fine, but on this one particular screen, I'm seeing a black gap at the top as shown below.  This is two layers into the stack. I've tried it on a real device as well as the simulator and I'm seeing the same error in both cases:

![Simulator Screen Shot - iPhone 8 - 2020-03-26 at 13 16 10](https://user-images.githubusercontent.com/38163337/77682477-64b62b00-6f6d-11ea-8087-dd1a461415b1.png)

```js
const AdminStack = () => {
    return (
        <AdminStack.Navigator
            initialRouteName="First"
            screenOptions={{
                headerShown: false,
                swipeEnabled: true,
                gestureEnabled: true,
                gestureResponseDistance: {
                    horizontal: width,
                    vertical: height,
                },
                cardOverlayEnabled: true,
                ...TransitionPresets.ModalPresentationIOS,
            }}
            mode="modal"
            headerMode="none"
        >
            <AdminStack.Screen name="First" component={FirstScreen} />
            <AdminStack.Screen name="Second" component={SecondScreen} />
            <AdminStack.Screen name="RedScreen" component={RedScreen} />
        </AdminStack.Navigator>
    )
}
```
  [1]: https://i.stack.imgur.com/vEow8.png

software | version
-- | --
iOS or Android | iOS
    "@react-native-community/viewpager": "2.0.2",
    "@react-navigation/material-top-tabs": "^5.0.1",
    "@react-navigation/native": "^5.0.1",
    "@react-navigation/native-stack": "^5.0.1",
    "@react-navigation/stack": "^5.0.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",

**Comment by amirmcs** [comment]
I am seeing the same thing. I happens when you are calling modal from within a details screen in the stack. It works fine from the first screen on the stack.

1) This is from the first sceen on the stack (works fine):

<img width="456" alt="Screen Shot 2020-03-28 at 12 37 31 AM" src="https://user-images.githubusercontent.com/49243041/77814969-688c9f00-708c-11ea-97f5-59b8285dbf49.png">

2) This is from the 2nd screen on the stack. See the gap and cut of 2/3 of the way.

<img width="446" alt="Screen Shot 2020-03-28 at 12 35 46 AM" src="https://user-images.githubusercontent.com/49243041/77814954-4561ef80-708c-11ea-9496-0a01a6607307.png">


 "@react-navigation/native": "^5.0.9",
  "@react-navigation/stack": "^5.1.1",

**Comment by satya164** [comment]
Closing since you didn't provide a repro.
