### ISSUE TITLE
Resetting Stack when switching stack for  auth flow 

### ISSUE THREAD

**Issue by neemssoni** [react-navigation/react-navigation#7986]
**Current Behavior**
In my App.js I am switching between one stack and one drawer navigator(drawer navigator is on top of stack navigator). When I come from Any notifications, the first screen goes to stack on the top, and when I log out and login back it goes to the same screen  instead of going to Home Screen. 

my App.js : ( ignore the variables )

`export default App = props => {
  return (
    <Provider store={store}>
      <AppContext.Provider value={{appContext, updateAppContext}}>
        <NavigationContainer>
          <StatusBar barStyle="default" />
          {!isFirstRun ? (
            <OnboardStackNavigator />
          ) : !isUserLoggedIn || isUserLoggedIn === 'false' ? (
            <LoginStackNavigator />
          ) : (
            <DrawerNavigator />
          )}
        </NavigationContainer>
      </AppContext.Provider>
    </Provider>
  );
};`

My Drawer Navigator : 
`export const DrawerNavigator = props => {
  return (
    <Drawer.Navigator
      drawerContent={props => <DrawerScreen {...props} />}
      initialRouteName={'HomeScreen'}
      drawerPosition={'right'}
      drawerStyle={{width: '100%', backgroundColor: 'transparent'}}
      screenOption={{backBehavior: 'order'}}>
      <Drawer.Screen
        name="App"
        component={AppStackNavigator}
        options={{gestureEnabled: false}}
      />
    </Drawer.Navigator>
  );
};`

My AppStackNaviator: 
`export default function AppStackNavigator() {
  return (
    <AppStack.Navigator initialRouteName={'HomeScreen'}>
      <AppStack.Screen
        name="HomeScreen"
        component={HomeScreen}
        options={{
          title: 'Sales View',
          ...headerStyles,
        }}
      />
      <AppStack.Screen
        name="ContactUsHome"
        component={contactUsHomeScreen}
        options={{
          title: 'Contact Us',
          gestureEnabled: false,
          ...headerStyles,
        }}
      />
.
.
)}
    `
**Expected Behavior**
After Login, user should always go to Home Screen

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 13.x |
| Android         | 10 |
| @react-navigation/native       | latest |
| @react-navigation/stack        | latest |
| react-native-gesture-handler   | latest |
| react-native-safe-area-context | latest |
| react-native-screens           | latest | 
| react-native                   | 0.61.2 |

What I have already tried : 

1. My Logout button is on Drawer component, where I tried StackActions.reset to Home Screen and then log out, that didn't work, as it is drawer, and I tried push and pop and replace also,, those did not work.

**Comment by nicewahson** [comment]
Any solution here?

**Comment by JoniVR** [comment]
Is there any way we could either open this back up or point me towards a solution? I've been searching tirelessly but can't find a solution (v5/v6).

Basically same issue: 
When the user's auth token expires, the user gets booted back to the Login screen through the Auth Flows method in the docs. 

When the user then logs in again, they are taken back to their last active screen. This is all fine, but there's no back button anymore (I assume due to the switch action resetting state?), so the user is stuck. 

I'd like to know if it's possible to either:
* Reset the stack state when switching screens inside the navigator when the condition changes, so that when the user logs in they are taken back to the `initialRoute`.
* Have the same behaviour as we currently have but with a back button.

Any help/info/pointers would be greatly appreciated.

**Comment by pablof300** [comment]
I have the same question. Resetting the state seems to be an option, but is there a better way?
