### ISSUE TITLE
Action.Type missing in React Navigation 5

### ISSUE THREAD

**Issue by SamKissee** [react-navigation/react-navigation#8009]
**Current Behavior**

- NavigationContainers function onStateChange now only has a state param

**Expected Behavior**

- Previously in React Navigation 4 the NavigationContainers onNavStateChange had 3 params: prevState, currentState, action. This was changed in React Navigation 5 to only have 1 parameter. 
- I am able to reproduce the prevState and currentState functionality using the useRef hook. I am unable to find any documentation on where the action parameter went or how to reproduce similar functionality in React Nav 5
- I am currently converting our large application to use the new React Nav 5 and we do tracking and ad related actions based of the action param that used to be available. 

**Example** 
`if (
 currentScreen === 'ArticleLandingPage' &&
      action.type !== 'Navigation/BACK'
  ) {
     const actionParams = this.getCurrentActionParams(action)
     if (actionParams && !actionParams.notification) {
    stores.fbAd.showInterstitial()
    }
 }`

Any input on where I need to look in the documentation for React Navigation 5 or suggestions on how to get access to the actions that are being performed would be awesome!

**Comment by satya164** [comment]
It's not exposed. You shouldn't be relying on checking on which action triggered the change.
- Various things can change navigation state, e.g. list of screens changing in a navigator.
- Whether something dispatches `POP`, `GO_BACK` or `RESET` is an implementation detail and can change, as long as the final result is the same, the type of action shouldn't matter.
- React could batch updates, this means multiple actions could cause a single state update, in this case it's not reliable to check for action type.

What you should do is check what changed in the state by comparing previous state and new state. It's a bit more work, but it's always reliable and will continue to work regardless of changes in the action dispatched by your/React Navigation's components.

Also, the kind of logic you wrote above looks like something that should probably be in the `ArticleLandingPage` instead of at the root.
