### ISSUE TITLE
web: linkBuilder does not work for nested routes

### ISSUE THREAD

**Issue by RWOverdijk** [react-navigation/react-navigation#8178]
**Current Behavior**

```
const buildLink = useLinkBuilder();

buildLink('Home', { screen: 'ProfileStack', params: { screen: 'Faq' } })
```

Does not create the correct url because it's not in a "state" format. 

Output:

https://localhost:19006/en/Root/Home/ProfileStack/Home?params=%5Bobject%20Object%5D&screen=ProfileStack

Expected output: 

https://localhost:19006/en/faq

I don't know where react-navigation makes the path when I actually `navigation.navigate()` to it, because that does work properly. It's only the generated link that doesn't work (and I use for my anchor tags on web).

**Expected Behavior**

The path to be correct.

**How to reproduce**

See "Current Behaviour"

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Web

    "@react-navigation/bottom-tabs": "^5.3.3",
    "@react-navigation/native": "^5.2.3",
    "@react-navigation/stack": "^5.2.18",
    "react-native": "~0.61.4",
    "expo": "^37.0.0",

**Misc**

I've found two additional issues I'd like to group here:

1. I can't pass in my linkingConfig, meaning I'd have to use the linking prop on the NavigationContainer.
2. Building links from anywhere is difficult right now because of the context it expects. It'd be nice to have a way to define the root for the link (for example with a footer component that is used on multiple screens. The links won't work on all screens because of the context).

**Comment by satya164** [comment]
It's intended to be used in navigators to provide links for the screens it has based on your linking config. It's not a general purpose utility to build links out of navigate actions.

> This hook is intended to be used in navigators to show links to various pages in it
> The screen to navigate to must be present in the navigator it's used in

You should use `Link` or `useLinkProp` and pass the path you want instead of rebuilding the path.

> I can't pass in my linkingConfig, meaning I'd have to use the linking prop on the NavigationContainer

Use `getPathFromState`

> for example with a footer component that is used on multiple screens. The links won't work on all screens because of the context

It's not intended to be used like that. Don't use it if you aren't building a custom navigator or custom tab bar/drawer.

**Comment by RWOverdijk** [comment]
@satya164 So how should people create a link then? Write them by hand and not use the linking config?

**Comment by RWOverdijk** [comment]
@satya164 Very unsatisfying answers to be honest 😅

> It's intended to be used in navigators to provide links for the screens it has based on your linking config. It's not a general purpose utility to build links out of navigate actions.

Yes, and that's exactly what I want to do. Screens are allowed to have links to nested navigators and I'm trying to create a link to one so I can show it on the page and it's **not working**.

> You should use Link or useLinkProp and pass the path you want instead of rebuilding the path.

Right but then how do I make the path. Link wants a path. I need a way to make the path. Am I supposed to write the path myself instead of using a perfectly good linking config? Whic his exactly what useLinkBuilder says it does?

If so, that's pretty silly.

> Use getPathFromState

Alright, but then how do I get the state to make the path with? Is there a makeStateFromIntendedNavAction function, too?

> It's not intended to be used like that. Don't use it if you aren't building a custom navigator or custom tab bar/drawer.

What's the alternative? How can I create those links then?

**Comment by satya164** [comment]
> Yes, and that's exactly what I want to do. Screens are allowed to have links to nested navigators and I'm trying to create a link to one so I can show it on the page and it's not working.

You are displaying a footer in your app, which you'll be reusing in multiple places. It's a different use case. It's *for navigators to link to the screens in them* not for *screens to have links to nested navigators*.

It's needed for navigators because they don't know about your app code. React Navigation's tab navigator doesn't know what links you have in your app to be able to display them. The hook is for those cases.

> Right but then how do I make the path. Link wants a path. I need a way to make the path.

You already know the paths in your apps, you have to use them instead of rebuilding the path from state. If you're building a web app, your code needs to work with URLs directly like you would do with React Router or plain web apps. You have to think URL first instead of in terms of navigation actions.

> Am I supposed to write the path myself instead of using a perfectly good linking config?

The config is needed for both parsing the path and serializing navigation state to a path. You're still using that config no matter which one you write, path or action. It's a different approach.

> Which is exactly what useLinkBuilder says it does?

The docs needs to be more clear about when not to use this hook, right now it also says "This hook is intended to be used in navigators to show links to various pages in it", by which I also mean don't use it in your screens and use it only if you're not building/customizing a navigator.

> Very unsatisfying answers to be honest

Look, I'm trying to help you by answering your issues on holidays and weekends. When you say things like "I think you think I'm lying", "Very unsatisfying answer", it doesn't make me feel very motivated to answer you.

**Comment by RWOverdijk** [comment]
Hmm... I'll use paths for now. But I do think there might be an easier way to facilitate this. It can't be expected that users make their query strings, paths etc by hand and maintain their sanity 😄.

Maybe a nice config would help here. Something that can be used more widely (for paths, linking, routing). Manually writing urls is something I haven't done in a long time.

> Look, I'm trying to help you by answering your issues on holidays and weekends. When you say things like "I think you think I'm lying", "Very unsatisfying answer", it doesn't make me feel very motivated to answer you.

I apologise for being rude. I appreciate you taking time out of your spare time to answer me. You're everywhere, working on everything at the same time and it's awesome to see. I have nothing but respect for you and did not intend to be rude.

Now... From my end I'm trying to help and get some insight so I can contribute and it feels like the project is locked. Like I have to just wait for people to fix things instead of trying to do it myself. So getting a reply that doesn't really answer my question in a way that I can actually do something to help make things better is frustrating for me as well. I'm a dev, same as you. Let me help 😄

**Comment by satya164** [comment]
If you have ideas on how to make the config for linking nicer, we have a place for discussions regarding new APIs - https://github.com/react-navigation/rfcs

Regarding paths, that's the primary way how we're going forward with web support. It's not really possible to have some way to convert navigate actions to paths in the same way `navigate` will work because of the bubbling that React Navigation does, so it's not something we're planning to support.

If you want customize how paths are built, `useLinkBuilder`'s implementation is pretty simple, which you could fork and modify to suit your use cases https://github.com/react-navigation/react-navigation/blob/master/packages/native/src/useLinkBuilder.tsx

**Comment by RWOverdijk** [comment]
Thanks. I'll give it a go!

I'll try to set something up locally and see if that works. If it does I'll write something up for rfcs.
