### ISSUE TITLE
Material Top Tab Navigator: Should be 2 different height remains constant at the highest 

### ISSUE THREAD

**Issue by mkalayci35** [react-navigation/react-navigation#8218]
Working with 2 different takes the highest height and extends the other screen. 
The homepage needs to be lower in height. But according to the height on the settings screen, it extends its place. 
<img width="260" alt="Screen Shot 2020-05-08 at 22 34 19" src="https://user-images.githubusercontent.com/38668796/81442341-0f7c5480-917c-11ea-9daa-2169cefc8d90.png">
<img width="260" alt="Screen Shot 2020-05-08 at 22 34 31" src="https://user-images.githubusercontent.com/38668796/81442351-16a36280-917c-11ea-9c39-4ba5a26fc39f.png">

**Comment by leonamjlpaula** [comment]
I'm facing this situation. I need screens to adjust TabView height dinamically but parents gets the highest screen fixed to all screens. I'm using this navigator inside a scrollview.

**Comment by satya164** [comment]
this is expected behaviour. tab view isn't supposed to dynamically resize to content.

**Comment by PatrissolJuns** [comment]
I'm facing the same issue too

**Comment by yfunk** [comment]
Did anybody find a way to achieve this behavior?

**Comment by jamesshaw49** [comment]
@satya164 thank you for creating this library, it has been very useful for our project and many others I am sure. 

I have seen this question asked countless times across many tickets and while it is not the expected behaviour, many people would expect this behaviour, so it would be greatly appreciated by all who implement the library if you could provide an example of how to best implement functionality to adapt the height.

**Comment by mtahir08** [comment]
any update

**Comment by bryanltobing** [comment]
is there any update on this? we are struggling with this issue as well

**Comment by sagarj-iprogrammer** [comment]
required minHeight for conetent
