### ISSUE TITLE
console.warn() should be used instead of console.error() for warnings

### ISSUE THREAD

**Issue by nferrara100** [react-navigation/react-navigation#8251]
`console.error()` is currently called whenever react-navigation wants to warn the developer about something. This is problematic because it prevents developers from hiding warnings with React Native's `YellowBox` component.

All such messages currently say:

> This is a development-only **warning** and won't be shown in production.

 As a warning it should be classified as such.

In some cases the warnings are quite important and should be addressed immediately. However, in some circumstances the urgency of addressing them is debatable. While some spectacular developers address all warnings in their projects immediately, many of us do not have the time to do so.

Should the community be amenable to this proposal I would be happy to open a pull request.

**Comment by satya164** [comment]
I don't think unhandled actions are something you should ignore. If you're navigating to a screen which doesn't exist/dispatching a navigation action which doesn't get applied, it's an error and affects the functionality of your app.

It's a development only warning because we want to avoid crashing your app in production, not because it's not an important error. It's not a deprecation warning that you can temporarily ignore. You should absolutely fix such issues.
