### ISSUE TITLE
Stack header back icon is not visible

### ISSUE THREAD

**Issue by LoganWlv** [react-navigation/react-navigation#8609]
**Current Behavior**

I am running a Stack example  from the documentation :  [here](https://snack.expo.io/?platform=android&name=createStackNavigator%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fbottom-tabs%40%5E5.7.0%2C%40react-navigation%2Fdrawer%40%5E5.8.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.13%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.13%2C%40react-navigation%2Fnative%40%5E5.7.0%2C%40react-navigation%2Fstack%40%5E5.7.0%2Creact-native-paper%40%5E3.10.1%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E3.0.2%2Creact-native-screens%40%5E2.9.0%2Creact-native-tab-view%40%5E2.14.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fsimple-stack.js)

When I navigate to the stack, the header "back arrow" icon is invisible, but it exists. Bellow a screenshoot when I touch it

![109694622_572296333453331_2440486867997689296_n](https://user-images.githubusercontent.com/22358070/87872563-faad1000-c9b9-11ea-84eb-31d8e0f59cb2.jpg)

**Expected Behavior**

Seeing the "back arrow icon" 

**How to reproduce**

Here a minimal [repo to reproduce the bug](https://github.com/LoganWlv/react-navigation-expo-yarn-workspace-bug)
Run "yarn install" in the root folder then "expo start" in ` ./packages/react-native-expo-app/`

I am using a monorepo configuration to share code between React and React Native, with yarn workspaces.
Without the monorepo configuration it works perfectly ! I did compared both node_modules/ packages, for the monorepo and config and the one without it, versions for @react-navigation/* are the same.

It is probably a dependency issue but I have no idea where could it come from

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
|  Android                 |  9
| @react-navigation/native       | 5.6.1
| @react-navigation/stack        | 5.6.2
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 3.0.7
| react-native-screens           | 2.9.0
| react-native                   | https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
| expo                           | 38.0.8
| node                           | 12.16.2
| npm or yarn                    | 1.22.4

**Comment by LoganWlv** [comment]
Same issue with the latest versions

**Comment by satya164** [comment]
https://github.com/facebook/metro/issues/290

**Comment by Dharmi201** [comment]
Facing the same issue. I even tried resolving "AssetsSourceResolver.js" using patch-package as issued in this https://github.com/facebook/react-native/commit/7deeec73966d84140492c2a767819977318c4d2d but in vain.
### Environment:

| Library | Version |
| --- | --- |
| react-native | 0.61.4 |
| @react-navigation/stack | 5.2.16 |
| @react-navigation/native | 5.2.1 |
| @react-navigation/stack | 5.2.16 |
| react-native-safe-area-context | 0.7.3 |
| react-native-reanimated | 1.8.0 |
| @react-native-community/masked-view | 0.1.10 |
| react-native-screens | 2.7.0 |

This behaviour started happening recently only in IOS. On Android the back icon (default for stacks) is visible as expected. [A minimalistic repo](https://github.com/Dharmi201/BackIconNavIssue).

##Update:
Tried upgrading the react-navigation/native to 5.7.6. and react-navigation/stack to 5.9.3 along with the patch but still issue persists.

I am thinking this could be because of IOS14 but not sure. 
Anyway I can solve this without upgrading react-native version as the app is in production?

@satya164  Let me know if you need help with any other information.
Thanking you in advance!

**Comment by iquabius** [comment]
Setting up `server.enhanceMiddleware` in Metro configuration solved this issue for me. The function implementation can [be found here](https://github.com/expo/expo/issues/7545#issuecomment-712737616). For React Navigation only the second half of the function is necessary.

**Comment by Dharmi201** [comment]
Upgrading to react-native 0.63.3 solved the issue. Thanks though 🙏

**Comment by TristanSkoda** [comment]
Not for me

**Comment by JennaFi** [comment]
same here, iOS.

**Comment by phatmann** [comment]
Still an issue.

**Comment by corybcromer** [comment]
Check the order of your screens in your `<Stack.Navigator>`. 

```
    <AuthContext.Provider value={authContext}>
            <NavigationContainer theme={Theme}>
                <Stack.Navigator>
                    {state.userToken == null ? (
                        <>
                            <Stack.Screen name="SecondScreen"
                                component={SecondScreen}
                            />
                            <Stack.Screen name="FirstScreen"
                                component={FirstScreen}
                            />
                </>
                </Stack.Navigator>
            </NavigationContainer>
        </AuthContext.Provider>
```

So in the above example, if I tried to navigate from the `FirstScreen` to the `SecondScreen` a back button would not appear in the navigation header. If you switch the order, and then navigate, the back button appears.
