### ISSUE TITLE
React navigation v5 not scrolling in web

### ISSUE THREAD

**Issue by ksairi** [react-navigation/react-navigation#8631]
**Current Behavior**

- Screen is not scrollable in web platform

**Expected Behavior**

- Be able to scroll in web platform

**How to reproduce**

Go to [expo snack](https://snack.expo.io/@ksairi/nav5) and see how the screen is scrollable in ios and android but not in web

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| web                 |
| @react-navigation/native       |5.7.1
| react-native                   | 0.62
| expo                           |38
| node                           |12
| yarn                    |1.22

**Comment by SleeplessByte** [comment]
This is because your `ScrollView` has unlimited height. `react-native-web` + the default expo `index.html` makes it possible to scroll on the web _without_ a scrollview. That is the correct behaviour. This is **not** a bug in `@react-navigation`.

In order to make this work with react-native, you'll need to limit the `Scrollview` height (for example to the window height). You can also change the `index.html` to make this behaviour default.

**Comment by ksairi** [comment]
@SleeplessByte awesome. It worked, thanks so much!
Now I have the problem that measured height is actually the wrapper without scrolling and not the whole Scrollview so if I want to color the background it only does it to the first bit. You can check the [snack](https://snack.expo.io/@ksairi/nav5) as I added a way to get the height in a proper way but it still doesn't work. (this is only in web, the rest works fine even giving it a height value)

**Comment by SleeplessByte** [comment]
The `ScrollView` now is _too high_ because you're using the "window height" instead of "window height - appbar". If you're going this route, I recommend taking into account elements outside of  the scrollview. However, the _easier_ solution is to use a "100%", and add `max-height: 100vh` to your `index.html`.

----

```diff
- <RootWrapper style={{ padding: 0,backgroundColor: 'green', height }}>
+ <RootWrapper style={{ padding: 0,backgroundColor: 'green' }}>
```

The `RootWrapper` is _inside_ the scrollview, so it should have the height of the _content_, not the scroller. 

----

Instead of using `onContentSizeChange`, use a window listener:

```typescript
const [height, setHeight] = useState(Dimensions.get('window').height)

useEffect(() => {
  const updateHeight = ({ window }) => setHeight(window.height)
  Dimensions.addEventListener('change', updateHeight)
  return () => {
    Dimensions.removeEventListener('change', updateHeight)
  }
}, [])
```

**Comment by ksairi** [comment]
@SleeplessByte thanks again for your reply man! Actually I used the `useDimensions` hook as the listener wasn't triggering!

**Comment by SleeplessByte** [comment]
If you update your snack I can look at it again.

**Comment by ksairi** [comment]
> If you update your snack I can look at it again.

sorry! done!

**Comment by SleeplessByte** [comment]
https://snack.expo.io/@derk-jan/nav5

The height needs to be set on the `ScrollView` _style_, not the `content`. You want to limit the "frame", not the content inside the frame.

This should work on all platforms, but you need to change - 64 according to the height of the navigationbar.

**Comment by ksairi** [comment]
> https://snack.expo.io/@derk-jan/nav5
> 
> The height needs to be set on the `ScrollView` _style_, not the `content`. You want to limit the "frame", not the content inside the frame.
> 
> This should work on all platforms, but you need to change - 64 according to the height of the navigationbar.

awesome bro @SleeplessByte thanks so much for your help!

**Comment by ksairi** [comment]
@SleeplessByte me again sorry!
if you have the time, enter here https://testapp.galagym.com/
Steps:

Click in `Explorar`
credentials:
DNI: 32552566
password: Ksairi11
and go to `Reserva tus Clases` --> swipe all questions to no and click `Firmar` and you will see the list that is bigger than the window(hopefully if you don't have a big big monitor :) ) and you can't scroll. It was working before with your solution.
Is anything you can spot from the web source code? I will appreciate!
cheers!
