### ISSUE TITLE
App crashes with linking

### ISSUE THREAD

**Issue by heroic** [react-navigation/react-navigation#8753]
**Current Behavior**

The app crashes with error "Looks like you have configured linking in multiple places." This error happens at random.

**Expected Behavior**

The app should work normally. 
![crash](https://user-images.githubusercontent.com/523335/90801226-8b567300-e30d-11ea-8b5e-5293b6e11e67.jpeg)

**How to reproduce**

I haven't found a way to make the bug reproduce.

The app is currently using this code:

```
const getActiveRouteName = (
  state: NavigationState,
): {name: any; params: any} => {
  const route = state.routes[state.index];

  if (route.state) {
    // Dive into nested navigators
    return {
      name: getActiveRouteName(route.state),
      params: route.params,
    };
  }

  return {
    name: route.name,
    params: route.params,
  };
};

const linking = {
  prefixes: [
    'https://www.prefix.co',
    'https://prefix.co',
    'http://www.prefix.co',
    'http://prefix.co',
    'prefix://',
  ],
  config: {
    screens: {
      Video: {
        initialRouteName: 'Feed',
        screens: {
          Video: {
            path: 'post/:video',
            parse: {
              video: (video: string) => ({id: parseInt(video)}),
            },
          },
        },
      },
      Profile: {
        initialRouteName: 'Feed',
        screens: {
          Profile: {
            path: 'user/:id',
          },
        },
      },
      Home: '*',
    },
  },
};

export default function AppProvider() {
  const routeNameRef = useRef<string | undefined>();
  const navigationRef = useRef(null as NavigationContainerRef | null);

  useEffect(() => {
    const navigationState = navigationRef.current?.getRootState();

    if (navigationState) {
      routeNameRef.current = getActiveRouteName(navigationState).name;
    }
  }, []);

  return (
    <NavigationContainer
      linking={linking}
      ref={navigationRef}
      onStateChange={(navigationState: NavigationState | undefined) => {
        const previousRouteName = routeNameRef.current;
        if (navigationState) {
          const {name, params} = getActiveRouteName(navigationState);
          const id = params?.id || params?.parent_id || params?.video?.id;
          if (previousRouteName !== name) {
            amplitude.logEvent('Screen Open', {
              name,
              id,
            });
            amplitude.logEvent('Screen Close', {
              name: previousRouteName,
              id,
            });
          }
          routeNameRef.current = name;
        }
      }}>
      <ContextProvider>
        <App />
      </ContextProvider>
    </NavigationContainer>
  );
}
```

This component is included from /index.js

```
AppRegistry.registerComponent(appName, () => App);
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |      9
| @react-navigation/native       |     5.7.3
| react-native                   |     0.63.2
| expo                           |
| node                           |       12.18.2
| npm or yarn                    |        yarn - 1.22.4

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.

**Comment by sjungwirth** [comment]
I've been battling this same error for a few months in my project, the problem I have is that the assumption here that linking should only be used in one place is very restrictive. The project I work in has multiple react-native modules (`AppRegistry.registerComponent`) and also have legacy native code that does some navigation between different RN modules. Now if I wanted to use path/url style navigation in multiple modules, I cannot due to this error, but also the legacy native integrations are glitchy, and RN doesn't always seem to get cleaned up properly when it should. I realize this has nothing to do with the library here and if it could be fixed that might fix one of my issues, but from the perspective of having a very complex app with multiple RN modules and wanting to do url style navigation in multiple places, this check that linking is only used in one place seems very restrictive. In the end I have had to give up on using the linking config for now because even when I only have it in a single module, I still have my glitchy native implementation that is triggering this and it causes an app crash - I can't even catch the error with an Error boundary.

**Comment by jayshah123** [comment]
Even with all three conditions met:
1. only using linking prop.
2. Not using useLinking 
3. singleTask already present
Not sure why the error occurs or the restriction exists.

**Comment by satya164** [comment]
> Even with all three conditions met

If you can repro this issue with all the conditions met, then open an issue with a repro.

**Comment by jayshah123** [comment]
We checked our sentry logs and last log is the one by : https://github.com/facebook/react-native/blob/eeb36f470929c2fdd8e1ed69898a5ba9144b8715/Libraries/ReactNative/AppRegistry.js#L182
I think the spurious relaunching of app was not due to any application specific use.

**Comment by annie-elequin** [comment]
I might be crazy, but I'm suspicious that the cause is here... 
https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useLinking.native.tsx#L51

This is the file where my error comes from. 

I'm ONLY using the `linking` prop, not using useLinking anywhere in my project. 

If I'm looking at this useEffect correctly, enabled should start off being `true` because of the default prop on line 18. 

Since this is the case, and isUsingLinking starts `false` because of line 13, it should go to the else statement, which I confirmed mine does. 

The problem is that there's no dependency array on this useEffect! So it runs on _every re-render_. I put a console log in this useEffect and confirmed that it gets run twice and THEN my error shows up, because the useEffect sets isUsingLinking to the value of enabled, and then compares them the next time it's run. 

I'm not sure if this is a bug in react-navigation, or if perhaps it's a misuse of the linking prop itself (making the linking prop changes, which makes the useEffect be called again when it shouldn't be?)

**Comment by heroic** [comment]
Shouldn't the dep array be `[]`?

**Comment by satya164** [comment]
@annie-elequin do you have a repo where this happens so I can debug it?

>. because the useEffect sets isUsingLinking to the value of enabled, and then compares them the next time it's run

It also sets `isUsingLinking` to `false` in the returned cleanup function which should run and set it to `false` before the `useEffect` gets called again.

**Comment by heroic** [comment]
@satya164 I don't have a debug app, but it's happening quite often on our app, and if you want I can give you access to the crash logs and to out codebase if it helps you in any way

**Comment by annie-elequin** [comment]
> @annie-elequin do you have a repo where this happens so I can debug it?
> 
> > . because the useEffect sets isUsingLinking to the value of enabled, and then compares them the next time it's run
> 
> It also sets `isUsingLinking` to `false` in the returned cleanup function which should run and set it to `false` before the `useEffect` gets called again.

The cleanup function won't get run unless the component useLinking is used in gets unmounted, which we aren't sure happens. 

I'm going to try putting in the `[]` dep array like @heroic mentioned because I think that could be a possible solution, though I'm not sure how that affects other places useLinking is used. 

I unfortunately don't have a repo available because this is in my code at work, so it's private. I can potentially make a minimal example of what we're doing if the problem persists.

**Comment by annie-elequin** [comment]
So putting in that dep array... I haven't seen the error anymore. 

Still not guaranteed it's fixed, because the error was sporadic at times, but so far so good.

**Comment by heroic** [comment]
So a quick check reveals `[]` won't make a difference. What seems to be happening is that somehow 2 copies of the app are being launched and since `isUsingLinking` is not namespaced the error occurs. Might be caused due to react-native-firebase which could be triggering another copy of react when a notification is being received in the background.

**Comment by annie-elequin** [comment]
so, in our case, we found out it was because our native apps handle deep linking in the native code (we only have RN as a view in our native apps) 

so we enabled the linking config ONLY on web which is where we were using it, and the error is now gone!

**Comment by jayshah123** [comment]
> @annie-elequin do you have a repo where this happens so I can debug it?
> 
> > . because the useEffect sets isUsingLinking to the value of enabled, and then compares them the next time it's run
> 
> It also sets `isUsingLinking` to `false` in the returned cleanup function which should run and set it to `false` before the `useEffect` gets called again.

@satya164 for some reason react native app root render gets called (essentially app re-running from scratch, probably reactrootview reset?): 
https://github.com/facebook/react-native/blob/eeb36f470929c2fdd8e1ed69898a5ba9144b8715/Libraries/ReactNative/AppRegistry.js#L182
Would you or the react team know why this would happen?

**Comment by afonsopbarros** [comment]
I’m having similar experience, just using the linking config, the 3 conditions from the error are met. But crashlytics logs show this error a lot, no repro found

**Comment by Rehubbard** [comment]
I'm seeing crashes with this issue on Android.  I'm just using the linking prop, no useLinking or anything. I can't reproduce it on my own at the moment, but it seems like a legit issue.

**Comment by Gerlison** [comment]
I'm having exactly the same problem. The 3 conditions to work are met, the bugsnag throws the error several times and I cannot reproduce it. Fortunately, this has only occurred for some users in my base, but I fear it grows up in scale.

**Comment by sjungwirth** [comment]
I think this is definitely bad behavior by react-navigation, it should not be throwing an error here, at best log a warning or throw in react-native DEV mode but there are use cases where I might want to use url style navigation in multiple places in my app. I think the idea that the linking config can ONLY be used for deep linking and therefore should only have one instance ever is wrong.

**Comment by heroic** [comment]
@satya164 I added some debugging breadcrumbs(Via Bugsnag) and I see the issue happening because the app went from `onResume` to `onCreate` and there doesn't seem to be an `onStop` which would indicate, that 2 instances of `App` are getting mounted resulting in the issue.

<img width="553" alt="Screenshot 2021-06-15 at 11 34 55 AM" src="https://user-images.githubusercontent.com/523335/122001294-bbf02780-cdcd-11eb-90ae-3210eafb3f89.png">

Not sure how to fix this issue, and if it's a react navigation issue or react native issue. Your thoughts?

**Comment by jayshah123** [comment]
@satya164 Worth a revisit?

**Comment by SmilinAtYa** [comment]
I am experiencing the same issue. All 3 conditions are met but the error randomly appears. Any updates on how to fix? At least for me it seems to be Android specific.

**Comment by gabrielbezerra81** [comment]
Still having this issue in latest react-navigation

**Comment by sunny1105** [comment]
I am also experiencing the same issue with all 3 conditions met. I was able to reproduce the issue. This is happening when you have these conditions met:

-  multiple prefixes with one being custom and other being universal
- open app with a custom prefix link then open app with the universal link

with the above two conditions met, it's crashing for me every time.

**Comment by ryanlntn** [comment]
I'm seeing this issue when opening a second window in a multi window iPad app. Is there a workaround for this use case?

**Comment by thisisadarshjaiswal** [comment]
Were you guys able to solve this?
