### ISSUE TITLE
React Navigation with MobX

### ISSUE THREAD

**Issue by chongchungyin** [react-navigation/react-navigation#8882]
Hi guys,

I am using MobX for my React Native project. I noticed that if i have multiple screens in one stack, if those screens are **observing** same **observable**, it will cause all the screens rerender even if screens are in backstack. Is there anyway we can stop screen observing changes?

**Comment by rolivegab** [comment]
Hi!
I believe this is the expected behavior.
All screens in stack are still rendered in background, even if its not showing at screen.
I believe you can set prop `unmountOnBlur` on your router, so it will be unmounted if its on backstack.
a little example:

![image](https://user-images.githubusercontent.com/7359906/94372506-9a7ecc80-00d4-11eb-880d-4f1ce5c732b1.png)

**Comment by chongchungyin** [comment]
@rolivegab thanks for that. However i don't think `unmountOnBlur` is not available for stack navigation (May be it's true for drawer or bottombar?).
