### ISSUE TITLE
react-navigation/native@5.8.4 requires a different react version from react-native@0.63.3

### ISSUE THREAD

**Issue by Cully-Curwen** [react-navigation/react-navigation#9021]
```bash
$ npm ls react
<Project>
├─┬ @react-navigation/bottom-tabs@5.10.4
│ └── react@16.13.1 deduped
├─┬ @react-navigation/drawer@5.10.4
│ └── react@16.13.1 deduped
├─┬ @react-navigation/native@5.8.4
│ ├─┬ @react-navigation/core@5.13.4
│ │ ├── react@17.0.1
│ │ └─┬ use-subscription@1.5.0
│ │   └── react@17.0.1 deduped
│ └── react@16.13.1 deduped
├─┬ @react-navigation/stack@5.12.1
│ └── react@16.13.1 deduped
├─┬ react-native@0.63.3
│ └── react@16.13.1 deduped
└── react@16.13.1
```

This is causing below error when using hooks

``` bash
[Tue Nov 03 2020 11:53:33.736]  ERROR    Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

This error is located at:
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at Routes.tsx:15)
    in Unknown (at Providers.tsx:13)
    in Unknown (at Providers.tsx:12)
    in _default (at Providers.tsx:11)
    in Unknown (at Providers.tsx:10)
    in Providers (at App.tsx:17)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Tue Nov 03 2020 11:53:33.743]  LOG      [Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.]
```

**Comment by satya164** [comment]
It doesn't require different versions. Looks like npm isn't handling peer deps correctly. I suggest you to switch to `yarn` v1.

**Comment by Cully-Curwen** [comment]
how is "switch to yarn" a solution to this problem

**Comment by 3xpedia** [comment]
Hello, "switch to yarn" is not a solution. I tried and the problem is not there.

Here is the problem : 
@react-navigation/native depends on @react-navigation/core. And since 5.13.0 @react-navigation/core depends on use-subscription@^1.15.0. use-subscriptions has a peer-dependency on react@^17.0.0. There is the problem.

The temporary solution I used is forcing the versions by doing so : 
package.json
```
"dependencies": {
    "@react-navigation/core": "5.12.5",
    "@react-navigation/native": "5.7.6",
    "use-subscription": "1.4.1",
  }
```

I enforced using use-subscription @1.4.1 (last version having a peer-dependency on react@^16.13.1)
I downgraded @react-navigation/core to the latest version working with use-subscription@1.4.1
I downgraded @react-navigation/native to the latest version working with @react-navigation/core@5.12.5

Not that I did not use the " ^ " to ensure the version are the one I want.

I hope it could help :)

**Comment by satya164** [comment]
> Hello, "switch to yarn" is not a solution

NPM changed theier behaviour in latest major which automatically installs peer dependencies, and the algorithm breaks a lot of existing packages. As you might have guessed, `use-subscription` does not really require react 17, it works fine with older React versions. But it's peer dep entry is incorrect: https://github.com/facebook/react/pull/20062

This behaviour from NPM is pretty new and will keep breaking many packages. It changes the meaning behind peer dependencies, they were supposed to be installed only once, not multiple times for nested deps. Many packages in React Native community use peer dependencies to ensure only one instance of a specific package is installed and this change breaks that assumption, so it's likely that you'd encounter more of this issue with latest NPM>

Switching to Yarn may not be long term solution, it's easier to switch to Yarn rather than dealing with such breakages until the ecosystem stabilizes. We can and probably will downgrade `use-subscription` here, but it becomes pretty hard to upgrade any package in future due to such a breaking change.
