### ISSUE TITLE
Why wont the height field accept anything other than '8%' ?

### ISSUE THREAD

**Issue by chai86** [react-navigation/react-navigation#9068]
@satya164 @WoLewicki Why can't i use: `global.App_BottomTabBarHeight `below to set the height. where` global.App_BottomTabBarHeight = '8%'`

  ```
  //Tabs across the bottom of the screen
    const MainScreenTabNavigator = createBottomTabNavigator(
      {
        HomeStack,
        
        OtherStack,
    
      },
      {
    
        tabBarOptions: {
    
          activeTintColor: 'orange',
          inactiveTintColor: 'black', //white 
          style: {
            backgroundColor: '#ff8278',
            height: global.App_BottomTabBarHeight   // DOESN'T WORK but manually typing  '8%' or 0.08 does
          },
          indicatorStyle: {
            backgroundColor: 'black'
          },
          showLabel: false
        },
        
      }
      
    );

```
The height wont set with the variable `global.App_BottomTabBarHeight = '8%'`. 

I've also tried doing this:
 `height: Dimensions.get('window').height * global.App_BottomTabBarHeight`, where `global.App_BottomTabBarHeight = 0.08`, but still nothing

If i manually type `height: '8%'` it works fine.

**Comment by chai86** [comment]
@react-navigation/native version: 5.8.9

**Comment by satya164** [comment]
Please don't open multiple issues and tag maintainers. I'm already subscribed to issues in the repo, I don't need additional notifications for every issue.

React Navigation doesn't care if you pass your height through a variable or by typing the literal, and it also cannot detect or react to it. It's just JavaScript. So either your value is not being passed or something else is broken in your build.

I'm closing the issue since I believe this isn't a bug in React Navigation and you haven't provided a repro or followed the issue template.
