### ISSUE TITLE
Linking for stack to call 'push' action instead 'navigate'

### ISSUE THREAD

**Issue by KestasVenslauskas** [react-navigation/react-navigation#9090]
**Current Behavior**
- Opening deep link for the same screen several times keeps only 1 screen with latest linking props.

**Expected Behavior**
- Option to configure linking to option new screen on top (for example opening different articles for news app).

**Your Environment**
 ```
   "react-native": "0.63.3",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
```

**Comment by jparksecurity** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.8.9`, latest: `5.8.10`)
> * `@react-navigation/stack` (found: `5.12.6`, latest: `5.12.8`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes!

+1 for this issue

**Comment by 2xSamurai** [comment]
+1 I am also facing the same issue. There should be an option to push if we are on the same screen.

**Comment by satya164** [comment]
With [this commit](https://github.com/react-navigation/react-navigation/commit/b19f76bfffe623759e67d925bfd067c753a453bf), you can return an ID for a screen to open a new screen instead of reusing previous one when using navigate, which should address your use case.

**Comment by brianreavis** [comment]
@satya164 Thanks! Though I don't believe that improvement quite addresses the desired behavior here.

Example: You're at Profile A, browse to a bunch of new screens and then click a link to go to Profile A. 

Should it pop all the history to go back to Profile A (navigate), or add an additional one to the stack (push)? I feel the latter is standard behavior.

**Comment by 2xSamurai** [comment]
I think what @brianreavis says is correct.

I am facing this issue mainly while deep linking. 

Say you are currently on screen A.
You get a push notification with a payload to navigate to the same screen A but with different params. You do `Linking.openURL('Screen A with different param')`

In this scenario, I think it would be optimal to do a push to go to screen A. So that the user can return to the old screen.

Right now it just stays on the same screen (not sure the params are updated).

Hope it is clear for you.

@satya164 
Thank you for the work you do for everyone.

**Comment by satya164** [comment]
> @brianreavis: Should it pop all the history to go back to Profile A (navigate), or add an additional one to the stack (push)? I feel the latter is standard behavior.

You control what behavior you want. If you want every navigate to push a new screen, you just return a different ID every time.

**Comment by brianreavis** [comment]
Ahh gotcha. That crossed my mind but I didn't know if that was abusing things / could introduce problems. The one shortcoming of that approach is pushing an identical screen if you happen to be on the same exact screen as what's being linked to. Scenario: you're on your user profile, and then click a link in a global menu that references your profile (not someone else's). The ideal behavior here is not pushing because you're already there.

**Comment by phindell** [comment]
> You control what behavior you want. If you want every navigate to push a new screen, you just return a different ID every time.

Thanks for opening this issue and giving this answer, absolutely saved my life today!

**Comment by tr3v3r** [comment]
For those who still can't find a proper solution, here it is:
https://github.com/expo/router/issues/747#issuecomment-1652675829
