### ISSUE TITLE
[Question] Web support: Can web navigation be trigger programmatically? Is navigation callback supported?

### ISSUE THREAD

**Issue by Insullone** [react-navigation/react-navigation#9146]
I am using [react-native-web](https://github.com/necolas/react-native-web) and react navigation 5. According to documentation of [react navigation web support](https://reactnavigation.org/docs/web-support/), react navigation 5 supports navigation for web. To navigate to another internal path/URL, the only way I find from docs is to use [Link](https://reactnavigation.org/docs/link). It seems that \<Link\> is only triggered by clicking, not by explicitly function call, is it true? Can web navigation be triggered programmatically? In addition, I want to know whether I can set a callback (e.g. onPress) which is called when web navigation happens? Thank you.

**Comment by adamhari** [comment]
The usage of <Link> is advised because it will render out an <a> tag which improves accessibility on web. You are still able to programatically navigate using navigation.navigate etc. 

Similarly with the callback, if your navigation button needs to do more than simply navigate to a path, you can use a regular navigation action inside your handler function.

**Comment by Insullone** [comment]
Thanks, @adamhari I have used <Link> anyway with some workaround (useEffect). I will try what you said in the future if applicable.
