### ISSUE TITLE
Modal inside a tab disappears after a screen rotation on Android

### ISSUE THREAD

**Issue by Omarox** [react-navigation/react-navigation#9158]
**Current Behavior**

The Modal shown from within a Tab screen disappears after a screen rotation on Android.

The code that I use:
```js
import 'react-native-gesture-handler';
import React from 'react';
import { SafeAreaView, Modal, Text, View } from 'react-native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { NavigationContainer } from '@react-navigation/native';

const Tab = createBottomTabNavigator();

const HomeScreen = () => {
  return (
    <View style={{ padding: 10, flexDirection: 'row' }}>
      <Text style={{ flex: 1 }}>
        Test
      </Text>
      <Text style={{ flex: 1 }}>
        Background
      </Text>
      <Text style={{ flex: 1 }}>
        Text
      </Text>

      <Modal isVisible onRequestClose={() => { }}>
        <Text style={{ flex: 1 }}>
          Test Modal
        </Text>
      </Modal>
    </View>
  );
}

const App = () => {
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <NavigationContainer>
        <Tab.Navigator>
          <Tab.Screen name="Home" component={HomeScreen} />
        </Tab.Navigator>
      </NavigationContainer>
    </SafeAreaView>
  );
};

export default App;

```

Demonstration:
<img src="https://user-images.githubusercontent.com/17439681/102474810-61ae1e00-4059-11eb-9738-831427b10cac.gif" width="250" height="500"/>

**Expected Behavior**

The Modal remains shown after a screen rotation.

**How to reproduce**

Run the app in portrait mode and then rotate the screen in any direction.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | 5.8.10
| @react-navigation/bottom-tabs | 5.11.2
| react-native-screens          | 2.16.1
| react-native                  | 0.63.4
| node                          | v12.19.0
| npm                   | 6.14.9

**Comment by nathan-castlehow** [comment]
@Omarox did you find a fix for this one? I am having the same issue.

**Comment by satya164** [comment]
`Modal` is a component from React Native. Please open issues related to it in React Native repo.

**Comment by nthnism** [comment]
@Omarox @nathan-castlehow You guys, I had the same bug:
Unlocking orientations in the app and rotating while a modal is shows moves the modal 'somewhere' (It's still open though). This modal is mounted on a screen which is nested in a bottomTabNavigator.

I testes against an older version of our app, with navigation 3.x. The issue was not present there, but we currently upgraded to 5.x, so I looked into the styling of our custom TabBar. Giving it explicit positioning style fixed the issue for me. The TabNavigator renders the component on the bottom by default, even without styles. but setting them explicitly to position: 'absolute' and bottom: 0 helped me to get the modal stay in place on rotation.

`export const TabBar = ({
  navigation,
  state,
}) => {
  const insets = useSafeAreaInsets()
  const safeAreaStyle = {
    backgroundColor: '#fff',
    paddingBottom: insets.bottom,
    width: '100%',
    position: 'absolute',
    bottom: 0,
  }
  return (
    <View style={safeAreaStyle}>
      <AppUpdater>
        <UserInfoUpdater>
          <View>
            <UsageInfoUpdater />
            <SnackBar />
            <View style={styles.iconContainer}>
              ...
            </View>
          </View>
        </UserInfoUpdater>
      </AppUpdater>
    </View>
  )
}`

**Comment by ktjd123** [comment]
I'm having same issue. Is there any update?

**Comment by Jayachandran369** [comment]
I'm to facing the issue modal is not working on top of the bottom navigator, did anyone find the solution.

**Comment by sanjeevsinghsaini-toddleapp** [comment]
For those who didnt find the solution try wrapping the modal under Portal 
worked for me
