### ISSUE TITLE
react-navigation drawer stays opened after app is initialised in SDK40

### ISSUE THREAD

**Issue by chuanxie** [react-navigation/react-navigation#9199]
## 🐛 Bug Report

after upgrade to sdk 40, app broken and drawer stays opened
<img width="392" alt="Screenshot 2021-01-05 at 10 45 48" src="https://user-images.githubusercontent.com/13952592/103637616-a7b51e00-4f43-11eb-87ee-767ab55563e7.png">

reverted into SDK39 and life back to normal

### Environment -
``` Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed
```
and ```    "@react-navigation/bottom-tabs": "5.11.2",
    "@react-navigation/drawer": "5.11.4",
    "@react-navigation/native": "5.8.10",
    "@react-navigation/stack": "5.12.8",```

**Comment by amanda-t** [comment]
I had the same issue (upgraded from Expo 39.0.2 to Expo 40 without changing any versions of my react-navigation packages). On iOS the drawer navigation was behaving oddly and was stuck open after upgrading to Expo 40 even though it worked fine in Expo 39. Figured out it was due to wrapping everything, including the navigation, in a top-level `SafeAreaView`. Changing my top-level `SafeAreaView` to a `View` fixed it.

**Comment by chuanxie** [comment]
yeah. sorted by removing from the top level and replacing the SafeAreaView with `react-native-safe-area-context` one
