### ISSUE TITLE
ReOpen the wrongly closed Non-serializable values were found in the navigation state...

### ISSUE THREAD

**Issue by cyphire** [react-navigation/react-navigation#9205]
Please.... I am not trying to cause any problems, be nit-picking, nor am I trying to start a war....

React-native has a pretty steep learning curve and react-navigation is, in my opinion, worse.

There are few examples of real-world situations in the documentation.  If we all used react-navigation to make a one page app with a title on each page, and do  nothing more than this would be fine... But it's not.

I've been working with React-Native and all the versions of navigation for 5 years.

There should be examples of passing global state, using react context and global providers and other documentation that doesn't make learning react-navigation 10 times more work than it should be.

A perfect example is: Non-serializable values were found in the navigation state...

The smallest percentage of the contributors to this project want to be able to do time-travel and worry about serialization.  They think this is important and want to "steer" people toward that.  So they kill the simplest and most important feature in react-navigation, just being able to pass a function to an icon in the header!

It's time for those who work on this to actually make it easy to use for everyone else.

I moved all my functions to setParams in the page itself, and still get the error.  The documentation should ENDORSE a simple way of passing anything to the header, instead of crippling it and leaving everyone with the yellow box warning.

The documentation needs complete best-practices examples of putting an app together, not by searching all over for it, but a layered approach with examples of multi-page apps, passing context, using global state with the navigator and being able to pass functions and any level of data to the navigator.

I understand that the yellow box is just a warning - but... it's symptomatic of purity and unusability vs. giving the great mass of people who could benefit from this a reasonable chance of not spending 10x more hours on navigation because it isn't set up to be easily understood.

> satya164 commented on May 3, 2020
> The reasons are already documented on the website along with instructions on how to to suppress it, which should gives you an idea if you actually read the warning.
> 
> I'm locking this issue to prevent unnecessary spam from people not reading warnings when it's already explained. Of course the documentation can always be improved to make it more clear and add more examples for different use cases. Feel free to send pull requests for that to https://github.com/react-navigation/react-navigation.github.io
> 

I disagree.... Satya and others should rethink the minimalist approach to examples and certainly NOT steer people away from easily being able to set functions in react-navigation!!!  This cripples it.

If you see this issue all the time... Lets hear about it!

- What code are you running and what is happening?

Getting the yellow box warning after removing all the function calls through the stack navigator.

Moved the header icons and their callbacks to each screen like this:

```
const AddScreen = ({ route, navigation }) => {

	let [globalState, setGlobalState] = useContext(GlobalContext);

	useEffect(() => {
		navigation.setOptions(headerOpts({setGlobalState, globalState, isChild: true}));
	}, [navigation, globalState]);


```

This is the relevant parts of the headerOpts code which works fine (other than the non-serializable error which will not go away (even with cache cleaning):

function LogoTitle() {
  return (
	<View style={styles.logoStyle}>
		<Tv width={30} height={30} stroke={"black"} strokeWidth={3}/>
	</View>
  );
}

function BackTitle() {
	const navigation = useNavigation();

	return (
		<TouchableOpacity onPress={() => { navigation.goBack()} } style={styles.logoStyle}>
			<ChevronLeft width={30} height={30} stroke={"black"} strokeWidth={3}/>
		</TouchableOpacity>
	);
}

```
const headerOpts = ({setGlobalState, globalState, isChild = false}) => {

	return ({
		headerLeft: props => (isChild) ? <BackTitle {...props}/> : <LogoTitle {...props }/>,
		headerRight: () =>
			(!isChild) && <View style={styles.rightButtonArea}> 
				<TouchableOpacity 
					style={styles.rightMenu}
					onPress={() => setGlobalState({...globalState, editing: {editMode: !globalState.editing.editMode}})}>
					{(globalState.editing.editMode) ?
						<Activity width={30} height={30} stroke={"black"} strokeWidth={3}/>
						:
						<Edit width={30} height={30} stroke={"black"} strokeWidth={3}/>
					}
				</TouchableOpacity>
				<TouchableOpacity style={styles.rightMenu} onPress={() => alert('hi')}>
					<Menu width={30} height={30} stroke={"black"} strokeWidth={3}/>
				</TouchableOpacity>
			</View>
	})
}

```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android               Android Emulator
| @react-navigation/native      "^5.8.10",
| react-native               "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
| expo                         "expo": "~40.0.0"
| npm or yarn                1.22

**Comment by satya164** [comment]
> So they kill the simplest and most important feature in react-navigation, just being able to pass a function to an icon in the header!
> The documentation should ENDORSE a simple way of passing anything to the header, instead of crippling it and leaving everyone with the yellow box warning.

It's literally the first thing in the linked section

<img width="817" alt="Screen Shot 2021-01-07 at 11 25 40" src="https://user-images.githubusercontent.com/1174278/103881718-1ed0ea80-50db-11eb-8de8-be33fe73d392.png">

As well as documented in the fundamentals section, which is the first thing people need to read when working with the library:

<img width="267" alt="Screen Shot 2021-01-07 at 11 27 06" src="https://user-images.githubusercontent.com/1174278/103881916-635c8600-50db-11eb-81ef-1b66a7285bea.png">

And also mentioned in the upgrade guide if you're coming from older versions.

> The documentation needs complete best-practices examples of putting an app together, not by searching all over for it, but a layered approach with examples of multi-page apps, passing context, using global state with the navigator and being able to pass functions and any level of data to the navigator.

The documentation assumes existing React knowledge, and we link several resources in the getting started guide:

<img width="378" alt="Screen Shot 2021-01-07 at 11 32 01" src="https://user-images.githubusercontent.com/1174278/103882460-21800f80-50dc-11eb-8a85-a6ad584ffc9f.png">

If you have existing React knowledge, I think the fundamental section is structured in a tutorial like way covering practical use cases when using React Navigation library.

Passing context, using global state etc. is unrelated to navigation. If you use React, you should already know how to these things, and if not, there are plenty of resources on the internet to learn about them. There's nothing special to do in regards to navigation.

Besides, we have limited capacity and I'd rather spend time on improving documentation related to the navigation library and fixing bugs rather than write full fledged React tutorials, or in this case, state management library tutorials.

> Satya and others should rethink the minimalist approach to examples

Like I said, pull requests are always welcome to improve the examples.

> Getting the yellow box warning after removing all the function calls through the stack navigator
> other than the non-serializable error which will not go away (even with cache cleaning

If you still have this warning, it means that you are still passing functions in params. The warning also points out the exact screen where this warning occurs so you can find it. There's no reason for the warning to show if you're not doing it. If you believe there's actually a bug and the warning is a false positive, you can open an issue with a repro.
