### ISSUE TITLE
'beforeRemove' not triggered on the last remaining screen of a stack navigator

### ISSUE THREAD

**Issue by pedrox** [react-navigation/react-navigation#9472]
Hi.

Using:
```
    "@react-navigation/bottom-tabs": "5.11.8",
    "@react-navigation/native": "~5.9.3",
    "@react-navigation/stack": "~5.14.3",
```

I noticed 'beforeRemove' event is not being triggered on the last remaining screen of a stack nav. It seems reasonable to me that beforeRemove should trigger also for the very last screen of a stack nav.

Thanks in advance.

```js
import * as React from 'react';
import { View, Text, Button } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen({ navigation }) {
  React.useEffect(() => {
    function onBeforeRemove(event) {
        event.preventDefault();
        console.log("prevented nav from going back");
    }

    navigation.addListener('beforeRemove', onBeforeRemove);
    console.log("listener added");

    return function cleanup() {
      navigation.removeListener('beforeRemove', onBeforeRemove)
    };
  });
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ fontSize: 30 }}>This is the home screen!</Text>
    </View>
  );
}

const MainStack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <MainStack.Navigator>
        <MainStack.Screen name="Home" component={HomeScreen} />
      </MainStack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

**Comment by satya164** [comment]
Not sure what you mean, `beforeRemove` isn't a way for you to listen to `hardwareBackPress` event if that's what you're expecting. It's a way to know when a screen is being removed from a navigator (e.g. from history stack). If you need to listen to `hardwareBackPress` to prevent the app from exiting, then do that.

**Comment by pedrox** [comment]
The goal is to "prevent the user from leaving a screen" as described by https://reactnavigation.org/docs/preventing-going-back/

Apparently `beforeRemove` doesn't trigger for the last screen on a navigator.

**Comment by pedrox** [comment]
@satya164 I don't seem to have permission to re-open the issue. Should I just wait for your response on the closed issue? thanks

**Comment by origin-scm** [comment]
Have you been able to solve this issue?

**Comment by raajnadar** [comment]
Can you guys add a https://snack.expo.dev repo?? So that we can debug the issue.

**Comment by pedropedruzzi** [comment]
Sure. Here it is: https://snack.expo.dev/@pedruzzi/react-navigation-issue-9472

Updated the version since the above snack is using the current latest ones.

Please re-open the issue. Let me know if you need more information.

**Comment by pedropedruzzi** [comment]
@satya164 just to further clarify why I think it's a react-navigation issue: the stack navigator listens to back button events in order to prevent system default behavior, pop the current screen and go back to the next one in the stack. If we want to prevent users from navigating back on the stack nav, one should listen to 'beforeRemove' event as described https://reactnavigation.org/docs/preventing-going-back/.

However, when the current screen is the last one in the stack, it seems that react-navigation skips triggering the 'beforeRemove' event and lets the app close.

I believe it should instead trigger 'beforeRemove' even and prevent the default behavior if any listener calls preventDefault().

WDYT ?

**Comment by satya164** [comment]
As I already mentioned, the `beforeRemove` has nothing to do with the back button or system default behavior. It triggers whenever a screen is being removed from a navigator via any kind of navigation action (`navigate`/`goBack`/`reset` or any action) - which could originate from the back button or could originate from any other code that performs navigation.

If you want to handle what the system back button does and prevent that, then you should listen to `hardwareBackPress`. That's not what `beforeRemove` does and wasn't designed to handle that.

The documentation says "prevent the user from leaving a screen" because that's the primary use case for that and what people would search for. There are several things mentioned at the bottom of the page that try to clarify what this event handles. You can send a PR to mention that you need to handle `hardwareBackPress` on native and `beforeunload` events on web to prevent leaving the app.

**Comment by pedropedruzzi** [comment]
Hi @satya164. You are right: the back button is just a concrete example mentioned for the sake of documenting steps to reproduce. To clarify, I don't want to handle back button specifically. Instead I want to prevent the last screen of a stack navigator to be removed.

Knowing the definition of `beforeRemove` event, would you say it should or shouldn't trigger right before the last screen is removed ?

**Comment by shafqatbari** [comment]
Still Facing this issue

**Comment by izuutech** [comment]
> As I already mentioned, the `beforeRemove` has nothing to do with the back button or system default behavior. It triggers whenever a screen is being removed from a navigator via any kind of navigation action (`navigate`/`goBack`/`reset` or any action) - which could originate from the back button or could originate from any other code that performs navigation.
> 
> If you want to handle what the system back button does and prevent that, then you should listen to `hardwareBackPress`. That's not what `beforeRemove` does and wasn't designed to handle that.
> 
> The documentation says "prevent the user from leaving a screen" because that's the primary use case for that and what people would search for. There are several things mentioned at the bottom of the page that try to clarify what this event handles. You can send a PR to mention that you need to handle `hardwareBackPress` on native and `beforeunload` events on web to prevent leaving the app.

Perfect response

**Comment by enisgtf** [comment]
useEffect(() => {
        const backAction = () => {
          Alert.alert("Hold on!", "Are you sure you want to go back?", [
            {
              text: "Cancel",
              onPress: () => null,
              style: "cancel",
            },
            { text: "YES", onPress: () => BackHandler.exitApp() },
          ]);
          return true;
        };
    
        const backHandler = BackHandler.addEventListener("hardwareBackPress", backAction);
    
        return () => backHandler.remove();
      }, []); 
you can add this code which you dont want to go back on android. Gesture handling is not helpful on android. This is the link: https://reactnavigation.org/docs/preventing-going-back/
and on the documentation there is a link for android: https://reactnative.dev/docs/backhandler

**Comment by atultiwaree** [comment]
> ```
> useEffect(() => {
>     const backAction = () => {
>       Alert.alert("Hold on!", "Are you sure you want to go back?", [
>         {
>           text: "Cancel",
>           onPress: () => null,
>           style: "cancel",
>         },
>         { text: "YES", onPress: () => BackHandler.exitApp() },
>       ]);
>       return true;
>     };
> 
>     const backHandler = BackHandler.addEventListener("hardwareBackPress", backAction);
> 
>     return () => backHandler.remove();
>   }, []); 
> ```
> 
> you can add this code which you dont want to go back on android. Gesture handling is not helpful on android. This is the link: https://reactnavigation.org/docs/preventing-going-back/ and on the documentation there is a link for android: https://reactnative.dev/docs/backhandler

this only worked in android not ios
