### ISSUE TITLE
Bottom Tab become squished

### ISSUE THREAD

**Issue by Tj3n** [react-navigation/react-navigation#9562]
I'm using Expo in iOS, randomly after I reload the app, the bottom bar become squished similar to [this SO question](https://stackoverflow.com/questions/65153593/why-is-the-bottom-tab-navigator-height-smaller-squished-upon-reload), hope someone can give some feedback. Thanks in advanced.

Version:
"@react-navigation/bottom-tabs": "^5.11.8",
"@react-navigation/native": "5.9.3",
"@react-navigation/stack": "5.14.3",

![image](https://user-images.githubusercontent.com/13995715/117445575-0c6d9d00-af65-11eb-93c1-76cd7ed57ab8.png)

**Comment by Tj3n** [comment]
It still happening after update all these packages above

**Comment by nickksm** [comment]
Having the same issue, even after I updated all those packages to the latest.

**Comment by apedroferreira** [comment]
same here, still get this quite often

**Comment by Tj3n** [comment]
Seems like happen in iOS only, I don't recall it happen in Android.

**Comment by takacskalman** [comment]
We have the same issue. It happens only on IOS at startup (randomly), or when rotating the screen from portrait to landscape (always). Any updates?

**Comment by Tj3n** [comment]
Now that someone mentioned it, it really does looks like tabBar UI behavior on landscape iPhone, but in my app i specify it as portrait only, this is still happening. Probably bug within the orientation check on reload.

**Comment by AdrishS-AW** [comment]
I recently faced a similar problem, when I would navigate to 2 screens forward and come back, bottom tabs would get squished. For me it was due to SafeAreaView from 'react-native-safe-area-context'.

The issue was that it automatically added bottom padding to account for the home indicator and bottom tab navigator also accounts for the same safe area, so I ended up getting double bottom padding, making it looked squished.

The Solution was pretty simple, switched to SafeAreaView from 'react-native'.
