### ISSUE TITLE
Navigation state not always reset when navigators are unmounted

### ISSUE THREAD

**Issue by chrisparton1991** [react-navigation/react-navigation#9739]
### Current behavior

I have a skeleton app with the following screen hierarchy:
```
StackNavigator
    LoginScreen
TabNavigator
    HomeScreen
    StackNavigator
        ProfileScreen
        SettingsScreen
``` 

Screens are conditional (as per [auth flow docs](https://reactnavigation.org/docs/auth-flow/)), so only the `LoginScreen` is mounted when the user is unauthenticated, and vice-versa for the remaining screens.

When logging out via the `ProfileScreen` and then logging back in, the user is returned to the `HomeScreen`, as expected.

When logging out via the `SettingsScreen` and then logging back in, the user is returned to the `SettingsScreen`, which is unexpected. I can't figure out a way to reset that navigation state.

I've created a Snack and a video (with audio explanation) of the issue, and put the code up on GitHub.

### Expected behavior

Given that the tabs and stacks are unmounted after logging out, I would expect that logging back in would reset the navigation state and return the user to the initial tab.

Thanks!

### Reproduction

Snack (v5): https://snack.expo.io/SCWaKO40u
Snack (v6): https://snack.expo.dev/gIbYd7EX0
GitHub (v5): https://github.com/chrisparton1991/react-navigation-issue
Video (with audio): https://imgur.com/a/8Og3Cjc

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4, 6.0.0
| @react-navigation/bottom-tabs          | 5.11.11, 6.0.0
| @react-navigation/drawer               | 
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    | 
| @react-navigation/stack                | 5.14.5, 6.0.0
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.2.0
| react-native-tab-view                  | 
| react-native-pager-view                | 
| react-native                           | 0.64.1
| expo                                   | 
| node                                   | 14.15.1
| npm or yarn                            | npm 6.14.8

**Comment by chrisparton1991** [comment]
I've tested this issue in v6, it still exists unfortunately.

**Comment by chrisparton1991** [comment]
Still broken in v6.0.11

**Comment by vpsgvitor** [comment]
Still broken in v6.1.1 😱😱😱😱😱😱😱😱😱😱😱

**Comment by DanielZyger** [comment]
almost one year and not adjusted that...

**Comment by raajnadar** [comment]
Just doing a small structural change solved the issue in this snack demo https://snack.expo.dev/Vs20xIsVo

**Comment by Neiso** [comment]
Still broken in 6.1.7.

This is extremely annoying as even the `route.params` object is not being reset which leads to unexpected behaviour. Simple example of what I'm experiencing:
```
StackNavigator
    LoginScreen
TabNavigator
    HomeScreen
    MarketplaceNavigator
        MarketplaceScreen
        ProductScreen
```

1. Open product push notification which redirects to `('MarketplaceNavigator, {name: "ProductScreen", params: {productId: XX}})`
2. JWT token expires, user gets logged out and redirected to `StackNavigator => LoginScreen` (_Nav state not being reset here_)
3. User logs back in, StackNavigator unmounts and TabNavigator mounts
4. On accessing the Marketplace Stack, user is being redirected automatically to "ProductScreen" with params XX 

I tried reseting the nav state on first focusEvent directly in the `createBottomTabNavigator` component like this: 
```
  useFocusEffect(useCallback(() => {
    return navigation.reset({ index: 0, routes: [{ name: 'HomeNavigation' as never }] })
  }, []))
```
But the useFocusEffect is being mounted twice which triggers all `useEffect(() => , [])` twice (like API calls) unfortunately.

If the reset state reducers can be done in the JS part, I don't mind submitting a PR when I have some time.

**Comment by Jackman3005** [comment]
@Neiso We also have gone through this pain... In the end we have a very involved workaround which is accomplishing the goals we have.

Another thing not mentioned is that the browser back is not handled correctly in these situations either. For us, on logout we wanted to remove the browser back history as well.

Sample of our Navigator setup:
```
StackNavigator
        Login (only rendered when there is no `accessToken`)
        Home (only rendered when there is an `accessToken`)
        Logout (always rendered, blank screen)
```

What we're doing now...
1) `setIsLoggingOut(true)` (this will cause a full screen view to overlay everything so you cannot see the navigation animations that are coming up)
2) `navigation.popToTop()` (this is the only reliable way for us to reset the browser back history and also prevents us from keeping navigation state unexpectedly when logging back in)
3) `navigation.replace('Logout')` (when pop to top completes you'll be on the Home screen in the app, which can make API calls via `useSWR()` with the invalid access token while we perform some async logout actions, so we unmount it and swap it with a blank Logout screen. Now our routes stack only has the Logout screen in it)
4) remove the `accessToken` from our state. This causes the Home screen to be removed (not rendered) and the Login screen to be added (rendered). But since we are on the Logout screen and it is still in our `routeNames` when we do not have an `accessToken` we do not automatically navigate to Login (like what happened before when logged out while on the Home screen), we instead stay on the Logout screen.
5) we also perform all other manner of logout activities here like logging out of Auth0, revoking the refresh token, clearing SWR cache, etc.
6) We wait until all tasks in step 5 are done and the Login screen becomes available in the list of `routeNames`
7) `navigation.replace('Login', {redirectUrl: '/path/to/post/login/screen/})` (finally show the login screen with a configured redirect url in the params (this is also in the state already as well, but if the user refreshes the website on this page we want to maintain the redirect url)
8) `setIsLoggingOut(false)` (removes the full screen overlay to show the login screen behind it)

As mentioned, this is working well for us and is accomplishing all our current goals, but was wayyyy more work than we expected was necessary. All these steps happen quickly and because of the overlay the user does not see many navigation animations so the whole experience appears quite smooth.

Happy to expand on reasons or methods in more detail if it helps.

**Comment by Neiso** [comment]
@Jackman3005 Thank you for your very elaborate answer! Just a quick question about where do you insert the full screen overlay ? In the Navigation renderer (MainStackNavigator.tsx) or directly in the root level App.tsx ?

**Comment by Jackman3005** [comment]
It's at the bottom of the MainStackNavigator. Here's a snippet of the code that should clear it up and give you a place to start:

```typescript
  const userIsLoggedIn = currentUserId !== null;

  return (
    <>
        {/* initial screen  */}
        {userIsLoggedIn ? (
          <Stack.Screen
            name="Home"
            component={HomeScreen}
            navigationKey={currentUserId}
            options={() => ({
              title: "Home",
              headerLeft: OpenSideBarButton,
            })}
          />
        ) : (
          <Stack.Screen name="Login" component={LoginScreen} />
        )}

        <Stack.Screen
          /*  no navigationKey allows this screen to be used while transitioning from logged-in to logged-out */
          name="Logout"
          component={LogoutScreen}
          options={{
            headerShown: false,
            animationEnabled: false,
            gestureEnabled: false,
            detachPreviousScreen: true,
          }}
        />

        {/* shared screens  */}
        <Stack.Group navigationKey={String(currentUserId)}>
          {/* screens available to both logged-in and logged-out users go here */}
        </Stack.Group>

        {/* logged-in screens  */}
        {userIsLoggedIn && (
          <Stack.Group navigationKey={String(currentUserId)}>
            {/* screens available to only logged-in users go here */}
          </Stack.Group>
        )}
      </Stack.Navigator>
      {isLoggingOut ? (
        // In order to get the navigation state correct, multiple navigations are required during logout.
        // To hide the multiple screen transitions we put an overlay over the app until we reach the final screen to
        // show to the user.
        <LogoutOverlay>
          <Loader />
        </LogoutOverlay>
      ) : null}
    </>
  );
};

const LogoutOverlay = styled.View`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  background-color: ${(props) => props.theme.background};
  align-items: center;
  justify-content: center;
`;
```
